### ISSUE TITLE
Markdown link attributes are not supported (e.g. target=_blank)

### ISSUE THREAD

**Issue by webdeb** [elixir-lang/ex_doc#1004]

**Comment by josevalim** [comment]
@webdeb can you please link to the specification and provide examples of the feature you are referring to? Thank you.

**Comment by webdeb** [comment]
@josevalim https://yihui.name/en/2018/09/target-blank/

It says its **R Markdown**. However, its not in the original spec here: https://daringfireball.net/projects/markdown/syntax.text, feel free to close it, seems that plain html can also do the job very nicely.

**Comment by josevalim** [comment]
Thanks. You can see if Earmark, the underlying engine used by ExDoc supports it, but they may not since there are many markdown extensions.
