### ISSUE TITLE
Upcoming deprecation warnings in Earmark

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#1007]
I am planning quite some behavioral change in Earmark, making it more GFM like as this seems to be an issue for some users.

In 1.3.3 I will implement pure links rendering as in

```elixir
iex(21)> Earmark.as_html("https://github.com/pragdave", pure_links: true)
{:ok,
 "<p><a href=\"https://github.com/pragdave\">https://github.com/pragdave</a></p>\n",
 []}
```

However in order to maintain backwards compatibility `pure_links` defaults to `nil` (that will change in 1.4 as you will see shortly) and we get deprecation warnings like so:

```elixir
iex(23)> Earmark.as_html("https://github.com/pragdave")                   
{:ok, "<p>https://github.com/pragdave</p>\n",
 [
   {:deprecation, 1,
    "The string \"https://github.com/pragdave/earmark\" will be rendered as a link if the option `pure_links` is enabled.\nThis will be the case by default in version 1.4.\nDisable the option explicitly with `false` to avoid this message."}
 ]}
```
Forseeing that this might be a PITN the deprecation warnings can be disabled:

```elixir
iex(27)> Earmark.as_html("https://github.com/pragdave", pure_links: false)
{:ok, "<p>https://github.com/pragdave</p>\n", []}
```
I will gladly provide a PR after releasing Earmark 1.3.3 to avoid the deprecation warnings in ex_doc if you wish so, or do you prefer to keep them?

**Comment by josevalim** [comment]
A PR would be welcome, thanks for the heads up!

**Comment by RobertDober** [comment]
Sure thing.
BTW before 1.4 you might chose to still use `pure_links: false` to not change behavior, I will take care of that according to your wishes, but that will not be very soon.

**Comment by josevalim** [comment]
I think enabling pure_links makes sense, as most people would expect it indeed. :+1:

**Comment by josevalim** [comment]
I will go ahead and close this, as there is nothing actionable for us right now, but feel free to reopen or continue the discussion. :heart:

**Comment by RobertDober** [comment]
@josevalim Sorry but I am ready for the release for some weeks now, Dave seems to be on vacation.
As soon as I have his green light I will rebase on upstream and push to this PR.

Is this good 'nuff for you or do you wish me to ping you in a comment too?

**Comment by josevalim** [comment]
As you prefer :) thanks for the updates!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
