### ISSUE TITLE
Create a config to switch the EXDocs Blacklist Model to a WhiteList Model

### ISSUE THREAD

**Issue by rodespereira** [elixir-lang/ex_doc#1013]
Nowadays, the default of ExDoc is generate doc for all the .ex files. To exclude any file, we need to put the notation '@moduledoc false' in each file that i want to exclude .

Why don't you provide an optional flag that allow us to choose if all the files will be documented or not? So, when i want to doc some file, i will explicit define that.What do you think about it?

**Comment by josevalim** [comment]
Hi! You want modules that have no @moduledoc to be excluded by default?
What is the harm in adding @moduledoc false and be explicit about it?

Plus, even if we change ExDoc to ignore those, other tools that work with
docs, such as the h helper, won’t know about this choice, and then the
behavior between tools would be inconsistent.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Closing per the reasons above, thanks!
