### ISSUE TITLE
Docs not found in hex.pm

### ISSUE THREAD

**Issue by Maples7** [elixir-lang/ex_doc#1018]
While I publish https://hex.pm/packages/ex_fieldmask/0.1.0 via `mix hex.publish`:

```
Publishing package to public repository hexpm.
Proceed? [Yn] Y
Building docs...
Compiling 1 file (.ex)
Generated ex_fieldmask app
Docs successfully generated.
View them at "doc/index.html".
Local password: 
Publishing package...
[#########################] 100%
Package published to https://hex.pm/packages/ex_fieldmask/0.1.0 (0e57dd6eae6472f51a2de535549c8457021e527eb5beeb2ee27b1ddb5ee518d0)
Publishing docs...
[#########################] 100%
Docs published to https://hexdocs.pm/ex_fieldmask/0.1.0
```

But going to https://hexdocs.pm/ex_fieldmask/0.1.0 gets 404.

Source code here: https://github.com/seniverse/ex_fieldmask

Help please!

**Comment by josevalim** [comment]
You should file this issue in the Hex project. We only build the docs, we
don’t do any hosting!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by wojtekmach** [comment]
Please make sure the docs work locally before submitting an issue, you've misconfigured your `:docs` settings and that's why you're getting an error. It needs to be:

```elixir
       docs: [
         extras: ["README.md", "CHANGELOG.md"],
         main: "readme"
       ]
```

**Comment by Maples7** [comment]
Thanks very much! Got it!
