### ISSUE TITLE
Support author attribute

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1023]
It will be the author for epubs and use the relevant author tag for HTML: https://www.metatags.org/meta_name_author

/cc @msaraiva

**Comment by whatyouhide** [comment]
@josevalim do we need to support this at the module level as an actual doc attribute, or do you mean just using the author in the package config?

**Comment by josevalim** [comment]
@whatyouhide in the package config. This will be for the "whole artifact".
