### ISSUE TITLE
Support syntax highlighting in examples

### ISSUE THREAD

**Issue by vanstee** [elixir-lang/ex_doc#103]
It would be super nice to have syntax highlighting for all of the code examples in the documentation. I'm guessing this might be a decent bit of work if we can't depend on something like [pygments.org](http://pygments.org/).

**Comment by whatyouhide** [comment]
If I understand correctly, this should be now solved since ex_doc is using highlight.js (with Elixir support) to highlight code examples in the documentation. Should we close this?

**Comment by vanstee** [comment]
Yep good call. Here's the relevant ex_doc PR: https://github.com/elixir-lang/ex_doc/pull/168

Thanks for following up @whatyouhide.

**Comment by whatyouhide** [comment]
@vanstee no problem, my pleasure!
