### ISSUE TITLE
Do not move to docs root when switching version

### ISSUE THREAD

**Issue by panmichal** [elixir-lang/ex_doc#1033]
I noticed this when checking Elixir docs. When you are in a section (module, function etc.) on the docs page and switch version you are moved to the documentation root even when that section also exists in the version you just switched too. This happens a lot to me as I use browser search to look up things and usually land on docs for newest version which is not yet used in my projects. 

You can also see it in ExDoc own docs.

I think there would be two cases:
- section exists in the chosen version -> stay in this section
- section does not exists -> go to the root section

I think it should be opt-in so it will be necessary to mark URLs in `versionNodes` as 'base urls` and concatenate it with current sections URI.

Please let me know whether it makes sense and I will try to create a PR.

**Comment by wojtekmach** [comment]
I think this is a good idea, but I'm not sure how we can implement it. Could you elaborate on the opt-in behaviour you mentioned?

Imagine a user is on https://hexdocs.pm/mix/1.9.0/Mix.Release.html and switches to v1.8.0 (where such module does not exist) - what happens? If we naively redirect them to https://hexdocs.pm/mix/1.8.0/Mix.Release.html they'd land on a 404 page. Or do we land them on some intermediate page that will know whether a module exists or not and will redirect them appropriately? If so, how exactly would that work?

**Comment by panmichal** [comment]
That would be this case:
```
section does not exists -> go to the root section
```

But now when I started thinking more about it I'm not sure if it's possible to implement. Sections are just static html files and we don't know if given section exists.

Regarding opt-in. I meant by default everything would be as it is now. But you could somehow mark version URLs as base URLs. And that would mean new location would that base URL concatenated with current section's URI.

**Comment by josevalim** [comment]
Unfortunately checking for the exact session is non trivial. The best we
can do is to check if the page exists and if it does, we redirect to it,
otherwise we go to the project root. This checking could be done with an
Ajax request.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by panmichal** [comment]
Checking with Ajax request seems to be a not-so-bad solution. I'll play with it.

**Comment by eksperimental** [comment]
How about Chrome's restriction on remote calles when running from localhost?

**Comment by josevalim** [comment]
Not a problem here because we have a fallback and it is an opt-in feature
anyway.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
@panmichal are you still interested in implementing this? :)

**Comment by panmichal** [comment]
@josevalim yes! sorry for the late reply, was AFK for some time :) but I'll work on it soon.

**Comment by kenny-evitt** [comment]
This is something I notice wanting fairly often.

I think a 404 would be fine, e.g. in the case that a module doesn't exist in an earlier version. That's a somewhat-obvious clue that the thing doesn't exist in the other version and thus I think a *little* nicer than automatically redirecting to the root page.

Maybe even better than checking (e.g. via AJAX) and redirecting to *root* would be to redirect to a more specific/explicit 'this thing doesn't exist in this version' page?

**Comment by josevalim** [comment]
Closing in favor of #1214.
