### ISSUE TITLE
Links to functions containing `&` characters do not fully work

### ISSUE THREAD

**Issue by archdragon** [elixir-lang/ex_doc#1041]
Links to functions containing `&` will direct to the top of the module page (instead of scrolling to the relevant function description).

Took a quick look at it and from what I can see this happens because we're getting `&amp;` in the hash/link and just `&` in the anchor.

To reproduce:

1. Go to https://hexdocs.pm/elixir/Function.html
2. Click on `&/1`

**Current behaviour**: You are being redirected to the top of the `SpecialForms` module page
**Expected behaviour**: You are being redirected to the top of the `&/1` function description on the `SpecialForms` module page

**Comment by eksperimental** [comment]
I can look into it.

**Comment by eksperimental** [comment]
And thank you for the report.

**Comment by archdragon** [comment]
Thanks @eksperimental ! (it's awesome that I've mentioned an issue just before going to sleep and when I woke up it's already fixed :D )
