### ISSUE TITLE
Export in markdown instead of html or epub

### ISSUE THREAD

**Issue by sezaru** [elixir-lang/ex_doc#1043]
So, as far as I understand, ex_doc will first generate a markdown version of the documentation and then convert it into html version.

My question is, can I stop at the markdown version and output it instead of the html one? I need that because I want to try to "inject" the documentation for project inside the github wiki which only accepts markdown.

Is that possible or reasonable?

Thanks!

**Comment by eksperimental** [comment]
I would say it is totally feasible.
You will have to create a markdown formatter, which can be based upon both epub and html ones.

**Comment by eksperimental** [comment]
One of the features that is missing in IEx and I have wanted to propose for ages is (please enlighten me if I am missing something) the ability of read the documentation for the whole module, ie. moduledoc, plus funtions docs and types.
Supporting a Markdown formatter we could quickly grep and read the whole documentation from a terminal.
I support the idea of having a Markdown formatter

**Comment by cybrox** [comment]
I'm playing around with this idea a bit.

**Comment by josevalim** [comment]
It is not true that we build everything on Markdown. The docs are in
Markdown but the assembling is in HTML. Since we have standardized the Docs
chunk, I don’t see a reason to have this in ExDoc. Anyone can extract the
docs from the chunk and the API is quite uniform.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by cybrox** [comment]
> Anyone can extract the docs from the chunk and the API is quite uniform.

How would you do this without hooking into the formatting process of `ex_doc`? As far as I know, there is no straight forward way of getting the raw docs chunk, or am I missing something?

**Comment by wojtekmach** [comment]
The public API is [`Code.fetch_docs/2`](https://hexdocs.pm/elixir/Code.html?#fetch_docs/1) and it has all docs (but not specs) information you'd need and it's exactly what `ExDoc.Retriever` is using under the hood. Here's a quick example:

```elixir
    module = Atom

    {:docs_v1, _anno, _lang, "text/markdown", %{"en" => module_doc}, _metadata, docs} =
      Code.fetch_docs(module)

    IO.puts("# #{inspect(module)}")
    IO.puts("")
    IO.puts(module_doc)
    IO.puts("## Functions")
    IO.puts("")

    for {{:function, name, arity}, _anno, signature, %{"en" => doc}, _metadata} <- docs do
      IO.puts("### #{signature}")
      IO.puts("")
      IO.puts(doc)
    end
```

```markdown
# Atom

Convenience functions for working with atoms.

See also `Kernel.is_atom/1`.

## Functions

### to_charlist(atom)

Converts an atom to a charlist.

Inlined by the compiler.

## Examples

    iex> Atom.to_charlist(:"An atom")
    'An atom'


### to_string(atom)

Converts an atom to a string.

Inlined by the compiler.

## Examples

    iex> Atom.to_string(:foo)
    "foo"
```

**Comment by cybrox** [comment]
Oh, just when I thought I knew quite a bit about how ex_docs works... 😄    
Thanks! - I guess it is obsolete then.

**Comment by sezaru** [comment]
Thanks @wojtekmach for the code example, I guess I can use that to generate a task to do what I want without the need to change ExDoc behavior.

Should I close this then?

**Comment by josevalim** [comment]
We can do it, thanks!
