### ISSUE TITLE
Packaging for Debian

### ISSUE THREAD

**Issue by rajasekharponakala** [elixir-lang/ex_doc#1046]
Hey, any progress on the packaging so far? found an RFP bug.

RFP bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795495

**Comment by josevalim** [comment]
We publish ExDoc on Hex, which is Elixir's package manager. If someone wants this available elsewhere, then it is up to them, as we can't maintain packages for all distributions. Thanks!
