### ISSUE TITLE
How to escape backticks in inline code

### ISSUE THREAD

**Issue by krepflap** [elixir-lang/ex_doc#1047]
Might be an earmark issue, but I can't seem to produce the result I want. 

Consider this:

```elixir
  @moduledoc ~S"""

  This is a backtick: `\``. Some more `inline code`.

  """
```

Building docs gives warning : ``Closing unclosed backquotes ` at end of input``

Expected output:

```html
<p>This is a backtick: <code class="inline">`</code>. Some more<code class="inline">inline code</code>.</p>
```

Actual result:

```html
<p>This is a backtick: <code class="inline">\``. Some more</code>inline code`.</p>
``` 

Using double or triple backticks doesn't seem to help either.

**Comment by josevalim** [comment]
You write:

  * two backticks
  * space
  * one backtick
  * space
  * two backticks

Btw, this is a genereal markdown question. If you search for "how to ask backticks in markdown", it may show other answers.

**Comment by krepflap** [comment]
Thanks José, I didn't realize the need for the spaces and I (wrongly) assumed I was stumbling on some behavior particular to exdoc/earmark.

It works now.
