### ISSUE TITLE
Hardcode Elixir packages for goto functionality

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1048]
We should hardcode all 6 elixir packages in our go-to feature: elixir, eex, mix, ex_unit, logger, and iex, so autocompletion works for them too. Given they are specific to Elixir, I think it is worth hardcoding them.

What do you think @cybrox? If you agree, could you please submit a PR?

**Comment by cybrox** [comment]
I definitely agree! It shouldn't be too hard to just add them to the search list by default and re-filter that for display.

I would be happy to submit a PR, however, I can only do so in a week. Don't have my laptop with me atm, sorry.

**Comment by ericmj** [comment]
Please add `hex` to the list of applications. The full list of applications that are on hexdocs.pm but are not Hex packages is: `elixir`, `eex`,  `ex_unit`, `hex`, `iex`, `logger`, `mix`.
