### ISSUE TITLE
Potentially remove the requestId on iframes for caching

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1050]
Hi @archdragon!

You use a `requestId=` when loading the tooltip iframe. Unfortunately that makes it impossible for the page to be cached. Can you explain why the requestId is necessary? Do you know of any other options?

Thank you!

**Comment by archdragon** [comment]
Thank you for catching that  - I should have not trouble removing it. I've added it for two reasons:

First - to avoid race conditions. Sometimes I'll see an invalid response when I: 1) hover over a link `A`, 2) hover over a link `B` and 3) `A` sends the answer back just as I start the `B` hover. But that can be fixed just by checking if the requested function/module matches.

Second - to make sure I'm not getting an unwanted response. I'm disregarding anything that does not matches my latest request ID. But I think I can achieve the same just by checking if the  module/function matches and accepting only one matching response.

I think this can be safely removed (with a few extra changes to the code) - I'll prepare a PR.

**Comment by josevalim** [comment]
> But I think I can achieve the same just by checking if the module/function matches and accepting only one matching response.

Yeah, I agree. I actually think we can just match the URL. See if the URL in src is the same as in the frame?

**Comment by archdragon** [comment]
> Yeah, I agree. I actually think we can just match the URL. See if the URL in src is the same as in the frame?

I'm on it - it's a bit more involved because of the postMessage, which does not give me a full url directly.

**Comment by josevalim** [comment]
@archdragon you can pass the URL as parameter if you want. As long as the parameter is static, we are golden. You may need to escape the URI characters on it though.

**Comment by archdragon** [comment]
@josevalim 

👍

I've made it a bit simpler and prepared a PR here https://github.com/elixir-lang/ex_doc/pull/1054 - I'm sending the page URL back (next to the hint info) and check if it matches the one we just hovered over.

The URL stays static and cache works.

**Comment by princemaple** [comment]
Why did it have to be using an iframe? I'm sure there has been some discussion I didn't see, if I could get a pointer :)

Looking at all the things being passed around I just want to change it to use `(await fetch('https://hexdocs.pm/elixir/master/Kernel.html#content')).text()` and call the extraction functions.

**Comment by princemaple** [comment]
That said, I confirm that the cache works :)

**Comment by archdragon** [comment]
@princemaple Thanks for checking! 

Here is the discussion that contains some info and requirements for the popovers https://github.com/elixir-lang/ex_doc/issues/971 :)

**Comment by princemaple** [comment]
The implementation didn't end up using the iframe to directly render the tooltip, do you think iframe is still a good idea? (probably good enough with the cache in place)

**Comment by archdragon** [comment]
@princemaple I agree that iframe is good enough, but fetch would be more elegant. Wouldn’t we run into cross-origin issues with fetch? Tool tips can currently make requests between docs (ie localhost -> hex) and projects (ie Phoenix -> elixir). They also work on local static files (file://..., without a server running)

**Comment by princemaple** [comment]
Well, that could turn out to be a big advantage indeed. I guess it's not broken, let's not fix it. Thanks for all the replies!

**Comment by cybrox** [comment]
For the sake of completion, @archdragon, cross origin blocking would not be a problem between packages (since the host is always hexdocs.pm). For local -> hexdocs, that would work if hexdocs.pm allowed requests from any origin (which it could, there's no writes happening on the docs API, it's just served assets, so it wouldn't matter). For file:// however, you're most likely better off with iframes because browsers do browser things and that behaviour is very inconsistent.
