### ISSUE TITLE
Go to a HexDocs package list item shouldn't move as you mouseover it

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1055]
the purple selection indicator make the whole text to move to the right. It will be a much more smooth experience if there if there is a translucent filler in place, so when you mouse over it, all items stay in place

**Comment by josevalim** [comment]
IMO the "jump" is fine as it helps highlight the transition, especially when using the keyboard to select.  The same happens on autocomplete, so we unless we can say with confidence this is a design bug (rather than a preference issue), I would leave it as is, thanks!
