### ISSUE TITLE
Versions should be left aligned

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1056]
The new version menu looks good right aligned when all versions are of the same length, but then there is for example a Release Candidate, it gives the false impression of having submenus.

You can see it in Elixir,
![version_menu](https://user-images.githubusercontent.com/9133420/61513225-a4b03000-aa26-11e9-8348-f119896ba5cb.png)

changing the direction from `rtl` to `ltr` fixes it, but the title of the project is aligned to the right, so we should decide wether to realign the title accordingly.

**Comment by wojtekmach** [comment]
The problem with left-align is on non-RC versions we'll have space between currently selected version and the "down arrow" like here:

<img width="207" alt="image" src="https://user-images.githubusercontent.com/76071/61513443-5f2b3d00-a9fd-11e9-87c7-0fd64b434b84.png">

Also, I think the same argument that "it gives the false impression of having submenus." can be made here unfortunately :(

<img width="249" alt="image" src="https://user-images.githubusercontent.com/76071/61513454-67837800-a9fd-11e9-8774-b914a48537b4.png">

**Comment by eksperimental** [comment]
> The problem with left-align is on non-RC versions we'll have space between currently selected version and the "down arrow" like here:
> 
> <img alt="image" width="207" src="https://user-images.githubusercontent.com/76071/61513443-5f2b3d00-a9fd-11e9-87c7-0fd64b434b84.png">
> 
> Also, I think the same argument that "it gives the false impression of having submenus." can be made here too unfortunately :(
> 
> <img alt="image" width="249" src="https://user-images.githubusercontent.com/76071/61513454-67837800-a9fd-11e9-8774-b914a48537b4.png">



> The problem with left-align is on non-RC versions we'll have space between currently selected version and the "down arrow" like here:
> 
> <img alt="image" width="207" src="https://user-images.githubusercontent.com/76071/61513443-5f2b3d00-a9fd-11e9-87c7-0fd64b434b84.png">

maybe the arrow go on the left side?

**Comment by eksperimental** [comment]
> Also, I think the same argument that "it gives the false impression of having submenus." can be made here too unfortunately :(
> 
> <img alt="image" width="249" src="https://user-images.githubusercontent.com/76071/61513454-67837800-a9fd-11e9-8774-b914a48537b4.png">

How come? having a gap on the left it what gives the effect (at least on LTR languages)

**Comment by wojtekmach** [comment]
> maybe the arrow go on the left side?

we thought about this, it seems it's more common for arrow to appear on right side of dropdowns.

**Comment by eksperimental** [comment]
maybe flipping the logo to the left and the title and dropdown to the right? I'm terrible with design, so I will leave it to others

**Comment by josevalim** [comment]
We virtually explored all of those options when we added the feature and the best design we could come up with is the current one. So unless someone has a concrete change (i.e. a PR that changes it to something better), I don’t have any new input to add here. Otherwise we can spend hours talking about possible options. Thanks!
