### ISSUE TITLE
EPUB issues

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1057]
I have come across issues with the generated EPUB documentation: /cc @milmazz 

* [ ] 1. The table of contents menu, should have a tree structure like the HTML version. At the moment, the first page shows it right, but when in the reader I choose to open the TOC, it shows a flat list.

* [ ] 2. The TOC page and the TOC element, should take into consideration the --config option to structure the items.

* [x] 3. Internal links. https://github.com/elixir-lang/ex_doc/issues/1057#issuecomment-513113750

* [x] 4. Deprecated notice is missing. For example in the Behaviour module, the "This module is deprecated. Use @callback and @macrocallback attributes instead." message is missing.~~ https://github.com/elixir-lang/ex_doc/issues/1057#issuecomment-513117084
**PENDING:** the deprecation message needs a different background color, or border.

* [x] 5. Attributes such as since, or when the function is a macro are missing.

* [ ] 6. Can we make smaller the gap between a function signature and a function spec?, it's like a full line empty and it looks a bit odd.

**Comment by eksperimental** [comment]
2.  the TOC page and the TOC element, should take into consideration the `--config` option to structure the items.

**Comment by eksperimental** [comment]
3. Internal links.
Does it make sense to have them?
![image](https://user-images.githubusercontent.com/9133420/61514697-c8757500-aa2a-11e9-8c7e-27d76d1b8ede.png)

- "Anchor for this section" looks too big. I guess it could be removed, since AFAIK we cannot link from anywhere.
- "link to this function" doesn't look as bad, but I see no use for it.

**Comment by eksperimental** [comment]
3. Internal links.
Does it make sense to have them?

- "Anchor for this section" looks too big. I guess it could be removed, since AFAIK we cannot link from anywhere.
- "link to this function" doesn't look as bad, but I see no use for it.

**Comment by eksperimental** [comment]
4. Deprecated notice is missing.
For example in the Behaviour module, the "This module is deprecated. Use @callback and @macrocallback attributes instead." message is missing.

**Comment by eksperimental** [comment]
5. Attributes such as `since`, or when the function is a `macro` are missing

**Comment by josevalim** [comment]
Thanks @eksperimental!

PS: btw, I have enabled Two factor auth organization wide for security but you don't have it enabled. They should have sent you an e-mail. Once you enable it, please let me know, I believe I need to give you access again.

**Comment by eksperimental** [comment]
@josevalim Yes, I got that email by GitHub. I need to fix my phone and I don't have the time and energy for that now. So it will have to wait for a bit.
I will drop you an email when I have enabled that. Thank you for letting me know.

**Comment by milmazz** [comment]
@eksperimental Could you please update this issue with the things that are still pending to fix?

**Comment by eksperimental** [comment]
Thank you @milmazz ,
here's the updated report
1. still happening
2. still there
3. fixed
4. fixed, but the deprecation message needs a different background color, or border.
5. fixed

**Comment by eksperimental** [comment]
6. can we make smaller the gap between a function signature and a function spec?, it's like a full line empty and it looks a bit odd

**Comment by eksperimental** [comment]
> Thanks @eksperimental!
> 
> PS: btw, I have enabled Two factor auth organization wide for security but you don't have it enabled. They should have sent you an e-mail. Once you enable it, please let me know, I believe I need to give you access again.

@josevalim I have enabled it. Yes, you need to give me access again

**Comment by eksperimental** [comment]
> > Thanks @eksperimental!
> > PS: btw, I have enabled Two factor auth organization wide for security but you don't have it enabled. They should have sent you an e-mail. Once you enable it, please let me know, I believe I need to give you access again.
> 
> @josevalim I have enabled it. Yes, you need to give me access again

ping @josevalim

**Comment by eksperimental** [comment]
Thank you @josevalim.
I also had a commit permissions to https://github.com/elixir-lang/elixir-lang.github.com, just in case you want to revert things as they were before.

**Comment by josevalim** [comment]
@eksperimental can you please resubmit this issue using checkboxes in the issue for everything that is still valid? PRs are welcome, as EPUB is HTML. Thank you!

**Comment by eksperimental** [comment]
> can you please resubmit this issue using checkboxes in the issue for everything that is still valid?

Updated and checked

**Comment by josevalim** [comment]
Now that Erlang support in ExDoc is almost complete, we are gearing towards v1.0. So if someone would like to pick this up, it would be awesome.

**Comment by milmazz** [comment]
> Now that Erlang support in ExDoc is almost complete, we are gearing towards v1.0. So if someone would like to pick this up, it would be awesome.

Let me see what issues are still around, and I'll try to catch up with the code and help fix bugs.

**Comment by milmazz** [comment]
> Can we make smaller the gap between a function signature and a function spec?, it's like a full line empty and it looks a bit odd.

It probably is about personal preferences, but I don't mind the current spacing. The following is on Apple Books:

![Screenshot 2024-01-23 at 7 00 39 PM](https://github.com/elixir-lang/ex_doc/assets/34700/4978800b-33ac-4e5c-ae1a-b8b4b790f97c)

**Comment by milmazz** [comment]
From the table of contents, it seems that we're considering the `groups_for_extras` option:

![Screenshot 2024-01-23 at 7 08 21 PM](https://github.com/elixir-lang/ex_doc/assets/34700/94d16dce-8269-4283-ae82-532a97cbbbf1)

But we're ignoring the details for `groups_for_modules`:

![Screenshot 2024-01-23 at 7 09 20 PM](https://github.com/elixir-lang/ex_doc/assets/34700/c81a7a17-8303-491e-bc2a-4e2caaa2735a)

So, I think I will work on this issue first.

**Comment by milmazz** [comment]
In the table of contents for the EPUB version, we prioritize the extra files, and then we render the modules and the mix tasks.

But in the HTML version, the Modules tab seems to have a "higher" priority than the extras or pages because is selected.

![Screenshot 2024-01-23 at 7 27 03 PM](https://github.com/elixir-lang/ex_doc/assets/34700/a8d31254-0f6a-49bc-8463-e2b126a4e7dc)

Is that okay, or should we change how we arrange the documents in the EPUB version to keep some consistency between both formats?

**Comment by josevalim** [comment]
@milmazz I am glad to go with whatever decision you believe makes the most sense here. :)

**Comment by milmazz** [comment]
> Deprecated notice is missing.
> For example in the Behaviour module, the "This module is deprecated. Use @callback and @macrocallback attributes instead." message is missing.

While I will prefer to see the following note in a more prominent background, I think this bug is already fixed.

<img width="620" alt="Screenshot 2024-01-24 at 9 46 49 p m" src="https://github.com/elixir-lang/ex_doc/assets/34700/f2b4d83a-ed68-444a-ac69-54ea11355fc6">


> Attributes such as since, or when the function is a macro are missing

This too seems to be fixed.

<img width="449" alt="Screenshot 2024-01-24 at 9 48 51 p m" src="https://github.com/elixir-lang/ex_doc/assets/34700/0ba02287-2e75-4422-a127-dfe56b303a82">

> "Anchor for this section" looks too big. I guess it could be removed, since AFAIK we cannot link from anywhere.

I don't see these links anymore. Fixed?

>  "link to this function" doesn't look as bad, but I see no use for it.

I don't see these either.

@eksperimental If you have any spare time, could you please close this ticket and open new ones but one ticket per issue? The way this is now arranged is difficult to track. I will work on setting up a new background for the deprecation note, so, you can skip creating that one. Thanks.

**Comment by milmazz** [comment]
> I will work on setting up a new background for the deprecation note, so, you can skip creating that one. Thanks.

Interesting that when I change the appearance to "light" on Apple Books the deprecation background is nice and clear, so, I will investigate how we can provide multiple "themes" for the EPUB clients.

<img width="556" alt="Screenshot 2024-01-24 at 10 04 14 p m" src="https://github.com/elixir-lang/ex_doc/assets/34700/5695b6ac-b6c1-4b5c-be1d-87598784de89">

**Comment by milmazz** [comment]
> @milmazz I am glad to go with whatever decision you believe makes the most sense here. :)

Thanks, I'm happy with what we have after https://github.com/elixir-lang/ex_doc/pull/1850 but I'm open to hear other opinions =)
