### ISSUE TITLE
Add prefix for explicit linking on module

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/ex_doc#1066]
Currently, erlang module is not autolinked in docs since it's impossible to tell it's for atom or erlang module. See [ExDoc: link to docs for Erlang dependency ](https://elixirforum.com/t/exdoc-link-to-docs-for-erlang-dependency/17691)

However, EDoc has module page, so it would be great if we can introduce new prefix for erlang module.

## Proposal

Markdown: Add `m:` prefix to the name.

- Erlang module: `m::brod_topic_subscriber`
- Elixir module: `m:MyModule`

Link

- Elixir module: keep the existing behavior (ex_doc link)
- Erlang module: add EDoc link - such as https://hexdocs.pm/brod/brod_topic_subscriber.html

**Comment by josevalim** [comment]
AFAIK we only link to Erlang modules, because opposite to Elixir, there is no standard for documentation in the Erlang community. I don't want to add new format for now until Erlang/OTP offiicially adopts the new doc chunk, so we can adopt those options with their input instead of one sided. For the reasons above, explicit references is the best call for now.

**Comment by chulkilee** [comment]
Seems like I wasn't clear enough. This is for markup in Markdown, not code annotation level. So doc chunk is not relevant here.

> there is no standard for documentation in the Erlang community

Is this true? [EDoc](http://erlang.org/doc/apps/edoc/chapter.html) seems to part of main Erlang/OTP , and I could not find any other doc generation tool.

I thought EDoc is de-facto Doc tool for Erlang, as ExDoc for Elixir - isn't it? Also please note that ExDoc already generates links with EDoc style for erlang functions :)

I'll update the title - @josevalim could you reopen it?

**Comment by josevalim** [comment]
I understand you correctly, the point above still stays.

The Erlang docs themselves actually are not generated with Edoc. Other projects like rebar3 and cowboy have their own style. Unfortunately we cannot assume a standard when it comes to Erlang modules.

**Comment by josevalim** [comment]
>  with EDoc style for erlang functions

IIRC this was mostly to cover Erlang stdlib. For anything outside of Erlang's stdlib, I don't think we should link to.

**Comment by chulkilee** [comment]
> The Erlang docs themselves actually are not generated with Edoc. Other projects like rebar3 and cowboy have their own style. Unfortunately we cannot assume a standard when it comes to Erlang modules.

Thanks for the explanation :heart: 

Seems like "standard on URLs of generated documentation"  should be a part of [Erlang Ecosystem Foundation – Documentation Working Group Proposal](https://erlef.org/documentation-working-group/)
