### ISSUE TITLE
EPUB: Broken links on Elixir embedded documentation

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#1075]
After creating an EPUB document from the Elixir source code I noticed that the embedded documentation introduce a couple of _broken links_ (basically the markdown link assumes that the extension is `.html`) in the following modules:

* [`Kernel`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L130-L142)
* [`Application`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/application.ex#L451-L454)
* [`Config`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/config.ex#L36-L39)

Also, some _broken links_ can be found on some guides like: `guards`, `library-guidelines`, and `syntax-reference`.

So, my question is how we want to handle those cases from ExDoc?, at least for the EPUB document generation. Should we explicitly transform the extension on those cases in the ExDoc code-base, seems a bit ugly, but I'm open to suggestions. /cc @josevalim

**Comment by josevalim** [comment]
I can’t think of anything better than that. I.e. we have to rewrite local
links from html to xhtml.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
what if we embrace that extras pages are always in markdown (though that might change when we support other beam languages) and support:

```
[Compatibility and Deprecations](compatibility-and-deprecations.md)
```

and when we parse this we transform it to .html and .xhtml respectively? A nice side benefit is these links will now work on GitHub too (it occasionally comes up in issue trackers). Or that's too clever and may have unintended consequences? Notably, doesn't seem appropriate to show `.md` in IEx.

**Comment by josevalim** [comment]
I like keeping it .md so it works on GitHub. Great call. IEx wil have to handle it too. Keeping it as `.md` makes it easier to handle it there as well.
