### ISSUE TITLE
Warn if `:main` does not point to an existing file

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#1076]
It is easy to give the wrong casing on this config. Since some file systems are case insensitive it would work locally but not when uploaded to hexdocs.pm.

**Comment by cybrox** [comment]
Can look into this

**Comment by josevalim** [comment]
@cybrox I think we raise a warning but our warning doesn't check for the casing when it runs on a case insensitive OS. So we need to change the warning to check for casing. Probably we should stop using File.exists? and instead we need to get the dir the file name, perform a File.ls and see if the filename is in the returned result or something.

**Comment by cybrox** [comment]
Ah, you're right. I've dug up my MacBook, going to take a look at this.
