### ISSUE TITLE
Documentation for typespecs

### ISSUE THREAD

**Issue by narrowtux** [elixir-lang/ex_doc#1081]
It would be great to be able to document `@type`-specs. 

My use case would be documenting all the options a function supports in an options keyword list:

```elixir
@doc "Slugs the foobar"
@type slug_foobar :: {:slug, boolean}

@doc "Prefix to use in the foobar"
@type foobar_prefix :: {:prefix, Path.t}

@doc "Options for foobar"
@type foobar_options :: list(slug_foobar | foobar_prefix)

@doc "Executes foobar on the given bar"
@spec foobar(any, foobar_options)
def foobar(bar, opts \\ []) do
  # ...
end
```

**Comment by cybrox** [comment]
You can use `@typedoc` for this, check out [this](https://github.com/elixir-lang/elixir/blob/v1.9.1/lib/elixir/lib/string.ex#L206-L213) as an example.

**Comment by josevalim** [comment]
Exactly as @cybrox said. Thanks!

**Comment by narrowtux** [comment]
Oh, cheers!
