### ISSUE TITLE
func doc is not generated when @impl is given

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/ex_doc#1084]
If `@impl` is given - either `true` or module name - the func doc is completely hidden (not even using the doc of the `@callback`).

Expected behavior would be: include the callback doc if `@doc` is missing, even `@impl` is given.

- Elixir: 1.9.1 (compiled with Erlang/OTP 22)
- ex_doc: 0.21.1

```elixir
defmodule My.Behaviour do
  @moduledoc """
  This is module doc
  """

  @doc """
  this is callback doc
  """
  @callback hello(String.t()) :: :ok
end

defmodule My do
  @behaviour My.Behaviour

  @impl My.Behaviour
  def hello(_foo), do: :ok
end
```

**Comment by josevalim** [comment]
Yes, it is documented as part of the `@impl` attribute. It automatically sets `@doc false` unless you explicitly override it.

**Comment by josevalim** [comment]
I don't see how we could do that without changing existing behaviour. Because even if we store in different places, you want to change the behaviour `@impl` no longer implies `@doc false`, correct? In your case, you need explicit docs.
