### ISSUE TITLE
Searches should search the function/macro/types titles

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1098]
This has bug me for quite some time since the new search has been introduced.
When I type something and I hit the enter key, I want to find it in the search results pages, regardless of whether it is the function name or it is in the text. It happens way too many times that I want to access a function name and I hit enter, to get no results, the function appears on the left bar as I type it, but when I hit enter it does not show in the results. You can try it with "List.foldl" in the Elixir docs.

So my proposal is that it should appear since the function name it is part of the documentation, and it should be prioritized to appear at the top

WDYGT?

**Comment by josevalim** [comment]
I believe we can easily make It work by also indexing “mod.fun” and “mod.fun/arity”. You can even see “list foldl” appears in the results.

**Comment by eksperimental** [comment]
Well it happends more often when Im searching for a "non-qualified" function name, and I hit enter.
Basically, what I would like to propose is to have the search results on the left sidebar that we've got just before hitting `ENTER`, merged in the the search results on the right, and be at the top of the list.

**Comment by eksperimental** [comment]
...since search term if they are part of the function title, and it should be ranked more relevantly

**Comment by josevalim** [comment]
If you search only for “foldl” it already works today and it has high
relevance.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment]
awesome. thanks for the fixes

**Comment by eksperimental** [comment]
@josevalim the search results are not prioritizing functions with the search name in their terms.
Searching for `quote` gave me a long list of results and `Kernel.SpecialForms.quote/2` in result no. 38!

**Comment by eksperimental** [comment]
should I create a new issue, or we reopen this one?

**Comment by josevalim** [comment]
I already assigned a very high weight to function names. We can increase it
a bit but it is unlikely we will solve all of these cases.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
