### ISSUE TITLE
Search "MODULE." should list all module functions in the sidebar and the search results

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1099]
So far it is not giving any results. 
Let's say I type "Agent.", it should give me all functions in the Agent module

**Comment by josevalim** [comment]
I will have to disagree with this one. The autocomplete and the search are distinct functionalities. If necessary, we can make it clearer that search is full-text based. For example, we may add some fuzzing to the autocompletion (similar to editors) that won't be available on search. I don't think we should expect complete parity between both.

**Comment by eksperimental** [comment]
That's acceptable, but IMO still "Agent." should return in the sidebar all functions within Agent module.
Let's say I want to quickly glance all functions in a module because I can't recall its name.
