### ISSUE TITLE
Search doesn't deal with complete and incomplete `function/arity` terms

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1100]
It doesn't return any results in the main search page:

while
* it does deal with `module.function/arity` (ex. `List.foldl/3`)
* it does deal with `module.function` (ex. `List.foldl`)

also
* it DOES NOT work with `function/arity` (ex. `foldl/3`)
* it DOES NOT work with `function/` (ex. `foldl/`)
* it DOES NOT work with `module.function/` (ex. `List.foldl/`)
* it DOES NOT work with `incomplete_function_name` (ex. `fold_do`)
* it DOES NOT work with `module.incomplete_function_name` (ex. `List.fold`)

**Comment by josevalim** [comment]
Yes, and it won't work, as mentioned in previous issues. It is full-text search, it isn't autocomplete. I will change the copy to make it clear which kind of search it is.

**Comment by eksperimental** [comment]
Stil, IMO it should deal with `function/arity` which is the title of the function within the module.

**Comment by josevalim** [comment]
Yup, just pushed function/arity and title boosting. Thanks!

**Comment by eksperimental** [comment]
@josevalim `foldl/3` still gives no results

**Comment by josevalim** [comment]
Fixed.

**Comment by eksperimental** [comment]
Sorry, but it is still not showing up

**Comment by josevalim** [comment]
it is definitely working here. `foldl/3` directly from Elixir docs.

**Comment by eksperimental** [comment]
I see it now. thank you
