### ISSUE TITLE
ExDoc should pull function specs when using defdelegate

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1101]
related #902

**Comment by josevalim** [comment]
This has come up a couple times and the answer is the same: it is not trivial to copy specs because they may refer to local types, so we would need to copy or rewrite those too, which is further complicated by opaque and private types. So we can’t do much here.

**Comment by eksperimental** [comment]
So what is adviced here? to copy and paste the specs from the function that we delegated to?

**Comment by josevalim** [comment]
You can’t quite copy and paste either, but yes.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
