### ISSUE TITLE
Describe math in ExDoc

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/ex_doc#1102]
I'm developing Numexy, which is a math library for Elixir.

I'd like to describe mathematical expressions in ExDocs because to understand the program code requires to understand the numerical theory of it using them.

Can I describe them in ExDocs?

If not, I propose to make the notation of them follow Jupiter Notebook: https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html

**Comment by josevalim** [comment]
I know there are JS libraries for formatting mathematical annotations. ExDoc supports you to add custom ode to your HTML header, so my recommendation is for you to add such JS libraries to your header and have them automatically format it for you. It is probably not a feature we would focus to have on ExDoc itself for now.

**Comment by zacky1972** [comment]
Oh, really? Would you teach me how to add custom JS libraries?

**Comment by zacky1972** [comment]
I got an information.

Is it to add `before_closing_head_tag` to the following `project` setting? :
 
https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html

**Comment by josevalim** [comment]
Yes!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
