### ISSUE TITLE
Make Exceptions a sub-grouping inside modules

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1104]

**Comment by archdragon** [comment]
Took a look at this one today.

One quick question - should we change the grouping rules on the "frontend" (in the JS menu generation) or on the "backend" side (in the Elixir doc generation code)?

### a) changing the groupings just on the "frontend" side


Currenly JS code receives a data structure that looks like:

```
{
  "extras": ...
  "exceptions": ...
  "modules": ...
  "tasks":...
}
```

So we can just ignore "exceptions" when generating  root menu elements and add them in the part that displays modules.

### b) changing the groupings on the "backend" side

We can change the elixir code to generate the data structure that will look more or less like this:

```
{
  "extras": ...
  "modules": [
    ...
    (append exceptions here)
  ]
  "tasks":...
}
```
This seems like a cleaner solution, but will still need some adjustments/cleanup in JS/HTML and EPUB generators.

b) is also a potentially breaking change for other, custom generators that people might be using (ie. if they assume that the `exceptions` key is always present).

I assume b) is what we want, but just want to make sure there is no additional context behind this issue.

**Comment by archdragon** [comment]
This is how I see it (and how I understand the "sub-grouping inside modules"):

![image](https://user-images.githubusercontent.com/1810732/72680548-5eae5480-3abb-11ea-8a08-7977f8adf208.png)

^ I'm assigning Exceptions to an "Exceptions" group, which is always displayed last under the "Modules" top menu item.

**Comment by josevalim** [comment]
Precisely! And i would make "Exceptions" the last group (exactly as you did below deprecations).
