### ISSUE TITLE
Tooltips should pop-up when hover in any part of a custom link

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1105]
I have the following text,

```
Converts a data structure into a [`Phoenix.HTML.Form` struct](`t:Phoenix.HTML.Form.t/0`).
```

but the tooltip is only showing when I hover `Phoenix.HTML.Form`, but "struct" which is part of the link doesn't show this behaviour. it is a confusing, as it should cover the whole of the anchor text IMO,  since what gives the order of what to link to is "(`t:Phoenix.HTML.Form.t/0`)" and what's inside the brackets shouldn't matter

/cc @archdragon

**Comment by eksperimental** [comment]
Additionally, if there is no anchor text that uses backticks, no tooltip is shown at all

**Comment by archdragon** [comment]
> but the tooltip is only showing when I hover Phoenix.HTML.Form, but "struct" which is part of the link doesn't show this behaviour. it is a confusing, as it should cover the whole of the anchor text IMO, since what gives the order of what to link to is "(t:Phoenix.HTML.Form.t/0)" and what's inside the brackets shouldn't matter

> Additionally, if there is no anchor text that uses backticks, no tooltip is shown at all

I somehow assumed using backticks are always there, but I can totally see how it makes sense to have tooltips working for links without them.

The change is simple - let me just check if it does not create any additional issues and I'll prepare a small PR :)

![image](https://user-images.githubusercontent.com/1810732/68229638-e8d83800-fff7-11e9-83c2-2294e0a127ea.png)

**Comment by eksperimental** [comment]
Thank you @archdragon
