### ISSUE TITLE
Code fence with more than 3 backticks

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/ex_doc#1108]
To include code with three backticks, GFM allows wrapping the code with more than three backticks.

From https://github.github.com/gfm/#fenced-code-blocks

> A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~).

For example:

`````
````elixir
defmodule Foo do
  @moduledoc """
   Foo bbar

   # Example

   ```elixir
      defmodule MyFoo
      end
   ```
  """
end
````
`````

This is rendered in GFM  as follows:

````elixir
defmodule Foo do
  @moduledoc """
   Foo bbar

   # Example

   ```elixir
      defmodule MyFoo
      end
   ```
  """
end
````

For now, I circumvent it with using `~~~` instead of using four backticks.

Not sure this is earmark bug or ex_doc though.

**Comment by OvermindDL1** [comment]
It's not just a GFW thing, but in every markdown engine I routinely use.  You can use 3-or-more backticks to delinate code blocks:

Like this:
`````
````
Like to delinate code fences:
```elixir
Some code!
```
````
`````

Which becomes:
````
Like to delinate code fences:
```elixir
Some code!
```
````

And of course I wrote it with 5 backticks.  ^.^

**Comment by wojtekmach** [comment]
> Not sure this is earmark bug or ex_doc though.

Yeah, that'd be responsibility of the markdown engine (e.g. earmark) to handle.
