### ISSUE TITLE
Allow custom generators?

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/ex_doc#1115]
I'm building a library which makes a nice interface for ziglang NIFs in elixir (https://github.com/ityonemo/zigler).  One of the features is that it takes zig code, parses the docstrings in the zig code, and marshals it into elixir documentation.  I can readily accomplish this by passing a custom generator to `Mix.Tasks.Doc.run/3` inside of a custom mix task.  However, this won't be executed as a part of the `mix hex.publish` pipeline.  It would be nice to be able to supply a custom generator as part of the config! thanks!  (Discussion welcome -- is this a bad idea because it could make forward improvements difficult?; PR forthcoming)

**Comment by wojtekmach** [comment]
Note, you can achieve the same result by overriding `docs` task with an alias that calls Mix.Tasks.Doc.run/3 with desired arguments.

But I think your change about customising generator is fine too, not sure how common it would be though, I believe passing custom generator so far was only used for tests.

**Comment by josevalim** [comment]
Oh, you can override the docs task by doing this:

```
def project do
  [aliases: [docs: "your_other_mix_task"]]
end
```
