### ISSUE TITLE
Add repo link

### ISSUE THREAD

**Issue by skbolton** [elixir-lang/ex_doc#1117]
I have had the case pop up a couple of times lately where I wish that the docs had a link to the source code repository. I think this would be an awesome feature to have.

**Comment by skbolton** [comment]
For the record I would be willing to put some work on making this happen just want to get information if this would be something that is considered useful.

**Comment by wojtekmach** [comment]
If you set :source_url and :source_ref in your project docs configuration, a source link will be added on each module/function/etc like here: https://hexdocs.pm/ecto/Ecto.Changeset.html

If you propose to have something beyond this, could you describe in detali what you have in mind?

**Comment by skbolton** [comment]
Ha! I had never noticed those like code links before. That works perfectly!
