### ISSUE TITLE
The hierarchical menu of html docs is hard to understand for a newcomer

### ISSUE THREAD

**Issue by jukvalim** [elixir-lang/ex_doc#1119]
This is from the perspective of a person who just got into Elixir (loving it!). It took me embarrassingly long time to grok how the menu at hexdocs.pm works.

I think the issue is that there are four (maybe five) hierarchy levels in the menu, but it's not something that is visually intuitively clear. Once you start clicking around, each hierarchy level behaves differently.

-The first level of hierarchy flash-changes the contents of the second-level hierarchy under the first-level menu dynamically.
-Clicking on an item in the second-level hierachy opens the third level of hierarchy under the particular item, tree-menu style.
-The third level items are links if they don't have children. If they have, they open fourth level under them, tree menu style.
-A fourth level item opens the fifth level child items under it, tree menu style. If the item doesn't have children, it works as an anchor link.
-Fifth level items are always anchor links, as far as I can see.

On each level, where we are in the document hierarchy is illustrated differently.
Here is an example: https://hexdocs.pm/elixir/GenServer.html#t:debug/0
First level, "MODULES": Purple horizontal line, subtle color change
Second level, "GenServer": Subtle color change
Third level, "Types": No illustration
Fourth level, "Option": Subtle color change, arrow in front of the item

What I mean by my "maybe five" comment above is that "Summary" is another hierarchy level, above "Types", "Functions" and "Callbacks", but this cannot be seen in the menu.

All this doesn't matter that much once you get used to the way it works, but it's less than ideal for a newcomer trying to look at guides.

**Comment by josevalim** [comment]
Hi @jukvalim!

Thank you for your input. We are aware of the issues with the sidebar and we have discussed them a couple times. However, in order to address them properly, we would need a full sidebar redesign and we would probably need to hire someone to do so. It is something we are planning to do this year, since we want to start supporting Erlang projects, so hopefully we will have news sooner rather than later.

Btw, great last name! :D Welcome and happy new year!

**Comment by jukvalim** [comment]
@josevalim Splendid! Thank you for your fantastic work, and happy new year!
