### ISSUE TITLE
Typo / incorrect use of class in html - Library Guidelines

### ISSUE THREAD

**Issue by HoumanVSR** [elixir-lang/ex_doc#1121]
Hi,
If you please go to:
https://hexdocs.pm/elixir/library-guidelines.html#avoid-using-exceptions-for-control-flow

![Screen Shot 2020-01-14 at 2 41 06 pm](https://user-images.githubusercontent.com/59855903/72312334-eb33ce00-36db-11ea-86b6-0561afc7d7bd.png)

in the HTML code it is:
![Screen Shot 2020-01-14 at 2 41 53 pm](https://user-images.githubusercontent.com/59855903/72312380-128a9b00-36dc-11ea-8ea4-375eba5c38bd.png)

The HTML class `err` needs to change to `w`

Cheers

Thanks

**Comment by josevalim** [comment]
Hi, can you please report it to https://github.com/tmbb/makeup_elixir? That’s the project that performs syntax highlighting. Thanks!

**Comment by HoumanVSR** [comment]
Done. Thanks
