### ISSUE TITLE
nest_modules_by_prefix does not group all modules at once

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/ex_doc#1123]
### Environment

- ex_doc: 0.21.2
- Elixir 1.9.4
- Erlang 22.2.2

`docs` option:

```
nest_modules_by_prefix: [
  B,
  B.B
]
```

Modules:

```elixir
defmodule B.A do
end

defmodule B.B.A do
end

defmodule B.C do
end
```

### Current behavior

Sidebar structure is:

```
B
    A
B.B
    A
B
    C
````

### Expected behavior

Sidebar should group modules like this, so that the nested group does not appear multiple times.

```
B
    A
    C
B.B
    A
````

**Comment by josevalim** [comment]
Thanks! A PR would be welcome!
