### ISSUE TITLE
0.21.3, release on hex legit?

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/ex_doc#1125]
There is a release of `ex_doc` on hex.pm that is not visible in the repository as of writing this.

The release in question is v0.21.3.

The diff has a bunch of Mac specific files added, also there's a bunch of obfuscated JS and CSS. I wasn't able to see much more as my mobile crashed.

**Comment by josevalim** [comment]
Yup, the tag has been pushed! Thanks!
