### ISSUE TITLE
Provide A Link In Hex Docs Package Referring To Hex Package Page

### ISSUE THREAD

**Issue by s0kil** [elixir-lang/ex_doc#1130]
The documentation page for a package ([Crawly on Hex Docs](https://hexdocs.pm/crawly)) should provide a link that refers back to the Hex package page ([Crawly on Hex](https://hex.pm/packages/crawly))

This will make the process of finding a package metadata, repository, etc simpler, easier and potentially improving SEO for a package.

**Comment by josevalim** [comment]
Hi @s0kil! ExDoc is a general documentation tool that is not tied to Hex, so we can’t always assume that there is a Hex package. For example, we use it for Elixir and Elixir is not a package. For this reason, we rather suggest for you to add links to the package source yourself. Thanks!
