### ISSUE TITLE
Support for other BEAM languages

### ISSUE THREAD

**Issue by lpil** [elixir-lang/ex_doc#1131]
Hello!

I'm interested in using exdoc to render documentation for [Gleam](https://github.com/gleam-lang/gleam/).

What is the current situation for use of exdoc with other languages? :)

Thank you,
Louis

**Comment by josevalim** [comment]
Hi @lpil!

We are currently working on supporting Erlang. Once the Erlang work is done, we will likely have a behaviour for languages to implement, making it relatively straight-forward to support Gleam.

In any case, implementing EEP 48 is a requirement for ExDoc to work, so if you don't support EEP 48 yet, then that is a good starting point. :)

**Comment by lpil** [comment]
Thanks for the update Jose. Is there somewhere I can follow the progress?

**Comment by josevalim** [comment]
https://github.com/erlef/eef-documentation-wg/issues

**Comment by lpil** [comment]
Thanks!

**Comment by josevalim** [comment]
Erlang is well supported at this point. There are places that could be improved, but the basic foundation is here. If any other beam language wants to use ExDoc, pull requests are welcome.
