### ISSUE TITLE
Function names sorting

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#1133]
should we keep non-letter functions together?

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/76071/76161985-eb2ed800-6138-11ea-85f4-b03e42ba9461.png">

**Comment by josevalim** [comment]
Yes, it would probably be helpful.

**Comment by michalmuskala** [comment]
Would it make sense to always separate them into an `Operators` group?

**Comment by wojtekmach** [comment]
@michalmuskala not sure, I actually like the idea but grouping sometimes makes things harder. Just the other day I forgot on Elixir docs there's a "Guards" group and couldn't find stuff in "Functions". Speaking of things in "Guards", some of them are operators and we can't have them in both groups.
