### ISSUE TITLE
Add Module Doc headings to the side nav

### ISSUE THREAD

**Issue by davydog187** [elixir-lang/ex_doc#1145]
# Feature Idea
The Elixir standard library, as an example, has a lot of great and useful module documentation. Take the [Supervisor](https://hexdocs.pm/elixir/Supervisor.html) module for example. There are several headings that contain useful information that are linkable

* https://hexdocs.pm/elixir/Supervisor.html#module-examples
* https://hexdocs.pm/elixir/Supervisor.html#module-child-specification
* https://hexdocs.pm/elixir/Supervisor.html#module-shutdown-values-shutdown
* https://hexdocs.pm/elixir/Supervisor.html#module-restart-values-restart
* https://hexdocs.pm/elixir/Supervisor.html#module-child_spec-1
* https://hexdocs.pm/elixir/Supervisor.html#module-module-based-supervisors
* https://hexdocs.pm/elixir/Supervisor.html#module-start_link-2-init-2-and-strategies
...etc

Now, when I'm directly linked to one of these sections from somewhere else, great! However, what if I'm just browsing the docs? Navigating the description can be quite tedious looking for a section, or even just discovering what is available.

My suggestion is adding a section in the sidebar, call it `Description`, `Module Docs`, etc. It would be a dropdown similar to `Types`, `Functions`, and `Callbacks` that when clicked, it reveals the names of all these sections, and links to them.

<img width="160" alt="Screen Shot 2020-04-15 at 12 27 57 PM" src="https://user-images.githubusercontent.com/1019721/79363879-7bb9be80-7f16-11ea-9e54-3f2dc61fc125.png">

**I would really like to implement this feature myself**, but I am first looking for guidance.

1. Is there a reason that this doesn't already exist?
2. Are there any technical hurdles I should know about?

## Thank you
I love `ex_doc`. It is best in class, IMO, and I would love to help improve it further.

**Comment by josevalim** [comment]
It is a great idea! Perhaps we can call it "Sections"? But it doesn't matter. We can decide the name later. Furthermore, we already have all of the logic to extract the headings out, that we already use for pages, so we can probably reuse it. :) PR is welcome!

**Comment by davydog187** [comment]
Yay! I'll get started then :)

**Comment by wojtekmach** [comment]
Should we have similar thing but for functions? A function would commonly have two sections "Options" and "Examples" but occasionally they have many more. Notably, [`quote/2`](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#quote/2) has 9 sections :)

**Comment by josevalim** [comment]
@wojtekmach maybe it is something to consider on the sidebar redesign (/cc @archdragon) but functions are already very nested. Not sure if worth it.
