### ISSUE TITLE
Optimize the front end build of ex_doc

### ISSUE THREAD

**Issue by davydog187** [elixir-lang/ex_doc#1153]
# Problem
I noticed that `ex_doc` was using jquery and handlebars, and wondered how large the frontend build of the project was. I was surprised that it was quite big.

```
~/D/e/doc/dist [moduledoc-sidebar-sections] λ du -h *.js
212K	app-6efcc579bb079899793d.js
40K	search_items-39b2a5cbd3.js
8.0K	sidebar_items-342be7f185.js
```

I quickly added [Webpack Bundle Analyzer]( https://github.com/webpack-contrib/webpack-bundle-analyzer) to the project to get more information.

<img width="1920" alt="Screen Shot 2020-04-26 at 6 43 49 AM" src="https://user-images.githubusercontent.com/1019721/80305259-c2ff4500-8789-11ea-840e-03a91e789afb.png">

As you can see, jQuery is taking up a considerable amount of space (84kb parsed), followed by `lunr` and `highlight.js`

# Proposed Solution
So why do we need jQuery in the first place? The reason is that `ex_doc`'s approach to front end is a bit old school. Append and replace containers, basically. First off, [You might not need jQuery](http://youmightnotneedjquery.com/), but I think its more about the approach than whether or not the browser supports some DOM API.

In order to optimize the front end bundle size and get it down by less than a third of what it is now, I suggest:

1. Replace jQuery, Handlebars and lodash.find with [Preact](https://preactjs.com/), which is a lightweight version of React that is well supported and popular in the JS community. At The Outline, we used it for 3 years to power our CMS and parts of our front end
2. The search functionality of `ex_doc` is likely not used on every visit. Regardless, `lunr` should be lazy loaded into the bundle. Luckily, webpack makes this easy to do through [Code Splitting](https://webpack.js.org/guides/lazy-loading/) and dynamic imports
3. SQL, Javascript and other languages are great to highlight, but also can be lazy loaded. 

## Pros
* Smaller bundle size means a faster webpage
* Moving to Preact will make the frontend implementation simpler and hopefully make it easier to contribute to.
* Any design changes to `ex_doc` would be easier to make with a simpler templating system :wink: 

## Cons
* Refactoring is expensive and takes time
* Preact is one choice of many in the frontend world. My experience has shown that it's a good one though!

I would love to move forward with this, but I would like to get a blessing that this is desirable before getting started.

**Comment by josevalim** [comment]
We will be very glad if someone contributes those changes since we don't have the expertize of doing it ourselves. :)

Regarding syntax highlighting though, I would not touch it for now. Our goal is to move as much as possible to `makeup`, so we do it at compile time, and remove the dependency on highlight.js altogether.

**Comment by davydog187** [comment]
I'll take that as a blessing! Thank you @josevalim and noted on highlight.js

**Comment by whatyouhide** [comment]
@davydog187 do you have an idea on a plan to make these changes incrementally, so that we can start ripping the benefits and make sure we move more "surgically"?

**Comment by davydog187** [comment]
@whatyouhide I was going to start with the lazy loading (2). As for the move from handlebars to something else, I'm not sure yet, but there is very likely an incremental path forward.

**Comment by whatyouhide** [comment]
Sounds great @davydog187, thanks for your answer! Lazy loading seems like a great place to start, agreed. :)
