### ISSUE TITLE
Broken links to dependent code

### ISSUE THREAD

**Issue by brettbeatty** [elixir-lang/ex_doc#1156]
The elixir docs have several broken links from autolinking failing to find modules that belong to applications like `:iex` and `:ex_unit`.

Examples include references to `IEx.Helpers.i/1` (https://hexdocs.pm/elixir/List.html#module-charlists) and `ExUnit.DocTest` (https://hexdocs.pm/elixir/writing-documentation.html#doctests).

The most closely-related issue I could find was https://github.com/elixir-lang/elixir/issues/9221, though it was attributed otherwise (accurately, I believe; module did not have docs). The solution there was to write the docs in such a way as to not include `ExUnit.CLIFormatter` in backticks.

It looks to me like the issue is with how `ExDoc.Autolink` handles modules for which `:application.get_application/1` returns `:undefined`. I'm looking here: https://github.com/elixir-lang/ex_doc/blob/1efd29116456106e80b03814e3f08c5814925ab5/lib/ex_doc/autolink.ex#L410 From what I can tell, any module for which an application can't be found is linked as if available in the current application. In the `ExUnit.DocTest` example above, it ends up trying to link to https://hexdocs.pm/elixir/ExUnit.DocTest.html.

I don't know what the best solution is. I think I would expect modules that cannot be found to just not be autolinked. `ExUnit.Doctest` would be like any other text in backticks. It may be interesting, though, to add an annotation for explicitly stating which application your module belongs to. Not this specifically, but something like `a:ex_unit:ExUnit.DocTest`.

**Comment by wojtekmach** [comment]
Thank you for the report, this is a regression in ExDoc. I see that https://hexdocs.pm/elixir/1.9.0/writing-documentation.html#doctests had the correct link.
