### ISSUE TITLE
Feature Request: Show "Table of Contents" for moduledoc

### ISSUE THREAD

**Issue by axelson** [elixir-lang/ex_doc#1158]
For modules with in-depth moduledoc's (such as https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html) the anchor links on the left do not catch the majority of the document. For LiveView in fact the "Summary" link is already 70% or so of the way through the document. It would be very helpful to have auto-generated links such as "Use cases", "Life-cycle", "Focus and Blur Events", etc.

I think it would generally be okay to generate these links by default, but only when the moduledoc has sections (i.e. markdown lines that begin with `#`, `##`, etc). I am not sure what the "heading" for this new moduledoc section would be, maybe "Details"?

To be clear I'm proposing adding a section like "Details" after "Top" and before "Summary":
![Screenshot 2020-05-01 16 37 33](https://user-images.githubusercontent.com/9973/80853219-96548e80-8bca-11ea-99a4-bbb39dfce2ac.png)

It would operate similarly to the other existing sections where it will start collapsed. If this seems like a viable solution I'd be willing to work on a PR.

**Comment by wojtekmach** [comment]
This is already done on master thanks to @davydog187, see: https://github.com/elixir-lang/ex_doc/pull/1148 :)

**Comment by axelson** [comment]
Ah, guess I must have missed that! Thanks davydog :heart:
