### ISSUE TITLE
Add support for links in the @deprecated tags

### ISSUE THREAD

**Issue by jvdvleuten** [elixir-lang/ex_doc#1159]
I tried adding a link to the Kernel.Config and Kernel.Config.Reader in the docs of https://hexdocs.pm/mix/Mix.Config.html, so it would point in the right direction. Unfortunately, the \` \` and () tags are not working inside of the @deprecated tag. 

I am not quite sure where to hook this in, so that links will generated to be output by the template...

**Comment by josevalim** [comment]
Correct. The deprecated tag is also used by command line tools, the compiler, and other places that are not markdown aware, so you shouldn’t use markdown aware code in there. So this behavior is expected. If necesssry, link to the function in the docs themselves.

**Comment by wojtekmach** [comment]
and fyi this is how this information is stored internally:

```
iex> {:docs_v1, _, _, _, _, meta, _} = Code.fetch_docs(Mix.Config); meta
%{deprecated: "Use Config and Config.Reader instead"}
```

as you can see it's unstructured and for the reasons mentioned above we'll keep it that way.

**Comment by jvdvleuten** [comment]
Thanks :) Will try to update in the docs themselves.
