### ISSUE TITLE
feature request/proposal: group callbacks in the same way as functions

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/ex_doc#1160]
related to:

https://github.com/elixir-lang/ex_doc/issues/876

Happy to take a crack at it and submit a pr, I will have some time starting early june.

**Comment by wojtekmach** [comment]
Do you have an example use case for this? Perhaps a public project docs that would benefit from it?

**Comment by ityonemo** [comment]
https://hexdocs.pm/transport/Transport.html

Note that Transport.Tcp and Transport.Tls are broken into "Server Functions" and "Client Functions" and I'd like to do that for Transport callbacks too.

**Comment by josevalim** [comment]
@ityonemo can you please submit a PR for this? Here is the code that adds this functionality for docs: https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/retriever.ex#L228 We can either introduce groups_for_callbacks or make the groups_for_functions generic.

**Comment by ityonemo** [comment]
Will do!  It might be a bit though as I've just started a new release cycle at work.

**Comment by josevalim** [comment]
Closing this for now. If there is still interest, please submit a PR!
