### ISSUE TITLE
Breaking change in 0.22: HTML entity support

### ISSUE THREAD

**Issue by garthk** [elixir-lang/ex_doc#1168]
Not mentioned (explicitly?) in the change log:
```elixir
  @doc "&mdash;"
```
… in 0.21.3 will result in the HTML
```html
&mdash;
```
… but in 0.22.0 will result in the HTML
```html
&amp;mdash;
```
… with similar results for `&hellip;` _etc._ This diverges from 0.21 and [GitHub Flavoured Markdown](https://github.github.com/gfm/#entity-and-numeric-character-references).

**Comment by wojtekmach** [comment]
Thank you for the report, that's definitely a regression.

**Comment by josevalim** [comment]
Closing in favor of #1190.

**Comment by wojtekmach** [comment]
Btw, this issue has been fixed by switching to https://hex.pm/packages/earmark_parser.
