### ISSUE TITLE
See "Foo" section docs and linking

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#1171]
It's common to refer to other sections in the docs, should we link them?

It's actually super easy, see: 
* https://github.com/wojtekmach/elixir/commit/dfbb4fc42308a09e39ef33a7fc9105c270980cb5#diff-3b89dff3429a39440b077c60dd5cd932R38

* http://wojtekmach.pl/otp_docs/elixir/mix/Mix.Tasks.Test.html#module-command-line-options

There are 2 minor problems with it:

- [ ] it shouldn't trigger a popover 
<img width="832" alt="image" src="https://user-images.githubusercontent.com/76071/82143691-01969580-9846-11ea-8f9c-340979b4e6b1.png">

- [ ] We should probably trim `` ` (#module-coverage)` `` in IEx as it's not useful
<img width="819" alt="image" src="https://user-images.githubusercontent.com/76071/82143668-c98f5280-9845-11ea-96ce-f2a655772f27.png">

both seem easy to fix.

What do you think?

**Comment by wojtekmach** [comment]
Oh, worth mentioning that since we put module section links in the sidebar there's perhaps less of a need for this but I think it's still worth pursuing.

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by eksperimental** [comment]
@josevalim can you remind me what was the reason we were not linking internally in Elixir? Was is just becuase IEx was showing the link, or something else?

**Comment by ggpasqualino** [comment]
What's the status on this? Could I give it a try? I also felt the need to have this before https://github.com/dashbitco/broadway/pull/169/commits/04c47febd7ff03e67566b427da78798262ca0727 😄

**Comment by wojtekmach** [comment]
@ggpasqualino sorry for dropping the ball on this, if you are still keen on giving this a shot, please do after we land full Erlang support which should be in ExDoc v0.26.0.

I'm gonna close this for now.
