### ISSUE TITLE
Correctly link to sibling in umbrella

### ISSUE THREAD

**Issue by mathsaey** [elixir-lang/ex_doc#1173]
When documentation is generated for an entire umbrella project at once, links between siblings do not behave as expected. I'll explain the exact issue based on an example scenario:

- Umbrella project `:parent`, with child applications: `:core` and `:other`.
- `:core` contains definitions which are used by all other child applications.
- Documentation is generated for the entire umbrella application at once (`mix docs` is invoked in `:parent`). 
- Functions in `:other` may return types defined in `:core`. Therefore, we want to use `t:Core.Type.t/0` inside the documentation of `:other`.
- **expected behavior:** Using `t:Core.Type.t/0` inside the documentation of `:other` generates a link to `Core.Type` inside the umbrella documentation (`<base url>/parent/doc/Core.Type.html#t:t/0`). 
- **actual behaviour:** ex_doc treats the sibling dependency as any other external dependency and generates a link to hexdocs: (`https://hexdocs.pm/core/Core.Type.html#t:t/0`)

It would be nice if ex_doc could detect sibling applications and adjust the generated link accordingly.

**Comment by josevalim** [comment]
ExDoc, at the moment, can only link to other hexdocs Dependencies, which always assumes a flat structure. We want to support custom linking based on the app, but it is not currently in our plans. If someone wants to submit a PR, we would gladly merge it.

**Comment by mathsaey** [comment]
I'm not 100% sure if I understood you correctly.  As far as I understand a "sibling link" is not a link to an external dependency; instead, it is an internal link to the documentation that's currently being generated. 

So wouldn't a fix amount to: 
1. Detecting if the documentation is being generated for an umbrella project.
2. Checking if a given "target" links to a module of a dependency inside the umbrella
3. Linking to the current documentation if this is the case.

I might take a stab at doing this, but since I'm not familiar with the internals of ExDoc I want to be sure I understand the problem correctly. I'm guessing it might not be possible to verify if (2) is the case.

**Comment by josevalim** [comment]
Exactly. ExDoc treats everything as an external dependency. So we would need to teach it how not to. We can probably skip step 1, but we would need to detect which deps are umbrella siblings (2) and then step 3.
