### ISSUE TITLE
What is ExDoc's versioning policy?

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/ex_doc#1176]
ExDoc is still at sub-stable versions if we were to look at it from a Semantic Versioning perspective, where every new version might break behaviour of the previous one.

However, at the same time, many projects (essentially all projects that are published to HexPM at least) depend on ExDoc using the document string `~> 0.x`, which will happily switch over to the newest version that might not necessarily backwards compatible.

So is ExDoc attempting to follow another versioning policy than normal Semantic Versioning?

There probably is a good reason for ExDoc to it the way it is currently doing, but I cannot find it documented anywhere. Maybe this could be added to e.g. the README?

**Comment by josevalim** [comment]
It is semantic versioning but we still have breaking changes on the way - especially as we add Erlang support - which is why we don't plan to release v1.0 quite yet.
