### ISSUE TITLE
Unexpected bahavior on hovering over a download link

### ISSUE THREAD

**Issue by wesley6j** [elixir-lang/ex_doc#1177]
Example [Phoenix 1.5.3 doc](https://hexdocs.pm/phoenix/overview.html): 
> If you would prefer to read these guides as an EPUB [click here!](Phoenix.epub)

**Comment by josevalim** [comment]
We should probably check if the extension is `.html` before we do the pop-up thingy. :)

**Comment by josevalim** [comment]
Another fix related to the pop-over is that we are loading the pop-over for "#module-" anchor tags and we probably don't want to. We should probably check that if anchor tag finishes with `/N`, where N is a number.

**Comment by archdragon** [comment]
Thanks for catching that! I've addressed both issues in #1234
