### ISSUE TITLE
Difficult to access mix tasks docs for gettext at hexdocs.pm

### ISSUE THREAD

**Issue by smaximov** [elixir-lang/ex_doc#1179]
_(originally reported in the gettext repo, see elixir-gettext/gettext#250)_

At [hexdocs.pm](https://hexdocs.pm/gettext), click on the "MIX TASKS" section in the sidebar:

![Screenshot from 2020-05-28 11-24-32](https://user-images.githubusercontent.com/1370047/83118028-7d120580-a0d6-11ea-9e4c-b787faf863a3.png)

## Expected behaviour

The list of all mix tasks for gettext is shown.

## Actual behaviour

Nothing happens (aside from modifying the page URL fragment to `full-list`). Also, there's no package version selector.

## Workaround

You can still access mix task docs by navigating to the URL corresponding to a mix task module (eg. [Mix.Tasks.Gettext.Extract](https://hexdocs.pm/gettext/Mix.Tasks.Gettext.Extract.html)).

## Environment

I can reproduce the issue with the following browsers:

* Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
* Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

The current `gettext` version (v0.18.0) is locked at [v0.21.3](https://github.com/elixir-gettext/gettext/blob/v0.18.0/mix.lock#L3).

**Comment by wojtekmach** [comment]
Thank you for the report, this is really weird, docs for get text v0.17.0 https://hexdocs.pm/gettext/0.17.0/Gettext.html (generated with ExDoc v0.20.2) worked fine.

Unfortunately, I wasn't able to reproduce this locally. FWIW I send a PR to update ExDoc: https://github.com/elixir-gettext/gettext/pull/251.

**Comment by josevalim** [comment]
Good call, i pushed a fixed version with latest ExDoc.
