### ISSUE TITLE
Clicking same-page anchor in floating sidebar should close sidebar

### ISSUE THREAD

**Issue by henrik** [elixir-lang/ex_doc#1194]
Hi! Whenever I check docs on my phone, I find this a little frustrating:

![issue](https://user-images.githubusercontent.com/216/85635567-100e7300-b676-11ea-902e-2c942e483f0e.gif)

If I click/tap a function in the floating sidebar, I want to read about it, not keep navigating – so I think it'd make sense for the sidebar to close when I click on it.

On a small display the sidebar is effectively modal. So it may also make sense to close it if clicking/tapping outside the sidebar – though perhaps that should be filed as a separate issue.

**Comment by josevalim** [comment]
I understand the need but, I often click on the wrong place on my phone, given the combination of large thumbs and small phone, and I would be extremely upset if I had to go through the whole dance again. :) So I will keep this one as a feature. :D

**Comment by henrik** [comment]
@josevalim Hehe, that's fair. What about if tapping outside the sidebar would close the sidebar, then? That would be intuitive IMO and might address both concerns to some extent.

**Comment by josevalim** [comment]
@henrik I like that :+1: A PR is welcome, but it is probably easier said than done. :)

**Comment by henrik** [comment]
Great. I may look into it sometime then :) Thank you!

**Comment by henrik** [comment]
Another approach I just thought of would be to make it more fat-finger-friendly on small displays - so it does close on click but it’s much harder to misclick.
