### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1198]
- `/` doesn't work, while `s` does.
- `?` doesn't work either

tested in latest versions of Chromium and Firefox.

**Comment by josevalim** [comment]
Both work here. AFAIK keyboard shorcuts are actually tricky when it comes to location and what not, so you need to find the proper keys it matches to and maybe we should "localize" the UI.

**Comment by eksperimental** [comment]
> Both work here. AFAIK keyboard shorcuts are actually tricky when it comes to location and what not, so you need to find the proper keys it matches to and maybe we should "localize" the UI.

well. the thing is it is working with GitHub, so maybe we can find out what they are doing and do it here.
One of the keys requires the use of <kbd><kbd>Shift</kbd></kbd>, the other one doesn't

**Comment by eksperimental** [comment]
Can we reopen? Still `/` doesn't work , neither `?`

**Comment by eksperimental** [comment]
Sorry, it does work. I just had to run `mix build`. Thank you.

**Comment by cw789** [comment]
😅
