### ISSUE TITLE
Search should support SIGILS

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1203]
If I type `~` I should get a list of all `sigil_*/2` functions , and if I type `~s` I should get `sigil_s/2`

**Comment by wojtekmach** [comment]
To play the devil's advocate, we cannot (and won't be able to without changing parser) do `iex> ~<tab>` either. I think it is consistent for the autocomplete suggestion to be a strict superset of your input.

**Comment by eksperimental** [comment]
Well. search results doesn't return anything. I think it is misleading for beginners who wouldn't know the inners of this feature.

**Comment by josevalim** [comment]
If someone wants to contribute, we would accept it, but given the unknowns and potential complexity of this feature, I wouldn't keep it in the "roadmap". Thanks!
