### ISSUE TITLE
QA report on search functionality

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1204]
* [ ] 1. Searching for  `~` gives no results, why the suggestions in the side appear. (In Elixir project you can see `=~` or `Bitwise.~~~`. So it is inconsistent the behaviour of the sidebar with the search results.

* [x] 2. In the previous example, the message in the search result page is weird. It mentions `EDIT_DISTANCE`.
  > Search results for ~
  > Invalid search: expected either a field or a term, found EDIT_DISTANCE.

  Related: https://github.com/elixir-lang/ex_doc/issues/1203

 * [x] 3. Not typing anything in the search form and hitting enter, shows a blank page with the title SEARCH.
I think we should display a message or something. Additionally we can disable the submit button unless there is some text in the form.

* [ ] 4. Another cryptic message, is  if you search for `::` in the sidebar appears the speacial form `::/2` and in the search results this message
  > Search results for ::
  > 
  > Invalid search: unrecognised field '', possible fields: 'title', 'doc'.

* [ ] 5. Searching in ExUnit for "assert" gives results but "assert_" gives no results and "assert_*" does give results
* [ ] 6. Searching for a "submodule" name such as "LoadError" does not return anything, but "Code.LoadError" does.
  "Requirement" does not return "Version.Requirement", which should be at the top of the list.

**Comment by eksperimental** [comment]
3+
Another cryptic message, is  if you search for `::` in the sidebar appears the speacial form `::/2` and in the search results this message
> Search results for ::
> 
> Invalid search: unrecognised field '', possible fields: 'title', 'doc'.

**Comment by eksperimental** [comment]
Searching in ExUnit for "assert" gives results but "assert_" gives no results and "assert_*" does give results

**Comment by eksperimental** [comment]
Searching for a "submodule" name such as "LoadError" does not return anything, but "Code.LoadError" does.
"Requirement" does not return "Version.Requirement", which should be at the top of the list.

**Comment by josevalim** [comment]
We probably need to split on dots for module names? 🤔

**Comment by eksperimental** [comment]
> We probably need to split on dots for module names? thinking

But if it is a substring, why isn't it finding it?

**Comment by garthk** [comment]
Related: I'd expect a search for ["handle_errors"](https://hexdocs.pm/plug/search.html?q=handle_errors) in the Plug documentation to bring up [Plug.ErrorHandler](https://hexdocs.pm/plug/Plug.ErrorHandler.html), but it doesn't. Previously raised as hexpm/hexdocs#21 but they sent me here.

**Comment by josevalim** [comment]
The reason why `~` and `:` cannot be searched is because they are reserved query keywords, that's explain in the docs below. The autocomplete and search are ultimately different, they are triggered by the same UI but once you trigger the search, the behaviour is different. Not much different to GitHub search.

**Comment by eksperimental** [comment]
points 4, 5 and 6 are still unsolved.

**Comment by josevalim** [comment]
Those are all correct to me. 4 shows the error message I mentioned. `assert` brings up `assert_impl` and others, `LoadError` brings the relevant results too. All verified here: https://hexdocs.pm/elixir/

**Comment by eksperimental** [comment]
Regarding

- 4. neither `::`  nor `:` are mentioned in the docs as special characters. Actually ":"  does return search results, it is "::" that does not.
- 5.  It is "assert_" does is reported not to work and still does not.
- 6. "LoadError" does not return results

**Comment by eksperimental** [comment]
give me a second, I was checking on a local version, maybe not the latest one. I will compare the results locally and in hexdocs.pm and update my previous comments

**Comment by eksperimental** [comment]
I have updated my comments based on hexdocs.pm's version of ExDoc.
https://github.com/elixir-lang/ex_doc/issues/1204#issuecomment-1013882573

**Comment by josevalim** [comment]
About 6:

<img width="921" alt="Screenshot 2022-01-16 at 15 54 59" src="https://user-images.githubusercontent.com/9582/149665198-ae61a9ed-1d8f-4c2c-b7f4-4a3d6d16d8e5.png">

The error message when you use `:` also indicates that `:` is being used as a field. For 5, please open up a separate issue.

**Comment by eksperimental** [comment]
> The error message when you use `:` also indicates that `:` is being used as a field

The error message is unclear. as we are not using foo:bar, only "::".
by the way shouldn't this feature only grep fro "field:" and "doc:" search terms?

**Comment by josevalim** [comment]
There isn't much we can do, that's how the full text library work. I will clarify the text though.

**Comment by eksperimental** [comment]
> There isn't much we can do, that's how the full text library work. I will clarify the text though.

I understand.  That's the best we can do I guess.
