### ISSUE TITLE
Retrieve docs as original Markdown?

### ISSUE THREAD

**Issue by arjan** [elixir-lang/ex_doc#1216]
It used to be the case that I could retrieve the raw doc annotations from modules, using `ExDoc.Retriever.docs_from_modules`. The returned `%ExDoc.ModuleNode` struct contained the raw markdown in `.doc` and `.docs` field. This has been changed recently so these fields contain an HTML AST.

I understand that I should not rely on internal functions, but my use case is that I extracted the docs from Elixir modules and integrated these into another system (a Jekyll site); where Jekyll did the markdown -> HTML transformation. What would be the best solution here?

**Comment by josevalim** [comment]
Use Elixir's official API for this, which is `Code.fetch_docs`. You can traverse the application directory to get all modules. :)

**Comment by arjan** [comment]
Thanks!!
