### ISSUE TITLE
Sort search results by arity if the same results have the same score, module and function name.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1221]
I search for "flatten" and I get `List.flatten/2` first, and second `List.flatten/1`.
If the search result has the same score and share the same module and name, we should sort by arity.

**Comment by josevalim** [comment]
It is very unlikely they will have the same score. The score is dictated by many things, such as how many times `flatten` appear in the docs. It is really best to treat the search as a "black box" instead of trying to fine grain the results it returns. :)
