### ISSUE TITLE
"Section" in sidebar should show arrow next to it when hover

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1229]
The new "Section" sections does not show an arrow next to it. I think it should work consistently as the rest of the tree branches that expand. As of now to achieve the same result we need to click in the "Top" branch

Introduced in https://github.com/elixir-lang/ex_doc/pull/1148

/@cc davydog187

**Comment by davydog187** [comment]
Happy to address this @eksperimental

**Comment by eksperimental** [comment]
Awesome @davydog187

**Comment by josevalim** [comment]
Ping @davydog187 :)

**Comment by davydog187** [comment]
Oy, I'm a bit behind on my OSS stuff. We just launched our product this week. I will try to get to it ASAP

**Comment by josevalim** [comment]
Good luck with the launch!

**Comment by davydog187** [comment]
@josevalim thanks! PR pushed up ;)
