### ISSUE TITLE
Bug: Reference popover for Kernel.<>/2 shows the introduction for the Kernel module.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1232]
/cc @archdragon

**Comment by eksperimental** [comment]
Same for the pipe operator `Kernel.|>/2`

**Comment by eksperimental** [comment]
Same for:  `||/2`, `</2`, `<=/2`, `>/2`, `>=/2`

**Comment by eksperimental** [comment]
I think the reason it is happening is because the href fragment in "id" of those links is escaped.

**Comment by archdragon** [comment]
> I think the reason it is happening is because the href fragment in "id" of those links is escaped.

Thanks, that's probably the case. Should be an easy fix - will take a look!

**Comment by eksperimental** [comment]
Thank you @archdragon
