### ISSUE TITLE
Show all the results for a empty search 

### ISSUE THREAD

**Issue by LauraBeatris** [elixir-lang/ex_doc#1236]
## Description

Should be possible to return all the results when searching for an empty value, instead of showing just a "Search" title. 

![Screen Shot 2020-07-26 at 14 18 09](https://user-images.githubusercontent.com/48022589/88485257-e5505c80-cf4a-11ea-98fc-df8421ec97e4.png)

## Solution

The template should show a different title according to the search value. 

For instance:
- A empty string: "All the results" 
- A valid result: "Search results for {value}" 

![Screen Shot 2020-07-26 at 14 22 21](https://user-images.githubusercontent.com/48022589/88485327-70315700-cf4b-11ea-936e-bfbfef3d276d.png)

**Comment by josevalim** [comment]
Hi @LauraBeatris, thanks for the report!

I don't think we should show all results for an empty string. None of the search engines I tried show something. However, I agree whatever we do right now is not clear enough. Maybe we should add some information instead? For example "<h1>Search</h1><p>Please type something into the search bar to perform a search.</p>". Would this be clearer? Thanks!

**Comment by LauraBeatris** [comment]
@josevalim Yup! Makes more sense 😁

I'll send a PR with that modification

**Comment by eksperimental** [comment]
I think I reported this, but I cannot find It.
What I proposed, additionally to what you suggesting here, it to disable the submit button if no string has been entered.

**Comment by eksperimental** [comment]
> I think I reported this, but I cannot find It.
> What I proposed, additionally to what you suggesting here, it to disable the submit button if no string has been entered.

It was here: https://github.com/elixir-lang/ex_doc/issues/1204 item 3

**Comment by josevalim** [comment]
There is no submit button though. Should we ignore `enter`? That can be confusing to some... So I would prefer to just showing the page and not changing submit.

**Comment by LauraBeatris** [comment]
Would be cleaner to not modify the events and just show a different title and text

**Comment by josevalim** [comment]
> Would be cleaner to not modify the events and just show a different title and text.

Agreed. Let's just add some extra text for now.

**Comment by eksperimental** [comment]
> There is no submit button though. Should we ignore `enter`? That can be confusing to some... So I would prefer to just showing the page and not changing submit.

the magnifying glass is a `<button type="submit" class="search-button">`, but yeah. disabling hitting ENTER as well.
Even Google uses this behaviour.
Either way is fine with me.

**Comment by josevalim** [comment]
> the magnifying glass is a <button type="submit" class="search-button">, but yeah. disabling hitting ENTER as well.

Yeah, good call on Google doing it. So it means we are probably fine with doing it too. But let's discuss that separately. The page can still be rendered manually without a proper input.

**Comment by eksperimental** [comment]
Showing the instructions of how to use the search page. same as what you get when no results are found seems like a nice option to show.

**Comment by LauraBeatris** [comment]
> Showing the instructions of how to use the search page. same as what you get when no results are found seems like a nice option to show.

Agreed! We should show the instructions too 

![Screen Shot 2020-07-26 at 15 02 34](https://user-images.githubusercontent.com/48022589/88486042-221f5200-cf51-11ea-8c71-a9fde84d57f5.png)

What do you guys think?

**Comment by josevalim** [comment]
Looks great!

**Comment by eksperimental** [comment]
Looks good. If we can stress that it we are showing this due to no string being entered. Either by using bold type in "Invalid search" or something.  Just to make it look different from the "no results found" page.
Thank you.

**Comment by LauraBeatris** [comment]
Just made a PR https://github.com/elixir-lang/ex_doc/pull/1238
