### ISSUE TITLE
compilation error with correct spec

### ISSUE THREAD

**Issue by zdcthomas** [elixir-lang/ex_doc#1239]
When compiling docs for my umbrella app, if there is a `@spec` tag with a `|` separating two values inside of a map, 
E.g this elixir-ls generate spec
```elixir
  @spec handle(%{__struct__: HTTPoison.Error | HTTPoison.Response}) ::
          {:ok, [any]}
```
running `mix docs` from the root of the umbrella app produces this syntax error message
```
  Generating docs...
  ** (SyntaxError) nofile:1: syntax error before: '{'
      (elixir 1.10.3) lib/code.ex:654: Code.format_string!/2
      (ex_doc 0.22.2) lib/ex_doc/autolink.ex:320: ExDoc.Autolink.typespec/2
      (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
      (ex_doc 0.22.2) lib/ex_doc/formatter/html.ex:86: anonymous fn/5 in ExDoc.Formatter.HTML.render_all/4
      (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ex_doc 0.22.2) lib/ex_doc/formatter/html.ex:83: anonymous fn/4 in ExDoc.Formatter.HTML.render_all/4
      (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
      (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
      (ex_doc 0.22.2) lib/ex_doc/formatter/html.ex:21: ExDoc.Formatter.HTML.run/2
      (ex_doc 0.22.2) lib/mix/tasks/docs.ex:343: anonymous fn/6 in Mix.Tasks.Docs.run/3
      (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ex_doc 0.22.2) lib/mix/tasks/docs.ex:342: Mix.Tasks.Docs.run/3
      (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
      (mix 1.10.3) lib/mix/cli.ex:82: Mix.CLI.run_task/2
      (elixir 1.10.3) lib/code.ex:926: Code.require_file/2
```

I'm fairly sure about the `|` being the differentiating factor, as changing only that to, for example ` @spec handle(%{__struct__: HTTPoison.Response}) ::
          {:ok, [any]}` works fine.
Am I writing specs wrong or is this an actual issue with the compilation happening here?

All other compiled actions work fine, e.g `mix test` `mix phx.server` `mix compile` etc

Versions:
elixir : 1.10.3
mix : 1.10.3
ex_doc : ~> 0.22

Let me know if there's any other info you need/If I'm being super dumb! Thanks!

**Comment by wojtekmach** [comment]
Could you try the latest ExDoc? I think we had something like this recently.

**Comment by zdcthomas** [comment]
is `v0.22.2` not the latest version?

**Comment by eksperimental** [comment]
> Could you try the latest ExDoc? I think we had something like this recently.

I am running it with master and it is there.

**Comment by eksperimental** [comment]
> ```elixir
>   @spec handle(%{__struct__: HTTPoison.Error | HTTPoison.Response}) ::
>           {:ok, [any]}
> ```

It is a bug, I think in Elixir Macro.to_string(),  I am looking into it.

for the time being you can obtain the same result with this ( and actually this is the recommended way to write the spec):
```
@spec handle(%ExUnit.TestModule{} | %ExUnit.Test{}) :: {:ok, [term]}
```

**Comment by zdcthomas** [comment]
Yeah, that's been our fix for now, we'll need to figure something else out for other fields that have an "union" typed value, Thanks for looking into it. I'm really to curious to see what you find!

**Comment by eksperimental** [comment]
ExDoc has nothing to do with it. Try that code and you will see it does not compile.
yes. Looking into it ATM. Thank you for the report.

**Comment by eksperimental** [comment]
> Yeah, that's been our fix for now, we'll need to figure something else out for other fields that have an "union" typed value, Thanks for looking into it. I'm really to curious to see what you find!

It is a bug in Code.Typespec module in Elixir.
I have already fix it. I submit a PR soon

**Comment by eksperimental** [comment]
This issue can be closed.
