### ISSUE TITLE
Details about the HTML AST

### ISSUE THREAD

**Issue by ScrimpyCat** [elixir-lang/ex_doc#1242]
I have a few questions about the new HTML AST approach. I'm not sure what's intentional or what might be a bug, as the docs are kind of non-existent (I'd be happy to update them though outlining the specifics).

## AST structure

Going off the `ast_to_html/1` function it would seem the AST is something like the following: `ast :: { tag :: String.Chars.t, attrs :: [{ String.Chars.t, String.Chars.t }], ast } | [ast] | String.t` can you confirm whether that's the expected type or is it something simpler? Maybe `ast :: { tag :: String.t, attrs :: [{ String.t, String.t }], ast } | [ast] | String.t`

```elixir
# Are these meant to be allowed by the API
{ :p, [id: :foo], "hello" }
{ [['p']], [{ 'id', [?f, ?o, "o"] }], "hello" }
# Or only this
{ "p", [{ "id", "foo" }], "hello" }
```

As the docs currently only refer to the ast as simply `term`. https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/markdown.ex#L19

## ast_to_html

https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html.ex#L129

This function is auto-encoding (`Templates.h/1`) any kind of element content, is this intentional? For intance raw text elements such as script or style blocks won't want their content encoded, so if those types of elements are meant to be possible then that could cause issues. 

On the other hand attribute values are not encoded and are just assumed to be compatible with double-quoted attribute value syntax. Is this desired? So we should be ensuring that the attribute values in our AST are compatible. e.g. instead of a Markdown processor returning this `{"p", [{"foo", ~S("bar")}], "hello"}` it should instead be returning this `{"p", [{"foo", ~S(&quot;bar&quot;)}], "hello"}`.

Will there be any ability to handle embedding other types of content aside from elements and plain text such as comments or CDATA?

**Comment by wojtekmach** [comment]
Hello!

> As the docs currently only refer to the ast as simply term. https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/markdown.ex#L19

Good call, we should definitely document that. The ast is basically:

```
ast :: [node]
node :: {atom, [{atom, String.t}], ast} | String.t
```

See https://github.com/erlef/documentation-wg/issues/3#issue-522052731 & https://erlang.org/doc/apps/erl_docgen/doc_storage.html for more information. 

> This function is auto-encoding (Templates.h/1) any kind of element content, is this intentional?

We need encoding for some aspects but for others it's indeed a regression (https://github.com/elixir-lang/ex_doc/issues/1189), it's still yet to be reconciled.

**Comment by josevalim** [comment]
One thing to keep in mind that the AST may change as we integrate both Erlang's Doc AST and Earmark AST. The long term goal is for both of these inputs to emit an ExDoc-specific syntax tree - but that is not fully fleshed at the moment.

**Comment by ScrimpyCat** [comment]
I see, but in the meantime that AST spec (the one you're showing @wojtekmach) is what is currently expected (won't be changing in a bugfix version of ExDoc)? Also is it a combination of the two that's allowed to be returned or just `ast`. e.g.

```elixir
@callback to_ast(String.t(), Keyword.t()) :: ast() | node() #this one
@callback to_ast(String.t(), Keyword.t()) :: ast() #or this one
```

And for attribute values should we just assume they need to be double-quoted compliant?

For instance if a Markdown producer returns the following AST: `[{ :p, [foo: ~S("bar")], ["hello"] }]` it would currently be converted to `"<p foo=\"\"bar\"\">hello</p>"` which isn't right. But if the producer returns the value `~S("bar")` either as one of `~S(&quot;bar&quot;)` or `~S('bar')` or `~S(bar)` (whichever is the most appropriate for the given use case) then it will work fine (as it will be compliant with the double-quoted attribute value syntax). 

So would it be safe to assume that behaviour is going to stick around for now? Or is it possible it might change to assuming they're singled-quoted compliant, or maybe it'll auto-encode them, etc. i.e. Something that could break one of the other variants.

**Comment by wojtekmach** [comment]
I think it's best to assume the AST is not stable yet and will most likely change. (it's very unlikely it will change in a bug fix release but we reserve the right to do so.)

We're not ready to commit to a particular shape yet because we don't want to paint ourselves into a corner. On one hand, we work with the Earmark AST but on the other hand in the near future we'll be integrating with the Erlang HTML AST, when we do so it might be practical for us to have an ExDoc specific AST to support wider range of use cases.

Behaviour around quotes is exactly the kind of thing we need to flesh out and eventually document so thank you for mentioning it.
