### ISSUE TITLE
Suggestions wrongly deal with escaped chars

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1244]
If you type in the search box "&" you will get the suggestion of functions that their name has been escaped such as "&lt;/2". Same if you type "gt".

I think we should keep the original name and the escaped name.

**Comment by TheFirstAvenger** [comment]
@eksperimental I have not yet been able to reproduce this. Do you have an example on hexdocs.pm that you can point me to where this happens? On https://hexdocs.pm/elixir/ I get only the three functions `&`, `&&`, and `&&&` when searching for `&`, and `gt` only suggests functions with the word `length` in them.

**Comment by eksperimental** [comment]
I am running ExDoc Master, and Elixir master.
![ex_doc_ampersand](https://user-images.githubusercontent.com/9133420/90279904-a453b580-de2f-11ea-98f6-6c4c3f519a85.png)

please run `mix build` in your master version of ExDoc

**Comment by eksperimental** [comment]
I am sure it is introduced by one of these two commits:
- d26ca71417c40f3e5d9ab49d0933b277c983962d
- 5fed479d94d2b94286c9d00a6fc905a63fb1b227
