### ISSUE TITLE
Feature request: automatically document a `@behaviour` and its callbacks

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/ex_doc#1252]
Using:
- Elixir 1.10.3 (compiled with Erlang/OTP 21)
- `ex_doc` as of the latest commit on master (7fb655fe5661)

If we specify `@behaviour Foo.Behaviour`, that is sufficient to tell Dialyzer to check that the callbacks in the implementation module return the expected types.

However, `@behaviour Foo.Behaviour` and `@impl Foo.Behaviour` have no effect on the generated documentation. Even if we add a `@doc` for a callback in the implementation, it doesn't use the behaviour's `@callback` to document its typespec.

To document the callback specs in the implementation module, we have to copy and paste each `@callback` from the behaviour to a `@spec` in the implementation. This duplication creates a maintenance burden.

Would it be possible for a module's documentation to automatically include 1) each `@behaviour` it implements and 2) the `@spec` for each `@callback` it implements, as marked by `@impl SomeBehaviour` or `@impl true`?

## Example

Here's a tiny behavior:

```
defmodule Foo.Behaviour do
  @doc "Is it foo? We want to know. We demand a boolean."
  @callback foo?(value :: any()) :: boolean()
end
```

Here's a module which implements it:

```
defmodule Foo.Implementation do
  @behaviour Foo.Behaviour

  @impl Foo.Behaviour
  def foo?(val) do
    val == "foo"
  end
end
```

Here's the documentation generated for the behaviour module:

![behaviour](https://user-images.githubusercontent.com/338814/90791722-9098cb00-e2d7-11ea-9b10-21f8e54031e1.png)

And the docs for the implementation module, which make no mention of the behaviour it implements, the callback it has, or the spec for that callback:

![implementation](https://user-images.githubusercontent.com/338814/90791730-94c4e880-e2d7-11ea-9ec9-7281af9d3727.png)

**Comment by josevalim** [comment]
@nathanl this is complicated because a lot of times the behaviour is an implementation detail. For example, do you care that `Plug.Upload` uses a GenServer or is an Agent behind the scenes? That's the reason why, when you use `@impl Foo`, Elixir will by default also add `@doc false`. If you want it to be documented, you need to publicly do so.

However, I agree there is currently no way to say that something implements a behaviour. Perhaps what we could do is to automatically say it implements a behaviour if any of the callbacks of the behaviour are documented. But generally speaking, it is not something that will happen automatically.

**Comment by wojtekmach** [comment]
I think showing which behaviours the given module is implementing would be a nice addition. We can easily grab it with:

```elixir
iex> Mix.Shell.IO.module_info(:attributes)[:behaviour]
[Mix.Shell]
```

do you have a proposal how would that look like?

Regarding copying `@callback` as `@spec` we can't reliably do that. Imagine:

```elixir
defmodule A do
  @typep t() :: term()

  @callback handle_a(t()) :: t()
end

defmodule B do
  @behaviour A

  @impl true
  def handle_a(...), do: ...
end
```

if we copy the specs it is as if we wrote:

```elixir
defmodule B do
  @behaviour A

  @spec handle_a(t()) :: t()
  def handle_a(...), do: ...
end
```

which is incorrect, there's no `t()` type in `B`. So I'm definitely -1 on copying the spec.

**Comment by wojtekmach** [comment]
José has a good point that implementing a behaviour is an implementation detail so yeah maybe we shouldn't do anything. After all if you want to signal that e.g. `Mix.Shell.Process` implements a `Mix.Shell` you can just write it down:

```
defmodule Mix.Shell.Process do
  @moduledoc """
  A `Mix.Shell` impelementation that uses the current process mailbox for communication.
  """
end
```

**Comment by nathanl** [comment]
What would you think of having a *Behaviours* section near the top of a module's documentation, listing each behaviour that it implements? https://github.com/elixir-lang/ex_doc/pull/1253 would be the first step (I didn't add it to the templates because the autolinking looked like more work than I wanted to bite off at the moment).

**Comment by josevalim** [comment]
@nathanl that's a good first step! However, as I mentioned, we probably need to filter those behaviours to keep only the ones that have one of its callbacks implemented publicly and, even then, we most likely need a way to opt-out of this behaviour. Please see my original comment for more details. :)

**Comment by josevalim** [comment]
I will close this one. My suggestion is to explicitly docs the important behaviours you implement in the docs for now.
