### ISSUE TITLE
Long-named sections in the sidebard do not show the arrow 

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1274]
They show the ellipsis, and if you click on it it works as if you clicked in the arrow.
I find it weird it is not consistent depending on the length

**Comment by josevalim** [comment]
Can you please provide screenshots that better describe the issue? Or a short way to reproduce. The more information the better.

**Comment by eksperimental** [comment]
the cursor is missing in the screenshot, but i am hovering the ellipsis
![image](https://user-images.githubusercontent.com/9133420/93131992-8bdaf300-f69a-11ea-82ed-6a4a26374202.png)

**Comment by josevalim** [comment]
I see. We have asked @archdragon to do a redesign of the sidebar to better handle all of this, so we will revisit this once that is proposed, thank you!
