### ISSUE TITLE
:filter_prefix yields file not found

### ISSUE THREAD

**Issue by felipelincoln** [elixir-lang/ex_doc#1279]
I have a module in my project called `CMS` and I want to generate documentation to it, so according to the documentation I tried
```elixir
# mix.exs
def project do
  # some project configs
  docs: [
    filter_prefix: "Myapp.CMS",
    # some more docs configs
end
```

but this is what I got:
```shell
$ mix docs
Generated myapp app
Generating docs...
warning: index.html redirects to Myapp.html, which does not exist
View "html" docs at "docs/index.html"
View "epub" docs at "docs/Myapp.epub"
```

and when I open docs/index.html I get "file not found".
When I remove the `:filter_prefix` everything works as expected. Since there is not much in the documentation regarding this configuration I may be missing something.

**Comment by josevalim** [comment]
You will have to configure `:main` too to point to which module you want to be the new home page. We are most likely redirecting you to Myapp.html, which is why it fails. I will improve the docs, thanks.

**Comment by felipelincoln** [comment]
That's it, thank you! :tada: :tada:
