### ISSUE TITLE
Search suggestions in sidebar should mention "(exception)"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1280]
Otherwise it looks like a regular module

**Comment by josevalim** [comment]
They are regular modules and we have stopped treating them as something special for some time now (i.e. they don't have their sidebar entry either). Luckily the name provide enough hint too! Thanks!

**Comment by eksperimental** [comment]
> They are regular modules and we have stopped treating them as something special for some time now (i.e. they don't have their sidebar entry either). Luckily the name provide enough hint too! Thanks!

well they appear in the sidebar
![image](https://user-images.githubusercontent.com/9133420/93898574-f7cfe380-fcb8-11ea-91ee-fd5f8af77c0d.png)

**Comment by josevalim** [comment]
Yes, they appear on the sidebar as regular modules, they don't have their own sidebar *group* (my bad).

**Comment by eksperimental** [comment]
> Yes, they appear on the sidebar as regular modules, they don't have their own sidebar _group_ (my bad).

they do have it,

![image](https://user-images.githubusercontent.com/9133420/93900861-7f1e5680-fcbb-11ea-8c6f-66705fa7bdce.png)

**Comment by josevalim** [comment]
By group i mean the one we had at the top. Like modules and pages. It is easier if you compare to an old version of ExDoc, where exceptions was treated separately from modules.

**Comment by eksperimental** [comment]
I get you now. All good then. I just wanted to make sure we were on the same page.
