### ISSUE TITLE
Suggestion: remove "Top" links

### ISSUE THREAD

**Issue by joeapearson** [elixir-lang/ex_doc#1282]
I may be alone here, but I find it quite disorientating that, when opening any section of an ex_doc created set of docs I:

1. Click the section
2. Have to click the "Top" link to actually cause navigation to occur

IMHO I'd love to see the removal of Top, and clicking the section header just takes you straight there instead.  If there is still a desire is for the ability to return to the top of the doc, it seems like there might be some better UI to achieve that without overloading the sidebar.

Is this a simplification that the community might enjoy?  I'd be happy to submit a PR if so.

**Comment by josevalim** [comment]
We have discussed this many times and changed it many times and every time we find it, some people find the new behavior confusing. The way you suggested is actually how it worked some time ago. :) So I recommend checking out the previous issues.

At some pint we actually want to rework the whole sidebar. We even got funds for it, but we need a bit of time to prioritize that. Thanks!

**Comment by joeapearson** [comment]
Roger that.  Would it be useful to create an issue for others (myself included) to watch?  Happy to pitch in if needed once decisions made.
