### ISSUE TITLE
Sidebar entries are incorrectly escaped

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#1283]
See e.g.:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/76071/94997835-2057b780-05ae-11eb-85d0-a047a3e1d09e.png">

https://hexdocs.pm/phoenix_ecto/main.html#the-phoenix-ecto-integration

It's easy to reproduce this on master.

**Comment by davydog187** [comment]
I've got a PR coming
