### ISSUE TITLE
Code block under list without extra empty line failed to render HTML correctly

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1286]
Sample Markdown taken from https://raw.githubusercontent.com/elixir-unicode/unicode/master/README.md

# GitHub
GitHub renders it correctly, https://github.com/elixir-unicode/unicode/blob/master/README.md
![image](https://user-images.githubusercontent.com/134518/95658478-443a7080-0b4d-11eb-8855-9a7fa521334f.png)

# ExDoc
`ex_doc` renders it incorrectly, https://hexdocs.pm/ex_unicode/1.11.0/readme.html
![image](https://user-images.githubusercontent.com/134518/95658501-721fb500-0b4d-11eb-8a82-32feb2400610.png)

# Testing Results

How to repeat the test.
```
$ git clone https://github.com/elixir-unicode/unicode.git
$ git checkout tags/v1.10.0 -b v1.10.0

# Set fix ex_doc version
{:ex_doc, "== 0.19.0", runtime: false},

$ mix deps.get
$ mix docs
```

Version that failed to generate the code example correctly.
- 0.22.6, 0.22.5, 0.22.4, 0.22.2, 0.22.1, 0.22.0*
- 0.21.3, 0.21.2, 0.21.1, 0.21.0
- 0.20.2, 0.20.1, 0.20.0
- 0.19.3, 0.19.2, 0.19.1, 0.19.0

Version that crashed.
- 0.22.0

```
Generating docs...
warning: ExDoc.Markdown.Earmark (warning) mix/tasks/download_unicode.ex:0 DEPRECATION: Earmark.as_ast
will be removed in version 1.5, please use EarmarkParser.as_ast, which is of the same type

** (FunctionClauseError) no function clause matching in ExDoc.Markdown.Earmark.fixup/1

    The following arguments were given to ExDoc.Markdown.Earmark.fixup/1:

        # 1
        {"p", [], ["Downloads the required Unicode files to support Unicode"], %{}}

    Attempted function clauses (showing 3 out of 3):

        defp fixup(list) when is_list(list)
        defp fixup(binary) when is_binary(binary)
        defp fixup({tag, attrs, ast})

    (ex_doc) lib/ex_doc/markdown/earmark.ex:58: ExDoc.Markdown.Earmark.fixup/1
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:214: ExDoc.Retriever.get_module_docs/2
    (ex_doc) lib/ex_doc/retriever.ex:133: ExDoc.Retriever.do_generate_node/3
    (ex_doc) lib/ex_doc/retriever.ex:124: ExDoc.Retriever.generate_node/3
    (elixir) lib/enum.ex:2986: Enum.flat_map_list/2
    (ex_doc) lib/ex_doc/retriever.ex:43: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:26: ExDoc.generate_docs/3
```
# Workaround

Add extra empty line as shown in screenshot below.

![image](https://user-images.githubusercontent.com/134518/95658623-67195480-0b4e-11eb-88a2-c4f68cc5f0f4.png)

**Comment by wojtekmach** [comment]
Thank you for the report. I believe it's Earmark bug, it probably produces invalid html for this markdown. Try upgrading Earmark to the latest version and see if it is still incorrectly rendered. If it isn't, consider reporting the bug there.

**Comment by RobertDober** [comment]
@kianmeng yes this is an EarmarkParser problem, I am currently working on it, alas very slowly
