### ISSUE TITLE
Feature request: Warnings as Errors

### ISSUE THREAD

**Issue by jnfingerle** [elixir-lang/ex_doc#1294]
Hi,

it would be great to have a switch to treat warnings as errors. One could use that in automated builds.

Cheers, Jan Niklas

**Comment by josevalim** [comment]
We don't have bandwidth to tackle this right now but I think it is a good idea, so a pull request is welcome!  :)

**Comment by eksperimental** [comment]
I am going to tackle this one as I think it will beautifully integrate with CI and test tasks in general.
If you have any considerations, suggestions, please let me know.

**Comment by wojtekmach** [comment]
Let's hold off on this given while working on Erlang support, we're revamping that part of ExDoc. I'd wait until at least next release. Given it's not a high priority feature, I wouldn't even track it, but anyone is of course welcome to send a PR!
