### ISSUE TITLE
Add Next Previous Buttons to theme

### ISSUE THREAD

**Issue by lszyba1** [elixir-lang/ex_doc#1295]
Hello,
Could you add next /previous buttons to a theme in a similar fashion as sphinx (python).

I'm in a middle of reading 
https://hexdocs.pm/phoenix/request_lifecycle.html#another-new-page
But I need to step out of learning, figure out where I'm in a tree of documents, then click on next section. Very distracting when you are following along.

Example of how the "Next Button Should Look":
scroll to bottom of the page to see "next" button:
https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

Thank you
Lucas

**Comment by eksperimental** [comment]
regardless of introducing the buttons to the interface, the `rel="prev"` and `rel="next"` can be implemented since there is a linear login based on the sidebar tree.
