### ISSUE TITLE
Building documentation for Elixir failed

### ISSUE THREAD

**Issue by henrythebuilder** [elixir-lang/ex_doc#1303]
Hi
with last version of ex_doc building documentation for Elixir failed:
```
elixir on master (5627de67) 
❯  make docs
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.12.0-dev" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "5627de674f28a3533e641c8a4da1984967d75ee8"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/master/" --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"

13:12:45.966 [info]  Application makeup_elixir exited: :stopped

13:12:45.973 [info]  Application makeup exited: :stopped

13:12:45.973 [info]  Application nimble_parsec exited: :stopped

13:12:45.973 [info]  Application earmark_parser exited: :stopped

13:12:45.973 [info]  Application crypto exited: :stopped

13:12:45.973 [info]  Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:makeup_erlang, {'no such file or directory', 'makeup_erlang.app'}}}
    (ex_doc 0.23.0) lib/ex_doc/cli.ex:8: ExDoc.CLI.main/2
    (elixir 1.12.0-dev) lib/code.ex:935: Code.require_file/2
make: *** [Makefile:190: docs_elixir] Error 1
```
checking latest commits from [v0.23.0](https://github.com/elixir-lang/ex_doc/releases/tag/v0.23.0) it seam the error come from 0a9863f5 with the introduction of 'makeup_erlang' dependency.
Adding this dependency to `bin/ex_doc` with `Code.prepend_path...` seam solve the problem:
```
diff --git a/bin/ex_doc b/bin/ex_doc
index ce30723..efde357 100755
--- a/bin/ex_doc
+++ b/bin/ex_doc
@@ -3,6 +3,7 @@ mix_env = System.get_env()["MIX_ENV"] || "dev"
 Code.prepend_path Path.expand("../_build/#{mix_env}/lib/nimble_parsec/ebin", __DIR__)
 Code.prepend_path Path.expand("../_build/#{mix_env}/lib/makeup/ebin", __DIR__)
 Code.prepend_path Path.expand("../_build/#{mix_env}/lib/makeup_elixir/ebin", __DIR__)
+Code.prepend_path Path.expand("../_build/#{mix_env}/lib/makeup_erlang/ebin", __DIR__)
 Code.prepend_path Path.expand("../_build/#{mix_env}/lib/earmark_parser/ebin", __DIR__)
 Code.prepend_path Path.expand("../_build/#{mix_env}/lib/ex_doc/ebin", __DIR__)
```
With this change `make docs` work again.

P.S. probably this is not the best place to notify a note but during test I found a probably circular dependency in `makeup_erlang` because `ex_doc` [depend on `makeup_erlang` ](https://github.com/elixir-lang/ex_doc/blob/e50718b2786d89270d9482846c99da1201629df0/mix.exs#L35)that depend on `ex_doc` ( [`mix.ex` >>  `{:ex_doc, "~> 0.21.1", only: [:dev, :test]}` ](https://github.com/elixir-makeup/makeup_erlang/blob/f236cfeea32459fecbb701fc1b57a4809cb81d94/mix.exs#L56)), only for note, Elixir documentation build as expected.

Thanks for your work
Enrico

**Comment by josevalim** [comment]
Can you please send your proposed changes to `bin/ex_doc`? I will fix the makeup_erlang dependency.

**Comment by henrythebuilder** [comment]
OK, pull request requested, probably the best way, sorry for long issue text but I don't known if the proposed changes are the best to fix the error

**Comment by henrythebuilder** [comment]
Thanks for merging :+1:

**Comment by josevalim** [comment]
Both this issue description and the PRs are appreciated, thank you!
