### ISSUE TITLE
Wrong link in API Refecence with local links in the module summary.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1307]
```elixir
defmodule Foo do
  @moduledoc """
  Documentation for `Foo`.
  """
end
```

The API will link `Foo`  to `#content` intead of `Foo.html#content`.

This happens with any local link

**Comment by josevalim** [comment]
Fixed already with b46dab1b4a8e4fc16663a5e4bb6e90bcd186f6ce.
