### ISSUE TITLE
Epub docs not compliying with requirements in README file

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1309]
The generate epub is not including the link to this repo on every page.

> Any documentation generated by ExDoc, or any documentation generated by any "Derivative Works" (as specified in the Apache 2 License), must include a direct link to ExDoc repository on every page.

/cc @milmazz

**Comment by milmazz** [comment]
@eksperimental based on the `README` description, you're right, a direct link is needed to the repository on every page, so I think we should put a new _footer_ template, and then use that template on:

* `title_template.eex`
* `module_template.eex`
* `nav_template.eex`

Should we also update the content of the `head_template.eex` too? I mean, currently we describe the generator as:

```elixir
<meta name="generator" content="ExDoc v<%= ExDoc.version() %>" />
```

Should we put the URI of this repo instead there? I saw that WordPress for example use the following approach:

```html
<meta name="generator" content="WordPress.com" />
<meta name="application-name" content="WordPress.com" />
```

So, we could set the repo URI as the `generator` key and `ExDoc` as the `application-name` key, wdyt?

**Comment by josevalim** [comment]
I will change the README to say it is one reference for every printed material. This means it is per page for HTML and once per PDF. :)

**Comment by eksperimental** [comment]
> ```
> <meta name="generator" content="WordPress.com" />
> <meta name="application-name" content="WordPress.com" />
> ```
> 
> So, we could set the repo URI as the `generator` key and `ExDoc` as the `application-name` key, wdyt?

application-name is for applications running the page. I think it does not apply to ExDoc. I also read it is used in mobiles when you want to add a link in the home screen.

**Comment by milmazz** [comment]
@eksperimental This issue seems fixed since José updated the last paragraph of the license.

> Any documentation generated by ExDoc, or any documentation generated by any "Derivative Works" (as specified in the Apache 2 License), must include a direct, readable, and visible link to the [ExDoc repository](https://github.com/elixir-lang/ex_doc) on each rendered material. For HTML pages, a rendered material represents every single page. For PDF, EPUB and other ebook formats, it means one entry for the whole material.

Do you agree on closing this issue now? or is there any remaining action?

**Comment by eksperimental** [comment]
> Do you agree on closing this issue now? or is there any remaining action?

Yes. Thank you
