### ISSUE TITLE
Adding support for LaTeX rendering via MathJax

### ISSUE THREAD

**Issue by andfoy** [elixir-lang/ex_doc#1318]
Thanks for your great work on this project! I was wondering if it is possible to bring LaTeX support for docstrings, which could be rendered on HTML via MathJax. Basically, the idea would be to provide support for strings surrounded by $$$$. 

I can also implement this functionality if I can get pointers about how JavaScript dependencies work on ExDoc

**Comment by jonatanklosko** [comment]
This is a rather specific feature, so it probably makes more sense to set it up manually when needed. ExDoc configuration supports adding custom content to the HTML page via `before_closing_body_tag`/`before_closing_head_tag`, so you can easily load external JS. I created an example of that [here](https://github.com/jonatanklosko/latex_example).

**Comment by josevalim** [comment]
Exactly! We support custom assets and custom tags, which means you can bring MathJax in! Thanks @jonatanklosko!

**Comment by andfoy** [comment]
Thanks for the pointers @jonatanklosko @josevalim!
