### ISSUE TITLE
Callbacks are ignored if declared inside a protocol

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1320]
If a callback is declared inside a protocol. ExDoc does not list them.

Example:
https://github.com/eksperimental/buildable/blob/master/lib/buildable.ex

**Comment by josevalim** [comment]
It shouldn’t. A protocol is already a behavior with its own callbacks, we shouldn’t promote mixing.

**Comment by eksperimental** [comment]
On Mon, 18 Jan 2021 22:42:47 -0800
José Valim <notifications@github.com> wrote:

> It shouldn’t. A protocol is already a behavior with its own
> callbacks, we shouldn’t promote mixing.
> 

Then shouldn't we emit some kind of warning in Elixir when this is done?

**Comment by eksperimental** [comment]
@josevalim There is also a thread in ElixirForum asking opinions on how to tackle this issue.
https://elixirforum.com/t/putting-non-protocol-functions-in-a-protocol/36503/
I think it will clarify if you can share your input.
