### ISSUE TITLE
Sidebar status should be remember across pageloads

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1340]
If you collapse the sidebar and hit a link that takes you to another page, within the same project, the sidebar is expanded again.
I think it should remain collapsed.

**Comment by josevalim** [comment]
I disagree. :) Those are really distinct pages and for example, if i am going to a completely separate project, it is not clear this state should persist. I think avoiding state here would be a good thing. Thanks for the report tho!

**Comment by eksperimental** [comment]
Yes, they are distinct pages but within the same project. Same happens with disable tool tips and setting the night mode. They are kept across pages, but if you go to a different project, they are lost.

The use case here is that if you are in a mobile, or in a screen where the sidebar is interfering with your reading and you choose to collapse it, IMO it will be really annoying that the user will have to hide it every time a page is loaded.

**Comment by jonatanklosko** [comment]
> The use case here is that if you are in a mobile, or in a screen where the sidebar is interfering with your reading

For small screens sidebar is collapsed by default and we definitely wouldn't want to remember that the user expanded it temporarily =)

**Comment by eksperimental** [comment]
> > The use case here is that if you are in a mobile, or in a screen where the sidebar is interfering with your reading
> 
> For small screens sidebar is collapsed by default and we definitely wouldn't want to remember that the user expanded it temporarily =)

Fair point for the mobile case, it wouldn't apply to it. But what about if you are in a desktop of 1024x768, the side bar take 38% of the screen width

![image](https://user-images.githubusercontent.com/9133420/109969235-aa24c180-7cc1-11eb-825a-df0ada2eb0ff.png)

versus the screen with no sidebar.
![image](https://user-images.githubusercontent.com/9133420/109969280-b9a40a80-7cc1-11eb-910c-e105acb19abc.png)

**Comment by eksperimental** [comment]
I think this issues should be considered to be reopened, until we come up with a solution that is not annoying for users where the sidebar takes such a significant percentage of the screen-width as mentioned in https://github.com/elixir-lang/ex_doc/issues/1340#issuecomment-790610196

**Comment by josevalim** [comment]
I don’t think it is a critical issue, so a PR is welcome, but not something we should be investigating. Thanks!
