### ISSUE TITLE
Autolink captures

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#1348]
Say we have these docs:

```markdown
  * `:json_decoder` - defaults to [`&Jason.decode!/1`](`Jason.decode!/1`)
```

it would be nice if we could simply write:

```markdown
  * `:json_decoder` - defaults to `&Jason.decode!/1`
```

thoughts? If so, should we do it for local captures too?

**Comment by eksperimental** [comment]
+1

**Comment by josevalim** [comment]
I am unsure because we start blurrying the line with auto linking code. Should we also autolink: `Kernel.is_atom(:foo)`?

**Comment by wojtekmach** [comment]
Fair enough, i don’t think that's a bridge we want to cross yet. I'm gonna close it for now.
