### ISSUE TITLE
Markdown to HTML new line behaviour

### ISSUE THREAD

**Issue by cw789** [elixir-lang/ex_doc#1350]
I'm very unsure if this belongs to ex_doc or to another place (earmark_parser).
Sorry upfront if I'm wrong.

Following:
I would expect the markdown below (double space + line ending) to give me the following HTML.

**Markdown**
```
hello∙∙
world
```

**HTML**
```
<p>
  hello
  <br>
  world
</p>
```

But it seems to me that ExDoc produces double breaks in HTML:

```
<p>
  hello
  <br>
  <br>
  world
</p>
```
Means there is an unexpected empty line before the next line.

My quick test shows me that the AST seems to be correct.

---

Thread within the Elixir forum where I didn't got any helpful responses:
[elixirforum.com/t/exdoc-extras-markdown-newline-behaviour-html/38505](https://elixirforum.com/t/exdoc-extras-markdown-newline-behaviour-html/38505)

**Comment by wojtekmach** [comment]
This is an ExDoc bug:

```
iex> ExDoc.Markdown.to_ast("foo  \nbar") |> IO.inspect() |> ExDoc.DocAST.to_string()
[{:p, [], ["foo", {:br, [], [], %{}}, "bar"], %{}}]
"<p>foo<br></br>bar</p>"
```

we're incorrectly changing `{:br, [], [], %{}}` to `<br></br>` that then gets rendered as two br's.

**Comment by kelvinst** [comment]
I can fix this one if no one else is interested.

**Comment by eksperimental** [comment]
We need to detect when a tag is a void one.
See this PR as an example

https://github.com/pragdave/earmark/commit/d946315ade9509a4c022f5b60ff1d09d5588b857#diff-07e611b6c1c5c00433da7d769f5c8b5c4135aaeaf6d9726ef003767c01b56fe7R5-R6
