### ISSUE TITLE
Restructure message in landing page

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1355]
We are currently showing this message at the top of the page
>  You're seeing just the function cast, go back to Agent module for more information. 

I think this should be placed at the bottom of the page, in the html structure. but display with CSS where it is. Otherwise it is the first think that will show up in the search engines.

**Comment by kelvinst** [comment]
If no one else is interested, I can take a shot on this one too.

**Comment by josevalim** [comment]
Can we depreoritize it so it doesn’t show up in text engines but still have it at the top?

@eksperimental do you have any example of it showing up first?

**Comment by eksperimental** [comment]
> Can we depreoritize it so it doesn’t show up in search engines but still have it at the top?

I was thinking of using the `<small>` tag but still move it to the bottom. I don´t know if an approach like that is what you mean by depreoritizing it.


> 
> @eksperimental do you have any example of it showing up first?

I haven't since this feature is very recent. Do you 
![image](https://user-images.githubusercontent.com/9133420/114326233-75462e80-9af9-11eb-8563-bec64cd37e38.png)

**Comment by eksperimental** [comment]
Also, "link to the function" can be hidden for SE if the is a trick to to that.

**Comment by josevalim** [comment]
https://developers.google.com/search/docs/advanced/crawling/special-tags?hl=en&visit_id=637538080264416026-2100439240&rd=1#inline-directives

**Comment by josevalim** [comment]
Closed by 66f3a15bb1a05e14792bb786200b04d2e98113a7.
