### ISSUE TITLE
Move landing pages to a subfolder

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1356]
I am overwhelmed by the amount of pages in the root folder for the docs.
Currently Elixir has 1370 html files

Maybe having subfolders named `callback/` and `function/` will help with the SEO purposes of this feature

**Comment by kelvinst** [comment]
Would gladly take a shot at this one, let me know if someone is already working on it.

**Comment by josevalim** [comment]
Won’t happen because it will break all
Links, assets, layouts, which are based on relative paths. We can change it so it is easy to filter them out, but they will stay at rootx
