### ISSUE TITLE
Allow html files as extras

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#1358]
It would be nice for extras to allow for plain .html files, which ex_doc would just link to from it's navigation. The use-case is coverage reports, which excoveralls exposes as a single .html page.  Currently one needs to go on one of the markdown pages and click a link there, which is more navigation and even more less obvious.

**Comment by josevalim** [comment]
Thanks for the request but we don't have plans to support this at the moment. The link is likely the best option for now. :)
