### ISSUE TITLE
Autolink of `Application` module incorrect - missing / after master

### ISSUE THREAD

**Issue by stefanluptak** [elixir-lang/ex_doc#1359]
Here  https://hexdocs.pm/mix/master/Mix.Tasks.Escript.Build.html

<img width="599" alt="Screenshot 2021-04-15 at 19 55 30" src="https://user-images.githubusercontent.com/23926/114920437-b906a400-9e29-11eb-9cef-27046cf5b188.png">

**Current behavior:**
Link to `Application` module is https://hexdocs.pm/elixir/masterApplication.html

**Expected behavior:**
Link to `Application` module should be https://hexdocs.pm/elixir/master/Application.html

**Notes:**
I am not sure if this bug is relevant or even in the correct repo, maybe it should be in the Elixir one. I would be happy if you enlighten me. :-)
Also, I tried to at least investigate that on my own, but I immediately failed on running `make docs` on the `master` Elixir, because of
```
** (FunctionClauseError) no function clause matching in Enumerable.Range.slice/1    
    
    The following arguments were given to Enumerable.Range.slice/1:
    
        # 1
        %Inspect.Error{message: "got FunctionClauseError with message \"no function clause matching in Inspect.Range.inspect/2\" while inspecting %{__struct__: Range, first: 48, last: 57}"}
    
    Attempted function clauses (showing 1 out of 1):
    
        def slice(first.._//step = range)
    
    (elixir 1.13.0-dev) lib/range.ex:315: Enumerable.Range.slice/1
```

**Comment by josevalim** [comment]
For the error, you need to compile ExDoc with the Elixir version you are building docs for. :)
