### ISSUE TITLE
Problem rendering unicode characters

### ISSUE THREAD

**Issue by matt-mazzucato** [elixir-lang/ex_doc#1360]
The documentation I'm working on makes use of some fancy characters such as &#x2714;.
Currently the symbol isn't rendered in the correct way and the generated html simply renders it as `&#x2714;`.

From a quick test I can see that `&` is replaced with `&amp;`, which breaks the rendering:
```elixir
ExDoc.Markdown.to_ast("&#x2714;") |> IO.inspect() |> ExDoc.DocAST.to_string()
[{:p, [], ["&#x2714;"], %{}}]
"<p>&amp;#x2714;</p>"
```

I think that dropping the replacement of `&` with `&amp;` fixes the problem. I tested it on my machine and it works. However I'm not sure that this quick fix isn't breaking anything else.

Thanks in advance for your support

**Comment by wojtekmach** [comment]
This should have been fixed in the latest release, could you update and double-check? If the option persists, could you share a minimal repo that exhibits the problem? Thanks!

**Comment by matt-mazzucato** [comment]
Thanks @wojtekmach for your reply.
I just created a repo with a minimal example. Here you are the link: https://github.com/matt-mazzucato/minimal-doc-example

Additional info: I'm working with `elixir 1.11.4-otp-23`

**Comment by wojtekmach** [comment]
Thank you, this is extremely helpful!

Note that if you write down the actual emoji:

```diff
diff --git a/001-intro.md b/001-intro.md
index edf625b..f8f2d93 100644
--- a/001-intro.md
+++ b/001-intro.md
@@ -1,3 +1,3 @@
 # Title

-We are trying to render the following character: &#x2714;.
+We are trying to render the following character: ✔.
```

it will render correctly:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/76071/117145892-ece34280-adb3-11eb-8edd-63149742a271.png">

Another reason to prefer the actual thing is then it will be nicely rendered in `iex> h` too, as opposed to seeing the escape code.

But perhaps we need to handle the escape code too when rendering the HTML, not sure.

**Comment by eksperimental** [comment]
> But perhaps we need to handle the escape code when rendering the HTML as well, not sure.

I think we should. At least, that is what the CommonMark parsers are doing.

**Comment by matt-mazzucato** [comment]
I am aware that the symbol is correct if rendered from the markdown file (as we can see opening the .md file here on GH). But I suppose that if you check the doc generated with `mix docs` you won't see the checkmark symbol, both epub and html.

**Comment by wojtekmach** [comment]
> But I suppose that if you check the doc generated with mix docs you won't see the checkmark symbol, both epub and html.

The screenshot posted above is from the HTML generated by `mix docs`.

**Comment by matt-mazzucato** [comment]
Sorry I was keeping on trying with the unicode char. Working with the actual emoji fix my issue. 
Thank you so much!

**Comment by wojtekmach** [comment]
> I think we should. At least, that is what the CommonMark parsers are doing.

In that case I guess it should be handled by Earmark?

```elixir
iex> EarmarkParser.as_ast("We are trying to render the following character: &#x2714;")
{:ok,
 [{"p", [], ["We are trying to render the following character: &#x2714;"], %{}}],
 []}
```

Feel free to pursue this on Earmark front but honestly given the workaround exists, I'm inclined to leave this as is as we all have bigger fish to fry first. Thanks for the report though!
