### ISSUE TITLE
Link to URL should not include "."

### ISSUE THREAD

**Issue by tedhexaflow** [elixir-lang/ex_doc#1366]
Related to PR https://github.com/elixir-lang/ex_doc/pull/1362

While checking the demo, I just noticed the "." in the URL ("https://github.com/hexpm/specifications." instead of "https://github.com/hexpm/specifications" 

Hence, clicking on the link, go to the Github 404 page.

![image](https://user-images.githubusercontent.com/2466052/119465293-bfb00180-bd6d-11eb-9d85-1da8901bf437.png)

But clicking on the Github repo, it will go to the correct URL. (without ".")

![image](https://user-images.githubusercontent.com/2466052/119465876-4a90fc00-bd6e-11eb-8ed1-7372c01ecf9c.png)

**Comment by wojtekmach** [comment]
Thank you for the report, a simple fix is https://github.com/hexpm/hex_core/commit/851649f90efa9566d12b30fcab2246b515c42b3f.

I'm not sure if handling URLs like that is part of markdown, basic commonmark, or some kind of extension like GFM. Fwiw I saw the following:

```
% echo 'https://github.com/foo/bar.' | cmark
<p>https://github.com/foo/bar.</p>
```

that is, cmark doesn't even render it as url, so I think the fix is good enough. If you can confirm that this behaviour is a known extension that Earmark is implementing, I'd open up an issue there. Thanks!

**Comment by eksperimental** [comment]
> I'm not sure if handling URLs like that is part of markdown, basic commonmark, or some kind of extension like GFM. Fwiw I saw the following:
> 
> ```
> % echo 'https://github.com/foo/bar.' | cmark
> <p>https://github.com/foo/bar.</p>
> ```
> 
> that is, cmark doesn't even render it as link, so I think the fix is good enough. If you can confirm that this behaviour is a known extension that Earmark is implementing, I'd open up an issue there. Thanks!

I can confim that the `<URL>` format is a basic feature implemented in the original Markdown syntax.

https://daringfireball.net/projects/markdown/syntax
> The link URL may, optionally, be surrounded by angle brackets:
> 
> [id]: <http://example.com/>  "Optional Title Here"

It is also supported in CommonMark, and all but one formatters in BabelMark.

https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Chttps%3A%2F%2Fjohnmacfarlane.net%2Fbabelmark2%2F%3E.

I have actually used it myself recently when reviewing the Phoenix documentation

**Comment by wojtekmach** [comment]
The problem was with `URL`, not `<URL>`. The latter was the fix :)

**Comment by eksperimental** [comment]
> The problem was with `URL`, not `<URL>`. The latter was the fix :)

Hahah. I totally misread it.
I will be a bug if the link is not rendered without the `.`, as this char it valid in URLs.
