### ISSUE TITLE
Unable To See full Module Name

### ISSUE THREAD

**Issue by Adzz** [elixir-lang/ex_doc#1369]
Hello I  ❤️  ex_docs, but for some libs it's not possible to read the full module names in the sidebar, and i can't seem to scroll even (on firefox if that makes a difference).

Attached a screenshot of what i mean.

![image](https://user-images.githubusercontent.com/8428277/121531531-63e4aa00-c9f6-11eb-8663-c2a8101f34c4.png)

**Comment by josevalim** [comment]
What version are you using? There has been improvements in this area lately, so please try latest and let us know. Thanks!

**Comment by Adzz** [comment]
Ah good point, I can't for the life of me find mention of ex_docs in the google libs

BUT I can see we are using version `0.22.2` and we have the same problem.

I'll try the latest and report back.

**Comment by wojtekmach** [comment]
https://hexdocs.pm/google_api_secret_manager/api-reference.html is generated with ExDoc v0.24.2

**Comment by fuelen** [comment]
Having something like `docs: [nest_modules_by_prefix: [GoogleApi.SecretManager.V1]]` might help a bit

**Comment by wojtekmach** [comment]
@fuelen is absolutely right, we already have such functionality. With this patch:

```diff
diff --git a/clients/secret_manager/mix.exs b/clients/secret_manager/mix.exs
index 48fe14f25..a1d481bf9 100644
--- a/clients/secret_manager/mix.exs
+++ b/clients/secret_manager/mix.exs
@@ -30,7 +30,8 @@ defmodule GoogleApi.SecretManager.Mixfile do
       description: description(),
       package: package(),
       deps: deps(),
-      source_url: "https://github.com/googleapis/elixir-google-api/tree/master/clients/secret_manager"
+      source_url: "https://github.com/googleapis/elixir-google-api/tree/master/clients/secret_manager",
+      docs: [nest_modules_by_prefix: [GoogleApi.SecretManager.V1, GoogleApi.SecretManager.V1beta1]]
     ]
   end
```

we'll get this:

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/76071/127640745-1abd4ee3-0c13-4708-ba48-d3323c15d3e4.png">

which goes a long way. There are still minor design issues, the name of the project is really long and doesn't fit at the top of the sidebar but not sure we can do much about that.

If someone would like to talk with the maintainers and use the `nest_modules_by_prefix` feature across all their libraries, that'd be appreciated!
