### ISSUE TITLE
Add support for custom SIDEBAR Types

### ISSUE THREAD

**Issue by epinault** [elixir-lang/ex_doc#1391]
so currently it s only supporting Pages , Modules and Tasks. I would also love to see some integration with Absinthe or Phoenix to auto document APIs/Objects etc

 I am working on converting GraphQL schema from JSON to Markdown and have a running libraries. I can easily add the page into ex_doc at the moment. I have attached a screenshot of what it looks like for now. It works but it s not ideal. 

What I really would want is being able to do:

* maybe for new SIDEBAR Type (like Graphql, REST, etc..)
* List a set of sections  (so mutations, queries, etc.. ) 
* List all queries under queries sections like we do with functions so I can access the reference quickly

I am not finding a way to extend ex_doc other than forking and would rather not.  I am looking mostly for suggestions and how I could build a plugin maybe that integrate within ex_doc? or how we could we build something in ExDoc to support plugin if not already done?

<img width="1596" alt="Untitled" src="https://user-images.githubusercontent.com/479143/132553837-d0d9eb89-3ed5-42ff-886f-c344c58cb913.png">

**Comment by josevalim** [comment]
You can use the functionality for sidebar grouping, similar to how it is done in Phoenix: https://hexdocs.pm/phoenix/overview.html - you don't get a new sidebar type, but you will be able to organize multiple pages, one for queries, one for mutations, and so on. WDYT?

**Comment by epinault** [comment]
yea I was thinking about that. I will need to make my code generate multiple files instead them which is doable. But it wont look as nicely grouped/filtered than what module/task filter provides . But that s a good temporary solution. Would be nice to have a way to add plugins to ex_doc and add other types :)

**Comment by josevalim** [comment]
We want to redesign the sidebar, so I don't want to commit for now with such a feature. Once the sidebar is redesigned, feel free to reach out again and we can revisit the discussion. :)

**Comment by epinault** [comment]
thanks! sounds good to me. can t wait to see what you will come up with for the redesign then!
