### ISSUE TITLE
Can't generate Erlang library documentation using ExDoc

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1393]
Running on Erlang: 24.0.2
Erlang library tested: https://github.com/certifi/erlang-certifi

I was following the instruction here, https://github.com/elixir-lang/ex_doc#using-exdoc-with-erlang-projects, but stuck at step 4.

`rebar.config` as follows:

```erlang
{erl_first_files, ["src/certifi_pt.erl"]}.

{erl_opts, [deterministic  %% Added since OTP 20
           ,{platform_define, "^2", 'OTP_20_AND_ABOVE'}
           ,{doclet, edoc_doclet_chunks}
           ,{layout, edoc_layout_chunks}
           ,{dir, "_build/default/lib/certifi/doc"}
           ]}.
```

To generate doc using rebar3:
```sh
rebar3 edoc
```
No issue, works just fine:
![image](https://user-images.githubusercontent.com/134518/132933723-7eed1c20-cc97-4a88-a4ea-65ee3c845940.png)

To generate doc using ExDoc:
```sh
rebar3 compile # <-- missing this step here otherwise `_build/default` folder is not found
ex_doc "certifi" "2.7.0" _build/default/lib/certifi/ebin
```

HTML files were generated, but without the content?
![image](https://user-images.githubusercontent.com/134518/132933751-f31540e7-5dae-4983-99aa-8e68c0497b94.png)

Not familiar with Erlang and its ecosystem, did I miss out something?

**Comment by wojtekmach** [comment]
Did you follow all the steps from the readme, in particular changing`rebar.config` to use edoc chunks and changing `certifi.app.src` too?

**Comment by wojtekmach** [comment]
Please use `edoc_opts`, not `erl_opts` for edoc stuff

**Comment by kianmeng** [comment]
@wojtekmach I still get the same result when running:

```sh
$ rebar3 edoc
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling certifi
===> Running edoc for certifi

$ ex_doc "certifi" "2.7.0" _build/default/lib/certifi/ebin/
```

The diff of my changes, https://github.com/certifi/erlang-certifi/compare/master...kianmeng:gen-doc-with-exdoc?diff=split

**Comment by michallepicki** [comment]
Hitting the same issue with a different library ([sesterl_stdlib](https://github.com/gfngfn/sesterl_stdlib/)) - following commands from README results in generated documentation being empty

**Comment by josevalim** [comment]
Can you please compare your setups with the one in beam-telemetry/telemetry? That one is working for sure, so maybe it can help :)

**Comment by michallepicki** [comment]
The only differences I see are:
- setting `edoc_opts` in a `docs` profile instead of on top level
- `{preprocess, true}` option being set which expands erlang macros

I made those changes and they didn't make a difference, generated html is still empty - I don't think they make a difference in that case.

Here are steps to reproduce with `erlang-certifi` (it's probably a better test case):
```
$ git clone git@github.com:kianmeng/erlang-certifi.git
$ cd erlang-certifi
$ git checkout gen-doc-with-exdoc 
$ rebar3 compile
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling certifi
$ rebar3 edoc
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling certifi
===> Running edoc for certifi
$ ex_doc "certifi" "2.7.0" _build/default/lib/certifi/ebin
# open doc/index.html and see it's empty
```

**Comment by kw7oe** [comment]
Hi all, I have briefly look into this issue and able to generate the Erlang docs successfully by applying this diff:

```diff
diff --git a/src/certifi.erl b/src/certifi.erl
index 6280642..93e44c7 100644
--- a/src/certifi.erl
+++ b/src/certifi.erl


@@ -1,3 +1,7 @@
+%% @doc
+%% Certifi Module
+%% @end
+
 -module(certifi).
 -compile({parse_transform, certifi_pt}).
 
@@ -24,4 +28,4 @@ cacertfile() ->
 %% passed to the connect function.
 -spec cacerts() -> [binary(),...].
 cacerts() ->
-    ok.
\ No newline at end of file
+    ok.
diff --git a/src/certifi_pt.erl b/src/certifi_pt.erl
index 4eecb89..1403102 100644
--- a/src/certifi_pt.erl
+++ b/src/certifi_pt.erl
@@ -1,3 +1,7 @@
+%% @doc
+%% Certifi PT module.
+%% @end
+
 -module(certifi_pt).
 -export([parse_transform/2]).

 ```
 
 It appears that ExDoc requires documentation on the top level module to be able to generate it successfully. I might be wrong tho.
 
 See screenshots as result of fixes:
 
 ![Screenshot 2021-09-16 at 10 29 18 AM](https://user-images.githubusercontent.com/12683067/133539594-2f441bab-a15b-4c28-8c9d-6488faba92cf.png)
![Screenshot 2021-09-16 at 10 29 57 AM](https://user-images.githubusercontent.com/12683067/133539643-af69255f-7719-4876-a504-289d31b51739.png)

**Comment by michallepicki** [comment]
So in elixir modules one has to explicitly set `@moduledoc false` but in Erlang modules this is assumed default? So it could be either
1. `edoc` setting the doc chunks wrongly
2. `ex_doc` interpreting the missing information wrongly
3. ambiguity and behavior not specified in EEP

**Comment by josevalim** [comment]
Awesome find @kw7oe! 💯 

@michallepicki I don't think this is a wrong setting. It is rather a difference of defaults: edoc legit considers everything not explicitly doc-ed as private, Elixir has a different perspective. The EEP does not say what the defaults should be, only how values should be stored. I will update the docs!

:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by michallepicki** [comment]
> edoc legit considers everything not explicitly doc-ed as private

If that would be the case, wouldn't those modules be hidden in html documentation generated by edoc?

**Comment by josevalim** [comment]
Oh, you are 100% correct. I missed that. Let's bring in the big guns: @erszcz :)

**Comment by josevalim** [comment]
@erszcz I believe I found the root cause:

https://github.com/erlang/otp/blob/master/lib/edoc/src/edoc_layout_chunks.erl#L452

I think it should return an empty map, otherwise it gets the same treatment as `edoc`'s `@private`. WDYT?

**Comment by josevalim** [comment]
@michallepicki I think I mixed the edoc behaviour with Erlang/OTP's XML behaviour. In Erlang, they consider everything not explicitly doc-ed as private. But don't hold that against me because now I am not sure. Thanks for catching it.

**Comment by michallepicki** [comment]
`hidden` is returned separately from `none`, so alternatively `ex_doc` could maybe check here for `if doc != :hidden`:
https://github.com/elixir-lang/ex_doc/blob/4655d525a4713c4a35693e5ac46a91dfcd1e9a4e/lib/ex_doc/language/erlang.ex#L12

**Comment by josevalim** [comment]
@michallepicki IIRC we recently a discussion to standardize `:none` on being "do not show docs". That's why Elixir v1.12 changed all `:none` to empty maps.

**Comment by josevalim** [comment]
@michallepicki you can even see in the codebase we added notes to the places we check only for `:hidden` to be changed to check for maps.

**Comment by michallepicki** [comment]
> IIRC we recently a discussion to standardize :none on being "do not show docs"

I understand there are ongoing discussions but as an outsider I'll just point out that the semantics seem to have been clearly defined in the EEP-48: https://github.com/erlang/eep/blob/fd2c7be792211fcd510bda5d2e956e09c79bf0ea/eeps/eep-0048.md#part-2-the-docs-format

> It may be the atom none in case there is no documentation or the atom hidden if documentation has been explicitly disabled for this entry

There's no documentation information for the module, so it's correctly set to `none` IMO. `@private` would set it to `hidden`

**Comment by erszcz** [comment]
Indeed, with certifi master and these `rebar.config` opts:

```erlang
{edoc_opts,
 [
  {doclet, edoc_doclet_chunks},
  {layout, edoc_layout_chunks},
  {preprocess, true},
  {dir, "_build/default/lib/certifi/doc"}
 ]}.
```

I can see the chunk gets generated properly apart from one little detail - `module_doc = none`:

```erlang
$ r3 compile && r3 edoc && ex_doc "certifi" "2.7.0" _build/default/lib/certifi/ebin
$ r3 shell
1> rr(edoc_layout_chunks).
2> code:get_doc(certifi).
{ok,#docs_v1{anno = [{file,"certifi.erl"},{location,1}],
             beam_language = erlang,
             format = <<"application/erlang+html">>,module_doc = none,
             metadata = #{},
             docs = [{{function,cacertfile,0},
                      [{file,"certifi.erl"},{location,10}],
                      [<<"cacertfile()">>],
                      #{<<"en">> =>
                            [<<"CACertFile gives the path to the file with an X.509 "...>>]},
                      #{}},
                     {{function,cacerts,0},
                      [{file,"certifi.erl"},{location,26}],
                      [<<"cacerts()">>],
                      #{<<"en">> =>
                            [<<"CACerts builds an X.509 certificate list contain"...>>]},
                      #{signature =>
                            [{attribute,25,spec,
                                        {{cacerts,0},[{type,25,'fun',[...]}]}}]}}]}}
```

When we add a top-level module doc, this changes to:

```erlang
3> code:get_doc(certifi).
{ok,#docs_v1{anno = [{file,"certifi.erl"},{location,3}],
             beam_language = erlang,
             format = <<"application/erlang+html">>,
             module_doc = #{<<"en">> => [<<"Top-level module doc.">>]},
...
```

The immediate fix to get ExDoc HTML for certifi is to add top-level doc comments to the modules in question. A fix in upstream Erlang/EDoc is only going to be available with one of the next patch releases.

@josevalim 
> IIRC we recently a discussion to standardize `:none` on being "do not show docs". That's why Elixir v1.12 changed all `:none` to empty maps.

Thanks for this pointer! In this light it makes sense to make EDoc `@hidden` always return `:none`, EDoc `@private` return `:none` or an empty map depending on the command line flag (that's the purpose of the `@private` EDoc tag - to control if private or public docs are generated), and default to an empty map. I'll prepare such a PR to OTP.

Thank you @kianmeng @wojtekmach @michallepicki @josevalim @kw7oe for reporting and troubleshooting 🙏

**Comment by josevalim** [comment]
@michallepicki good call! I actually think the terminology there is actually pretty vague ("may"). I will send a PR there!

**Comment by josevalim** [comment]
@erszcz thank you! I will keep this issue open for guidance. Meanwhile please add the moduledocs, it won't hurt anyway. :)

**Comment by kianmeng** [comment]
Thanks for the ongoing discussion. 

Is the PR  https://github.com/open-telemetry/opentelemetry-erlang/pull/268 by @kw7oe and https://github.com/beam-telemetry/telemetry the recommended practice to follow to generate Erlang library with ExDoc?

Do we need to introduce extra files like `docs.config` and `docs.sh` which is not really part of an Erlang library?

**Comment by wojtekmach** [comment]
You need `docs.config` for configuration that is not available via CLI flags. `docs.sh` is a totally custom script which is not needed but i imagine almost everyone will have something like that.
