### ISSUE TITLE
Erlang: non exported functions are included

### ISSUE THREAD

**Issue by cw789** [elixir-lang/ex_doc#1402]
I'm currently trying to generate docs with ExDoc for `gen_smtp`.
But it seems that all non exported functions, which should be private by default in my understanding, are also included in the generated docs.

Is there something I misunderstood? I'm currently lost where to debug this more in detail.

---

ExDoc v0.25.3
Erlang/OTP 24.1.1

**Comment by josevalim** [comment]
@cw789 you can do `mix escript.install github elixir-lang/ex_doc` and it should work until we address it in Erlang/OTP or we do a new release.

**Comment by josevalim** [comment]
This should be addressed!

**Comment by cw789** [comment]
Thanks. Concerning ExDoc it is definitely addressed.
