### ISSUE TITLE
Linking to `source_url` when project is a subdirectory of a repo

### ISSUE THREAD

**Issue by DHager** [elixir-lang/ex_doc#1404]
Currently the code assumes a 1:1 relationship between projects and repos. It would be nice to improve the flexibility of `source_url_pattern` to handle the case where multiple projects are in one repo.

If there's general approval for this feature, I'm willing to make a PR.

## Problem description:

Suppose I have a repo hosted at `git@github.com:_myorg_/_myrepo_.git`. However it contains projects in subdirectories that are not part of an umbrella, such as `_proj_/mix.exs` .

Suppose I'm looking at documentation generated for function `Thingy.Errors.format_error/1` , which has a hyperlink back to github.

* Current: `https://github.com/_myorg_/_myrepo_/blob/thebranch/lib/thingy/errors.ex#L123`
* Desired: `https://github.com/_myorg_/_myrepo_/blob/thebranch/_proj_/lib/thingy/errors.ex#L123`

While I can set `source_url_pattern` directly, it forces me to duplicate/hardcode most of the URL as well as the value `thebranch`.

## Proposed change

Allow more (existing) variables to be interpolated into `source_url_pattern`. Currently only `path` and `line` are supported.

* Add `source_url`
* Add `source_ref`

Example:

```elixir
docs: [
  source_url: "https://github.com/_myorg_/_myrepo_",
  source_ref: "thebranch",
  source_url_pattern: "%{source_url}/blob/%{source_ref}/_proj_/%{path}#L%{line}
]
```

In this way the user can avoid duplicating values in existing settings and still set an arbitrary prefix before `%{path}`.

**Comment by josevalim** [comment]
Hi @DHager!

I am not sure if this is necessary. `source_url` and `source_ref` are used exclusively to build `source_url_pattern`. So if you are passing `source_url_pattern`, you can put it all directly:

```elixir
docs: [
  source_url_pattern: "https://github.com/_myorg_/_myrepo_/blob/thebranch/_proj_/%{path}#L%{line}
]
```

If for some reason you have those variables defined elsewhere, then you can interpolate it yourself, it doesn't need to be handled by ExDoc:

```elixir
docs: [
  source_url_pattern: "#{source_uri}/blob/#{source_ref}/_proj_/%{path}#L%{line}
]
```

Does this make sense?

**Comment by josevalim** [comment]
Closing this for now. Please let me know if the above is not enough!
