### ISSUE TITLE
Some documentation assets don't look great in darkmode

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ex_doc#1405]
Example: https://hexdocs.pm/floki/readme.html  see the logo in darkmode. Screenshot:
<img width="890" alt="Screen Shot 2021-10-15 at 5 35 29 PM" src="https://user-images.githubusercontent.com/18524/137556145-0375df2b-6aa1-42ac-9e21-b8928ebb868d.png">

I don't know what the best path here is. Either a nudge to authors that they should check their logos in darkmode or if ex_doc supported darkmode/daymode specific logos.

**Comment by josevalim** [comment]
To be fair, the same issue happens on GitHub when running GitHub on dark mode. How does GitHub solve this?

**Comment by cw789** [comment]
I think this should be tackled by logo / banner designers.
It's doable within the `.svg` itself.

**Comment by yordis** [comment]
Should this issue be brought up to CommonMark folks? This sounds like a markdown issue unless we want to solve it for `ex_doc` specific.

A trick we could do is to inject `?theme=` query to all the links pointing to an image, and hopefully the server knows what to do with it, but it is less than ideally IMO.

**Comment by yordis** [comment]
Otherwise, I would suggest to suggest people add some background to the logos, but obviously this is a workaround

**Comment by josevalim** [comment]
Yeah, I will close this because this is not an ExDoc issue per-se. Feel free filing up issues upstream though.

It is also worth noting that in ExDoc the preferred style is to add the logo to the sidebar, which is always a single color, and therefore it doesn't have those issues.

Finally, Hex will eventually add README rendering to packages, so there is even less reasons to add the README to the docs. :)

**Comment by yordis** [comment]
> Finally, Hex will eventually add README rendering to packages, so there is even less reasons to add the README to the docs. :)

@josevalim  if you don't mind, what does that mean?

I have been trying to move away from adding anything to README.md other than contribution and non-elixir stuff and move it to somewhere else, so I am curious to understand where this is going because still less than ideal at the moment for me.

**Comment by ericmj** [comment]
> if you don't mind, what does that mean?

We will display the readme on the hex.pm package page in the future. This page: https://hex.pm/packages/ex_doc.

**Comment by yordis** [comment]
oooh LETS GOOOOOO!

**Comment by yordis** [comment]
https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

Hah, related to

> A trick we could do is to inject ?theme= query to all the links pointing to an image, and hopefully the server knows what to do with it, but it is less than ideal IMO.

Maybe we should follow them on this one?

**Comment by josevalim** [comment]
@yordis if somebody wants to send a PR, it will be welcome. My understanding is that it all happens on the JS side of things. When you go into light mode, show all images that end with `#gh-light-mode-only` and hide all ending with `#gh-dark-mode-only`, and then the opposite for dark mode.

**Comment by yordis** [comment]
@josevalim I think you can do it with CSS thou, you hide or show the image based on the theme, something around the lines of

```css
.dark-theme img[src*="#gh-light-mode-only"] {
  display: block;
}
```

Let me try and see how that goes.

**Comment by josevalim** [comment]
Ah, smart!

**Comment by yordis** [comment]
Hey folks, any idea how to deal with `epub` having the image twice?

https://github.com/elixir-lang/ex_doc/pull/1445#issuecomment-987405219

**Comment by bcardarella** [comment]
@yordis hiding the `img` element as is suggested in the PR could work but it might be better to have a background image that swaps out depending upon the dark/light mode rather than the `img` tag. This would avoid the double render

**Comment by yordis** [comment]
@bcardarella how do you see the markdown to work for that?

Would you mind elaborating a bit more? I am confused about what to "swap out".

The double rendering would be only in the `epub` which I have never done it before so I am not sure if JS is the way to fix things there.

**Comment by bcardarella** [comment]
@yordis I would imagine that this CSS could be modified: https://github.com/elixir-lang/ex_doc/blob/4b2f4704f1c1cdaf52efd4f3e56293a8d79a7d05/assets/less/sidebar.less#L49-L55 to something like:

```less
  .sidebar-projectImage {
    .gh-dark-mode-only {
       background-image: url("<%= dark_logo_path(config) %>");
    }
    background-image: url("<%= light_logo_path(config) %>");
    display: inline-block;
    max-width: 64px;
    max-height: 64px;
    margin-left: 15px;
    vertical-align: bottom;
  }
```

then the `img` element I believe would have to be changed to a `div`. This is off the top of my head so push back if this direction isn't desirable.

**Comment by yordis** [comment]
@bcardarella Aaah I see where your head is at, as far as I can tell, only the main content changes theme, while the sidebar stays the same, see the video.

The changes I did are only for the main content.

https://user-images.githubusercontent.com/4237280/144948058-1807591a-ce32-4a57-8afc-678ee67f1695.mov

**Comment by bcardarella** [comment]
@yordis looking at the dev console it looks like Hex will add the class `night-mode` to the body tag. In that case a rule like this should override the day mode setting:

```less
body.night-mode .sidebar-projectImage {
  background-image: url("<%= dark_logo_path(config) %>");
}
```

a background-image for day mode element still needs to be done and the `img` tag changed to a `div`

**Comment by yordis** [comment]
@bcardarella I don't think it is needed for the sidebar. But please, correct me here.

**Comment by bcardarella** [comment]
d'oh! The issue I opened and I was way off on the solution :)

So I just looked at what GitHub actually does. They appear to render both the dark mode and the light mode elements. For the following markdown:

```markdown
![GitHub Light](https://github.com/github-light.png#gh-dark-mode-only)
![GitHub Dark](https://github.com/github-dark.png#gh-light-mode-only)
```

renders the following HTML

```html
<a target="_blank" rel="noopener noreferrer" href="https://github.com/github-dark.png#gh-light-mode-only" class="rich-diff-level-one"><img src="https://github.com/github-dark.png#gh-light-mode-only" alt="GitHub Dark" style="max-width: 100%;"></a> <a target="_blank" rel="noopener noreferrer" href="https://github.com/github-light.png#gh-dark-mode-only" class="rich-diff-level-one"><img src="https://github.com/github-light.png#gh-dark-mode-only" alt="GitHub Light" style="max-width: 100%;">
```

The following two rules exist to manage the toggling of the day/night mode images:

<img width="298" alt="Screen Shot 2021-12-06 at 8 57 23 PM" src="https://user-images.githubusercontent.com/18524/144952164-1c009691-f9e8-4d15-b7c7-2bc78fd1279c.png">
<img width="318" alt="Screen Shot 2021-12-06 at 8 57 50 PM" src="https://user-images.githubusercontent.com/18524/144952181-a69483fb-f3e7-44be-bc53-ff4b04d37401.png">

So given this I think the following CSS rule should allow you to toggle the correct images:

```css
body.night-mode img[src=$gh-light-mode-only] {
   display: none;
}
body.day-mode img[src=$gh-dark-mode-only] {
  display: none;
}
```

This would require the `day-mode` class to be added to `body` when in day-mode. Maybe you could use a `:not` psuedo class to match when not in `night-mode` but I haven't used it before.

**Comment by yordis** [comment]
@bcardarella yep, I am using `:not` at the moment, and that is quite closer to what I ended up doing.
