### ISSUE TITLE
Search by sections

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/ex_doc#1418]
I'm having a hard time with search by sections. They are not present in autocomplete and barely visible on search page.
It would be great if sections are properly indexed and displayed on the search page in relevant order.
![зображення](https://user-images.githubusercontent.com/588762/140318663-9b9c5b90-9bc7-446f-ab71-c49c74fcd3c8.png)

**Comment by josevalim** [comment]
It is full text search running on the client, there is a limited amount of work we can do. We did try autocompletion in the past and that was often not satisfactory either, as there is no fuzzing there. Unfortunately this is really a limitation of how search works.
