### ISSUE TITLE
change OTP document location to the canonical one

### ISSUE THREAD

**Issue by derek-zhou** [elixir-lang/ex_doc#1431]
According to this:

https://github.com/erlang/erlang-org/issues/53#issuecomment-967222778

The canonical OTP document location shall be https://www.erlang.org/doc/man not https://erlang.org/doc/man The redirect don't always work, such as now. I'd suggest to point to the canonical location sanctioned by the OTP team.

**Comment by eksperimental** [comment]
> According to this:
> 
> [erlang/erlang-org#53 (comment)](https://github.com/erlang/erlang-org/issues/53#issuecomment-967222778)
> 
> The canonical OTP document location shall be https://www.erlang.org/doc/man not https://erlang.org/doc/man The redirect don't always work, such as now. I'd suggest to point to the canonical location sanctioned by the OTP team.

We chose erlang.org because of the shorter domain.
I can take care of fixing ex_doc and the documentation in Elixir linking to the cannonical domain.

**Comment by josevalim** [comment]
@derek-zhou they didn't mention www.erlang.org is the canonical though? Simply the one is currently working. The reason I say so is because Erlang docs themselves use "https://erlang.org", for things like "https://erlang.org/doc/link/seetype".

**Comment by derek-zhou** [comment]
I guess we can wait a bit and let the OTP team officially pick on URL.

**Comment by derek-zhou** [comment]
Another idea we can entertain is to always build and host a full set of OTP doc on hexdoc itself. It is not very big anyway; and most people don't need the search.

**Comment by eksperimental** [comment]
> @derek-zhou they didn't mention [www.erlang.org](http://www.erlang.org) is the canonical though? Simply the one is currently working. The reason I say so is because Erlang docs themselves use "https://erlang.org", for things like "https://erlang.org/doc/link/seetype".

@josevalim and the URL https://erlang.org/doc/link/seetype actually worked? Because now it is isn't

**Comment by josevalim** [comment]
It doesn’t work but my point is that the fact their official docs are generating erlang.org does confirm the fact the one with www. Is the canonical one. We need explicit confirmation. :)

**Comment by eksperimental** [comment]
> It doesn’t work but my point is that the fact their official docs are generating erlang.org does confirm the fact the one with [www](http://www). Is the canonical one. We need explicit confirmation. :)

Yes. I am going to submit a PR to OTP unifying the URLS. But my question is did the link mentioned above ever worked? or it was a URL just for reference?

**Comment by josevalim** [comment]
I think it is just a reference.

**Comment by eksperimental** [comment]
> It doesn’t work but my point is that the fact their official docs are generating erlang.org does confirm the fact the one with [www](http://www). Is the canonical one. We need explicit confirmation. :)

I will explicitely ask, but for references. 
https://github.com/erlang/erlang-org#redirection-fixes
