### ISSUE TITLE
Error on build 'Phoenix' documentation from source

### ISSUE THREAD

**Issue by henrythebuilder** [elixir-lang/ex_doc#1432]
Hi,
I've found problem by building the documentation in some projects like Phoenix.
I'm not sure if the problem concerns only ex_doc, but building the docs produce this error:

```
Generated phoenix app
Generating docs...
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a list

    :erlang.length(nil)
    (elixir 1.14.0-dev) lib/list.ex:793: List.pop_at/3
    (elixir 1.14.0-dev) lib/code/normalizer.ex:187: Code.Normalizer.do_normalize/2
    (elixir 1.14.0-dev) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.0-dev) lib/code/normalizer.ex:325: Code.Normalizer.normalize_call/2
    (elixir 1.14.0-dev) lib/code.ex:1107: Code.quoted_to_algebra/2
    (elixir 1.14.0-dev) lib/macro.ex:946: Macro.to_string/1
    (ex_doc 0.25.1) lib/ex_doc/language/elixir.ex:132: ExDoc.Language.Elixir.callback_data/2

```
The same error was found with _ex_doc 0.25.5_ and _0.26.0-dev_

In this case the source of problem seems to be the `callback handle_control`

`lib/phoenix/socket/transport.ex:201:  @callback handle_control({message :: term, opts :: keyword}, state) :: ...`

The problem can be reproduced in an empty project by copying the same callback definition in a module and trying to generate docs with `MIX_ENV=docs mix docs`

Thanks.
___________
_Elixir: 1.14.0-dev (d4a2dfc3) self-compiled
OTP:  24.1.5 self-compiled_

**Comment by josevalim** [comment]
Thanks for the report! This was an Elixir bug and I am submitting a fix shortly.

**Comment by henrythebuilder** [comment]
Thanks :+1:
