### ISSUE TITLE
struct/0 is displayed differently

### ISSUE THREAD

**Issue by NickNeck** [elixir-lang/ex_doc#1433]
When `defstruct` has an `@doc` annotation the function will be displayed as `%MyStruct{}` in the content area but the link in the sidebar has the text `__struct__/0`. Example: https://hexdocs.pm/elixir/1.12.3/Task.html#__struct__/0

Is this intended?

**Comment by josevalim** [comment]
That's a bug. Thanks for the report!

**Comment by eksperimental** [comment]
I can take care of this.

**Comment by josevalim** [comment]
@eksperimental ping :)

**Comment by josevalim** [comment]
There is no rush, the ping was just in case you forgot about it. :)
