### ISSUE TITLE
Trimmed whitespace in embedded HTML breaks Mermaid.js diagrams

### ISSUE THREAD

**Issue by fhunleth** [elixir-lang/ex_doc#1434]
I am trying to use [Mermaid.js](https://mermaid-js.github.io/mermaid/#/) to add state diagrams to my documentation. Why Mermaid.js? Mostly because it looks easier to maintain than what I'm currently doing with ASCII art and exporting PNGs from another tool. 

There is a good blog post on this at 
https://fireproofsocks.medium.com/enhancing-elixir-documentation-with-mermaid-charts-340fad5c6426. To summarize the post, adding a diagram to a `moduledoc` looks like this:

```elixir
@moduledoc """
My documentation goes here...
<div class="mermaid">
graph TD;
classDef server fill:#D0B441,stroke:#AD9121,stroke-width:1px;
classDef topic fill:#B5ADDF,stroke:#312378,stroke-width:1px;
classDef db fill:#9E74BE,stroke:#4E1C74,stroke-width:1px;T1(TopicA):::topic --> G1{{GenServerA}}:::server;
T1(TopicA):::topic --> G2{{GenServerB}}:::server;
G2{{GenServerB}}:::server --> T2(TopicB):::topic;
T2(TopicB):::topic ==> DB[("Storage#nbsp;")]:::db;
</div>
"""
```

Note the semicolons at the end of the line. They're needed since the generated documentation trims all whitespace in the `div` so the diagram specification is one long line. This almost works. It turns out that the Mermaid.js parser requires new lines on some state diagram statements (like `direction LR`). Check out [this example](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoic3RhdGVEaWFncmFtLXYyXG4gICAgWypdIC0tPiBTdGlsbFxuICAgIFN0aWxsIC0tPiBbKl1cbiAgICBTdGlsbCAtLT4gTW92aW5nXG4gICAgTW92aW5nIC0tPiBTdGlsbFxuICAgIE1vdmluZyAtLT4gQ3Jhc2hcbiAgICBDcmFzaCAtLT4gWypdXG4gICAgICAgICAgICAiLCJtZXJtYWlkIjoie1xuICBcInRoZW1lXCI6IFwiZGVmYXVsdFwiXG59IiwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ) for what a state diagram spec looks like.

One fix to this would be to turn off the code that trims whitespace in the embedded HTML. I could not find an option to do this. It naively seems like this should be an easy thing to turn off, but I didn't find the code from my brief skim through the ex_doc source.

Before I dig deeper, I was wondering if this was a reasonable approach or whether support for this already existed and it was just a matter of decorating the HTML properly.

**Comment by jonatanklosko** [comment]
Hey! Instead of using a div directly it would be cleaner to use a code block, then do any necessary transformations with a bit of injected JavaScript. So basically

````elixir
@moduledoc """
My documentation goes here...

```mermaid
<graph definition>
```
"""
````

This is loosely related to [embedding Vega-Lite plots](https://github.com/elixir-lang/ex_doc#rendering-vega-lite-plots). Once we figure this out, we can add it to the README too.

I will try integrating this shortly :)

**Comment by fhunleth** [comment]
Oh wow, this works really well. Thank you @jonatanklosko!!
