### ISSUE TITLE
Support the contents of types and specs in full-text search

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/ex_doc#1437]
Currently when searching for the name of a type, the type shows up in the results.
But this is the only way a type is searchable.

However, it is not possible to search where (in which other types and as part of which function specs) a type is used.
This would be very helpful to for instance:
- See which functions depend on a particular type
- See which other types depend on a particular type
- See which types or functions match an approximate type signature.

As further argument, the definition for (public) types and specs is visible as text in the documentation. 
Since currently e.g. the contents of doctest code-snippets are searchable, it would make extra sense for the contents of types and specs to be searchable as well.

**Comment by josevalim** [comment]
This is unfortunately much trickier to do in practice. For example, what if a function uses a type through an alias? Do we want direct uses only or indirect too?

Wr could use full text search but I don’t feel like full text search would be the correct way to tackle this, it doesn’t solve the problems above, it won’t be well tokenized, etc.

I think this problem could be really interesting to tackle generally, see Haskell’s Hoogle but at the moment I would say it is outside of the scope of ExDoc.

thanks!

**Comment by josevalim** [comment]
In any case, thanks for opening the issue and asking! Sometimes when I reply from my phone I am too brief.  :D

**Comment by Qqwy** [comment]
No worries! I think there might be some merit in doing the simple thing (e.g. just use the text as-is, similarly to code examples are currently searched), 
but if you think this will do more harm than good then I trust your judgement :slightly_smiling_face:.

**Comment by josevalim** [comment]
Yeah, it is just that full text indexing is really not that reliable for stuff like this due to the tokenizer and everything else. It has to be structured but that has its own challenges.
