### ISSUE TITLE
Sort items "naturally" in menu, summary, function list, etc.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1440]
Functions in the menu are current listed like this:

- reraise/2
- reraise/3
- send/2
- sigil_C/2
- sigil_D/2
- sigil_N/2
- sigil_R/2
- sigil_S/2
- sigil_T/2
- sigil_U/2
- sigil_W/2
- sigil_c/2
- sigil_r/2
- sigil_s/2
- sigil_w/2
- spawn/1
- spawn/3 

I was trying to hop from the documentation from sigil_S to sigil_s, and i found it counter intuitive that they were that far apart, specially inside the module. I think we should make it more "natural".

**Comment by josevalim** [comment]
Sounds good to me. A PR is welcome.

**Comment by eksperimental** [comment]
> Sounds good to me. A PR is welcome.

If anybody wants to tackle it, please be welcome. If not, I will eventually take care of it. As of now, I am kind of busy with other stuff.

**Comment by josevalim** [comment]
We should avoid libraries in ExDoc because otherwise your documentation generation tool can impose restrictions on your actual lib/app code. :)

**Comment by eksperimental** [comment]
> We should avoid libraries in ExDoc because otherwise your documentation generation tool can impose restrictions on your actual lib/app code. :)

A library like this is likely to to not have dependencies... given this and the Elixir requirements match the ones of ExDoc, would this still be an issue?

**Comment by josevalim** [comment]
First, that library will be unable to use ExDoc to publish their own docs, so we would need to coordinate at least that with them.

Second, any user of that library may not be limited by ExDoc particular requirements. So my answer would still be a no. :)

**Comment by eksperimental** [comment]
> > Sounds good to me. A PR is welcome.
> 
> If anybody wants to tackle it, please be welcome. If not, I will eventually take care of it. As of now, I am kind of busy with other stuff.

I am already taking care of this.

**Comment by am-kantox** [comment]
Since the “natural” in “natural order” is quite specific here, I’d propose the custom sorter that is explicitly optimized for valid elixir names (unquoted Unicode atoms, variables, and calls to be in NFC form).

It is nimble for 99% of the input and has a fallback to properly sort exotics like Greek/Cyrillics and/or umlauts and other diacritics.

```elixir
defmodule M do
  @case_shift ?a - ?A + 1
  @lowercase_ascii Enum.to_list(?a..?z)
  @uppercase_ascii Enum.to_list(?A..?Z)
  @ascii_letters @lowercase_ascii ++ @uppercase_ascii
  @digits Enum.to_list(?0..?9)
  @service [?_]
  @ascii @ascii_letters ++ @digits ++ @service

  defguard is_same_group(c1, c2)
           when (c1 in @lowercase_ascii and c2 in @lowercase_ascii) or
                  (c1 in @uppercase_ascii and c2 in @uppercase_ascii)

  @spec sorter(String.t(), String.t()) :: boolean()
  def sorter(<<c::8, tl1::binary>>, <<c::8, tl2::binary>>) when c in @ascii,
    do: sorter(tl1, tl2)

  def sorter(<<c::utf8, tl1::binary>>, <<c::utf8, tl2::binary>>), do: sorter(tl1, tl2)

  def sorter(<<c1::8, _::binary>>, <<c2::8, _::binary>>) when is_same_group(c1, c2),
    do: c1 <= c2

  def sorter(<<c1::8, _::binary>>, <<c2::8, _::binary>>)
      when c1 in @lowercase_ascii and c2 in @uppercase_ascii,
      do: c1 <= c2 + @case_shift

  def sorter(<<c1::8, _::binary>>, <<c2::8, _::binary>>)
      when c1 in @uppercase_ascii and c2 in @lowercase_ascii,
      do: c1 + @case_shift <= c2

  def sorter(<<c1::8, _::binary>>, <<c2::8, _::binary>>) when c1 in @ascii and c2 in @ascii,
    do: c1 <= c2

  def sorter(s1, s2) do
    [s1, s2]
    |> Enum.map(&String.normalize(&1, :nfd))
    |> Enum.map(&String.split(&1, "", trim: true, parts: 2))
    |> case do
      [[c, ""], [c, <<d::utf8, _::binary>>]] ->
        not (c in @digits and d in @digits)

      [[c, <<d::utf8, _::binary>>], [c, ""]] ->
        c in @digits and d in @digits

      [[c, tl1], [c, tl2]] ->
        sorter(tl1, tl2)

      [[c1 | _], [c2 | _]] ->
        cond do
          String.upcase(c1) == c2 -> true
          c1 == String.upcase(c2) -> false
          true -> String.upcase(c1) <= String.upcase(c2)
        end
    end
  end

  #############################################################################

  @input ~w|
    reraise/2
    reraise/3
    send/2
    sigil_C/2
    sigil_D/2
    sigil_c/2
    λ/1
    spawn/1
    spawn/3
    Λ/1
    a1/1
    a0/1
    a10/1
    a1_0/1
    a_0/1
    äpfeln/1
    Äpfeln/1
    умножить/1
    Вычесть/1
    вычесть/1
  |

  @sorted ~w|
    a0/1
    a1/1
    a10/1
    a1_0/1
    a_0/1
    äpfeln/1
    Äpfeln/1
    reraise/2
    reraise/3
    send/2
    sigil_c/2
    sigil_C/2
    sigil_D/2
    spawn/1
    spawn/3
    λ/1
    Λ/1
    вычесть/1
    Вычесть/1
    умножить/1
  |

  def test(), do: Enum.sort(@input, &sorter/2) == @sorted
end
```

**Comment by josevalim** [comment]
@am-kantox that's an interesting approach, thanks for sharing! I wonder if we can simplify it by doing `to_charlist` and then sorting everything as usual for the ascii ones?

The reason why I think we can simplify this further is because mixed case is extremely uncommon, so I think we don't really need to worry about it besides ascii.

**Comment by am-kantox** [comment]
> mixed case is extremely uncommon
That’s right, but it’s still handled in the last clause, that’s why I said in 99% of cases we go through bitstream pattern match. I am not sure if `charlist` match would be faster, are you? I could have done benchmarks tonight.

> we don't really need to worry about it besides ascii
One it’s the last clause, I don’t get why would not we handle it as well. ASCII goes through the first clauses.

Several clauses are still needed because of ordering here:
```elixir
  a0/1
  a1/1
  a10/1
  a1_0/1
```

**Comment by am-kantox** [comment]
The only glitch I see is `Äpfeln/1` and `äpfeln/1` are not consequent. I’d appreciate seeing them together, but AFAICT that’s impossible without extra clauses to handle diacritics. 

Also, I’ve just figured out that clauses for ASCII might be actually generated (as those in `String.{down,up}case/1`) to avoid going through `:unicode.characters_to_nfkd_list()` for long strings.

OTOH, the number of items to sort in this case barely exceeds several dozens, so I surely like your proposal more.

**Comment by josevalim** [comment]
> The only glitch I see is Äpfeln/1 and äpfeln/1 are not consequent.

Right, as I said above, it won't happen in practice because identifiers can't start with uppercase. Also note this is order defined by Unicode too (Á comes before A).

> OTOH, the number of items to sort in this case barely exceeds several dozens, so I surely like your proposal more.

I also use sort_by, which is not pairwise, so it should be faster generally.

**Comment by am-kantox** [comment]
> it won't happen in practice because identifiers can't start with uppercase

Well, technically it will.

```elixir
die_äpfeln/1
die_Äpfeln/1
```

but we should not care much about it, yes.

**Comment by eksperimental** [comment]
Thank you @am-kantox for chiming in.
I found https://github.com/BinaryNoggin/natural_order
and I have submitted a PR with improvements, but the code is here.
https://github.com/eksperimental/natural_order/blob/refactoring/lib/natural_order.ex

I will for sure take any lessons from this discussion and apply it to that library.

**Comment by josevalim** [comment]
We either need to support the full Unicode specification, which is complex, or we do only a subset, and any subset we pick is random. So I am more inclined to go with the solution I posted above, for the ASCII only subset, and call it a day. :D

**Comment by eksperimental** [comment]
@josevalim the one other issue with your approach the how it treats numbers,

```elixir
iex(21)> Enum.sort_by(~W(var_2/0 var_11/0), &Sorter.to_sorted_charlist/1) 
["var_11/0", "var_2/0"]
```

**Comment by josevalim** [comment]
Which is fine. Once it becomes an issue, we work on it? But you could also do a pass in my code that converts any sequence of numbers into a regular integer, so they are compared correctly.

**Comment by josevalim** [comment]
I can update the snippet to address numbers later.

**Comment by adkron** [comment]
I released a new version of `NaturalOrder` with the changes that @eksperimental submitted.

https://hex.pm/packages/natural_order if that helps.

**Comment by am-kantox** [comment]
FWIW, benchmarks:
```
## Sorter.Bench
ben iterations   average time 
jv      100000   18.14 µs/op
am       50000   66.86 µs/op
no        1000   1833.19 µs/op
```

**Comment by josevalim** [comment]
Solution with numbers solved and moved underscored before letters [as proposed by Unicode](https://www.w3.org/TR/xml-entity-names/bycodes.html):

```elixir
defmodule Sorter do
  def to_sortable_charlist(string) do
    string
    |> :unicode.characters_to_nfkd_list()
    |> make_sortable()
  end

  @offset -1_000_000_000

  # Numbers come first, so group and pad them with offset
  defp make_sortable([digit | chars]) when digit in ?0..?9 do
    {digits, chars} = Enum.split_while(chars, & &1 in ?0..?9)
    [@offset + List.to_integer([digit | digits]) | make_sortable(chars)]
  end

  # Then underscore
  defp make_sortable([?_ | chars]), do: [?0 | make_sortable(chars)]

  # Then uppercased letters and lowercased letters
  defp make_sortable([char | chars]) when char in ?a..?z do
    [char - 31.5 | make_sortable(chars)]
  end

  defp make_sortable([char | chars]), do: [char | make_sortable(chars)]
  defp make_sortable([]), do: []
end

ExUnit.start()

defmodule Example do
  use ExUnit.Case, async: true

  @input ~w|
    reraise/2
    reraise/3
    send/2
    sigil_C/2
    sigil_D/2
    sigil_c/2
    λ/1
    spawn/1
    spawn/3
    Λ/1
    abc/1
    a2/1
    a1/1
    a0/1
    a10/1
    a1_0/1
    a_0/1
    äpfeln/1
    Äpfeln/1
    умножить/1
    Вычесть/1
    вычесть/1
  |

  @sorted ~w|
    Äpfeln/1
    a0/1
    a1/1
    a1_0/1
    a2/1
    a10/1
    a_0/1
    abc/1
    äpfeln/1
    reraise/2
    reraise/3
    send/2
    sigil_C/2
    sigil_c/2
    sigil_D/2
    spawn/1
    spawn/3
    Λ/1
    λ/1
    Вычесть/1
    вычесть/1
    умножить/1
  |

  test "sort" do
    assert Enum.sort_by(@input, &Sorter.to_sortable_charlist/1) == @sorted
  end
end
```

**Comment by josevalim** [comment]
@eksperimental do you want to send a PR for this or we can leave it up for grabs? :)

**Comment by eksperimental** [comment]
To give the possibility to new contributors to ExDocs, I'll leave it up for grabs, but if in one week nobody takes it, I will take care of it.

**Comment by eksperimental** [comment]
I will start working on it then.

**Comment by eksperimental** [comment]
Cool!
Same should apply for `?`
