### ISSUE TITLE
Depends (indirectly) on Erlang development environnement

### ISSUE THREAD

**Issue by bortzmeyer** [elixir-lang/ex_doc#1441]
```
==> earmark_parser
Compiling 1 file (.yrl)
/usr/lib/erlang/lib/parsetools-2.3.1/include/yeccpre.hrl: no such file or directory
could not compile dependency :earmark_parser, "mix compile" failed. You can recompile this dependency with "mix deps.compile earmark_parser", update it with "mix deps.update earmark_parser" or clean it with "mix deps.clean earmark_parser"
```

This is because the file `yeccpre.hrl` is distributed only with Erlang development files. An Erlang runtime is not enough. IMHO, it is worth to mention this dependency (on Debian, just install the package `erlang-dev`).

**Comment by josevalim** [comment]
Can you please send a pull request that updates the README? :)

**Comment by bortzmeyer** [comment]
> Can you please send a pull request that updates the README? :)

Done, see #1442.
