### ISSUE TITLE
Add an ability to sync night mode with system preferences

### ISSUE THREAD

**Issue by mkaput** [elixir-lang/ex_doc#1443]
Currently, night mode is controlled by a local storage variable, and it must be manually enabled/disabled. Some people tend to extensively use the system settings for controlling the light/dark mode depending on lightning conditions, and this does not play well with the local storage approach ex_doc uses. Ideally, it would be best if there was an `Sync with system` option, just like for example GitHub does. Even better, it would be awesome to let it be the default option.

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by josevalim** [comment]
A pull request to implement this would be welcome. IIRC, we already consult the system preference, but then we store that in the cookie.

**Comment by yordis** [comment]
If you want to observe the theme changes

```js
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
    const systemTheme = e.matches ? "dark" : "light";
});
```

**Comment by josevalim** [comment]
Closing this for now but a PR is welcome if you want to improve this!

**Comment by mkaput** [comment]
If anyone would like to work on this, then please welcome! Sorry for not mentioning this earlier, but I do not have free bandwidth.
