### ISSUE TITLE
ExDoc as an escript does not support multiple formatters at once.

### ISSUE THREAD

**Issue by starbelly** [elixir-lang/ex_doc#1448]
Currently, the mix task for ex_doc will iterate over multiple formatter options (defaults to `["html", "epub"]`) to produce html and epub by default, This is not supported when ex_doc is an escript. 

In order to support this from the escript, most of the following would need to change I believe : 

- add `formatter: [:string, :keep]` around here https://github.com/elixir-lang/ex_doc/blob/c86f4b81c20591cb328121eab3dc6342bef1f131/lib/ex_doc/cli.ex#L23 

- Modify https://github.com/elixir-lang/ex_doc/blob/c86f4b81c20591cb328121eab3dc6342bef1f131/lib/ex_doc.ex#L15 to iterate over formatter options ala `mix docs` 

- Possibly change https://github.com/elixir-lang/ex_doc/blob/c86f4b81c20591cb328121eab3dc6342bef1f131/lib/ex_doc/config.ex#L21 to be a list of strings vs a string. This would not be required necessarily as we could simply iterate the formatter options and produce a new config on each go.  

- Finally, we could adjust the mix task to simply pass the options on vs iterate and generate per formatter option. 

I'm happy to do a PR for this, but I wasn't sure if there was a caveat around adjusting all this.

**Comment by josevalim** [comment]
Hi @starbelly!

I was writing a somewhat longish reply and I realized it would be simpler if i did the changes. In a nutshell, I wanted to keep the handling of multiple formatters in the cli/task and not in the internals. I pushed my code!
