### ISSUE TITLE
UTF8 or not UTF8?

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#1451]
I just got this [issue](https://github.com/RobertDober/earmark_parser/issues/80)

and EarmarkParser crashes on the particular input because it is not legal UTF8 so I somehow suspect (actually: I am horrified) that I need to handle non UTF8 input?

Is this true or can I (and you in ex_doc :blush:) just reject non UTF8 input.

Here is the string again for your convenience:

```
"\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*"
<<137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 2, 42>>
iex(7)> ["\x89PNG\r\n\x1A\n\0\0\0\rIHDR\0\0\x02*"] |> EarmarkParser.LineScanner.scan_lines
** (ArgumentError) argument error
```
which happens because I use `~r/..../u` in the scanner.

**Comment by josevalim** [comment]
We don't expect to handle not non-UTF8 input. It is fine to crash IMO. :)
