### ISSUE TITLE
Incorporate new sidebar designs

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1458]
* [ ] Improve sidebar navigation (Top should no longer be required, clicking navigates by default)
* [ ] Replace all icomoons by their remix equivalent
* [ ] Bring keyboard shortcuts inside settings (see screenshot below for an example)

/cc @cristineguadelupe 

<img width="515" alt="Screenshot 2022-01-07 at 02 23 43" src="https://user-images.githubusercontent.com/9582/148476498-0f0dff65-239f-46d5-afc2-6ac286313d7f.png">

**Comment by cristineguadelupe** [comment]
Done!
