### ISSUE TITLE
Few notes regarding the new design

### ISSUE THREAD

**Issue by Qizot** [elixir-lang/ex_doc#1465]
1. With a new design of the sidebar the module gets automatically loaded on expand action. It is quite distracting for a user (at least for me) that the page start to reload resulting in lost position of the scroll. The selected module gets scrolled to the top of the sidebar. 

It looks quite strange to see the accordion to expand and then after a while to reset its position after the load. It was less noticeable without the auto selection.

2. Don't you think that the new dark mode is a little bit too aggressive? It is of a really high contrast therefore it looks like it is glowing, I mean the code part, the sidebar seems fine. 

I'm fine to discuss the problems stated above and hear from you what is your point on them.

**Comment by josevalim** [comment]
> It looks quite strange to see the accordion to expand and then after a while to reset its position after the load. It was less noticeable without the auto selection.

Yes, we are working on it. :)

> Don't you think that the new dark mode is a little bit too aggressive? 

People complained that the previous one was too soft. Maybe the new is too aggressive, we will keep our ears open for feedback.

**Comment by josevalim** [comment]
We will push a slightly reduced contrast soon. Closing this as we are working on it right now. :) Thanks!
