### ISSUE TITLE
Overflow of text in the new sidebar - still an issue

### ISSUE THREAD

**Issue by bblaszkow06** [elixir-lang/ex_doc#1466]
As the changelog states:
> :nest_modules_by_prefix is no longer supported with the more spacious sidebar. If there are still issues, please reach out

I'm reaching out to let you know the new sidebar might not be enough :wink: 

In particular, `membrane_core` has a bunch of structs like `Membrane.Pipeline.CallbackContext.CrashGroupDown`, `Membrane.Bin.CallbackContext.CrashGroupDown` and `Membrane.Element.CallbackContext.Caps` that look like this with `ex_doc` at a011116

![image](https://user-images.githubusercontent.com/2119556/148807699-1cc6c123-7219-4c3e-a9de-68c10b8e04c7.png)

IMO the nesting not only prevents overflow but also improves readability on things that fit into the sidebar, effectively creating a subgroup. I'd love to see the support for that option continued, but I'm open to other options to solve that as well.

**Comment by josevalim** [comment]
Ah, we definitely need to bring it back then. Can you please send a PR then that reverts b9afe96c971f5376da9ccef7997e9a5b6b5313b1 and adds styling to the nesting? Previously nesting had its own style but I think we can make it have the same styling as the current sidebar groups.

**Comment by josevalim** [comment]
It is back!
