### ISSUE TITLE
JS null error when loading

### ISSUE THREAD

**Issue by adamu** [elixir-lang/ex_doc#1470]
When I open the elixir `main` docs: https://hexdocs.pm/elixir/main/, I get a JS error (happens in Firefox, Safari, and Chrome):

<img width="875" alt="image" src="https://user-images.githubusercontent.com/498229/148954237-8ce97541-c29c-4272-9e64-8c31df96180a.png">

Clicking the ⚙️ icon here does nothing.

However, it seems isolated to `main`, because , https://hexdocs.pm/ex_doc/, which is on v0.27.0, is working correctly.

**Comment by josevalim** [comment]
Thank you! That's a nightly build, so it may error, it will be automatically updated again soon and it should be good!
