### ISSUE TITLE
Bug with settings menu in 0.26.1

### ISSUE THREAD

**Issue by starbelly** [elixir-lang/ex_doc#1474]
In generating documentation with the latest release, the settings menu would not pop, I found an error in the console of my browser. This was from publishing rebar3_ex_doc 0.2.5, which I reverted per this bug. 

I also tried this in an elixir project, locally, and got the same problem. 

```
Uncaught TypeError: Object(...)(...) is null
    tt https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    <anonymous> https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    h https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    <anonymous> https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    n https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    <anonymous> https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
    <anonymous> https://hexdocs.pm/rebar3_ex_doc/dist/app-973561a99a0985d496b3.js:2
app-973561a99a0985d496b3.js:2:98595
```

I'm happy to look into this further, but it'll be a minute.

**Comment by cristineguadelupe** [comment]
Hey @starbelly 
I don't know why but when I generate the documentation for Ecto using the current 0.27.1 and when I do the same for rebar3_ex_doc I got a different footer and I'm almost sure that's the reason for the problem. The rebar version is not rendering the hex search.

Ecto footer with the hex search and no problems
<img width="591" alt="Screen Shot 2022-01-11 at 16 26 21" src="https://user-images.githubusercontent.com/5660941/149009416-5d3fe3b4-f8aa-4a19-9140-881efef28598.png">

Rebar footer
<img width="1125" alt="Screen Shot 2022-01-11 at 16 26 33" src="https://user-images.githubusercontent.com/5660941/149009471-8589c924-40b4-4531-b66f-eacbb16dc715.png">

**Comment by jonatanklosko** [comment]
The first part is rendered conditionally here:

https://github.com/elixir-lang/ex_doc/blob/0d4ca8be0fb765ad42edacc563902a4dba398dcb/lib/ex_doc/formatter/html/templates/footer_template.eex#L2-L4

`rebar3_ex_doc` doesn't define `project()[:package]` in `mix.exs`.

So the "Search" link may not be there, and we should have a check before adding listener here:

https://github.com/elixir-lang/ex_doc/blob/a16e570db95d77fe4c20a05a7869beac06a82e23/assets/js/quick-switch.js#L39

**Comment by josevalim** [comment]
I am pushing a fix and shipping new versions soon. But you may want to pass the package option forward if you have this information available.

**Comment by josevalim** [comment]
v0.27.2 is out, thanks everyone!

**Comment by starbelly** [comment]
@josevalim @jonatanklosko Thanks for pointing out the package issue, patched rebar3_ex_doc to pass that long ❤️
