### ISSUE TITLE
Is `API Reference` Page Still Needed?

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1476]
I've noticed that ExDoc generated an extra `Modules` and `Mix Tasks` tab section, and it looked like a duplication of the `API Reference` page. Should the `API Reference` page be deprecated or removed in favour of the new tab section?

![image](https://user-images.githubusercontent.com/134518/149187600-3b930bbf-df23-4585-a09a-be0577d57eb2.png)

**Comment by josevalim** [comment]
Yes, it provides a quick listing of all modules, and it is the default page unless users configure something otherwise. :)
