### ISSUE TITLE
Menu button interferes with sidebar content

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/ex_doc#1482]
While testing the custom scrollbar, I noticed that the top menu doesn't have a background when the browser windows height is relatively low.

This looks a bit odd:
<img width="647" alt="Screenshot 2022-01-14 at 15 22 48" src="https://user-images.githubusercontent.com/792046/149530699-227d2866-c990-4409-9b9b-70c05d827f94.png">

I am not sure what would be the best solution, without wasting too much screen space. 
Maybe just add some background with rounded corners?

**Comment by josevalim** [comment]
@moogle19 can we make it so the hamburger icon actually doesn't scroll with the sidebar? It should just always on stop.

**Comment by moogle19** [comment]
@josevalim 
No quite sure if I understand that correctly. 

So the menu stays with the search field and can scroll out of view? That could be a bit tricky, because the menu button is outside of the sidebar (probably because it needs to be visible when the sidebar is closed).

I considered to move it to the right, so it is outside of the sidebar, since there is enough space on the left of the content.
But it also transforms into the "x" to close the search, when the search field is selected.

This also results in behaviour like this:
https://user-images.githubusercontent.com/792046/149572655-7c4d2411-baa1-4f7c-8436-2851aa9f66ad.mov

**Comment by josevalim** [comment]
> So the menu stays with the search field and can scroll out of view? 

Exactly. When the sidebar is opened, it should stay within that sidebar location. If the sidebar is closed, then it moves. There is already some JavaScript to manage it, perhaps we could use that code to move it around.

**Comment by moogle19** [comment]
Sounds good. That could also fix the behaviour in the video, where the button jumps around.
