### ISSUE TITLE
Zero digit looks off in Upper case text

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1483]
The digits in general look smaller, but the problem with 0 is the passes as lowercase "o".

![image](https://user-images.githubusercontent.com/9133420/149548481-784f173c-9595-407c-9ed0-9b4084e3af9a.png)

The font in question is Merriweather Light.

**Comment by josevalim** [comment]
That's [how the font works](https://fonts.google.com/specimen/Merriweather?preview.text=0OS%20Almost%20before%20we%20knew%20it,%20we%20had%20left%20the%20ground.&preview.text_type=custom). We could revisit the fonts used in the application, but we would need a designer to consistently look at how fonts are used in the app, which is not in scope for now. Thanks!

**Comment by eksperimental** [comment]
IMHO, being technical documentation what we are generating we should avoid fonts that will treat numbers like that,
