### ISSUE TITLE
filename option in extras config fails with underscore

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1485]
There are two issues.

1.

```
extras: [
  "LICENSES/LICENSE.0BSD.txt": [filename: "license_0BSD", title: "BSD Zero Clause License"]
]
```

it will create a file named `license_0bsd.html` but the generated html file links to `license-0bsd.html` giving an 404 error

2.  I don't know if this is documented, or if it's a bug.
if i give a subfolder as the path for the filename `filename: "license/0BSD"` it crashes.
It makes sense because it is "filename" and not "path" but maybe we could raise with a better error than just crashing the app.

**Comment by josevalim** [comment]
I cannot reproduce this. Here is what I did in this repo:

1. I renamed `CHANGELOG.md` to `CHANGE.LOG.md`
2. I changed `extras` in `mix.exs` to this:

```
      extras: [
        "README.md",
        "LICENSE",
        "CHANGE.LOG.md": [filename: "change_log", title: "YADA"],
      ],
```

3. I called `mix docs`

Navigation worked as expected in the sidebar. Can you please provide reproduction steps?

**Comment by eksperimental** [comment]
> Navigation worked as expected in the sidebar. Can you please provide reproduction steps?

it is actually the contents of the .md file that link to the wrong file, not the navigation

**Comment by josevalim** [comment]
Do you mean the content that you wrote in another page? We don't rewrite links, except for the extension, because you might as well be linking to another resource that you are adding manually to `doc`.

**Comment by eksperimental** [comment]
the contents of the README.md file 

```markdown
[LICENSES/LICENSE.0BSD.txt](LICENSES/LICENSE.0BSD.txt)
```

with config `filename: "license_0BSD"` it links to a `license-0BSD.html` (giving error 404),
with config `filename: "license-0BSD"` it links to a `license-0BSD.html` and it works as excepected.

**Comment by eksperimental** [comment]
Cool. The fix seems to work.

What about the second issue, if the filename has a subfolder, it raises.

```
** (File.Error) could not write to file "extended_types/doc/license/0BSD.html": no such file or directory
    (elixir 1.13.1) lib/file.ex:1054: File.write!/3
    (ex_doc 0.27.3) lib/ex_doc/formatter/html.ex:233: anonymous fn/3 in ExDoc.Formatter.HTML.generate_extras/3
```

Should we allow the creation of subfolders? or raise with a better message when parsing the filename?

**Comment by eksperimental** [comment]
oh.. I thin we alraedy had the discussion about the subfolder generating an issue with the assets that are relative to the base folder.
So I guess we should raise as soon as we read the configs
