### ISSUE TITLE
Search field doesn't resize when scrollbar uses full height

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/ex_doc#1486]
The `sidebar-header`s background resizes and keeps it's `12px` margin to the scrollbar, but the search field  doesn't.
 
<img width="306" alt="Screenshot 2022-01-14 at 20 08 15" src="https://user-images.githubusercontent.com/792046/149571606-ec9e70bc-cdcc-455c-af30-44f7af119e1c.png">

I tried to fix it but couldn't find the class which controls the background and margin for the search field (`sidebar-search` does not).

**Comment by josevalim** [comment]
@moogle19 I could not reproduce this on Firefox nor Chrome. None of them resize for me. How do you reproduce this? :)

**Comment by moogle19** [comment]
I tried it on Firefox for macOS.
Just went to the ExDoc site and made the windows height <500px.

**Comment by josevalim** [comment]
Same here and I cannot reproduce it. :(

**Comment by moogle19** [comment]
Strange. 

This is how it looks for me:
https://user-images.githubusercontent.com/792046/149575545-a31100e1-7ca5-4c3e-afe4-abd67a646657.mov

**Comment by moogle19** [comment]
I think it is because I set `Show scroll bars` to `Always` in the System Preferences -> General. 
When I set it to `When scrolling` nothing resizes.
