### ISSUE TITLE
Are there plans for a new tab in the sidebar?

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1487]
I am asking this question because I don't know if there is any ongoing plan on making use on the spaces on the right of the tabs "PAGE" and "MODULES".

If not, I would like to make a proposal, but I will have to carefully think about it first.

**Comment by josevalim** [comment]
That’s already used for “Mix Tasks” in certain projects, such as hexdocs.pm/mix.

**Comment by eksperimental** [comment]
I see.
Well, I was thining about an "About" sections.
I feel there is a disconection from ExDoc documentation linking to the project Repository (I may be missing something here),
but I feel it is easy to  get to the docuementation in hexdocs.pm from the Project repository (for example Github) and from the hex.pm package page, but it is not easy to get to the repository or the hex.pm package page.
This is because the information is in the README page and this is not included by default.

So far what I need to do is when I read the documentation which has not enabled the "view sourced code" (not enabled by default), it to manually go to the hex.pm package page, and find the Github link.

May be we could add an (i)  [information] icon, or an "about" icon, where we could list the important links, such as:
- link to repository
- link to hex package page (currently at the bottom of the pages)
- License information
- Author/Maintainers
- etc

**Comment by eksperimental** [comment]
Additionally I would like the title of the project and the log to link to the main page (index.html) or to the API reference (maybe this one option is better).

As of now I cannot find a way to go back to it easily,
for example, when I read the Elixir documentation I never ever go to "https://elixir-lang.org/docs.html",
but maybe hundread times i go to Kernel , same with other projects, if it linked to the API Reference I would constantly use it

Linkiing to the project homepage could be added in this "about" section.

**Comment by josevalim** [comment]
We could allow external links under “Pages”. Also note that we have all of those Hex links in the footer. Perhaps we could have a Hex icon and move it to the top.

**Comment by eksperimental** [comment]
> Also note that we have all of those Hex links in the footer. Perhaps we could have a Hex icon and move it to the top.

As of now I only see the link to the current package, but it is way too inconvenient at the bottom specially for long pages.

> We could allow external links under “Pages”.
That is a really good idea. How about an "About" page under PAGES tab?  It will be standard in every package, same like API Reference.

**Comment by josevalim** [comment]
I would like to avoid introducing new pages into the user docs. So we have:

1. Introduce the package information at the top of API Reference.
2. Introduce a Hex icon close to the settings and source icons
3. Add external links to the "Pages" sidebar

**Comment by eksperimental** [comment]
+1 for number 1

**Comment by josevalim** [comment]
PR welcome! We can have the about section there!

**Comment by eksperimental** [comment]
So this information will be coming from the package config in the Mix file?

**Comment by josevalim** [comment]
Check how we handle the footer. But we have the package name, and we can render links to the rest from it. :)
