### ISSUE TITLE
Idea: CMD+K menu for easier navigation

### ISSUE THREAD

**Issue by davydog187** [elixir-lang/ex_doc#1488]
Opening an issue as this is an idea/experiment that I'd like to bring to `ex_doc` but haven't had the time to explore myself.

## Background
`ex_doc` provides several keyboard shortcuts such as `g` for switching between packages, or `/` to highlight the search menu. What I'd love to see is a faster way to navigate and jump between modules or sections, using the [CMD+K Menu](https://uiw.tf/cmdk) UI pattern. A similar pattern was just introduced to Github which I find highly beneficial and complementary to the existing search functionality.

<img width="1130" alt="Screen Shot 2022-01-15 at 9 14 15 AM" src="https://user-images.githubusercontent.com/1019721/149624804-4845ac03-bd72-4185-972d-fe5d6cfd6709.png">

## Feature
* Typing `CMD+K` on MacOS or `CTRL+K` on Windows initiates a modal
* Modal provides a quick access menu for switching between projects, modules, and sections
* Modal can be extended for future functionality

Possibly this was already part of the existing ideas for the `ex_doc` design upgrades, but I thought I'd share to collect feedback. Thanks!

**Comment by josevalim** [comment]
We discussed ways of unifying the current Hexdocs search with the current autocomplete and that sounds like a good way to do it. I like how it could be used to navigate everything though. My only question is if it is a separate modal or we reuse the existing search.

**Comment by davydog187** [comment]
I would suggest that search and the quick find menu be separate. The project navigation could be consolidated into this widget.

Ideally search is for fuzzy find of content, while quick find is for navigation

**Comment by josevalim** [comment]
Correct. My point is that the search today already has this duel behaviour: it works for fuzzy but also a quick find. We shouldn't have fuzzy and two quick finds. :)

**Comment by davydog187** [comment]
Got it, agreed!

**Comment by eksperimental** [comment]
Interestingly the new Erlangs docs use the same for opening up the Search modal.

**Comment by josevalim** [comment]
I will close this for now. It is a change we would like to explore but we don't have the bandwidth to work on it. If someone wants to work on it, let us know! Thank you!

**Comment by davydog187** [comment]
Thanks Jose, if I find time in the next few months I will try to take on
