### ISSUE TITLE
Dependency tracking?

### ISSUE THREAD

**Issue by alexrp** [elixir-lang/ex_doc#149]
It seems that ExDoc doesn't do any actual dependency tracking. Whenever I invoke `mix docs` it seems to always regenerate *all* of the documentation.

This is a bit inconvenient if you have an alias that's supposed to build everything, e.g. `make: ["deps.get", "deps.compile", "compile", "docs"]`, because that last `docs` step will always take a couple of seconds even if it doesn't need to do anything.

Would it be possible for ExDoc to check generated documentation files for staleness against the stuff in `_build`?

**Comment by whatyouhide** [comment]
@alexrp @ericmj does this still need to be open? Just trying to help cleaning out "dead" issues :smile:.

**Comment by ericmj** [comment]
This can be closed. If someone wants to do the work for checking if docs rebuild is necessary a PR would be appreciated. It is definitely not a priority for the core team at the moment.
