### ISSUE TITLE
Feature Request: Add `:short_title` to `:extras`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1492]
Sometimes I would like to use a shortened title in the side bar due to the limited space there.
For instance, I have this license file titled "Creative Commons Zero Universal version 1.0 license"
but on the side bar I would like to shot it "CC Zero"
and for the other files remove the "license" word since it is redundant.

![image](https://user-images.githubusercontent.com/9133420/149781377-c366cefe-4fd6-425d-bc50-96286d498c50.png)

So I propose to support `:short_title`

I can provide a PR

**Comment by josevalim** [comment]
Can't you keep the title permanently short and then immediately clarify its full context using a subheading in the page? 

I am not convinced there is a lot of need for this functionality and the issue here seem avoidable. :)

**Comment by eksperimental** [comment]
> and the issue here seem avoidable. :)

what do you mean?

**Comment by josevalim** [comment]
As I mentioned above: you can just give it a short title altogether. :)

**Comment by eksperimental** [comment]
> Can't you keep the title permanently short and then immediately clarify its full context using a subheading in the page?

In the particular case of the license no, I prefer to leave the license file as it is.

As we group items in the sidebar I think there is a need to edit the titles as they may become redundant, as in this case removing the word "license" as the groups is named like that.

Personally, I think since the sidebar is a little space with too much information, every little thing to unclutter it helps.
I don't think the titles of the documents should be determined by how many characters we have in the sidebar, or by which group they were placed under; it should be the other way around.

**Comment by cw789** [comment]
Isn't it covered by the `extras` `title` customization?:

```
extras: [
   {"LICENSE", [title: "My short title"]}
],
```

**Comment by eksperimental** [comment]
> Isn't it covered by the `extras` `title` customization?:

that is the title that will show at the top of the page.

the config the the screenshot above is the following:

```elixir
extras: [
  "LICENSES/LICENSE.CC0-1.0.txt": [
    filename: "license_CC0-1.0",
    title: "Creative Commons Zero Universal version 1.0 license"
  ],
  ...
],
groups_for_extras: [
  "Licenses": ~r{LICENSES/}
],

```

**Comment by josevalim** [comment]
Yes, just make the title a short one. You can call it License for example, and clarify the type of License inside the page. There are other options too, I don't think we  need a separate option for this. :)
