### ISSUE TITLE
Contrast of the sidebar is too harsh in normal mode

### ISSUE THREAD

**Issue by nicnilov** [elixir-lang/ex_doc#1495]
The sidebar styling, introduced, I believe, [by this commit](https://github.com/elixir-lang/ex_doc/commit/f860c527ae7ed254d5167c178d335facecf7005c), looks pretty in Night mode, but in normal mode it is quite unpleasant (subjectively, of course).

![image](https://user-images.githubusercontent.com/1060177/150427021-0b6e6259-d7e9-42d3-9c8a-194eb5bbfb05.png)

At a glance there is nothing wrong with this styling. Yet, since the sidebar is primarily used to find a needed entry, and that involves some peering, the subsequent switch to the bright content area becomes uncomfortable.

As not everyone prefers the dark mode, maybe it makes sense to support normal mode in the sidebar as well. Then, naturally, the Night mode should toggle the styling in sidebar and the content area together.

**Comment by josevalim** [comment]
If someone wants to explore a sidebar in night mode, we will be glad to consider it, but it is not in our current plans. Thank you!

**Comment by nicnilov** [comment]
Sorry for not making myself clear. The sidebar is already styled consistently with the night mode. The request is to match the sidebar styling to normal mode.

**Comment by josevalim** [comment]
Sorry, it was my bad. I understood it correctly but I wrote the wrong thing. :) yes, if someone wants to explore a sidebar for “day” mode, we will be glad to take a look at it.
