### ISSUE TITLE
Crash on package publish

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/ex_doc#1497]
version:  0.27.3

`mix hex.publish`
```
** (UndefinedFunctionError) function ExDoc.Config.default_formatter/0 is undefined or private
    (ex_doc 0.27.3) ExDoc.Config.default_formatter()
    (ex_doc 0.27.3) lib/mix/tasks/docs.ex:217: Mix.Tasks.Docs.get_formatters/1
    (ex_doc 0.27.3) lib/mix/tasks/docs.ex:208: Mix.Tasks.Docs.run/3
    (mix 1.13.2) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (hex 1.0.1) lib/mix/tasks/hex.publish.ex:231: Mix.Tasks.Hex.Publish.docs_task/0
    (hex 1.0.1) lib/mix/tasks/hex.publish.ex:190: Mix.Tasks.Hex.Publish.create/3
    (mix 1.13.2) lib/mix/task.ex:397: anonymous fn/3 in Mix.Task.run_task/3
    (mix 1.13.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

Edit:
It looks like it's a transient issue. After `mix deps.clean --all && mix deps.get` the publish succeeded. Probably elixir (1.13.2) is loading the wrong versions of some of the modules after update (I updated from 0.19 to 0.27.3) as there was a warning o compilation.
```
==> ex_doc
Compiling 26 files (.ex)
warning: redefining module Mix.Tasks.Docs (current version loaded from /Users/mylib/_build/dev/lib/ex_doc/ebin/Elixir.Mix.Tasks.Docs.beam)
  lib/mix/tasks/docs.ex:1
```

**Comment by josevalim** [comment]
The issue is that `mix docs` is invoked, then it calls `compile` which forces the deps to be recompiled. So at this point the old `docs` is in memory but the rest of the library is new. I have an idea for a fix.

**Comment by josevalim** [comment]
Ah, the fix is to use `@requirements ["compile"]` as it aims to solve exactly this. Pushing soon.
