### ISSUE TITLE
The classic color scheme as an option

### ISSUE THREAD

**Issue by sanks64** [elixir-lang/ex_doc#1498]
I noticed the recent design change and don't really like the colors used (they are too contrast for me)

Using [Stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) the color scheme is easily changeable. However, it requires having the extension installed

I already have CSS that brings back the old color scheme:
![image](https://user-images.githubusercontent.com/41530422/151220331-3032fff2-e9af-4e18-9b11-df733505ab8d.png)

Ideally I'd want to have it as an option (disabled by default is okay) in the newly added settings menu:
![image](https://user-images.githubusercontent.com/41530422/151220202-1ca7d09e-1c61-4fbb-9fca-10601cc5227d.png)

What's the opinion on this? Would a PR implementing this be welcomed?

**Comment by josevalim** [comment]
We don’t plan to bring the old style back for now. Some prefer the old, others prefer the new. At the same time, we can’t bear the complexity of maintaining two styles, especially as our goal is to support more languages (which may have smaller variations).

thanks for reaching out though!

**Comment by philosophy-is-poison** [comment]
Hello, could you please tell me the name of the color scheme that is used in https://hexdocs.pm/elixir/Kernel.html to highlight the code

**Comment by sanks64** [comment]
This issue is not the right place to ask, but it's Monokai

**Comment by philosophy-is-poison** [comment]
> This issue is not the right place to ask, but it's Monokai

Excuse me, please. You are absolutely right. That was awkward.
