### ISSUE TITLE
Erlang: Incorrect @type macro link

### ISSUE THREAD

**Issue by weiss** [elixir-lang/ex_doc#1500]
I'm using ExDoc for documenting Erlang code (thank you!).  When referencing a `{@type foo()}`, the generated link points to the non-existent target `#type-foo`.  The type definition is available via `#t:foo/0` instead.  (Not sure `{@type foo()}` macros are supposed to be supported?  But this does work with EDoc.)

**Comment by wojtekmach** [comment]
Thank you for the report.

> (Not sure `{@type foo()}` macros are supposed to be supported? But this does work with EDoc.)

Yes, they are supported. When ExDoc generates links, it'd use the `#type-foo` when linking against erlang.org/doc/man/* as that's the "EDoc-style" and `#t:foo/0` everywhere else, the "ExDoc-style". So it seems that ExDoc got confused when trying to generate links for your own types.

What's the ExDoc version you're running? Could you share your project or create a minimal one that reproduces the issue?

**Comment by weiss** [comment]
> What's the ExDoc version you're running?

ExDoc v0.28.0.

> Could you share your project or create a minimal one that reproduces the issue?

I stumbled over the issue [in eturnal][1], but I've now put together a minimal example of [the type macro][2] and the [resulting documentation][3].

[1]: https://github.com/processone/eturnal/blob/1.8.1/src/eturnal_module.erl#L38
[2]: https://github.com/weiss/example/blob/34a23fb1ef482f4d782973336e7d8bece0a121f4/src/example_app.erl#L1
[3]: https://eturnal.net/tmp/example/example_app.html

**Comment by wojtekmach** [comment]
Thank you, I can reproduce this locally and it's definitely a bug. Stay tuned!

**Comment by wojtekmach** [comment]
Okay, I know what this is.

On `{@type foo()}`, EDoc essentially writes the following to the doc chunk:

```html
<code><a href="#type-t">t()</a></code>
```

but on `{@link foo()}`, we have:

```html
<a href="#type1/0" rel="https://erlang.org/doc/link/seetype"><code>type1()</code></a>
```

we vastly prefer the latter as it's more precise given we can check against `rel="https://erlang.org/doc/link/*` and we do that for other things like references to modules, functions & callbacks.

So TL;DR, use `{@link foo()}`.

We _could_ support `@type` too but maybe given we have `@link` too, maybe it should be deprecated in EDoc instead?

**Comment by weiss** [comment]
> use `{@link foo()}`.

Works for me, except that only _exported_ types can be referenced that way.  But I guess that might be fine, as documenting local types usually makes no sense anyway.  Oh and e.g. `{@link atom()}` yields an `undefined or private` warning as well, whereas `{@type atom()}` seems happy, produces no link, but proper `<code>` markup.  But so does `` `atom()' ``.

> maybe given we have @link too, maybe @type should be deprecated in EDoc instead?

Yeah, actually I remember wondering about the difference back when I learnt about EDoc syntax.  I guess you could argue that `{@type foo}` is more readable in the source code, but that aside, I don't really see the point either.

Anyway, many thanks for looking into this!  As far as I'm concerned, the issue can be closed.

**Comment by wojtekmach** [comment]
Thanks @weiss!

If anyone would like to follow up with the OTP team regarding EDoc deprecating `{@type}`, that'd be appreciated!

**Comment by wojtekmach** [comment]
> Oh and e.g. {@link atom()} yields an undefined or private warning as well

I believe OTP 24.2 documents built-in types on the Erlang module, e.g. https://www.erlang.org/doc/man/erlang.html#type-atom, and it is supposed to "just work" with ExDoc. :)

**Comment by weiss** [comment]
> I believe OTP 24.2 documents built-in types on the Erlang module, e.g. https://www.erlang.org/doc/man/erlang.html#type-atom, and it is supposed to "just work" with ExDoc. :)

Hmm, doesn't seem to work here with OTP 24.2 (I pushed an [exampe][1]):

```
warning: documentation references type "atom()" but it is undefined or private
  src/example_app.erl:4: example_app
```

See <https://eturnal.net/tmp/example/example_app.html> for the result.

[1]: https://github.com/weiss/example/commit/be7bd572c4a24c9f866779642a987683e941b71e
