### ISSUE TITLE
Include page titles in the search autocomplete

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1518]

**Comment by ByeongUkChoi** [comment]
Isn't the page title already included in the search autocomplete?

**Comment by josevalim** [comment]
They appear on search but not in the autocomplete afaik?

**Comment by ByeongUkChoi** [comment]
Sorry, I didn't understand. Aren't those the titles of the page shown in the screenshot?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/43606066/159145471-0efe9124-e9d6-4b67-ae5a-2561cdcfe47a.png">

**Comment by josevalim** [comment]
Oh, by "pages" I mean the "Extras" / "Guides" / etc. You can customize how they are called, so in Ecto's case, it is "Guides". For example, I can't autocomplete for "Getting Started" in Ecto: https://hexdocs.pm/ecto/getting-started.html

And i think both the "Pages" title and the subtitles for each section are already available, we just don't autocomplete them.
