### ISSUE TITLE
Admonition block dark mode bug

### ISSUE THREAD

**Issue by davydog187** [elixir-lang/ex_doc#1519]
![image](https://user-images.githubusercontent.com/1019721/154863281-73140091-f7a8-4c82-9a31-fe2269d6c145.png)

Adding this from my phone but looks like the highlight on text in the blocks needs adjustment

**Comment by josevalim** [comment]
@davydog187 it is the new spoiler tag! 😅

**Comment by josevalim** [comment]
I have pushed a fix but I have asked the designer to see if a dark mode variation of the blocks make sense. /cc @milmazz

**Comment by milmazz** [comment]
@josevalim Thanks for taking care of this. Once you have the feedback from the designer, please let me know. Then, I can apply the changes to the dark theme.

**Comment by sorentwo** [comment]
<img width="868" alt="Screen Shot 2022-02-22 at 3 58 37 PM" src="https://user-images.githubusercontent.com/270831/155226583-cdda263a-7efd-4913-8cc7-719acf6bb08d.png">

Here's another example with the admonition in dark mode. Aside from it being _really_ bright, the link (at the end) lacks contrast.

**Comment by josevalim** [comment]
I fixed links (sorry, I saw your edit just now). I have already asked the designer, I will open up a new issue once I have the new mockups. :)
