### ISSUE TITLE
Hiding and showing the sidebar scrolls to weird position in narrow browser window

### ISSUE THREAD

**Issue by simonmcconnell** [elixir-lang/ex_doc#1520]
I often have docs open on half my screen.  When the browser window is narrow and you hide/show the sidebar, it scrolls to somewhere on the page.  If you've got the sidebar open, click a function and hide the sidebar, all good.  But if you show it again, you're scrolled to a "random" position.  If you hide it again, you'll go back to that function.

When you show the sidebar, you should not be scrolled to anywhere other than where you already are.

When you click a function, then scroll, then hide the sidebar, you should not be taken to the last function you clicked on.  Your current view position should not be changed.

This is looking at Elixir 1.13.3 docs.  Tested on Firefox and Edge.

**Comment by josevalim** [comment]
I am actually not sure if we can address this. The sidebar reduces the size of the readable area. The only option would be to allow the sidebar to overlap the content, like it does on small screens, but I actually think it would be worse.

**Comment by simonmcconnell** [comment]
Hmmm, there must be something we can do.  I'll poke around the internet, see what I can find.

**Comment by josevalim** [comment]
@simonmcconnell any news? :)

**Comment by simonmcconnell** [comment]
@josevalim I've had a couple of looks but haven't tried any of the options yet. I'm not going to have much free time for a number of weeks so you can close and I'll come back to it when I'm more available.

**Comment by josevalim** [comment]
Closing this for now but if you can crack the code, I would love to see a PR. I tried but failed :) Thanks!

**Comment by cw789** [comment]
Hey guys. First of all this wont be achievable without JS. 

The nearest ("best") solution I could imagine.
We could scroll to the first section heading in view. Would do you think?

```
# fire on the start of the sidebar event
const scroll_position = document.documentElement.scrollTop;
const sections = document.getElementsByClassName("section-heading"); 
for (let section of sections) {
  if (section.offsetTop >= scroll_position) {
    target_section = section;
    break;
  }
}

# fire on the end of the sidebar event
target_section.scrollIntoView(true);
```

Probably also doing a `document.body.scrollHeight`  on the start and end the event and do a no op if it hasn't changed.
So it only will affect the narrow browser window.

Opinions? Is this behavior at all better and worth it?

---

In a perfect world we do the same before and after a window resize event.
But I think it's not achievable to get the state before.
But this is also not part of the described problem.

**Comment by cw789** [comment]
The over solution would be to change the sidebar behavior.
Make it slide in only if the page width allows it (extra space given).
Else always make it an overlay, how it currently is done on mobile (real narrow screens).

**Comment by simonmcconnell** [comment]
That's all I could think of but wasn't sure if it would be a much better UX. I think treating it like the mobile menu would be better but @josevalim doesn't seem convinced.

**Comment by cw789** [comment]
I'm also not really convinced. I'll keep an eye open for a future good solutions.
