### ISSUE TITLE
Admonition block for dark mode

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1522]
![image](https://user-images.githubusercontent.com/9582/155383396-ab4c4358-b3c7-4eaa-a4d2-97234ff2af62.png)

/cc @sorentwo @davydog187 @milmazz

**Comment by davydog187** [comment]
@josevalim is there any highlighted text blocks in there, e.g. `v1.7`. Seems like that needs a background color?

**Comment by milmazz** [comment]
@josevalim Are we adding support for a new class? Currently, we have `warning`, `error`, `info`, and `neutral`, and here I see five callouts.

I'm assuming the following:

* red = `error`
* blue = `info`
* gray? (the last one in your screenshot) = `neutral`
* brown = `warning`

What's the purpose of the green one?

**Comment by josevalim** [comment]
@milmazz we do not need to add the green one. If you want to add it, we can open up a separate issue later. :)

**Comment by josevalim** [comment]
@milmazz I also know we used different icons, so just pick the colors. :)

**Comment by josevalim** [comment]
@davydog187 the code/link colors we use today (fixed from your reports) should work for those new colors too.

**Comment by milmazz** [comment]
@davydog187 Please let me know if you want to tackle this issue. If not, I can do it.

**Comment by sorentwo** [comment]
Those look much better! The green one seems handy, too.

**Comment by milmazz** [comment]
![Screen Shot 2022-02-23 at 13 08 55](https://user-images.githubusercontent.com/34700/155390138-d4d831f0-b80f-4679-9d11-f192f5574883.png)

Do you see a difference? I'm using the _Digital Color Meter_ included in macOS to guess the hex color values

**Comment by davydog187** [comment]
Seems like you've got it handled @milmazz and it looks great!
