### ISSUE TITLE
night-mode The blockquote has a wrong contrast for the code tag.

### ISSUE THREAD

**Issue by paridin** [elixir-lang/ex_doc#1533]
Currently 
![Screen Shot 2022-03-11 at 13 09 10](https://user-images.githubusercontent.com/5170054/157947047-7e89b052-6a77-4ba2-9087-343b27c72fa4.png)

Proposed
![Screen Shot 2022-03-11 at 13 38 31](https://user-images.githubusercontent.com/5170054/157947112-5299c27f-331e-4ed4-bd42-a737bfc1b139.png)

The proposal is based on the current color to keep the same theme feeling.

![image](https://user-images.githubusercontent.com/5170054/157948982-5e693e7f-56e0-4727-96f8-15158601a4fe.png)

If it looks good, I will do the PR.

**Comment by josevalim** [comment]
It has been fixed in master already. :) thanks for offering tho!

**Comment by paridin** [comment]
I tried master before the issue. I'm seeing this.

![image](https://user-images.githubusercontent.com/5170054/157951320-9907ca7b-22f6-4f9e-baff-571038168e20.png)

**Comment by josevalim** [comment]
Oh, so I misunderstood it by something else. Reopening. PRs welcome!
