### ISSUE TITLE
[Docs] References the API Reference page

### ISSUE THREAD

**Issue by yordis** [elixir-lang/ex_doc#1535]
What is the best way to point to the “API Reference” page from the docs?

I am trying to follow [Diátaxis Framework ](https://diataxis.fr/) and I can't find a way that I could link to it from my `README.md`, example:

```md
## Documentation

- [How-to Guides](./docs/how-to-guides/README.md)
- [References](...... what do I put here .....)
- [Explanations](./docs/explanations/README.md)
```

I ended up using `[References](api-reference.html)` but I am not sure if I should be doing this or if there is an alternative I should be following.

**Comment by josevalim** [comment]
What you used is correct.

**Comment by yordis** [comment]
Hey, @josevalim, is there any reason we couldn't support a relative path to a file? Primarily so GitHub links aren't broken.

**Comment by josevalim** [comment]
Can you expand what you mean and what you tried? I am almost sure we support relative paths as we use it in Elixir docs.

**Comment by yordis** [comment]
WHAT IN THE WORLD! 🤦🏻 sorry ....
