### ISSUE TITLE
weird look in exdoc

### ISSUE THREAD

**Issue by dustinfarris** [elixir-lang/ex_doc#1538]
i'm not sure when this changed, but exdoc nav feels off recently
<img width="313" alt="Screen Shot 2022-03-23 at 6 36 54 AM" src="https://user-images.githubusercontent.com/1087165/159712341-c30874c7-3869-4c46-af42-d88893126357.png">

**Comment by josevalim** [comment]
Can you expand on what feels off?

**Comment by dustinfarris** [comment]
> Can you expand on what feels off?

yes, sorry, the drop shadow is having an odd effect on my scroll bar

**Comment by josevalim** [comment]
I see! Can you please include OS and browser version then?

And please take a look if it still happens on the latest version, released today. If it does, a pull request is welcome. :) You can see the ExDoc version for Phoenix.LiveView by scrolling to the bottom of the page.

**Comment by josevalim** [comment]
Let me know how it goes. If this is still an issue, please post the versions, browser and stuff, and I will gladly reopen. Thanks!
