### ISSUE TITLE
Unable to build Elixir Docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1539]
Running both up-to-date branches Elixir and ExDoc.

```console
---
==> eex (compile)
==> mix (compile)
Generated mix app
==> ex_unit (compile)
Generated ex_unit app
==> logger (compile)
Generated logger app
Generated eex app
==> iex (compile)
Generated iex app
==> ex_doc (elixir)
CANONICAL=main/ bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.14.0-dev" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "beb6b4737b2ce07bce0e8798caa5ce51cae2dd19"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/main/" --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"

11:37:53.644 [notice] Application makeup_erlang exited: :stopped

11:37:53.655 [notice] Application makeup_elixir exited: :stopped

11:37:53.656 [notice] Application makeup exited: :stopped

11:37:53.656 [notice] Application nimble_parsec exited: :stopped

11:37:53.656 [notice] Application earmark_parser exited: :stopped

11:37:53.656 [notice] Application crypto exited: :stopped

11:37:53.656 [notice] Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:makeup_html, {'no such file or directory', 'makeup_html.app'}}}
    (ex_doc 0.28.3) lib/ex_doc/cli.ex:8: ExDoc.CLI.main/2
    (elixir 1.14.0-dev) lib/code.ex:1228: Code.require_file/2
```

**Comment by eksperimental** [comment]
It works now. Thank you.

Question: How come CI was passing on Elixir?

**Comment by eksperimental** [comment]
I see building docs is part of the release.yml, but not part of the CI.yml.
I wonder whether we should test the building of Elixir Docs, with the master version of ExDoc.
With the introduction of the `--warnings-as-errors` flags in ExDoc we could guarantee that the Elixir Docs are generating no warnings.

**Comment by josevalim** [comment]
@eksperimental I like that. Can you please submit a PR?

**Comment by eksperimental** [comment]
@josevalim Should we wait until #1412  is merged?
I found a way to exit with an error in Linux, so it could still be done I guess.

**Comment by josevalim** [comment]
We can do without #1412 and add the flag later. :) Catching a broken docs build will already be good enough.

**Comment by eksperimental** [comment]
So no warning catching for now.
I will submit a PR.

**Comment by eksperimental** [comment]
@josevalim Would it be possible to have a new release that includes this change? I am working to make Elixir build docs automatically based on the latest stable version of ExDoc for building docs (and testing the latest release of ExDoc at the same time) and it is not working because of this bug.

**Comment by josevalim** [comment]
I would rather prefer to have Elixir run against master, so we catch bugs earlier. No?

**Comment by eksperimental** [comment]
Another thing that we may consider is to add to the CI of ExDoc a test for bulding Elixir documentation

**Comment by eksperimental** [comment]
> I would rather prefer to have Elixir run against master, so we catch bugs earlier. No?

I answered above partially this (as I was writing the previous message your comment popped in)

I think we can:
- [ ExDoc CI ] Build Elixir docs from
- [Elixir Release Github Action] Build Elixir docs for Elixir releases using the latest stable release of ExDoc and this is chosen automatically.
-  [Elixir CI Github Action]  Build Elixir Docs with either ExDoc master or latest stable.

**Comment by josevalim** [comment]
I retaged v0.28.3 to include the update bin, so we should be good now!
