### ISSUE TITLE
Incorrect documentation for callback implementation

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/ex_doc#1544]
### Environment

```elixir
$ elixir --version
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)
```
```elixir
$ cat /etc/os-release 
NAME="KDE neon"
VERSION="5.24"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.24"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### Keep documentation metadata in callback

This was fixed only for `iex`, but not for `ex_doc` yet, see:  elixir-lang/elixir#11219

### Setting `@impl` attribute removes documentation

See: elixir-lang/elixir#11741

### Different default callback documentation in `ex_doc` and `iex`

Not sure if `ex_doc` here is just not updated (see documentation metadata section) or it's intended. I think it's more consistent to keep same messages, so at this point it's up to maintainers …

**Comment by josevalim** [comment]
Closing as the behavior is intentional ler the Elixir issue. :)

**Comment by Exadra37** [comment]
Hi Jose, you slipped a Portuguese word on your sentence `ler`.

**Comment by josevalim** [comment]
Fixed, thanks
