### ISSUE TITLE
Using @impl true masks the spec of the implemented @callback

### ISSUE THREAD

**Issue by fireproofsocks** [elixir-lang/ex_doc#1545]
When generating documentation using ExDoc, if I have defined a `@callback` and I have a function that implements that callback and is flagged via `@impl true`, my expectation is that the generated docs will list the `@spec` as it was defined in the original `@callback`.  However, the actual behavior is that no `@spec` is included with the generated documentation.  The only way I've found to get a `@spec` to appear in the generated docs is to manually include it along with the function implementation, e.g.

```
# In module A
@callback my_fun(thing :: atom()) :: integer()
```

```
# In module B
@behaviour B

@doc "My function"
@impl true
@spec my_fun(thing :: atom()) :: integer()  # <--- copied
def my_fun(thing) do
    # ...
end
```

However, this does not feel DRY because the `@spec` details are essentially copied verbatim from the `@callback` that is being implemented.

Elixir 1.13.0
ex_doc: 0.28.3

**Comment by josevalim** [comment]
The issue is that the spec from the behaviour may use types that are exclusive to that module. So we can't simply copy the types. We would need to copy and rewrite any local reference. If someone is interested in tackling this, we would accept a PR, but it is not something we have in our roadmap at the moment. Thank you! :)

**Comment by wojtekmach** [comment]
I believe it is particularly problematic with something like:

```elixir
defmodule Behaviour do
  @typep private() :: any()

  @callback foo() :: private()
end

```

The spec we'd automatically get is `@spec foo() :: Behaviour.private()` and I'm not sure if it is allowed to reference private types from outside. I think at the very least ExDoc would warn.
