### ISSUE TITLE
Proposal: docset formatter

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#1548]
There are many ways to consume ex_doc generated documentation. One very popular one for mac users is using [dash](https://kapeli.com/dash). Dash does have a built in (but proprietary) integration with hexdocs to pull in (and keep up to date) the documentation for any library published on hex. There's also a windows and linux alternative in [zeal](https://zealdocs.org/), which can also consume the same docset format, but doesn't include the integration with hex, so it does not provide documentation for libraries out of the box.

There are existing (and not very well maintained) elixir packages to create docsets for elixir packages, but I think it would be simpler to have an ex_doc formatter instead of either using the generated html and parsing information out of the html again or integrating with private api of ex_doc from an outside tool. In a way this would work similar to the epub formatter. It would also be interesting to see how this could later hold the potential for integration with hex/hexdocs.

What I'm not so sure about is the fact that docsets (besides the html pages) work with a sqlite database and adding sqlite capabilities to ex_doc does feel like quite a heavy dependency.

docset specification/documentation: https://kapeli.com/docsets#dashDocset

If this would be an intersting addition I'd be open to contributing the proposed docset formatter, but I wanted to check in about the sqlite dependency before moving ahead with an implementation.

**Comment by josevalim** [comment]
Unfortunately that would be a big dependency to add to the project. My suggestion is to build it on top of ex_doc Via a custom formatter And let us know of any API You may require.

Thanks for reaching out!

**Comment by LostKobrakai** [comment]
I've a working, but not complete, WIP for building a docset based on just the html files created by ex_doc:

https://github.com/LostKobrakai/doc_supply/blob/d8a49bfbe993659f7f1d508365b889da29d4c291/lib/doc_supply.ex#L12

There's a few potentially brittle parts with building directly on the html output:

* The sqlite db indexing the documentation needs to know a mapping from "type of content to index" to url (file path + hash fragment)  
  * This can probably be inferred from the config an ex_doc formatter receives from ex_doc, haven't tried that yet
  * It can also be parsed from the html files, but depends on classes or structure to stay consistent
    * Requires a bit of a heuristic of what's module documentation vs extras
* The table of contents are based on custom links within the documentation
  * Can be patched into the html files
* Show only "main" part of documentation without the "shell" (sidebar/footer/…)
  * Hiding the sidebar by setting all media queries to 1px (this also means no search/version switcher/…)
  * Disabling night mode by patching css class
  * Hide things like footer/…

Currently `ExDoc.Formatter.HTML` is non public API, so from an outside to ex_doc package I can't really customize how it's building the documentation. It would be interesting to have the (public) option to: 
* generate documentation without "shell" directly (possibly without things like js based search)
* receive a mapping of "relevant documentation pieces" to their urls
* pass in custom markup for the table of contents
  * Maybe this is can replace the summary part in the docs, which is kinda redundant within the app

**Comment by LostKobrakai** [comment]
Got the actual ex_doc formatter started as well: https://github.com/LostKobrakai/ex_doc_docset
