### ISSUE TITLE
Support <br> in markdown tables

### ISSUE THREAD

**Issue by anthonator** [elixir-lang/ex_doc#1549]
A common way to handle line breaks in markdown tables is using the `<br>` tag. Right now, `ex_doc` renders `<br>` as a literal string rather than HTML.

**Markdown**
```
| Field                           | Validations        | Constraints |
| ---                             | ---                | ---         |
| `:accepted_privacy_policy_at`   | required           |             |
| `:accepted_terms_of_service_at` | required           |             |
| `:email`                        | required<br>format | unique      |
| `:first_name`                   | required           |             |
| `:last_name`                    | required           |             |
```

**GitHub rendering**
| Field                           | Validations        | Constraints |
| ---                             | ---                | ---         |
| `:accepted_privacy_policy_at`   | required           |             |
| `:accepted_terms_of_service_at` | required           |             |
| `:email`                        | required<br>format | unique      |
| `:first_name`                   | required           |             |
| `:last_name`                    | required           |             |

**ex_doc rendering**
<img width="568" alt="Screen Shot 2022-04-09 at 1 14 05 PM" src="https://user-images.githubusercontent.com/420061/162584576-1fb3eb1c-0996-4353-9d4d-4ae429a87202.png">

**Comment by josevalim** [comment]
Please File an issue on the earmark project. Although it’s probably a won’t fix,  Since earmark accepts HTML only at very specific locations.
