### ISSUE TITLE
ExDoc could potentially wipe out any directory

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1555]
While working on improving the `make docs`  command in Elixir, I accidentally discovered this bug that deleted my entire Elixir repo locally loosing all local branches. I don't know if there could be any implication of anybody running ExDoc, but it could potentially wipe out the entire disk in a remote or a local user machine.

When `--output`  is provided to the ex_doc command, and it is empty, it will deleted  `--output ""` `--output ~` will wipe out your home dir.
My case was that `--output` was set to `"${VAR}"`  and `VAR` didn't get set properly and was evaluated to an empty string, so the project root directory was gone.

Additionally, I think we should review the use of File.rm_rf! across the project.
https://github.com/elixir-lang/ex_doc/search?q=File.rm_rf%21

These are the lines causing such behaviour.
https://github.com/elixir-lang/ex_doc/blob/6ba40a7383f87727c49c1fc51ddd5cf192ef3e7a/lib/ex_doc/formatter/html.ex#L159-L160

This removing of the output directory is intended to clean out old documentation copies. If a .build file in found, only files listed in .build are removed.

**Comment by Eiji7** [comment]
Securing an empty string should be simple, but the general problem is that we can erase any directory that wasn't created for generating an `Elixir` application documentation. How about a simple check for existence of empty file called `.ex_doc` within `output` directory?

**Note**: Creating of said file would need to be done immediately after `mkdir` call, so in case of any bug the code would know if said `output` directory can be erased.
