### ISSUE TITLE
[Feature] Add diff highlighting

### ISSUE THREAD

**Issue by yordis** [elixir-lang/ex_doc#1558]
### Proposal

Add support for `diff` highlighting

Example:

```diff
+ Adding
- Removing
```

#### Notes

Related to https://github.com/elixir-makeup/makeup_diff from https://twitter.com/sorentwo/status/1516873187358879746

**Comment by josevalim** [comment]
It should just work if you add that package as a deep in your project.

**Comment by josevalim** [comment]
I have updated the README to mention that how can add them as a dep and it just works.
