### ISSUE TITLE
Search should prioritise exact module name match

### ISSUE THREAD

**Issue by Nicd** [elixir-lang/ex_doc#1563]
When you search for a module and don't click on the autosuggestion but go to the search page instead, the module is not the first result but down the list somewhere. Example: https://hexdocs.pm/elixir/search.html?q=String

Earlier, the String module used to be at the top IIRC, but now it's way down somewhere, even though it's an exact match to the search string. I think such a module should be prioritised to the top of the list.

**Comment by josevalim** [comment]
> Earlier, the String module used to be at the top IIRC, but now it's way down somewhere, even though it's an exact match to the search string.

Are you sure? I went back to earlier Elixir versions on hexdocs and I could not reproduce this behaviour. I see what you are mean about going to the exact match but doing so also makes it a bit inconsistent. Today the search option is always first.

**Comment by Nicd** [comment]
In Elixir 1.8.0 docs String comes first: https://hexdocs.pm/elixir/1.8.0/search.html?q=String -- But maybe it's a lucky accident.

What do you mean by "search option"? I would expect "String" to be the best match for my search string "String".

**Comment by josevalim** [comment]
Oh, sorry. I got confused. You are literally talking about the search result and I was thinking about the autocomplete. I agree with you.
