### ISSUE TITLE
Text in @deprecated is not processed using Markdown

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/ex_doc#1566]
The summary is in the title
```elixir
@deprecated "*DON'T USE IT PLEASE*"
def test, do: :ok
```
![зображення](https://user-images.githubusercontent.com/588762/166565547-afa2a7d5-e4e5-4dee-aab9-1f985b577d92.png)

**Comment by josevalim** [comment]
Correct. This text is also show in terminal by the Elixir compiler and so on. So Markdown is not expected.

**Comment by fuelen** [comment]
@josevalim but wouldn't it be better if Markdown is expected? Could you please elaborate why showing this text in terminal by the Elixir compiler is an issue? I thought this is already present in Elixir  :thinking: 

Typically, I write `
```
Use `MyModule.my_func/2` instead
```
and it would be great if link to function is recognized automatically.

**Comment by josevalim** [comment]
You should think of the deprecation message as an error message. Elixir standard library won't format markdown in error messages, for example, as it shows those error messages in editors, CLI, etc.
