### ISSUE TITLE
Tex/LaTeX Support

### ISSUE THREAD

**Issue by hunterboerner** [elixir-lang/ex_doc#1570]
TeX or LaTeX support would be greatly helpful when reading the Nx documentation. For example, there is unrendered LaTeX on this page https://hexdocs.pm/nx/intro-to-nx.html#broadcasts. I've used [KaTeX](https://github.com/KaTeX/KaTeX) before and it's worked very well. I have time to implement this if you could give some guidance for where to start.

**Comment by josevalim** [comment]
Good find! We do support katex rendering (check the README) but the Nx project was mis-configured. I have fixed that and republished the docs!
