### ISSUE TITLE
Warn on missing column when linking to types and callbacks to Erlang docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1573]
I am missing a `:`

    [Text](`t:supervisor.child_spec()`)

the correct text should be 

    [Text](`t::supervisor.child_spec()`)

ExDoc should warn and suggest to use double colon for types and callbacks, if no module named `supervisor` is found locally, and one in Erlang is.

**Comment by josevalim** [comment]
This is the same as #1572. It is really invalid syntax. It parsers the first part to a variable, which we can warn on, as there is no valid reason to have backticks inside the link part.

**Comment by eksperimental** [comment]
As of now, the only way to link to Erlang modules in custom links is with backticks.
