### ISSUE TITLE
Error processing erlang source when function is called record

### ISSUE THREAD

**Issue by starbelly** [elixir-lang/ex_doc#1575]
An issue was reported on rebar3_ex_doc (https://github.com/starbelly/rebar3_ex_doc/issues/26). Specifically if a function is called record and more specifically has an accompanying spec an edge is hit. I came up with a quick fix (as seen in the issue), but this is probably not a good approach (i.e., may cause other issues). 

We specifically hit here : https://github.com/elixir-lang/ex_doc/blob/935f2dac019d0bdcb470e68fc8b077e4e27bfe15/lib/ex_doc/language/erlang.ex#L463 but we should be hitting the catch all in the `cond` I believe. 

My quick fix was to adjust the this line to : 

` name in [:"::", :when, :%{}, :{}, :|, :->, :record] and acc != [] ->` 

Of course, I don't know this code that well atm, and the above is based on an assumption as to what's going on in the code, and assumptions are bad :)

**Comment by wojtekmach** [comment]
Please send a PR!
