### ISSUE TITLE
Mix tasks with flags are not linked

### ISSUE THREAD

**Issue by BartOtten** [elixir-lang/ex_doc#1582]
While writing the [README for Phoenix Localized Links](https://github.com/BartOtten/phoenix_localized_routes/blob/main/README.md) I noticed that ExDocs does not link to a Mix task when it includes a flag.

**Software versions**
* Elixir 1.13.3 (compiled with Erlang/OTP 24)
* ex_doc 0.28.4 (Hex package) (mix)

**Working**
Run `mix gettext.extract` links to https://hexdocs.pm/gettext/Mix.Tasks.Gettext.Extract.html

**Broken**
Run `mix gettext.extract --merge` does not link

**Expected**
Run `mix gettext.extract --merge` links to https://hexdocs.pm/gettext/Mix.Tasks.Gettext.Extract.html

**Comment by wojtekmach** [comment]
We would not autolink these either:

```markdown
`&Foo.bar/0`
`Foo.bar()`
```

and the idea is we try to keep things simple, not adding special cases. There is always an wscape hatch which is creating a custom link: `` [`mid foo --bar`](`mix foo`) ``.

Id personally be open to include these and your example but I know José wanted to keep it limited.

**Comment by josevalim** [comment]
As Wojtek said. :)
