### ISSUE TITLE
Wrong color for heading in admonition in dark mode

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/ex_doc#1585]
If using markdown headings (`#`) in an admonition, the heading color is white in dark mode, which isn't really readable.

<img width="856" alt="Screenshot 2022-07-19 at 13 05 32" src="https://user-images.githubusercontent.com/792046/179737188-4ae6dda0-6658-4d44-a97a-14b9d324aae9.png">

**Comment by josevalim** [comment]
Can you please give us a link? What is the ExDoc version? A PR is also welcome. :)

**Comment by josevalim** [comment]
https://github.com/phoenixframework/phoenix/pull/4889/files#r924399203
