### ISSUE TITLE
ex_doc extensions / library generated documentation

### ISSUE THREAD

**Issue by btkostner** [elixir-lang/ex_doc#1586]
## What

This is an idea to allow library modules to generate documentation in ex_doc. Ideally this would be used for documenting things that don't follow Elixir modules, have a better way to organize, and would be tedious to hand write, like http routes. I don't have an exact API (I think the community can collectively make a better one), but see the [Example](#Example) section for my thoughts.

## Why

I've been working on getting great documentation for some internal projects, and right now we are importing some markdown pages for things like load testing, deploying in kubernetes, and it all works great. We are also generating an openapi spec file and have a custom markdown file that's imported that loads a swagger script and rewrites some styles. This works _ok_ in most cases, but I think we could do better with a more native ex_doc way.

For reference, this is what it looks like with swagger

<img width="1677" alt="Screen Shot 2022-07-20 at 7 51 33 PM" src="https://user-images.githubusercontent.com/3385679/180112428-b97bcce4-9559-494e-92d1-8ae8c99715a7.png">

It would be nice if modules could also inject styles and scripts, but that might get too complicated and break compatibility if / when ex_doc gets another redesign.

## Example

```ex
docs: [
  build_modules: [
    MyPhoenixDocumentationPlug
  ]
]
```

The `MyPhoenixDocumentationPlug` could look something like:

```ex
def MyPhoenixDocumentationPlug do
  def build(docs) do
    # I have no clue what I'm doing.
    docs
    |> add_tab("Routes", fn pages ->
      pages
      |> add_page("/_health", __MODULE__, :write, [:health])
      |> add_page("/api/v1/endpoint", __MODULE__, :write, [:endpoint])
    end)
  end

  def write(:health) do
    """
    # /_health

    This outputs health check status
    """
  end

  def write(:endpoint) do
    """
    # /app/v1/endpoint

    Here is some _markdown_ for this page
    """
  end
end
```

And that would end up with a screenshot like so:

<img width="1677" alt="Screen Shot 2022-07-20 at 8 57 55 PM" src="https://user-images.githubusercontent.com/3385679/180120413-b803d297-2fe8-4aa2-a763-4f71d9330c99.png">

Obviously a list of all the routes in the sidebar is not great, but it's a start and can be improved on library by library. It might also be better to have more power in page placement (like under the pages tab) but 🤷 Like I said, there is probably a much better API that could be built.

**Comment by josevalim** [comment]
Hi @btkostner, this is something we want to tackle in the long term, we already have a limited support via formatters, but we are not ready yet because the internals are changing, especially as we add other languages. I think once things estabilizes and we release v1.0, we will be ready to tackle this. Thank you!
