### ISSUE TITLE
Search doesn't find `phx-update`

### ISSUE THREAD

**Issue by tcoopman** [elixir-lang/ex_doc#1588]
Searching for: `phx-update` on https://hexdocs.pm/phoenix_live_view results in no direct result. As you can see in the screenshot below, it first searches for `update` variations and then for `phx` but not for `phx-update`. The page I was looking for (found via google):
https://hexdocs.pm/phoenix_live_view/dom-patching.html is really far down.

Searching for: `"phx-update"` (with `"`) or `phxupdate` gives no results at all.

Seeing that the `phx-...` hooks are important, it would be great if they are searchable as well.

Screenshot of search for `phx-update`:
![image](https://user-images.githubusercontent.com/45546/184364204-5fd62a84-302d-4f77-951b-b4ee84da55e2.png)

**Comment by josevalim** [comment]
It may be we are not indexing `-`, changing it should address it. A PR is welcome.

**Comment by tcoopman** [comment]
I might give it a go, but I'm not familiar with the codebase and `lunr`. Reading through some of the issues though it should be working already in the current version of `lunr`. Anyway, I'll try to take a look at it next week.
