### ISSUE TITLE
Regression in search result highlighting

### ISSUE THREAD

**Issue by jaminthorns** [elixir-lang/ex_doc#1594]
I recently used a library that hasn't had a release in a while and has its documentation published with an older version of ExDoc (v0.19.1). I noticed that the old search functionality highlights the parts of a function name that match the search query. Since then, full text search has been added. In newer versions of ExDoc, the matches within documentation are highlighted, but the matches in the function name are no longer highlighted.

In my opinion, this is a regression in functionality. I think that highlighting matches in the function name is even more important since the introduction of full text search, since it can easily help you discern how each search result was matched to the user's query (function name, documentation, or both).

# Old

![Screen Shot 2022-08-24 at 3 53 32 PM](https://user-images.githubusercontent.com/6618434/186521924-9e079364-27e3-431e-b567-2693654f1384.png)

# New

![Screen Shot 2022-08-24 at 3 53 42 PM](https://user-images.githubusercontent.com/6618434/186522008-580f85c1-00d4-45d3-9d37-00bf6c10cafd.png)

**Comment by josevalim** [comment]
The change was intentional because the highlighting would make it harder to read the context.

my understanding is that search engines don’t highlight titles either, so we plan to keep it as is. Thanks!
