### ISSUE TITLE
Search does not escape "%" and raises InvalidSecurity error

### ISSUE THREAD

**Issue by lubien** [elixir-lang/ex_doc#1604]
This was originally pointed out on Elixir lang's #phoenix channel on Slack

https://user-images.githubusercontent.com/9121359/189359900-07e394b1-042d-4ad1-96b3-9eafb6e64a9a.mov

I could not find a similar issue and seems a very minor concern

Apparently as long as you write "%" it errors

**Comment by vinibrsl** [comment]
I could not reproduce this locally with `mix build`. I'm guessing this is related to hexdocs.pm's web server?
