### ISSUE TITLE
Static hosting of google fonts

### ISSUE THREAD

**Issue by cw789** [elixir-lang/ex_doc#1607]
ExDoc states:

- Generates HTML documentation accessible online and offline

Yes it is offline usable but not that pretty without the fonts.

The other thing about using google fonts is the GDPR topic in some European countries - if you host our ExDoc docs in those countries.
At least in Germany it is problematic - in Austria it's currently also a topic.

Are we open to add the fonts directly to the assets?
I could take care of it.

**Comment by josevalim** [comment]
Closing in favor of PR.
