### ISSUE TITLE
Pop-ups (previews) would ideally also use special formatting for code

### ISSUE THREAD

**Issue by bernardosulzbach** [elixir-lang/ex_doc#1639]
I think it would be better if we had code formatting in the pop-ups (previews) shown when hovering a link to a function.

See in the image below how "value" and "fun" are written as if they were just text, which of course we can still read, but is somewhat confusing when everywhere else code entities are written in a monospaced font with a special background.

![image](https://user-images.githubusercontent.com/8271090/209463753-40d87cef-6ea4-4c46-a97e-c73f0ac822fc.png)

**Comment by josevalim** [comment]
A PR is welcome!

**Comment by bernardosulzbach** [comment]
No, it's not about the header, where there can be no ambiguity about what those words are and there is no other text.

I've highlighted the original image to make it completely clear where _value_ and _fun_ look just like plain English words in a sentence. Ideally, those would look like the `some_fun` you can see in the background, for both consistency and ease of reading.

![image](https://user-images.githubusercontent.com/8271090/209989043-3c6fbeac-f184-48ee-8151-faf078026238.png)

Pinging @solar05 just in case.
