### ISSUE TITLE
Macro specs

### ISSUE THREAD

**Issue by ScrimpyCat** [elixir-lang/ex_doc#164]
I was wondering if macro specs were meant to be stripped from the generated documentation or not? Since I think specs for macros are still useful for documentation purposes. 

I'm specifically referring to https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/retriever.ex#L151
Since it's looking up the specs for the function with name and arity, however macro specs are prefixed with `MACRO-`, so any applied specs won't be added to the function node for a macro. 

Should I submit a PR? Or was this a design decision?

**Comment by bgianfo** [comment]
Can this be closed, as the PR has been merged and appears to fix the issue?

**Comment by josevalim** [comment]
Definitely, thanks!
