### ISSUE TITLE
Please Link to a Project's Source Repo From Somewhere

### ISSUE THREAD

**Issue by Miserlou** [elixir-lang/ex_doc#1648]
I face this annoyance multiple times a day.

I search for a project - I find the hosted hexdocs. I read the hexdocs. I want to read the source code. There is no link to the source code anywhere I can see. I have to leave the docs and go to a search engine to find "{projectname} github" or "{projectname} gitlab" until I find something. I then have to check if the project is the same as the one I was looking at before.

There's space in the bottom of the sidebar. Please, please, put a link to the project's source code down there.

**Comment by wojtekmach** [comment]
The link is in top-right corner, left of the gear icon:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/76071/212133900-46e93952-b3d3-4640-8afa-435962a831dd.png">

**Comment by Miserlou** [comment]
I didn't see that, but it still doesn't go where I want it to. That goes, for instance, to `https://github.com/owner/project/blob/v1.9.1/lib/project.ex#L1`. Why not the real source homepage?

**Comment by Munksgaard** [comment]
I also miss this functionality on a daily basis. I'm not sure where to ideally put it, but I'd also be happy with a keyboard shortcut or something that takes me to the source repo (not a particular page, just e.g. `https://github.com/owner/repo`).

**Comment by Munksgaard** [comment]
As a workaround, I asked codex to create me this tampermonkey script: https://gist.github.com/Munksgaard/bbfe9902eacadaf8d4a7c405df338356. It works, but I haven't reviewed the code carefully. Use at your own risk (or create your own).
