### ISSUE TITLE
No doc generated when @impl Application specified

### ISSUE THREAD

**Issue by RaymondLoranger** [elixir-lang/ex_doc#1656]
In the module for the top-level process, specifying ```@impl Application``` before ```def start(_start_type, _start_args) do``` somehow prevents any doc to be generated.

```
defmodule Identicon.TopSup do
  use Application

  alias __MODULE__
  alias Identicon.DirPath.Server

  # @impl Application
  @spec start(Application.start_type(), term) :: {:ok, pid}
  def start(_start_type, :ok = _start_args) do
    [
      # Child spec relying on `use GenServer`...
      {Server, :ok}
    ]
    |> Supervisor.start_link(name: TopSup, strategy: :one_for_one)
  end
end
```

**Comment by wojtekmach** [comment]
`@impl true` adds `@doc false` (unless you explicitly added `@doc` to that function), that's why the docs don't show up.

**Comment by princemaple** [comment]
Just ran into this. Hmmm didn't expect that. Would make sense if it lowers the priority of the function somehow.
