### ISSUE TITLE
Codeblocks that contain ? throws a warning

### ISSUE THREAD

**Issue by jared-mackey** [elixir-lang/ex_doc#1661]
Hi, I am getting this warning when generating a module doc with the following snippet in it. I think there's two issues here. 

1. `nofile` when there was indeed a file that it was in and no additional context. This made it pretty tricky to track down where it was coming from (just started generating docs for the project). 
2. Not being able to use `?` inside code blocks. Is this a bug or something by design?

Warning
```
warning: found ? followed by code point 0x20 (space), please use ?\s instead
  nofile:1:15
```

Snippet of docs
```md
    - `FOR UPDATE OF ? SKIP LOCKED` is used to ...
 ```

**Comment by wojtekmach** [comment]
It is definitely a bug. Thank you for the report.
