### ISSUE TITLE
Showing `:since` metadata for modules

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#1664]
Right now, `@typedoc since: "..."` and `@doc since: "..."` show up in the respective type and function documentation. However, `@moduledoc since: "..."` doesn't. I think we might want to support this?

**Comment by josevalim** [comment]
We don't have a place to put this information at the moment but perhaps we can find one.

**Comment by whatyouhide** [comment]
Closed by https://github.com/elixir-lang/ex_doc/pull/1680.
