### ISSUE TITLE
Search HexDocs appears even when a package is not specified

### ISSUE THREAD

**Issue by starbelly** [elixir-lang/ex_doc#1678]
This looks like because it's hardcoded in the js. It seems like we'd be able to conditional input some html and then sprinkle to some js on the element to facility the search modal. 

Thoughts?

**Comment by josevalim** [comment]
@starbelly what do you mean? Is it the "Search HexDocs" on the bottom of the page? It is meant to always appear. Even if you are running it locally, or for Elixir, you may want to go elsewhere to search for packages. We also have a keyboard shortcut and it would be weird if it only worked in some versions.

**Comment by starbelly** [comment]
@josevalim That makes sense, closing this.
