### ISSUE TITLE
Load `dist/html-3CAFJ3W7.js` script as deferred?

### ISSUE THREAD

**Issue by fercasgal** [elixir-lang/ex_doc#1688]
When opening the autogenerated HTML documentation there are many instances where the rendering of the side bar items fails due to the `html-3CAFJ3W7.js` not being able to find some element (in an example here, the "toast" element). The script is loaded from `readme.html` as `<script async src="dist/html-3CAFJ3W7.js"></script>`. Changing the `async` to `defer` fixes the problem for me.

**Comment by josevalim** [comment]
The toast issue has been fixed on main. We will ship a new release soon! :)

**Comment by josevalim** [comment]
Yeah, that's the toast issue.
