### ISSUE TITLE
Link to hexdocs.pm for references to dependencies' modules and functions

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#169]
1. Should the link be to the mix.lock version or the latest version (http://hexdocs.pm/plug/Plug.Conn.html vs http://hexdocs.pm/plug/0.8.4/Plug.Conn.html)?
2. Should we always assume that an Elixir dependency has published docs on hexdocs.pm or should we query first?

/cc @josevalim @tonini @chrismccord

**Comment by milmazz** [comment]
@josevalim Any advice on how to solve this issue?

**Comment by josevalim** [comment]
In master!
