### ISSUE TITLE
No formatting inside of details elements

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/ex_doc#1693]
[Example here](https://hexdocs.pm/gen_lsp/GenLSP.html#module-examples) (click disclosure to expand)

I haven’t looked into this yet so not sure whether this is a problem with ExDoc or markdown parsing.

**Comment by josevalim** [comment]
It is an Earmark limitation. It doesn't parse inside HTML. So if there is HTML, it assumes all rest is HTML.

**Comment by zachallaun** [comment]
Got it! Thanks for the quick explanation. Going to close this.
