### ISSUE TITLE
ExDocs prints errors on case insensitive filesystems in some cases

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/ex_doc#1712]
Reproduction is simple, be on macOS/Windows or run it on Linux with case-insensitive FS and include sentence:

```
Be sure that `foo` is in your `PATH`
```

And see the documentation generation errors with:

```
14:28:44.394 [error] Loading of /nix/store/ibbxg0rclvxnjbs81p0x8dn24vgxh1jw-elixir-1.14.4/lib/elixir/bin/../lib/elixir/ebin/Elixir.PATH.beam failed: :badfile


14:28:44.394 [error] beam/beam_load.c(180): Error loading module 'Elixir.PATH':
  module name in object code is 'Elixir.Path'
```

It still succeeds, but this is pretty confusing and may be scary to some people who do not understand what is going on. This is similar to elixir-lang/elixir#8780

**Comment by josevalim** [comment]
Yeah, maybe we can do some checks before trying to load the code (or use `:code.which` to find the beam instead of loading the code).

**Comment by wojtekmach** [comment]
And yes, we should have `` `PATH` vs [`Path`] `` so there's no ambiguity what was the intent. :)

**Comment by sabiwara** [comment]
Not sure if this is related, but it reminds me of https://github.com/elixir-lang/elixir/issues/12006.
