### ISSUE TITLE
on-hover anchor's are overlapped by admonition block icons

### ISSUE THREAD

**Issue by polvalente** [elixir-lang/ex_doc#1714]
![Screenshot 2023-05-31 at 8 22 29 AM](https://github.com/elixir-lang/ex_doc/assets/16843419/9e126de6-90a0-4d9b-8566-43ccbf71373d)

As seen in the image above, the H3 anchor is being shown in an overlap with the icon. It also seems to be on a lower z-level, which makes it difficult to click and get the link.

A possible work around would be to somehow provide a way to name anchors for a given admonition block directly, which was the reason I went for H3 instead of H4 in the first place

**Comment by josevalim** [comment]
Can you please check main? I am almost sure this is fixed. :)

**Comment by josevalim** [comment]
Ignore me, it has not. It happens if we use h3 for admonition. I think we should simply hide the anchor.

**Comment by DavidOliver** [comment]
Apologies if that was my doing. I'll take a look today.

**Comment by DavidOliver** [comment]
Ah, thanks. :)
