### ISSUE TITLE
Improve named typespec

### ISSUE THREAD

**Issue by yordis** [elixir-lang/ex_doc#1720]
I am unsure if this is even allowed. It is not failing so I assumed it is.

-----

I have the following module:

```elixir
defmodule Command do
  @type aggregate_identifier_opt ::
  key_name :: atom() # notice here
  | {key_name :: atom(), type :: atom()}
  | {key_name :: atom(), type :: module()}
```

Notice that I gave a name to the `atom()` as follow `key_name :: atom()`

Notice that it renders a bit weird, adding a jump line after the `key_name` instead of inlining the name and type:

![Screen Shot 2023-06-15 at 10 00 00 PM](https://github.com/elixir-lang/ex_doc/assets/4237280/2d0b898f-1f4d-4055-9e5d-9ad4152a237e)

**Comment by josevalim** [comment]
The format is correct. The fact it prints wrong indicates that the code you think you wrote is not how Elixir sees it. You want this:

```
  @type aggregate_identifier_opt ::
  (key_name :: atom()) # notice here
  | {key_name :: atom(), type :: atom()}
  | {key_name :: atom(), type :: module()}
```

In other words, `|` has higher precedence than `::`.

**Comment by yordis** [comment]
I see ... thank you so much!
