### ISSUE TITLE
Compilation warnings from `makeup_html` and `makeup_erlang`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [elixir-lang/ex_doc#1721]
`ex_doc` depends on `makeup_erlang` and `makeup_html`:

```
ex_doc
├── makeup_erlang ~> 0.1 (Hex package)
└── makeup_html >= 0.0.0 (Hex package)
```

Otoh, `makeup_html` also depends on `ex_doc` :):

```
makeup_html
├── ex_doc ~> 0.24 (Hex package)
```

---

When compiling `makeup_erlang` I get no compilation warnings.

When compiling `makeup_html` I get compilation warnings:

```
==> makeup_erlang
Compiling 3 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/makeup/lexers/erlang_lexer.ex:250: Makeup.Lexers.ErlangLexer

==> makeup_html
Compiling 5 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/makeup/lexers/html_lexer.ex:135: Makeup.Lexers.HTMLLexer
```

When compiling `ex_doc` I also get compilation warnings:

```
==> makeup_erlang
Compiling 3 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/makeup/lexers/erlang_lexer.ex:250: Makeup.Lexers.ErlangLexer

Generated makeup_erlang app
==> makeup_html
Compiling 5 files (.ex)
warning: Application.get_env/3 is discouraged in the module body, use Application.compile_env/3 instead
  lib/makeup/lexers/html_lexer.ex:135: Makeup.Lexers.HTMLLexer
```

I do `mix deps.update makeup_erlang` and `mix deps.update makeup_html` next to `ex_doc`, and even though this yields a change to `nimble_parsec`'s version, the compilation issues are still apparent.

I do similar next to `makeup_html`, `mix deps.update ex_doc`, and even though this yields changes to `mix.lock` it still doesn't solve the compilation issues.

I did a recent pull request to fix `makeup_html`'s compilation warning (https://github.com/elixir-makeup/makeup_html/pull/5).

---

I think to get `ex_doc` compilation error free, we need to:

* tag-release the latest `makeup_erlang` and `mix deps.update` it in `ex_doc`
* merge the `makeup_html` pull request
* tag-release the latest `makeup_html` and `mix deps.update` it in `ex_doc`
* tag-release `ex_doc`

(at this moment we should be able to `mix deps.update` `ex_doc` elsewhere to prevent compilation issues in other libraries)

I can pull request for all this, I might just need your help in tag-releasing stuff, if you're willing to go this route. Thanks.

**Comment by josevalim** [comment]
We don't need to release a new ex_doc, because if users do `mix deps.update`, they will get the latest versions of its deps. So nothing to be done here but PRs to remove the warnings from `makeup_*` are welcome. :)

**Comment by paulo-ferraz-oliveira** [comment]
> they will get the latest versions of its deps

This is interesting to know. I'm still learning the ins and outs of mix 😄 Thanks, @josevalim.

**Comment by josevalim** [comment]
makeup_erlang/makeup_html have to be released with fixes first. But it is entirely up to them, ExDoc doesn't play a role. :)

**Comment by paulo-ferraz-oliveira** [comment]
Understood, and as expected. Shall I request releases (no pressure, though), or do maintainers usually get around to those?

**Comment by josevalim** [comment]
Ping me once you patched both and I can do it. :)

**Comment by paulo-ferraz-oliveira** [comment]
`makeup_html` was already patched and merged.
`makeup_erlang` was not patched because it wasn't required, but it could do with a release :)

Thanks.

**Comment by josevalim** [comment]
makeup_erlang is out, i don't have permission for makeup_html, i will ask.
