### ISSUE TITLE
Code within admonition block is hard to read in dark mode

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/ex_doc#1726]
The background of code blocks within admonition blocks has a very light background in dark mode, which makes some of the code almost invisible:

<img width="848" alt="Screenshot 2023-07-02 at 22 25 13" src="https://github.com/elixir-lang/ex_doc/assets/11598866/76ac41e5-c454-4402-ac23-e6f2261b7016">

Example taken from [here](https://hexdocs.pm/elixir/1.15.0/Kernel.html#defoverridable/1).

**Comment by DavidOliver** [comment]
I'll take a look at this today.
