### ISSUE TITLE
Always provide uncompressed/original version of libraries, to facilitate debugging.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#173]
_I came across this issue trying to debug #172_
It's kind of hard to know what compressed into, specially when it's a customized version of the library, like in the case of highlight-js. So I think it's advisable to also have the uncompressed version. Same should go for JQuery.

Also, in the case of taylored versions, a comment explaining what options were included in would be greatly appreciated.

**Comment by whatyouhide** [comment]
The jQuery version at https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html/templates/js/jquery.js already has a version tag at the top of the file. As for highlight.js, I have no idea what version https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html/templates/js/highlight.pack.js is. If I get that, I'll be happy to send a quick PR for this!

**Comment by eksperimental** [comment]
hi @whatyouhide 
I had packed already a new version that supports a few more formats that will be common in elixir projects.
I will probably update this tomorrow as I will have some free time, and also submit an issue to hightlighthjs to include a comment at the top of the file and a link to license.

**Comment by eksperimental** [comment]
we can close this one, if it's all good with the new changes.
