### ISSUE TITLE
Error generating docs for Elixir 1.15.2

### ISSUE THREAD

**Issue by Kapeli** [elixir-lang/ex_doc#1730]
I'm trying to generate the docs for Elixir 1.15.2 using these commands:

```bash
git clone https://github.com/elixir-lang/elixir.git
cd elixir
git checkout tags/v1.15.2
make install

cd ..
git clone https://github.com/elixir-lang/ex_doc.git
cd ex_doc
../elixir/bin/mix do deps.get + compile
```

The last command gives this error:

```bash
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 4.3.1) :ets.lookup(Mix.State, :env)
    lib/mix/state.ex:31: Mix.State.get/2
    mix.exs:16: ExDoc.Mixfile.project/0
    lib/mix/project.ex:838: Mix.Project.get_project_config/1
    lib/mix/project.ex:141: Mix.Project.push/3
    (stdlib 4.3.1) lists.erl:1350: :lists.foldl/3
```

I've also tried to checkout tag [v0.29.4](https://github.com/elixir-lang/ex_doc/releases/tag/v0.29.4) of ex_doc, but I get the same error.

**Comment by whatyouhide** [comment]
Hey Bogdan! Ahah, I am just seeing this now and I reached out to you on Twitter like one hour ago 🙈 

Mh, I cannot reproduce this with:

```shell
# In the Elixir source directory
git checkout tags/v1.15.2
make clean compile

cd ../ex_doc
git pull
../elixir/bin/mix do deps.get + compile
```

What system are you on?

**Comment by Kapeli** [comment]
I'm on macOS 13.4.1, on a M1 Pro MacBook. I get the same error running these commands:

```bash
git clone https://github.com/elixir-lang/elixir.git
cd elixir
git checkout tags/v1.15.2
make clean compile

cd ..
git clone https://github.com/elixir-lang/ex_doc.git
cd ex_doc
git pull
../elixir/bin/mix do deps.get + compile
```

**Comment by josevalim** [comment]
@Kapeli the error is happening because you are using Mix from the Elixir repo but Mix is running against the Elixir on your system (not from your checkout). This should work instead:

    ../elixir/bin/elixir ../elixir/bin/mix do deps.get + compile

Where did you get your instructions from? They perhaps must be updated.

**Comment by Kapeli** [comment]
@josevalim Thanks, that works! I got the instructions from https://github.com/elixir-lang/elixir#building-documentation.
