### ISSUE TITLE
Elixir ExDocs Search index too big for SessionStorage

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ex_doc#1732]
When you visit the HexDocs page for an Elixir (or any large hex docs) such as https://hexdocs.pm/elixir/1.15.2/search.html?q=hi the console error log shows the following error:
```
html-JDI3AVDD.js:2 Failed to save index:  DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'index:Elixir v1.15.2' exceeded the quota.
    at Ui (https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:39805)
    at $i (https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:39572)
    at zi (https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:39047)
    at Ut (https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:38986)
    at https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:53681
    at at (https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:27572)
    at https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:53613
    at https://hexdocs.pm/elixir/1.15.2/dist/html-JDI3AVDD.js:2:53705
```
This is because the lunr index exceeds 5mb when we try and store it in the session here https://github.com/elixir-lang/ex_doc/blob/main/assets/js/search-page.js#L78

the page still works cause you can search the lunr index in memory, and every subsequent search forces a reload (and index rebuild) anyways. 

Not sure if this is a fix or ignore kinda bug but I figured I'd report it. :)

**Comment by josevalim** [comment]
I believe we started handling this case at some point, as otherwise it would crash. Perhaps we can partition or compress the lunr index somehow: https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API

**Comment by jeregrine** [comment]
Another one that is extremely broken is Scholar https://hexdocs.pm/scholar/search.html?q=hiu

I'm not 100% usre whats going on but the json it produces is 7mb gzippped and  a *mess*
![Screenshot 2023-07-07 at 11 41 36 AM](https://github.com/elixir-lang/ex_doc/assets/100886/a3317ce9-1eb3-42c8-a8ce-3663c21e0982)

**Comment by josevalim** [comment]
Scholar guides have large json/Vega-lite payloads. We should most likely do a pre-pass when generating the search documents and remove the vega-lite fences.

**Comment by jeregrine** [comment]
Would it make sense to pre-index the pages at compile time as part of the build instead of doing it in the browser?

**Comment by josevalim** [comment]
If you have ideas on how to do that without relying on lunr internals or on a JS runtime, let me know!
