### ISSUE TITLE
Error on Elixir 1.15.2/Erlang 26.0.2 Umbrella

### ISSUE THREAD

**Issue by Toady00** [elixir-lang/ex_doc#1733]
I have ex doc in the root mix.exs file, and I've upgraded to 0.30.1. I'm getting an error that the makeup application isn't available when trying to run `mix docs`:

```bash
$ mix docs

15:25:41.640 [notice] Application makeup exited: exited in: Makeup.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Makeup.Application.start/2 is undefined (module Makeup.Application is not available)
            (makeup 1.1.0) Makeup.Application.start(:normal, [])
            (kernel 9.0.2) application_master.erl:293: :application_master.start_it_old/4

15:25:41.761 [notice] Application nimble_parsec exited: :stopped

15:25:41.761 [notice] Application earmark_parser exited: :stopped

15:25:41.761 [notice] Application eex exited: :stopped
** (MatchError) no match of right hand side value: {:error, {:makeup, {:bad_return, {{Makeup.Application, :start, [:normal, []]}, {:EXIT, {:undef, [{Makeup.Application, :start, [:normal, []], []}, {:application_master, :start_it_old, 4, [file: ~c"application_master.erl", line: 293]}]}}}}}}
    (ex_doc 0.30.1) lib/mix/tasks/docs.ex:331: Mix.Tasks.Docs.run/3
    (mix 1.15.2) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.2) lib/mix/cli.ex:92: Mix.CLI.run_task/2
Error: exit status 1
```

**Comment by Toady00** [comment]
I has having another problem with dialyzer https://github.com/jeremyjh/dialyxir/issues/508 , and their solution was to add dialyzer to each child app. I tried that here and now I don't get the same error, but I'm getting an error for one of my apps `** (Mix) expected :name or :app to be found in the project definition in mix.exs` but there is a `app` key in the project of that app.

**Comment by josevalim** [comment]
Did you ExDoc to child projects or to the root? Are you invoking it from the root or the child projects? How have you specified it?

**Comment by Toady00** [comment]
Sorry, I originally had `{:ex_doc, "~> 0.29", only: :dev, runtime: false},`. I tried changing it to `{:ex_doc, "~> 0.30", only: :dev, runtime: false},` when I saw there was a newer version. Running `mix docs` from the umbrella root gave me the original error I posted in the first message.

Then I thought I'd add ex doc to each child, so I added `{:ex_doc, "~> 0.30", only: :dev, runtime: false},` to every child application and then tried running `mix docs` from the root again, and that's when I got the error about the `:name or :app` from the second post above.

**Comment by josevalim** [comment]
I cannot reproduce the error. `mix docs` at the root always tells me missing ":name or :app", which is expected. You need to add it to every child and, if you want to run on all of them, you can do `mix cmd mix docs`. :)

**Comment by Toady00** [comment]
Ah, I incorrectly assumed that running `mix docs` at the root would generate an aggregated doc at the root level. I was hoping to have all the documentation for the entire umbrella project together under one `index.html` entry point.

**Comment by josevalim** [comment]
Yeah, perhaps we could implement this feature, but it certainly isn't one we support right now. :)

**Comment by halostatue** [comment]
Generating an aggregate docset at the root would *definitely* be of interest. An pointers on what would be required to explore this?
