### ISSUE TITLE
Regression in headers on small screens

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/ex_doc#1739]
0.29.4:

![079EB393-6672-4481-BF32-6F4025603C1A](https://github.com/elixir-lang/ex_doc/assets/503938/ef6e268d-9b65-41c2-a9f7-8f672d7895f3)

![8A9B2C6A-D25A-4819-BC54-DA09144B068B](https://github.com/elixir-lang/ex_doc/assets/503938/7e9d27ad-5b59-4eab-b94b-cae7d4ad5b30)

0.30.2:

![5C617697-9D02-4626-BAF0-2D2AED09C25C](https://github.com/elixir-lang/ex_doc/assets/503938/644ad0a2-de56-4fd4-a8f3-2bf8799e1e75)

![356E447C-3B86-44EC-9792-2D2C0CF01FF2](https://github.com/elixir-lang/ex_doc/assets/503938/492fe572-4d99-4873-9be5-e81849d4d1ed)

---

I'm also not sure whether the lack of purple H3 in cheatsheets is intended or a regression. I personally preferred the pop of color and thought it helped to visually differentiate, especially in cheatsheets where there is a lot of header stacking.

**Comment by josevalim** [comment]
This is weird because I fixed that in v0.30.1 but something seems to have reverted the assets.

**Comment by josevalim** [comment]
v0.30.3 is out!

**Comment by zachallaun** [comment]
Thanks for the quick fix! Now get going on that summer vacation! 🌴

**Comment by wojtekmach** [comment]
I’ve added that gh action that is supposed to update assets. Maybe it caused the issue. I’ll investigate later.
