### ISSUE TITLE
Proposal: --warnings-as-errors

### ISSUE THREAD

**Issue by halostatue** [elixir-lang/ex_doc#1740]
I just had my documentation point out that I had done an imperfect refactoring of `t:AppIdentity.Plug.option/0` to `t:AppIdentity.Plug.Config.param/0` (and other related changes), but there's no way to see that except to manually run the document generation and watch for this.

If I could call `mix docs --warnings-as-errors`, then I could add this to my CI steps and ensure that I don’t documentation that won't resolve internally.

**Comment by wojtekmach** [comment]
Closing in favour of #1564. :)

**Comment by halostatue** [comment]
I searched issues. I did not search open PRS. Sorry for the noise.
