### ISSUE TITLE
Using `filter_modules` doesn't produce warning referencing `hidden or private` docs

### ISSUE THREAD

**Issue by WojciechBarczynski** [elixir-lang/ex_doc#1744]
Using `filter_modules` in the `mix.exs` doesn't produce warnings indicating undocumented code reference.

Using `@moduledoc false`:
1. Code:
```elixir
defmodule Foo do
  @moduledoc false
  # "Private" module

  @type foo :: integer()
end


defmodule Bar do
  @moduledoc """
  "Public" module
  """
  alias Foo

  @spec bar(Foo.foo()) :: nil
  def bar(num) do
    IO.inspect(num)
    nil
  end
end
```

2. Generates warring while trying to generate docs to notify users, that they are using type reference unavailable in the documentation:
```console
$ mix docs
Generating docs...
warning: documentation references type "Foo.foo()" but it is hidden or private
  lib/membrane_template.ex:16: Bar.bar/1

View "html" docs at "doc/index.html"
```

Using `filter_modules`:
1. `mix.exs`
```elixir
defmodule Mixfile do
  use Mix.Project

  def project do
    [
...
      # docs
      name: "Example",
      source_url: @github_url,
      docs: docs()
    ]
  end

...

  defp docs do
    [
      main: "readme",
      extras: ["README.md", "LICENSE"],
      formatters: ["html"],
      source_ref: "v#{@version}",
      filter_modules: ~r/Bar/,
    ]
  end
end
```

2. Code
```elixir
defmodule Foo do
  @moduledoc """
  "Private" module excluded with `filter_modules`
  """

  @type foo :: integer()
end


defmodule Bar do
  @moduledoc """
  "Public" module
  """
  alias Foo

  @spec bar(Foo.foo()) :: nil
  def bar(num) do
    IO.inspect(num)
    nil
  end
end
```

3. Doesn't generate any warring, despite `Foo.foo()` being unavailable in `docs`
```console
$ mix docs       
Generating docs...
View "html" docs at "doc/index.html"
```

4. Generated docs with `Foo.foo()` reference:
<img width="1324" alt="Screenshot 2023-07-27 at 11 49 43" src="https://github.com/elixir-lang/ex_doc/assets/104033489/0b702131-dcb4-4f56-860f-47a8dbee07b8">

**Comment by viniciusmuller** [comment]
I gave this issue a try and I'm not sure what the correct fix would be.
When autolinking typespecs referenced by functions we only have a `{Module, :type_name}` tuple, if the user provides a regex/string as `filter_modules`, we can use the regex to match against the module name and warn if the module is being filtered.

But if the user provides a function that takes the module and its metadata, we don't have these values available in the typespec linking context

**Comment by josevalim** [comment]
@viniciusmuller could we somehow filter the modules and keep a list of all modules that were filtered out and pass the filtered modules list to autolink?

**Comment by viniciusmuller** [comment]
Do you think [something like this](https://github.com/elixir-lang/ex_doc/compare/main...viniciusmuller:ex_doc:fix-filter-modules-typespecs) could work?

Allowing the retriever only retrieve modules and then we can filter its results and get them already nicely separated.
My first attempt was to refactor the retriever as to return a `{modules, filtered_modules}` tuple but it broke its API (in case someone is using a custom retriever) and made the changes much more complex.

I think if we retrieve everything and then filter the resulting list we can use the list that passes the filter as usual and give the name  of filtered ones directly to an autolink config, which I believe would then be enough for us to do:

```ex
if Enum.any?(filtered_module_names, & &1 == module_string) do 
   # warn
end
```

**Comment by josevalim** [comment]
@viniciusmuller could we perhaps change retriever to also return a list of all filtered modules?
