### ISSUE TITLE
Annotate modules visually when `@moduledoc since: "..."` is present

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#1755]
We recently made `@moduledoc since` propagate to all the types, functions, and macros in the module (https://github.com/elixir-lang/ex_doc/pull/1680), but I think it would be really nice to have the *module itself* annotated with this.

I was looking at `PartitionSupervisor` in Elixir, for example, and had to scroll through functions to know that *all* the functions were added in Elixir 1.14, which made me realize the whole module was added in Elixir 1.14. We can always annotate the module manually in the module-level doc (as I did in https://github.com/elixir-lang/elixir/pull/12895), but I think visually showing the "since ...", like we do for functions and friends, could be nice for modules too.

There was discussion around this in https://github.com/elixir-lang/ex_doc/pull/1680 itself and we opted for a simple solution (propagating), but I wanted to figure out if there is appetite for the full-fledged feature, if someone is willing to take on the visual work (I’m not good at that 😉), and so on 🙃 

Worst case, we can close this out and it'll help folks read about this feature in this issue at least 😄

**Comment by viniciusmuller** [comment]
I would like implementing this, but I'm not sure how this should look like :/
I did some experimentation locally but couldn't find a way that looks nice 
- maybe adding it on the right, but there's no background as opposed to the functions
- maybe adding in a box below, similar to the deprecation message

**Comment by josevalim** [comment]
I will go ahead and say no on this one because, we would still need to propagate it, as someone can still be linked directly to the function, so I am not that sure the additional information and clutter is worth it, given we propagate and refer to it on all entries too. :)

**Comment by whatyouhide** [comment]
@josevalim mmm I disagree here, because: 

> I was looking at PartitionSupervisor in Elixir, for example, and had to scroll through functions to know that all the functions were added in Elixir 1.14, which made me realize the whole module was added in Elixir 1.14

I think this is a pretty big DX deal. Considering this feature is visually a really tiny addition, are we sure we want to let it go? 😬

**Comment by wojtekmach** [comment]
I think it would be a nice addition and it looks good in this particular case:

<img width="1188" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/76071/233f50e6-ed93-4087-bf50-3effb453ccdd">

<img width="686" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/76071/a3873822-8dd7-48ac-a570-38c81c9fec88">

But it can get really busy:

<img width="687" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/76071/7e0573b2-4299-43c8-9a06-eabfa4796211">

so yeah not sure.

**Comment by whatyouhide** [comment]
What about something like "This module is available since v..." as the first sentence of the module doc, styled slightly different?

**Comment by josevalim** [comment]
Our goal is to move the search bar into the main page and, when we do so, we might move the cog icon, making it more or less cluttered, but I think right now is not the time for this. We can reevaluate in the future.

**Comment by whatyouhide** [comment]
@josevalim maybe we can out a solution for this and then re-evaluate when we do the changes you just mentioned? Like, we go with the sentence at the start of the moduledoc to get the feature and info to users, and then re-evaluate. 🙃

**Comment by josevalim** [comment]
We typically don't automatically add sentences. If that's a concern, then Elixir can add it directly to its docs. I would personally wait, there is no reason to rush and churn.
