### ISSUE TITLE
Internal linking from one extra to another

### ISSUE THREAD

**Issue by kybishop** [elixir-lang/ex_doc#1757]
I have a top-level README.md doc, as well as an internal `lib/some/module/path/README.md` for a specific module in our project. If I attempt to link to the internal README from the top-level one via its relative codepath it leads to a dead link (e.g. `[see here](lib/some/module/path/README.md)`. I also notice the internal README is renamed to just "readme-2.html" with the path cut off, which suggests the names of extras are dynamic, which makes linking via static literals potentially not possible?

Happy to add a documentation fixup PR for this if it is actually possible, but I can't seem to find a way to link to docs included via the `extras` option.

Perhaps I'm doing this wrong and I should instead be using moduledocs? I'd just hate to throw massive amounts of documentation into modules that already have a fair amount of code; being able to split documentation out into separate concerns would really help large projects like ours.

**Comment by wojtekmach** [comment]
extras works best when they are in the same directory which will make it impossible to have multiple files with the same names so there is no need for the automatic -2 suffix. You can definitely autolink to extras by their basename.

My suggestion is to move the docs to extras/README-module.md. However if you’d like to keep it alongside the code, perhaps symlink extras/README-module.ex -> lib/x/y/README.md.

I don’t think we can support your use case directly so I’m going to close this but please feel free to continue discussing.

**Comment by wojtekmach** [comment]
Come to think of it, see if this works: [title](../path/to/README.md), make the path relative to the extra you are referencing it from. One of the goals was to have links that work on both ExDoc and GitHub. If this does not work today I think we can try making it work without too much effort.

**Comment by kybishop** [comment]
Hey @wojtekmach, that works, but only if the filename is unique amongst the extras (e.g. no two files named README.md, regardless of their relative path).

**Comment by kybishop** [comment]
If the goal is to mirror functionality in GitHub, could we potentially re-open this issue to fix that particular problem? My wish-list aside, that is the biggest issue we're facing right now.

**Comment by wojtekmach** [comment]
Ok and today the other README ends up as readme-2.html but the links is to readme.html or the link is removed altogether?

**Comment by wojtekmach** [comment]
All generated .html file names need to be unique and we don’t allow nesting because most of not all links are relative.

I think we might be able to keep track of what links to where that ../lib/a/README.md is readme-2.html and ../lib/b/README.md is readme-3.htmlz

**Comment by kybishop** [comment]
> Ok and today the other README ends up as readme-2.html but the link is to readme.html or the link is removed altogether?

The former, it links to `doc/readme.html` when it should link to `doc/readme-2.html`.

A similar issue is presented with the `main` option, where initially you can be pointing to `main: "readme"`, but it breaks when another README.md file is introduced, since it now needs to be pointing at `readme-1`.

**Comment by wojtekmach** [comment]
Ok, if you’d like to explore this it would be very appreciated.

**Comment by kybishop** [comment]
> All generated .html file names need to be unique and we don’t allow nesting because most of if not all links are relative.

I'm not sure I understand the issue since keeping fully qualified relative paths, either through explicit url paths matching the file paths, or replacing `/` with `-`, would ensure uniqueness as well, but without all the hassle of cramming things into single-depth urls that have to worry about numbering due to collisions on the filename. 🤔

**Comment by wojtekmach** [comment]
I believe ExDoc generating files as a/b/c.html will be difficult to implement within the current design in general and there might be assumptions about flat file names elsewhere too. Feel free to explore. I think changing / to - might be the most pragmatic way.

**Comment by kybishop** [comment]
I will explore that option as I look around. Happy to take the easiest path on this 🙂

**Comment by josevalim** [comment]
@kybishop you may be able to handle this in your app today, something like this:

```elixir
  def extras do
    extras_folder("foobar") ++ extras_folder("bazbat")
  end
```

And then that does a Path.wildcard on the folder, collects all filenames, and returns entries like:

    [{"foobar/readme.md", filename: "foobar-readme.md"}, ...]

I am not sure though if our path resolution would be able to distinguish between foobar/readme.md and bazbat/readme.md, but that at least reduces the scope of the change.

---

Regarding the use of a flat namespace, note that we don't assume where the pages are hosted, so we can never use absolute paths. This means if we support directories, we would need to generate relative links, such as "../foobar/readme.html" and we want to avoid this trouble.

**Comment by josevalim** [comment]
@kybishop how did it go? Did the above work? Thank you!

**Comment by josevalim** [comment]
Closing this for now, as we convert file folders into file namespaces. If someone runs into issues with this approach, please let me know.
