### ISSUE TITLE
Can't find publicly defined type from another module

### ISSUE THREAD

**Issue by kybishop** [elixir-lang/ex_doc#1758]
When building via `mix docs`:
```
warning: documentation references type "Foo.my_type()" but it is hidden or private
   lib/bar.ex:123: Bar.function/1
```

ex_doc warns that it can't find a type defined in a separate module, yet the return type referenced in the specs:
1. Comes from a module that is properly aliased
2. The aliased module defines the type and it is publicly exported:
   1. `@type my_type() :: {:ok, SomeEctoSchema.t()} | {:error, Ecto.Changeset.t()} | {:error, %{String.t() => String.t()}}`
3. dialyzer reports no errors.

**Comment by wojtekmach** [comment]
Does the module has moduledoc false?

**Comment by kybishop** [comment]
Ah indeed it does (though the module where the type is defined does not). Is that expected that it would generate a warning about that file? I would think that would cause it to just skip the file entirely.

**Comment by kybishop** [comment]
Ah I'm dumb and was misreading, it was indeed the type-defining module that had `@moduledoc: false`. That makes perfect sense with the above.

I'll close, but I guess a light +1 for potentially changing the error message to point out the above? I'll see if I can think something up and put in a PR

**Comment by josevalim** [comment]
Please give a stab at the error message! It should be a quick change and easy to discuss if it improves things or not :)
