### ISSUE TITLE
Add syntax for explicitly linking to modules and pages

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1772]
`m:file` will be required to link to Erlang (`m::file` for Elixir?).

We should also introduce something to link to pages, such as `e:app:page.md` (or just `app:page.md`). We will also need to decide if we want to include the extension or not on `e:app:page.md`. If we remove the extension, it could be used to link to any page (including a module page). This means we can use the `p` prefix or `l` for link. We can automatically add the relevant extension (either .html or .xhtml for epub).

We will be glad to work on this if/when the Erlang/OTP team needs it. /cc @garazdawi

**Comment by garazdawi** [comment]
IMO we should go with `e:app:page.md`. This makes it explicit what we are linking to (an extra page with .md extension) in case we want to add more things later, maybe a link to an html page? or something we haven't thought about yet.

For Erlang I think it would make sense to turn off auto-linking of `` `atom` `` and `` `atom/2` ``, so that you have to write `m:atom` or `m:atom/2`. Or at least have it as a configuration to do so. In our code we have a lot of false positives and I would imagine that other code bases will have similar problems.

In my [ex_doc branch](https://github.com/garazdawi/ex_doc/tree/lukas/fix-erlang-doc-support) I've already implemented support for:

* `m:`
* `p:` (to be renamed `e:`)
* Linking to anchors in modules
* Linking to autoimported types/functions (i.e. [is_integer/1](https://www.erlang.org/doc/man/erlang.html#is_integer-1) and [integer/0](https://www.erlang.org/doc/man/erlang.html#type-integer))
* Documentation groups for types (unrelated to linking, but something that I think would be nice to have). You can see an example [here](https://garazdawi.github.io/otp/crypto/crypto.html).

Anything you make will be much better than my hacky Elixir so feel free to use as much or little as you want.

**Comment by wojtekmach** [comment]
> `` `m:atom/2` ``

double-checking, what would this mean? I thought m: is for modules.

**Comment by wojtekmach** [comment]
regarding `` `e:app:page.md` ``, two things:

1. it doesn't hurt, but I believe we can drop e: prefix.
2. I'd keep .md extension only if we verify the thing we link to exists.

In other words, if we don't verify, `app:foo:bar` would be a dumb link to hexdocs.pm/foo/bar.html, the link can 404. This would allow linking to a `bar` module or any `bar` extras page. I think the flexibility to link to either is nice.

Now, verifying the link is a bit different discussion and I see a path towards that but it may not be easy or work 100% of time. I think we could verify "OTP" app: links if one has OTP with doc sources. I think we could verify app links for Mix dependencies (by looking at their Mix.Project.config()[:docs]) however the Hex packages might not ship with doc sources. As you can see it might be a fair amount of complexity.

**Comment by garazdawi** [comment]
`m:` is indeed for modules... I meant it as a way to write a function/arity link, but as you say `m:` is for modules so the naming does not make sense there.

I've found that in our docs we have quite a lot of examples that looks like this `` `example/2` `` without example actually being a function... and when the autolinker attempts to link that it of course fails. Maybe this is just one of those places where we will have to add some warning skips.

**Comment by wojtekmach** [comment]
> Maybe this is just one of those places where we will have to add some warning skips.

yeah, exactly, that's a shame.

I was gonna write that we could use `e:` for Erlang things meaning you have to "opt-in" to linking to a module or a local call. However, `e:example/2` of course means calling example/2 on an e module.

It never occurred to me before but for the same reason linking to types (t:) and callbacks (b:) is somewhat broken too. Linking to _remote_ ones works: `b:gen_server:handle_call/3` but `b:handle_call/3` is ambiguous, we could never have a `b` module.

**Comment by garazdawi** [comment]
If ExDoc could do extra pages checks that would be great, but for our usage I've written a small html parser that just crawls the generated html and checks the links after ExDoc has created all our applications. The earlier those types of errors can be caught the better though.

**Comment by garazdawi** [comment]
> It never occurred to me before but for the same reason linking to types (t:) and callbacks (b:) is somewhat broken too. 

Luckily single letter module names are not very common, and [`c` is already taken by us](https://www.erlang.org/doc/man/c.html) :)

**Comment by wojtekmach** [comment]
ah, right, it was `c:`. I'm not sure if it would ever come up in practice besides this particular example but ExDoc would have to pick whether `c:flush/0` means `flush/0` callback of the current module or `c:flush/0` function and I believe it picks number 1 and there's no way to overwrite it. I can't think of a way to improve this, just point this out.

**Comment by wojtekmach** [comment]
well I suppose ``[`c:flush/0`](`app:stdlib:c#flush/0`)`` is the way to overwrite it :)

**Comment by josevalim** [comment]
We don't warn on `` `example/2` `` but we do (or should) warn on ``[Foo](`example/2`)`` if `example/2` does not exist. So in my mind, you should be able to write `example/2` just fine? Otherwise, it is either an autolinker bug (or a bug in the Erlang handling part of ExDoc).

In any case, the downside of `example/2` is fewer warnings on actual missing functions. One option to consider is to always warn if `example/2` if not defined, and then if you want to refer to an example in the docs, you always refer to it using a full qualified name. So you would say `my_example:example/2` (because warning for modules is just much trickier anyway). If you are fine with this direction, I would be happy to migrate ExDoc to this as a whole.

@garazdawi regarding your improvements to ExDoc, let us know whenever your branch is ready for merging, and we will cherry-pick the important bits.

**Comment by whatyouhide** [comment]
> In any case, the downside of `example/2` is fewer warnings on actual missing functions. One option to consider is to always warn if `example/2` if not defined, and then if you want to refer to an example in the docs, you always refer to it using a full qualified name. So you would say `my_example:example/2` (because warning for modules is just much trickier anyway). If you are fine with this direction, I would be happy to migrate ExDoc to this as a whole.

So would this mean that `my_example:example/2` doesn't warn? I’m confused by this because I thought we'd warn for `my_module:function/2` if the module/function don't exist.

**Comment by wojtekmach** [comment]
> So would this mean that my_example:example/2 doesn't warn?

if `my_example` module exists and the referenced function doesn't, we warn. If the module does not exists, we don't warn.

**Comment by whatyouhide** [comment]
Got it, thanks @wojtekmach. Then @josevalim your suggested approach (warn on `example/2`) sounds great for ExDoc too IMO.

The consideration about `.md` vs `.html` is also really interesting, and makes me think that maybe we do want `e:app:page.html`?

**Comment by garazdawi** [comment]
> Otherwise, it is either an autolinker bug (or a bug in the Erlang handling part of ExDoc).

Most likely it is a bug/feature in my ExDoc branch. The warnings look like this: https://github.com/garazdawi/otp/actions/runs/6224126656/job/16893382921#step:13:6454

> Maybe it is using an older ExDoc version with slightly different rules, and so on. 

I would consider a change to how paths are converted to URIs to be a backwards incompatible change. If you change it, you run the risk of making a lot of links from random places on the internet end up in 404s. So I would say that you have larger problems then cross-application linking if you change that algorithm.

**Comment by josevalim** [comment]
Good point on the URL changes. I guess that rules out this particular case but it still makes me a bit worried that we are linking to an internal page rather than the produced artifact. :)

**Comment by josevalim** [comment]
This is now being tracked in other issues.
