### ISSUE TITLE
Should the sidebar still be dark with light theme enabled?

### ISSUE THREAD

**Issue by florish** [elixir-lang/ex_doc#1774]
Hi, not 100% sure if this is a bug or not, but today I accidentally switched from dark to light thema, and noticed that the sidebar does not change color (still light text on dark background, at least for https://hexdocs.pm/elixir/Kernel.html and other `elixir` core documentation pages).

A quick code search learned me that there have been some changes to the sidebar CSS, notably the introduction of CSS variables:

https://github.com/elixir-lang/ex_doc/commit/1e738731378438456c04363fe1d9981486a45dd9

As a side-effect, it seems like the previous dark/light color differences have disappeared, as all `--sidebar*` color values are exactly the same for light and dark mode.

Again, not entirely sure if this is a bug or intended behaviour, so feel free to close without commenting!

**Comment by josevalim** [comment]
Yes, this is intentional, and has always worked like this. :)
