### ISSUE TITLE
Sidebar CSS broken in v0.30.6

### ISSUE THREAD

**Issue by seancribbs** [elixir-lang/ex_doc#1779]
Reverting to `v0.30.5` resolves this issue.

[Correct](https://hexdocs.pm/hardhat/Hardhat.html):

![image](https://github.com/elixir-lang/ex_doc/assets/1772/9e710043-cd85-468a-9df2-cc4dde32813c)

[Incorrect](https://hexdocs.pm/hardhat/1.0.0-rc.1/Hardhat.html):
![Screenshot 2023-09-18 at 10 20 34 AM](https://github.com/elixir-lang/ex_doc/assets/1772/4531ab6e-8f93-431b-a40b-e17e7ce08b74)

Note the mispositioned and mis-sized toggle widgets (ignore the differences in the number of modules displayed, I was tweaking the grouping settings).

**Comment by josevalim** [comment]
Can you do a hard page refresh just in case?

**Comment by josevalim** [comment]
Errr, it is not a page refresh. Can you do this:

```
$ rm -rf doc/
$ mix docs
```

And see if the error exists locally? I think we are failing to override some assets between ExDoc versions. :(

If this works, you can republish only the docs as `mix hex.publish docs`.

**Comment by josevalim** [comment]
Here is an example of working docs on v0.30.6, so I believe it is indeed something stale: https://hexdocs.pm/nx/Nx.html :D

**Comment by seancribbs** [comment]
Thanks for clearing that up!

**Comment by josevalim** [comment]
@seancribbs please let me know if it works, if it does not even with cleaning, then feel free to reopen :)
