### ISSUE TITLE
missing `docs_config.js`

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1789]
Follow up on https://github.com/starbelly/rebar3_ex_doc/issues/62.

![Screenshot from 2023-10-04 13-04-40](https://github.com/elixir-lang/ex_doc/assets/134518/5c2565b1-6d71-4c0e-9325-99a136a175c8)

We have noticed that `doc_config.js` was missing when viewing the generated doc locally. Was this an intended behaviour, or it is a bug?

**Comment by josevalim** [comment]
Yes, the file is never there by default. It is added by hex.pm with metadata about the docs, but otherwise, you can safely ignore it.
