### ISSUE TITLE
Documentation Issue.

### ISSUE THREAD

**Issue by kevinmontuori** [elixir-lang/ex_doc#179]
ExDoc.Formatter.HTML.generate_readme/3 expect that the value of config.readme will be a path; the documentation in Mix.Tasks.Docs:29-30 indicates that the value for :readme is a Boolean.  Seems like a trivial documentation error.

**Comment by josevalim** [comment]
Yes, thank you, let's fix the task docs! A pull request is welcome!

**Comment by whatyouhide** [comment]
@josevalim I think #180 actually solved this issue, maybe we can close this?
