### ISSUE TITLE
Style issues after version 0.30.4

### ISSUE THREAD

**Issue by general-CbIC** [elixir-lang/ex_doc#1794]
Hi 👋🏻 

Could you help me to find the style problems reason?
I thought it was a general problem and would be fixed, but I still have a problem after four patches.

I use `ex_doc` version `0.30.4` and everything is fine.
But when I try to upgrade the version, I get something strange 😞 

| Version | Problems | Example |
|---------|----------|--------|
| 0.30.4 | Good ✅ | <img width="676" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/13352583/2a910ad2-3212-492b-a252-647292c9876d"> |
| 0.30.5 | Broken header styles | <img width="785" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/13352583/b9b9fb46-18ac-469b-bb35-bffb6cdff5d6"> |
| 0.30.6 | Broken header and menu styles | <img width="791" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/13352583/5d119a24-8358-438d-a47b-510e5f9ea9bc"> |
| 0.30.7 | Broken menu styles | <img width="790" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/13352583/9aa15326-7c91-48ab-9565-7fbe89e82632"> |
| 0.30.8 | Broken menu styles | <img width="794" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/13352583/ea1a6a2b-b4fa-4a45-b9b4-f2482cf4af77"> |

**Comment by josevalim** [comment]
Remove doc/ and run “mix hex.publish docs” to publish them again and it shall be fixed!

**Comment by general-CbIC** [comment]
Oh, thank you very much 💜
It works!

**Comment by josevalim** [comment]
I will ship a new version with a fix, hopefully. :)
