### ISSUE TITLE
ex_doc > 0.30.5 generating incorrect HTML output for ex_money

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/ex_doc#1804]
I received [an issue on ex_money](https://github.com/kipcole9/money/issues/153) that indicated that docs on [hexdocs](https://hexdocs.pm/ex_money) were broken.

On investigation it appears that the docs generate correctly up to ex_doc version 0.30.5, but incorrectly on later versions.  I lack the proper skills to debug this very well but I'm more than happy to provide any assistance I can.

I have checked on both Safari Mac 16.6 and Chrome 119.0.6045.105.

Here are the examples:

### Ex_doc version 0.30.5 (correct)

![ex_doc 0 30 5](https://github.com/elixir-lang/ex_doc/assets/15895/183f5717-74cd-426e-929a-9d7b9f543bd3)

### Ex_doc version 0.30.6 (incorrect)

![ex_doc 0 30 6](https://github.com/elixir-lang/ex_doc/assets/15895/38fb9e68-cd0c-4a92-b221-fe02eeae2ab6)

### Ex_doc version 0.30.9 (incorrect)

![ex_doc 0 30 9](https://github.com/elixir-lang/ex_doc/assets/15895/177a1cb1-51fe-485e-ba9d-f4cf00740161)

**Comment by josevalim** [comment]
Please `rm -rf doc` and then `mix hex.publish docs`.

**Comment by kipcole9** [comment]
Arrghhhh, it's too late at night. I was `rm -rf docs` (spurious `s`). Apologies for the noise. Closing.
