### ISSUE TITLE
Admonition block content in cheat sheets has incorrect background colour

### ISSUE THREAD

**Issue by sevenseacat** [elixir-lang/ex_doc#1814]
The same admonition block content is rendered fine as part of moduledoc content. The same issue occurs in both light and dark mode.

eg. we have some content copied to cheat sheets - 

The cheat sheet version - https://hexdocs.pm/ash_authentication/dsl-ashauthentication-strategy-oauth2.html#secrets-and-runtime-configuration

<img width="405" alt="Screenshot 2023-11-13 at 2 12 35 pm" src="https://github.com/elixir-lang/ex_doc/assets/543859/e66c352f-dd54-4555-aee2-90a4de596789">

The module doc version - https://hexdocs.pm/ash_authentication/AshAuthentication.Strategy.OAuth2.html

<img width="332" alt="Screenshot 2023-11-13 at 2 12 46 pm" src="https://github.com/elixir-lang/ex_doc/assets/543859/40930e59-223c-4512-afab-4ffd38c240a2">

Source content - 

```markdown
> ### Warning {: .warning}
>
> We **strongly** urge you not to share actual secrets in your code or
> repository.
```

**Comment by josevalim** [comment]
Please try to it on v0.30.9, cc @zachdaniel.

**Comment by josevalim** [comment]
I will close it as you can see it working here: https://hexdocs.pm/ex_doc/readme.html on latest . Glad to reopen otherwise!

**Comment by sevenseacat** [comment]
Odd, I'm still seeing it in 0.30.9. I'll dig into it and try to see what's going on.

**Comment by josevalim** [comment]
Admonition blocks are definitely not supported in cheatsheets. The styles there are quite limited (on purpose).
