### ISSUE TITLE
Search for terms beginning with colon (e.g. ":if")

### ISSUE THREAD

**Issue by rhcarvalho** [elixir-lang/ex_doc#1820]
Unexpected results when searching Phoenix documentation.

Cannot search for Heex template attributes like `:if` and `:for`, as that sort of input gets interpreted in some particular way by the search tokenizer. I tried wrapping in quotes, but that doesn't work either.

![image](https://github.com/elixir-lang/ex_doc/assets/88819/81e278e0-7487-4458-9338-e2e2c08441bb)

![image](https://github.com/elixir-lang/ex_doc/assets/88819/716bed0f-1bbb-405d-8ac1-93287a7b773e)

**Comment by josevalim** [comment]
It is understand that `:if` does not work, because that's the syntax used for fields, but in my opinion `":if"` should work. PRs welcome.

**Comment by rhcarvalho** [comment]
Upon first look, the relevant code / limitation seems to be within the `lunr` dependency, in particular the `QueryParser` implementation.

https://github.com/elixir-lang/ex_doc/blob/4f5a221fa6bf110c989a692164d8b6445e97cbca/assets/package.json#L48

I see `ex_doc` configures `lunr` in https://github.com/elixir-lang/ex_doc/blob/4f5a221fa6bf110c989a692164d8b6445e97cbca/assets/js/search-page.js#L48-L51

---

Any suggestions or tips how to test changes to `ex_doc` in a feature branch? Is there an easy way to render some docs and interact with it in the browser and/or write unit tests?

**Comment by rhcarvalho** [comment]
https://lunrjs.com/guides/searching.html#fields

I was not familiar with Lunr.js. I think one path forward is to use a pre-processor to replace a colon ":" in the beginning of a word (quite common in Elixir, atom syntax) with something that is not a special character to Lunr (e.g. `_COLON_`), and also do a similar processing when indexing documents.

That would solve not only the `:if` query (same for `":if"`, as apparently `"` doesn't mean anything to Lunr), but also allow searching for atoms :smile: 

If I figure out how to do the above, we may also find a way to search for trailing colons, because of keyword lists. E.g. finding ":current_user" and "current_user:".

**Comment by rhcarvalho** [comment]
BTW, I learned `\` can be used to escape special characters https://lunrjs.com/docs/lunr.Index.html#~QueryString.

Searching for `\:if` returns results, but not the most relevant results -- it is as if the colon prefix is ignored.

![image](https://github.com/elixir-lang/ex_doc/assets/88819/c767e931-b98f-4804-abe3-d3215eae95b3)

![image](https://github.com/elixir-lang/ex_doc/assets/88819/6cccab10-0237-4005-88d9-69633eed192d)

**Comment by josevalim** [comment]
Yeah, I was playing with this code and so i pushed a fix. :)
