### ISSUE TITLE
Support converting GitHub alerts to admonitions?

### ISSUE THREAD

**Issue by jjcarstens** [elixir-lang/ex_doc#1821]
Currently the ExDoc way of specifying admonition blocks is incompatible with GitHub markdown (which they call [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts))

I sometimes have cases sharing markdown between module docs and markdown files which forces me to choose to have one or the other and lose the nice callout of text. In fact, that seems to be the case for the readme in this repo
<img width="450" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/11321326/505fdb89-02a2-44d2-bfc0-db2c6ae2c170">

I recently made a change [here](https://github.com/jjcarstens/pint_broker/blob/v1.0.1/mix.exs#L66-L85) to handle a conversion of GitHub alter to ExDoc admonition which seems to work. Is that something that might be wanted to officially support?

You can compare the [repo readme](https://github.com/jjcarstens/pint_broker/tree/v1.0.1) with the [generated HexDoc](https://hexdocs.pm/pint_broker/readme.html) to see admonition is shown in both places.

The caveat with this is that the GitHub alerts don't seem to support a title for it( i.e. you cannot convert `> [!IMPORTANT] something` to `> ### something {: .info}`. I am unsure if they will have that in the future or not

**Comment by josevalim** [comment]
There are no plans at the moment. I find our version better as it supports titles :) so hopefully once something like this is standardized, it will support titles.
