### ISSUE TITLE
Adding formal support for filenames

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#1828]
The Sentry documentation ([`sentry-docs` repository](https://github.com/getsentry/sentry-docs)) does something cool with filenames + code blocks.

It uses MDX, so things work a bit different over there, but I think maybe this might make sense for ExDoc too. Basically, they let you define blocks of code with support for a syntax for specifying a filename. For example (original source [here](https://github.com/getsentry/sentry-docs/blob/82a3fc5cb4ebdf5f61abe2c606472e2ad1ba06ff/src/platform-includes/set-environment/elixir.mdx)):

~~~markdown
```elixir {filename:config/prod.exs}
config :sentry,
  environment_name: :prod
```
~~~

The `{filename:...}` bit after the code block backticks is what I’m talking about here. This is what it looks like when rendered:

![CleanShot 2023-11-27 at 18 02 52@2x](https://github.com/elixir-lang/ex_doc/assets/3890250/b01696d1-1876-4757-9afb-25d194d1a4eb)

A benefit of this is also that the `filename` key would allow us to use other configs in the future. I’m imagining something like `{filename:..., linenos:true}` or something.

Do you think something like this would be useful in ExDoc?

**Comment by josevalim** [comment]
This is tricky because it deviates from Markdown, so we need to consider it with care. We have two extensions to markdown today:

1. Admonition blocks, [which use IAL](https://python-markdown.github.io/extensions/attr_list)

2. Tabsets, which use HTML comments

We should probably support one of the two styles and not add a third one. With IAL, it would be like this:

````
```elixir
foo
```
{. data-file="config/prod.exs"}
````

With HTML comments, it would be like this:

````
<!-- code-file:config/prod.exs -->
```elixir
foo
```
````

However, note that we always show the copy button already. And the file location could be easily added as a code comments in the top too, so perhaps there are not strong incentives to deviate from markdown here.

**Comment by josevalim** [comment]
Also worth adding that the Sentry syntax and HTML comments both work on GitHub but the file is not visible. The IAL one renders the annotation as is which is not quite readable. So that's another concern to have in mind. Whatever we add won't show up on GitHub, in contrast to code comments, so I am :-1:.

**Comment by halostatue** [comment]
FWIW, The GFM spec does allow for this:

> The content of a code fence is treated as literal text, not parsed as inlines. The first word of the [info string](https://github.github.com/gfm/#info-string) is typically used to specify the language of the code sample, and rendered in the class attribute of the code tag. However, this spec does not mandate any particular treatment of the [info string](https://github.github.com/gfm/#info-string).

…

> An [info string](https://github.github.com/gfm/#info-string) can be provided after the opening code fence. Although this spec doesn’t mandate any particular treatment of the info string, the first word is typically used to specify the language of the code block. In HTML output, the language is normally indicated by adding a class to the code element consisting of language- followed by the language name.

> [Example 112](https://github.github.com/gfm/#example-112)
> ````markdown
> ```ruby
> def foo(x)
>  return 3
> end
> ```
> ````
>
> ```html
> <pre><code class="language-ruby">def foo(x)
>  return 3
> end
> </code></pre>
> ```

> [Example 113](https://github.github.com/gfm/#example-113)
> ````markdown
> ~~~~    ruby startline=3 $%@#$
> def foo(x)
>  return 3
> end
> ~~~~~~~
> ````
>
> ```html
> <pre><code class="language-ruby">def foo(x)
>  return 3
> end
> </code></pre>
> ```

I think that the `key=value` approach is better than `{filename:name.exs}`, but that's a personal preference.

mkdocs material has some nice extra [code block annotation capabilities](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/), but they are different than the annotations used for admonitions.

**Comment by josevalim** [comment]
Good find on the spec that confirms the behavior. I am afraid my concern remains though: if we use this feature for something as important as file names, it won’t show up in many places, such as Livebook and GitHub. It would be fine for things such as titles and highlighting certain line numbers though.

**Comment by wojtekmach** [comment]
we really shouldn’t invent new standards but here is one anyway :) after language we can have names and name/value pairs. Using „filename” means ExDoc should use the conventional commented out first line as the filename, remove from the code block and render it elsewhere, in a special way.

```elixir filename
# foo.exs
1 + 2
```

The nice thing about this is there’s clear fallback for non-ExDoc renderers, render the comment as usual. That being said it would be a precedent for messing with inside of the code blocks and as mentioned above yet another non-standard markdown thing.

**Comment by josevalim** [comment]
Closing this, as having it within the code is the most visible across different media.
