### ISSUE TITLE
Printing chars as default parameters in readable form instead of number.

### ISSUE THREAD

**Issue by h4cc** [elixir-lang/ex_doc#183]
Code to document:
```elicir
def slugify(text, separator \\ ?-), do: :something end
```
The created documentation entry will look like: `slugify(text, separator \\ 45)`

Maybe we could print that char as `?-` instead of `45`.

**Comment by josevalim** [comment]
@h4cc we won't be able to fix this one because it is impossible to know if it was given as a number or as a character as their representation in the AST is the same. :(

**Comment by whatyouhide** [comment]
@h4cc Be sure to document that the argument with the default value is expected to be a codepoint in the function's `@doc` block :smile:
