### ISSUE TITLE
Using keybind to focus search flickers the sidebar

### ISSUE THREAD

**Issue by drtheuns-enreach** [elixir-lang/ex_doc#1830]
When using either `s` or `/` to focus the search field, the sidebar flickers from closed to open quickly.

Browser: Firefox 118.0.2

Here's an example where I press `s` -> `Esc` -> `s` -> `Esc` -> `s`

[ex-doc.webm](https://github.com/elixir-lang/ex_doc/assets/104429717/594263ce-ec43-4de1-945a-88b0e2053e44)

**Comment by josevalim** [comment]
This has been fixed in main, thank you!
