### ISSUE TITLE
Auto link with anchor is not working

### ISSUE THREAD

**Issue by damir** [elixir-lang/ex_doc#1832]
This example from documentation is not working:

```
`Keyword#module-duplicate-keys-and-ordering` will create a link to https://hexdocs.pm/elixir/Keyword.html#module-duplicate-keys-and-ordering
```

No link is generated when using it like that:

```
[Keyword duplicate keys](`Keyword#module-duplicate-keys-and-ordering`)
```

and `mix docs` prints the warning:

```
Generating docs...
warning: documentation references "Keyword#module-duplicate-keys-and-ordering" but it is invalid
  README.md: (file)

View "html" docs at "doc/index.html"
```

It works with `e:elixir:` prefix:

```
[Keyword duplicate keys](`e:elixir:Keyword#module-duplicate-keys-and-ordering`)
```

But when there is nested module it does not:

```
[Functions](`e:elixir:Kernel.SpecialForms#functions`)
```

The link is generated but it points to invalid URL because it is missing `.html` part - https://hexdocs.pm/elixir/Kernel.SpecialForms#function, it should generate https://hexdocs.pm/elixir/Kernel.SpecialForms.html#functions

**Comment by wojtekmach** [comment]
Thank you for the report. Just double checking, what is your ExDoc version?

**Comment by josevalim** [comment]
When you use `e:app:page`, it is expected that you have the extension. The cases without an extension is only when the file itself does not have one (think about a LICENSE file).

Other than that, I think `Keyword#module-foo` should work.

@wojtekmach it is probably latest since `e:app` works?

**Comment by damir** [comment]
Yes, I used the latest version - `0.31.0`

**Comment by woylie** [comment]
This works:

```
[async operations](`e:phoenix_live_view:Phoenix.LiveView.html#module-async-operations`)
```

Should this work, too?

```
[async operations](`m:Phoenix.LiveView#module-async-operations`)
```

If I read the documentation correctly, it should, but it doesn't in 0.31.0.

**Comment by josevalim** [comment]
It is fixed in main I believe.

**Comment by woylie** [comment]
> It is fixed in main I believe.

Confirmed, thanks.
