### ISSUE TITLE
URL in browser not updating when clicking link icon on iOS

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#1836]
I‘ve noticed that clicking the link icon for a section on iOS no longer updates the browsers URL in recent ex_doc versions. I need to long press the icon to have it open a context menu for the link and copy the link in that menu to have the fragment for the section available. 

Given the animation changed to scroll to the section differently (having an offset for the header) I‘m wondering it there‘s JS that broke the URL being updated.

Works by just clicking the icon an copying the updated url for the browser window:
https://hexdocs.pm/phoenix_live_view/0.19.0/Phoenix.Component.html

Does require long pressing the icon to copy the link. Clicking the icon triggers a scroll to animation, but doesn‘t update the windows URL:
https://hexdocs.pm/phoenix_live_view/0.20.3/Phoenix.Component.html

iOS 16.6.1

**Comment by josevalim** [comment]
Sorry, I am a bit confused. Which link icon? Do you mean a session title in the sidebar? And does it happen only on iOS but not on Firefox or Safari?

**Comment by LostKobrakai** [comment]
I had noticed it only on safari on iOS. Actually checking it on my laptop is seems to be working just fine on lastest safari (17.2) there.

![IMG_42BDAD2FF840-1](https://github.com/elixir-lang/ex_doc/assets/2489835/ae25a8ee-b207-40c3-9ece-014b8e0259b3)

**Comment by josevalim** [comment]
Fixed, thanks!
