### ISSUE TITLE
@since tag not rendered correctly for Erlang source Types?

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/ex_doc#1840]
Found in https://hexdocs.pm/oidcc/oidcc_authorization.html#summary

![image](https://github.com/elixir-lang/ex_doc/assets/134518/afae05c4-34b6-44a2-ac75-dbbcc9fde58c)

Expected to be like below:

![image](https://github.com/elixir-lang/ex_doc/assets/134518/537346bf-55b4-4a77-ab4a-1b12fea297a0)

ENV:

```
$ asdf current
elixir          1.16.0          /tmp/oidcc/.tool-versions
erlang          26.2.1          /tmp/oidcc/.tool-versions

$ mix hex.outdated | grep ex_doc
ex_doc              0.31.0   0.31.0  Up-to-date
```

How to reproduce the bug:

```
cd /tmp
git clone https://github.com/erlef/oidcc.git
cd oidcc
mix deps.get
mix docs --open
```

**Comment by josevalim** [comment]
@kianmeng we only render what was put in the docs chunk. So either edoc is wrong (the tool that generates the docs chunk) or the library (oidcc) has written the wrong annotation. My suggestion is to open up an issue on `oidcc`. Thank you :)
