### ISSUE TITLE
Search is not working for some terms

### ISSUE THREAD

**Issue by damir** [elixir-lang/ex_doc#1844]
When searching for `phx-update` on https://hexdocs.pm/phoenix_live_view there is no any result, it is here in the first paragraph - https://hexdocs.pm/phoenix_live_view/dom-patching.html.

That page is found when searching for `ignore`, but because it found and highlighted `ignores` and not `ignore`. Looks like strings between backticks are not indexed.

**Comment by josevalim** [comment]
It has been fixed, LV needs a new relaese with latest ExDoc.
