### ISSUE TITLE
Sidebar overflow is not showing a scrollbar on my browsers

### ISSUE THREAD

**Issue by rvnash** [elixir-lang/ex_doc#1846]
I noticed recently that this page started rendering strangely. There are these new icons in the leftside navbar, and more importantly, no scrollbar appears when the content extends beyond the bottom of the page: https://hexdocs.pm/openai_ex/0.5.6/userguide.html

Image of what I see:
![openai_ex](https://github.com/elixir-lang/ex_doc/assets/182201/8a80439e-ce94-480a-acc3-c4af84b6e656)

I took that as perhaps a one-off issue with the openai_ex documentation, but then I encountered it again when browsing a different library's docs
https://hexdocs.pm/ecto_sqlite3_extras/readme.html#content
![ecto_sqlite3_extras](https://github.com/elixir-lang/ex_doc/assets/182201/b4505f3c-3ca3-4724-8fa7-4de3be9554d5)

I've tried it in a bunch of different browsers, and got more or less the same behavior. No scroll bar.

I've looked into it a little bit, and it looks like the `.sidebar` class has the attribute `overflow: hidden`, until the height of the viewport drops below 500px, then it switches to `overflow: auto`

**Comment by josevalim** [comment]
The docs were published with mixed outdated ExDoc versions (it was an ExDoc bug).

Run `rm -rf doc` and `mix hex.publish docs` again and you should fix it!
