### ISSUE TITLE
SVG logo is not shown

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/ex_doc#1847]
`img` tag is 0x0 and logo is invisible. Works fine with PNG.

It used to work in v0.30.9. Doesn't work starting from v0.31.0

**Comment by josevalim** [comment]
PRs welcome!

**Comment by DavidOliver** [comment]
It was SVGs without their own width/height attrs that were not showing. PR incoming.

**Comment by josevalim** [comment]
I was wrong, the docs say only PNG and JPG are supported, so you will have to convert. We may support it with the PR, but not guaranteed. :) use supported formats instead.
