### ISSUE TITLE
New Github Label for Low Priority Enhancement

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#186]
I was reading #149
Where it was closed because it was considered not a priority for the core team, but I'm afraid a lot of these good ideas will just get lost in the pile up new issues.
Wouldn't it be good to have a label that we can still reference to these ideas. An easy way to find them all in one place, even though the issue has been closed.
While not a priority, a lot of newcomers to elixir, may want to contribute and get their hands into elixir, and these tasks I'm sure will interest some people who want to gain real practice or simply contribute.

I'm proposing a label that once the issue has been tackled, the label can be removed.
Something like "Priority:Low", or "Pending Enhancements", etc...
what do you guys think.

**Comment by ericmj** [comment]
Closed issues can still be found when you search. Keeping around every potential feature as an open issue has the exact problem you are talking about; important issues will be lost among them.

**Comment by eksperimental** [comment]
@ericmj maybe I didn't explain myself clear enough, the idea is to apply this level to the closed issues, so they don't get lost. that's the main idea.

**Comment by ericmj** [comment]
Ah :+1:

**Comment by josevalim** [comment]
:+1: we could start tagging those from now on, even if closing!
