### ISSUE TITLE
Head of document missing when printing

### ISSUE THREAD

**Issue by rhcarvalho** [elixir-lang/ex_doc#1864]
When printing documentation, the top of the page content seems to be missing.

I'm not sure if this is some local issue with my browsers/system, but managed to reproduce in both Chrome and Firefox on Fedora Linux:

https://hexdocs.pm/elixir/1.16.1/Kernel.html

## On screen

![image](https://github.com/elixir-lang/ex_doc/assets/88819/d7e49a77-5c62-4456-bd86-a86e61ed4a5d)

## Print preview

![image](https://github.com/elixir-lang/ex_doc/assets/88819/2f29e014-5887-4c19-bcaf-81dd53d99aed)

## Print preview -- white text on white background?!

I am able to select some invisible text that seems to correspond to the missing heading, "Kernel" in this example.

![image](https://github.com/elixir-lang/ex_doc/assets/88819/15673ee2-8164-44ca-b4e1-2eeeb465b2de)

---

Reporting in case this is not just me :)

**Comment by josevalim** [comment]
Do you know if it is fixed in main?

**Comment by rhcarvalho** [comment]
Was also broken when I tried earlier today.

**Comment by rhcarvalho** [comment]
When I was testing https://github.com/elixir-lang/ex_doc/pull/1863 I noticed it was happening after removing the search bar too.
