### ISSUE TITLE
Equivalent for edocs's {sort_functions, false}

### ISSUE THREAD

**Issue by nixxquality** [elixir-lang/ex_doc#1865]
I've noticed that ex_doc sorts all functions alphabetically by default, and this is what edoc does as well.
However, edoc has an option to disable this sorting: https://www.erlang.org/doc/man/edoc_layout

Is there a way to make ex_doc list functions by order of occurence in the source file? If not, I would like to request that feature.

**Comment by josevalim** [comment]
It is not possible right now, however, we do provide grouping, so you can create different groups. Can you please expand on the use case?

**Comment by nixxquality** [comment]
Sure, it's for my library jsonpull, you can see the edoc documentation here: https://hexdocs.pm/jsonpull/ (check the jsonpull or _read modules inside)
In my opinion, it made the most sense to sort in order of complexity, so I've put the primitive types first and then the complex types later.
I could see grouping serving the same purpose, so I might take a closer look at that.

**Comment by josevalim** [comment]
@nixxquality please let us know if grouping was enough. :)

**Comment by nixxquality** [comment]
I suppose so. If you don't have any interest in implementing this feature, you may close this issue.

**Comment by josevalim** [comment]
We would accept contributions but not something we plan chasing ourselves. Thanks!
