### ISSUE TITLE
new option: generated zipped file

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#187]
this idea comes from https://github.com/elixir-lang/elixir/issues/2989

I think it will be a good asset to have an option to generate a .zip/.gz/.gzip version of the docs for easier distribution.

**Comment by eksperimental** [comment]
the question is whether should it be created by default, parent folder makes sense, ex:
/docs/stable/elixir/
/docs/stable/elixir_v1.0.3_doc.zip

the thing is that we may not always have writing access to it. Otherwise inside the folder, but there are so many files there it can be lost and pass unnoticed.

Also a good name for the file will be good: Elixi

**Comment by ericmj** [comment]
A zip file can easily be created by aliasing the docs task. I don't think this is the job of exdoc. If you think we should distribute core docs as zip files we can discuss it on the mailing list as it is not directly related to exdoc.

**Comment by eksperimental** [comment]
Well, my idea is to have the feature in ex_doc, regardless whether it's a good idea or not for the elixir project.
I think docs should be available in every useful format possible, not only only and zip.

**Comment by josevalim** [comment]
I agree with @ericmj. This is a very slippery slope. We start with supporting .zip, then it becomes tar.gz and so on. I don't think we should worry about this given it is very easy to create mix (or make) tasks that will package it afterwards!

**Comment by eksperimental** [comment]
that's true
