### ISSUE TITLE
Search thinks there are ids for <h4>

### ISSUE THREAD

**Issue by garazdawi** [elixir-lang/ex_doc#1875]
If I do [this](https://erlang.org/documentation/doc-15.0-rc1/erts-14.3/doc/html/search.html?q=binary_to_term%20warning) or [this](https://hexdocs.pm/elixir/search.html?q=You%20must%20use%20this%20function%20to%20read%20only%20your%20own%20application) query, the first result is a link with a broken anchor. Not sure if it the fact that it is a `<h4>` or an `<h4>` within a `<blockquote>` that makes it not work.

In addition, maybe the search title should have the markdown things removed?

**Comment by whatyouhide** [comment]
Nugget of context: `h4` within `blockquote` is also quite common since that's how you mostly write admonition blocks in ExDoc.

**Comment by wojtekmach** [comment]
Thank you for the report. Fixed on main!

**Comment by wojtekmach** [comment]
Regarding removing markdown, this was just unfortunate that admonition blocks like `#### {: .error} ...` were turned into search sections due to regexp bug. I think we should be good now but let us know otherwise. Thanks again!
