### ISSUE TITLE
Question concerning usage of EarmarkParser

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#1889]
I would like to implement **only** the options you specify [here](https://github.com/elixir-lang/ex_doc/blob/0e076ca5ec4d59da2698264beeb12ed97b2c21e1/lib/ex_doc/markdown/earmark.ex#L26) in version 1.5 and plan to deprecate different values/options in the next patch release.

Woud this be ok with you. If not can you please be specific which options you would want to keep?

Thank you in advance

**Comment by RobertDober** [comment]
IANM `opts` could go away, but I did not really scrutenize the code thorougly enough :blush:

**Comment by josevalim** [comment]
Those options look great to me. :)

**Comment by RobertDober** [comment]
Great news, thanx, can I close this or would you need it open as a reference?

**Comment by josevalim** [comment]
We can close!
