### ISSUE TITLE
Use External link icon for External links

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#189]
It's a bit confusing when you link to an external site if that's part of the documentation, or it will take you somewhere.

Same concept as in Wikipedia.
We could actually use the same icon:
http://en.wikipedia.org/wiki/Help:External_link_icons

**Comment by josevalim** [comment]
:+1:

**Comment by milmazz** [comment]
@eksperimental Are you working on this? If you need some help just let me know.

**Comment by eksperimental** [comment]
@milmazz feel free to go ahead with it
