### ISSUE TITLE
Version dropdown doesn't work in v0.32.0

### ISSUE THREAD

**Issue by rbino** [elixir-lang/ex_doc#1893]
When generating docs using the latest `ex_doc` release, the version dropdown does not allow to choose another version (it just shows the version without allowing to choose another one)

**Comment by zachdaniel** [comment]
I think we've only reproduced it with a `.rc` release. I don't *think* that is related, but figured I should mention it. https://hexdocs.pm/ash/3.0.0-rc.19/get-started.html
