### ISSUE TITLE
Empty source AST

### ISSUE THREAD

**Issue by williamthome** [elixir-lang/ex_doc#1896]
I have failling actions on [this PR](https://github.com/zotonic/template_compiler/pull/48) by running `rebar3 ex_doc`:
```shell
===> Running ex_doc for template_compiler
===> warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell) or set the ELIXIR_ERL_OPTIONS="+fnu" environment variable
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a nonempty list

    :erlang.hd([])
    (ex_doc 0.31.2) lib/ex_doc/language/source.ex:2[19](https://github.com/zotonic/template_compiler/actions/runs/8827353833/job/24236586917?pr=48#step:8:20): ExDoc.Language.Source.find_ast/3
    (ex_doc 0.31.2) lib/ex_doc/language/erlang.ex:167: ExDoc.Language.Erlang.type_data/2
    (ex_doc 0.31.2) lib/ex_doc/retriever.ex:388: ExDoc.Retriever.get_type/5
    (ex_doc 0.31.2) lib/ex_doc/retriever.ex:378: anonymous fn/6 in ExDoc.Retriever.get_types/4
    (elixir 1.16.0) lib/enum.ex:[25](https://github.com/zotonic/template_compiler/actions/runs/8827353833/job/24236586917?pr=48#step:8:26)28: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.31.2) lib/ex_doc/retriever.ex:377: ExDoc.Retriever.get_types/4
    (ex_doc 0.31.2) lib/ex_doc/retriever.ex:155: ExDoc.Retriever.generate_node/3

===> 
make: *** [GNUmakefile:43: edoc] Error 1
Error: Process completed with exit code 2.
```

That's the line that is causing the error: https://github.com/elixir-lang/ex_doc/blob/72bb75889d0eef8df71cbf40bfd9d7bb8ed16120/lib/ex_doc/language/source.ex#L219

I did not look at why the AST it's empty or if it can be empty.

**Comment by josevalim** [comment]
Either source file was compiled with debug_info or you have entries in your docs chunk for types that do not exist. In any case, we can likely improve the error message here.

**Comment by josevalim** [comment]
I have improved the error messages on main. It may help pinpoint the root cause.

**Comment by williamthome** [comment]
@josevalim  how can I use the main version on this [rebar.config](https://github.com/zotonic/template_compiler/blob/master/rebar.config) file?

**Comment by wojtekmach** [comment]
Please try:

```erlang
{project_plugins, [{rebar3_ex_doc, {git, "git://github.com/starbelly/rebar3_ex_doc"}}]}.
```

**Comment by williamthome** [comment]
> Please try:
> 
> ```erlang
> {project_plugins, [{rebar3_ex_doc, {git, "git://github.com/starbelly/rebar3_ex_doc.git"}}]}.
> ```

Hmm I think this is related to `rebar3_ex_doc` plugin and not to `ex_doc` itself.
I found [this](https://rebar3.org/docs/configuration/configuration/#hex-repos-and-indexes) on rebar3 docs. Will try.
Thank you!

**Comment by williamthome** [comment]
I'm closing this issue because now [all checks have passed](https://github.com/zotonic/template_compiler/actions/runs/8847764965/job/24296253906).
Thanks @josevalim @wojtekmach !
