### ISSUE TITLE
Remove headings from summary (and problably other html code)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#190]
An image is better than a thousand words
![exdoc_heading_in_summary](https://cloud.githubusercontent.com/assets/9133420/6020774/834221a4-abe2-11e4-981f-4fc576df2ef3.png)

We can leave stying code, such as `<strong>`, `<em>`, `<u>`, `<a>`, but not more than that.

Is there a function for the job, or we just need to do it with Regex.replace ?

**Comment by josevalim** [comment]
The summary is meant to contain just the first paragraph. How this whole text ended up there? :D

**Comment by eksperimental** [comment]
hahaha. that is the first paragraph indeed! ;-D
Let's say someone wakes up one morning and said, I want to start my documentation with a heading.

```
  @doc """
  ## This is the heading
  ### Python sintax highlighter
  Generic syntax highlighter suitable for use in code hosting, forums, wikis or other applications that need to prettify source code
```

**Comment by josevalim** [comment]
I am unsure if we should do something... People need to follow some standard to have nice summaries. For example, keeping the first line short. So I would rather work on documenting on how to document the functions properly than try to provide different fixes. :)

**Comment by eksperimental** [comment]
I agree, but there is one case that may happen, is that people don't write any text, and just go with 
## Examples

**Comment by josevalim** [comment]
That's exactly why they should write a text. :)
