### ISSUE TITLE
Truly light theme

### ISSUE THREAD

**Issue by fififionek** [elixir-lang/ex_doc#1900]
I was referred here from Erlang OTP where I [raised this problem](https://github.com/erlang/otp/issues/8447). I am raising it, because I tried using the new documentation in Erlang OTP 27 RC3 which uses `ex_doc`. I prefer to use light themes for my reading. But for documentation it means completely light, that is every part should have dark text on light background, even the sidebar.

I noted the dark sidebar in light theme is intentional as mentioned in [other issue](https://github.com/elixir-lang/ex_doc/issues/1774).

For me, this is a big usability problem. The contrast between the almost black sidebar and the white main area makes it hard for me to read anything in the sidebar. I have to consciously mentally switch just to be able to navigate elsewhere or merely scan the list of available types/functions/etc. and then switch back to read the text.

When comparing the new OTP documentation with the old one side by side, I initially thought the new one is somehow worse. But then I compared details and realized the new one is actually slightly improved in contents and even has some nice bells and whistles. It is just the difference in theming between the sidebar and the detail contents that makes it considerably less usable to me.

If you want to keep the current Light theme as is, could you please add a third, truly light theme with light sidebar? I would much appreciate it, since it will soon be thrust upon me with the new OTP release.

(I noticed there are three themes: System, Dark and Light. I initially suggested to change the Light theme, since it seems identical to the System theme to me. I didn't realize the System theme actually automatically changes between Dark and Light depending on browser settings.)

**Comment by josevalim** [comment]
We will be glad to consider a pull request that changes the sidebar background to a light gray in Light mode.

**Comment by DavidOliver** [comment]
I'd be happy to handle this, unless you particularly want to, @fififionek ?

**Comment by fififionek** [comment]
I am willing to try, but I have no knowledge of inner workings of this project. So I will gladly leave it to you, @DavidOliver

**Comment by fififionek** [comment]
Since nothing seemed to happen, I made my own attempt, @DavidOliver . If you are working on it, I am sorry, but since the new OTP release is near, I felt I shouldn't wait any more.

**Comment by DavidOliver** [comment]
Thanks, @fififionek. Sorry I didn't get to it in the meantime. Looking forward to trying it out.
