### ISSUE TITLE
Support blockquote highlighting for GitHub Markdown

### ISSUE THREAD

**Issue by Hentioe** [elixir-lang/ex_doc#1903]
My library documentation has an extensive tutorial, which is primarily on README.md. I'm using GItHub's blockquote highlighting, but the Hex documentation doesn't display them correctly：

![image](https://github.com/elixir-lang/ex_doc/assets/13946976/c7da7110-8b85-4536-b4cb-e836ea98b985)

Here is GitHub’s rendering:

![image](https://github.com/elixir-lang/ex_doc/assets/13946976/2d9c2b72-6a0d-4b0d-8f78-538df154af27)

I noticed that more and more open source projects are starting to use GitHub's blockquote highlighting. I wonder if it is necessary for ex_doc to also support (or be compatible with)?

Related link: https://github.com/orgs/community/discussions/16925

**Comment by josevalim** [comment]
We have discussed this in the past and I have dropped comments here: https://github.com/orgs/community/discussions/16925#discussioncomment-9233534

There are two issues at the moment:

1. GitHub is still changing its syntax
2. GitHub proposal introduces english specific keywords

We don't have plans to adopt it until those are addressed. Thank you.
