### ISSUE TITLE
Add syntax highlighting for JavaScript/TypeScript

### ISSUE THREAD

**Issue by srcrip** [elixir-lang/ex_doc#1904]
Hello,

I'm working on a phoenix library that includes a JS snippet the user needs to copy into their project.

I would really like to get this syntax highlighted in ex doc. how hard would it be to add?

**Comment by josevalim** [comment]
Hi @srcrip! You can look at the `makeup` project. Perhaps makeup_json is a good starting point: https://github.com/elixir-makeup/

Although I am almost sure you can also include a JS highlighting library on your document as well and hightlight it client side!

**Comment by maartenvanvliet** [comment]
I created a 'makeup_js' package some time ago. https://github.com/maartenvanvliet/makeup_js

It's far from perfect but enough for my goals at the time.

**Comment by srcrip** [comment]
@josevalim but the highlighting won't work on the Hex Docs website then won't it?

**Comment by zachdaniel** [comment]
You can add custom js snippets using snippets: 

https://hexdocs.pm/ex_doc/readme.html#extensions

We actually use this in Ash packages for a few different things.

1. we send metrics to plausible (with the blessing of the folks at hex, I checked with them if they thought it was okay to do and they did)
2. we use it to hide the first code block in a livebook when showing in hex (to make live books w/ big setup blocks cleaner when showing output)
