### ISSUE TITLE
links for otp apps' (gen_tcp/ssl) types use old format

### ISSUE THREAD

**Issue by ruslandoga** [elixir-lang/ex_doc#1907]
:wave:

Docs for a type like
```elixir
@type socket :: :gen_tcp.socket() | :ssl.sslsocket()
```
generate incorrect links to the new Erlang docs.

Generated:
- https://www.erlang.org/doc/apps/kernel/gen_tcp.html#type-socket
- https://www.erlang.org/doc/apps/ssl/ssl.html#type-sslsocket

Should be:
- https://www.erlang.org/doc/apps/kernel/gen_tcp.html#t:socket/0
- https://www.erlang.org/doc/apps/ssl/ssl.html#t:sslsocket/0

Example: https://hexdocs.pm/mua/Mua.html#t:socket/0

Mua's ExDoc is at v0.33.0: https://github.com/ruslandoga/mua/blob/73122aef37ce098e125c5e921e100bcdf61d19ef/mix.lock#L6

**Comment by josevalim** [comment]
YEs, we need to update to the new docs. Can you please send a PR? I think it is now much more standardized, so it should be a matter of sharing code with the existing ExDoc logic but just change the URL.

**Comment by ruslandoga** [comment]
👋 @josevalim 

Sure, I will!

**Comment by ruslandoga** [comment]
PR: https://github.com/elixir-lang/ex_doc/pull/1908

**Comment by josevalim** [comment]
Closing in favor of the PR.
