### ISSUE TITLE
Warn about docs for out-of-date versions

### ISSUE THREAD

**Issue by pdavies** [elixir-lang/ex_doc#1917]
Hi, as a relative newcomer to Elixir, I've been caught out several times by looking at outdated documentation without realising that it was for an old version of the language or a library. This is particularly easy to do because of Google's tendency to return old versions at the top of results:

<img width="675" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/1106188/b50a984d-dd70-4924-a67d-60157197a7a6">

<img width="656" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/1106188/280448c8-5a2a-443e-9d80-324a78820fca">

HTML docs built with exdoc could warn when viewing old versions, but they do not, and this seems like a shortcoming worth fixing. There is plenty of precedence for warnings like this in versioned HTML docs:

It is built into docs.rs:

<img width="412" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/1106188/3fecfefc-4269-469c-be11-66bba47fea7c">

And is a fairly common sight elsewhere:

<img width="483" alt="image" src="https://github.com/elixir-lang/ex_doc/assets/1106188/d01b317a-3079-47dc-bef0-bbe1c2ef1f2f">

I'll raise a PR! 🙂

**Comment by josevalim** [comment]
Closing in favor of the PR!
