### ISSUE TITLE
Signs in integer literals trigger warning

### ISSUE THREAD

**Issue by ecpeterson** [elixir-lang/ex_doc#1931]
Typing a function like

```erlang
-spec f(LimitedInteger :: +1 | -1) -> any().
```

results in a few different ex_doc warnings, depending on what else appears in the signature, e.g., `internal inconsistency` or `spec references type "+/1" but it is undefined or private`.

**Comment by josevalim** [comment]
Which version are you using? I believe this has been fixed in main/latest.

**Comment by josevalim** [comment]
I have pushed your example above to our test suite and it did not emit any warning. However, autolink got disabled in the presence of `+integer`, so that has been fixed. Given Lukas fixed the internal inconsistency errors earlier on, I believe this is handled in main. :) Thanks!
