### ISSUE TITLE
No information on how to run locally

### ISSUE THREAD

**Issue by harrisi** [elixir-lang/ex_doc#1936]
I'm working on a fix (#1935), and I was surprised there's no documentation for how to run the project locally. It seems the only information is for building the project but not running a local server for testing.

**Comment by harrisi** [comment]
I realize ex_doc doesn't actually serve anything, but it seems like for testing it could generate docs for `../elixir` for example.

**Comment by josevalim** [comment]
Steps here: https://github.com/elixir-lang/ex_doc?tab=readme-ov-file#contributing

Run `mix build` and open up the generated HTML file directly in your browser.
