### ISSUE TITLE
Sidebar missing until mermaidjs finishes loading

### ISSUE THREAD

**Issue by vlad-ngn** [elixir-lang/ex_doc#1941]
Hi!

Previous discussion: https://github.com/erlang/erlang-org/issues/150 

Screenshot 1:
Sidebar missing, mermaidjs loading

![Screenshot from 2024-08-12 18-28-14](https://github.com/user-attachments/assets/6438d0d7-7738-4b28-bbae-e4319ea759d5)

Screenshot 2:
Sidebar appeared after mermaidjs loaded

![Screenshot from 2024-08-12 18-28-45](https://github.com/user-attachments/assets/1ce24e94-a040-40ef-a412-672784bc4d67)

This is a problem for me, because mermaidjs takes ~ 1 minute to load.

Browser:
Google Chrome
Version 126.0.6478.126 (Official Build) (64-bit)

@Benjamin-Philip

**Comment by voughtdq** [comment]
Not a browser expert, but I think the problem here might be that because `html.js` is loaded async, but mermaid isn't, the sidebar loads after mermaid.

Maybe changing the mermaid script to async will fix it 🤔

**Comment by josevalim** [comment]
Thank you @voughtdq! Can you also please send a PR updating the examples here? https://github.com/elixir-lang/ex_doc?tab=readme-ov-file#extensions

**Comment by Benjamin-Philip** [comment]
I'll patch the Erlang docs.
