### ISSUE TITLE
Incorrect line-height of a code block in a header

### ISSUE THREAD

**Issue by sobolevn** [elixir-lang/ex_doc#1946]
Demo:
<img width="242" alt="Снимок экрана 2024-08-30 в 09 56 54" src="https://github.com/user-attachments/assets/f9917f5b-44ef-489c-ae57-3790cd7840cd">

Full page on FireFox:
<img width="1352" alt="Снимок экрана 2024-08-30 в 10 24 07" src="https://github.com/user-attachments/assets/12e2099f-cb66-46a6-a9db-7e08ba20a293">

Full page on Chrome:
<img width="1352" alt="Снимок экрана 2024-08-30 в 10 05 13" src="https://github.com/user-attachments/assets/15fff930-f9a4-48e8-a113-c1d5c6ec1da2">

Link:
https://hexdocs.pm/elixir/1.13/typespecs.html#the-string-type

It is created from https://github.com/elixir-lang/elixir/blob/e1b265ab5f3d24504d15f96b25d2d88494a3eaba/lib/elixir/pages/references/typespecs.md#the-string-type

---

Browser info: not related.

---

Ideas on how to fix:
1. Notice that for some reason this header is also a link for some reason

```html
<h2 id="the-string-type" class="section-heading">
  <a href="#the-string-type" class="no-underline">
    <i class="ri-link-m" aria-hidden="true"></i>
    The <code class="inline">string()</code> type
  </a>
</h2>
```

Other headers without `code` elements are not highlighted as links.
Is that correct?

2. We can try to just reset the `line-height`

**Comment by voughtdq** [comment]
That is from an old version of ExDox and the Elixir docs. I'm not sure where it got resolved, but if you go to the [latest version](https://hexdocs.pm/elixir/1.17.2/typespecs.html#the-string-type), it looks like it has been fixed.

**Comment by sobolevn** [comment]
Yes, thanks!

**Comment by josevalim** [comment]
Thank you @voughtdq for the help on the issue (and all other PRs!)
