### ISSUE TITLE
Searching for atoms only works if the colon is included in the query

### ISSUE THREAD

**Issue by lardcanoe** [elixir-lang/ex_doc#1948]
Go to https://hexdocs.pm/phoenix_live_view and search for `temporary_assigns` and it finds no results. If you instead search for `:temporary_assigns` you get results. I knew that atom was there so I had the thought to put the colon in, but if you don't know then you might just assume it really isn't in the docs.

https://hexdocs.pm/phoenix_live_view/search.html?q=temporary_assigns
vs
https://hexdocs.pm/phoenix_live_view/search.html?q=%3Atemporary_assigns

**Comment by josevalim** [comment]
Fixed by #1960.
