### ISSUE TITLE
auto-generated links for exception/1 need love

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/ex_doc#195]
It appears that the documentation for exception/1 and message/1 in the Exceptions documentation (eg, ArgumentError) ie auto-generated. In any event, the results look like:

  Callback implementation of Exception.exception/1.
  Callback implementation of Exception.message/1.

I think that "of" should be changed to "for".  More critically, shouldn't "Exception.exception/1" be changed to "Exception.exception?/1" and be a link?

**Comment by eksperimental** [comment]
links?

**Comment by RichMorin** [comment]
I'm referring to the generated HTML links in the online documentation.  Exception.message/1 shows up as a link, but Exception.exception/1 does not. Does that answer your question?

**Comment by eksperimental** [comment]
sorry, I was asking for the URLs to see what you are talking about.

**Comment by eksperimental** [comment]
anyway, i found it: http://elixir-lang.org/docs/stable/elixir/#!ArgumentError.html

**Comment by josevalim** [comment]
Ah, we should point to the callback link and not the Exception.message/1 link.

**Comment by josevalim** [comment]
There is currently a bug in Elixir so this will be fixed in master in a day or two (when the build tool kicks in) but the old docs will remain wrong. :) Thanks for reporting!
