### ISSUE TITLE
Copy buttons on code snippets not working if they are inside a <!-- tabs-open --> ... <!-- tabs-close -->

### ISSUE THREAD

**Issue by albinkc** [elixir-lang/ex_doc#1955]
The event listener defined in `assets/js/copy-button.js` is not being registered to the copy button if the button is inside of a "tablist" class

As an example, try clicking on the copy button on any snippet within a tab at https://hexdocs.pm/ex_doc/readme.html

Tested on Chrome and Firefox

**Comment by josevalim** [comment]
Hi @DavidOliver, if there is any chance you can look at this, it would be very appreciated. No worries if you cannot. :)

**Comment by DavidOliver** [comment]
@josevalim, yep, I was going to take a look. Hopefully it'll just be a case of re-ordering the JS.

**Comment by harrisi** [comment]
I'm not exactly sure why, but delaying adding the event listener by wrapping it in `setTimeout` or `queueMicrotask` seems to fix it. I don't think it's an ideal solution, but it might give someone with more awareness of the issue a hint as to what's wrong.

**Comment by DavidOliver** [comment]
@harrisi, thanks - I think it's because, currently, the copy button events are added before the tabset HTML has been formed. Running initTabsets() before initTabsets() does seem to fix.

Apologies for missing this when adding the tabsets. PR coming soon.
