### ISSUE TITLE
ExDoc should strip off underscore prefix from arguments in type signature

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#1970]
Same as with function and macro definition, ExDoc should strip off the underscore prefix from arguments in types.

Here's the example for `t:Enumerable:t/1` defined as `@type t(_element) :: t()`.

This is the output:
<img width="930" alt="image" src="https://github.com/user-attachments/assets/95d8d90b-9259-47be-abb9-6619696732d8">

**Comment by josevalim** [comment]
In this case, we should keep it, precisely because it carries the information mentioned in the docs: the type variable is not used anywhere.

The reason why we remove it for functions and macros is because they are _inferred_. But here it was an explicit choice.

Thank you!
