### ISSUE TITLE
custom sigils in doctests highlight inconsistently

### ISSUE THREAD

**Issue by jvantuyl** [elixir-lang/ex_doc#1977]
Most sigils are highlighted such that the tilde and the letter themselves with the same color.  As of Elixir 1.15, multi-character sigils are supported in the language.  `ex_doc` seems to not understand the multi-letter syntax in `iex` blocks.

Obligatory screenshot...
![image](https://github.com/user-attachments/assets/b9a357ce-cf34-437d-a81f-1ac1fde717c6)

Here's the HTML which also clearly shows the `err` class on the  span surrounding the tilde itself...
![image](https://github.com/user-attachments/assets/21388e57-8873-4534-bb86-ee68540e692d)

The above screenshot was generated with `ex_doc` version 0.35.1.

**Comment by josevalim** [comment]
Does it work after `mix deps.update makeup_elixir`?

**Comment by josevalim** [comment]
It won't work, I will push a fix there.

**Comment by josevalim** [comment]
It should work after `mix deps.update makeup_elixir`.
