### ISSUE TITLE
Render GitHub's WARNING, NOTE, etc. notes

### ISSUE THREAD

**Issue by ruslandoga** [elixir-lang/ex_doc#1979]
👋 

I wonder if it would make sense for ExDoc to format notes with `[!WARNING]` etc. similar to GitHub in Markdown files like README.md. Right now it doesn't seem to work out of the box: https://hexdocs.pm/bamboo_mua/readme.html

# Expected

https://hexdocs.pm/bamboo_mua/readme.html renders

> [!WARNING]
> Please consider switching to [Swoosh.Adapters.Mua](https://hexdocs.pm/swoosh/Swoosh.Adapters.Mua.html)

# Actual

https://hexdocs.pm/bamboo_mua/readme.html renders

> [!WARNING] Please consider switching to [Swoosh.Adapters.Mua](https://hexdocs.pm/swoosh/Swoosh.Adapters.Mua.html)

**Comment by josevalim** [comment]
This has been opened a couple times, here is an example: #1903

I wrote a comment in the GitHub thread with my concerns about their proposed syntax as well. No plans at moment to adopt a GitHub specific notation which I don't believe adhere to the principles of Markdown. :)

**Comment by whatyouhide** [comment]
Also https://github.com/elixir-lang/ex_doc/issues/1821, for reference.
