### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#198]
Add elixir favicon.ico as the default icon.
and 
`<link rel="shortcut icon" href="/favicon.ico" />`
to the header

So we can validate these files, with html-proofer

**Comment by eksperimental** [comment]
oops. i though I was posting it in my repository, anyway, I will take care of this

**Comment by ericmj** [comment]
I'm not sure about this, at the very least it should be configurable. The link to the favicon also needs to be relative instead of pointing at root.

> So we can validate these files, with html-proofer

What does favicon have to do with HTML validity?

**Comment by eksperimental** [comment]
Well, it is not HTML VALIDITY per se, but the html-proofer has an option to check for missing favicon icon.
Favicon its automatically requested by all browsers so it speeds up the loading of pages to have it, and saves the server's error log a 404 entry.

yeah, i meant `href="favicon.ico"`, ExDoc documentation is flat anyway.
I' m thinking we should use elixir's favicon when none is provided, the question is..
where in the mix project should we place stuff like this.
Maybe create a new folder called "media", where we can place files like this, and other files like css in case we want to enable to user to change the style of the documentation.

what do you guys think?
