### ISSUE TITLE
""" quoted string in doctest isn't handled properly

### ISSUE THREAD

**Issue by c4710n** [elixir-lang/ex_doc#1981]
<img width="862" alt="Screenshot 2024-12-16 at 11 20 31 PM" src="https://github.com/user-attachments/assets/dc21ce82-38d6-446e-8134-ae68b645fa8e" />

As we can see, the value of `:description` isn't handled properly.

**Comment by josevalim** [comment]
Can you please report the issue here? https://github.com/elixir-makeup/makeup_elixir

Thank you!

**Comment by c4710n** [comment]
> Can you please report the issue here?

No problem. Done.

**Comment by josevalim** [comment]
Closed in favor of upstream, thank you.
