### ISSUE TITLE
Use something like pjax for hosted docs

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#1982]
Today we perform full page navigation but we can use something like pjax for navigating across pages as long as they have relative paths. However, we need to be careful to not use pjax when running from the local file system. Note we don't need to use pjax per se, just something similar, to keep the navigation smoother.

**Comment by josevalim** [comment]
@jonatanklosko great idea, it feels really smooth. PR here: https://github.com/elixir-lang/ex_doc/issues/1982

**Comment by jonatanklosko** [comment]
I've just realised that `@view-transition` is also going to animate `#anchor` links, which we definitely don't want :<

**Comment by josevalim** [comment]
@jonatanklosko we can rule out anchors to the same page. I will change it accordingly.

**Comment by josevalim** [comment]
Unfortunately the view transition won’t work as expected. We should probably use something https://github.com/swup/swup instead, which seems to handle all concerns for us, including same page navigation.

**Comment by josevalim** [comment]
Now closed in favor of #1986.
