### ISSUE TITLE
Automatic links generated with incorrect version part

### ISSUE THREAD

**Issue by harrisi** [elixir-lang/ex_doc#1988]
I'm not sure why this is happening, or where the issue is coming from. I can't tell if this should be here in `ex_doc`, or `elixir`, or what. Hopefully this is close enough :)

Here's the behavior:

Go to [Doctests, patterns, and `with`](https://hexdocs.pm/elixir/docs-tests-and-with.html#doctests), the link for `mix help` points to https://hexdocs.pm/mix/v1.18/Mix.Tasks.Help.html (note the `v`), whereas it should either be https://hexdocs.pm/mix/1.18/Mix.Tasks.Help.html or https://hexdocs.pm/mix/Mix.Tasks.Help.html. [Further down, just above `with`](https://hexdocs.pm/elixir/docs-tests-and-with.html#with), you can see a link for `[ExUnit.DocTest](https://hexdocs.pm/ex_unit/v1.18/ExUnit.DocTest.html)`, which should be https://hexdocs.pm/ex_unit/1.18/ExUnit.DocTest.html or https://hexdocs.pm/ex_unit/ExUnit.DocTest.html.

This seems to be introduced in the 1.18.0-rc.0 docs.

**Comment by wojtekmach** [comment]
Thank you for the report.

This is an Elixir docs bug, not ExDoc one.

@josevalim I noticed that Elixir v1.18.0 was built with `CANONICAL=v1.18/` and I think there should have been no `v`:

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/299de9bb-13c3-43d0-8a88-6763990217fd" />

(https://github.com/elixir-lang/elixir/actions/runs/12417826084/job/34669641427)

**Comment by josevalim** [comment]
Yes, this has been fixed in the v1.18 branch and will be fully addressed in a new release, thank you for the report!
