### ISSUE TITLE
Do not link to the current page

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#200]
Take [HasDict](http://elixir-lang.org/docs/stable/elixir/HashDict.html) as an example:

**HashDict** is mentioned three times in the introduction, and every time it is linking to the very same current page.

Well, this applies to every Module page because the first word is a link to the module itself. This first word I think should be bold, and the rest of the links maybe italics.

Maybe after introduction, if we want to keep the links to the same page, it should be replaced with an internal link to the top of the page, so no new page is reloaded.

I would like to hear your opinions,
thanks

**Comment by josevalim** [comment]
I am ok with not linking to itself and replacing it by bold while generating ExDoc. /cc @ericmj @alco

**Comment by ericmj** [comment]
We could also just keep it in the <code> formatting.

**Comment by josevalim** [comment]
Good point.  Let's just keep it in the formatting and skip the link.

**Comment by eksperimental** [comment]
what about from summary downwards, do we link to the top of the page? or we remove the link?

**Comment by eksperimental** [comment]
I think we should link internally to the top of the page.
