### ISSUE TITLE
Fix inline code that is a link

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#201]
You won't be able to see this online here http://elixir-lang.org/docs/master/elixir/Regex.html#run/3
but if you generate the docs with master, you will see it,

```md
Check the moduledoc for `Regex`
```

will produce

```html
Check the moduledoc for <a href="Regex.html"><code class="inline">Regex</code></a>
```

but i have created a style that was missing before formatting inline code in a previous commit,
but now we are not seeing the link, because the color gets overriden by .line

this is how it looks like, notice `Regex` is a link,
![inline_code_link](https://cloud.githubusercontent.com/assets/9133420/6523641/414c6548-c424-11e4-876d-872c4c736dc9.png)
http://elixir-lang.org/docs/master/elixir/Regex.html#run/3

I think we should have `<a>` inside `<code>`,  but still not sure if this is the style we want. because blue link in red box looks awful.
Maybe different border and background color (blueish) ?

**Comment by josevalim** [comment]
Have you reloaded the page? I am seeing this:

![screen shot 2015-03-06 at 11 29 13](https://cloud.githubusercontent.com/assets/9582/6523861/12125e70-c3f4-11e4-9b1f-eee3b66c2d6b.png)

I have removed the border for inline code from docs because it was too distracting and consequently fixed this bug. :)

**Comment by eksperimental** [comment]
oops. I forgot to pull from master,
I was waing to mention it actually, if we should change the style,
but i think we DO need a style, 
something like github does, no border, grey background. something `like this`. What you think?

**Comment by josevalim** [comment]
Nah, it is fine to leave it as is. It works fine and doesn't distract much.
