### ISSUE TITLE
Missing the 0.7.2 tag?

### ISSUE THREAD

**Issue by rranelli** [elixir-lang/ex_doc#205]
I've noticed in the git log that there is a commit `Release v0.7.2` but no `0.7.2` tag. 

![screenshot from 2015-03-21 23 10 23](https://cloud.githubusercontent.com/assets/4231743/6767712/a772cf04-d01f-11e4-81d6-8736bf400888.png)

Is this intentional ?

Ty

**Comment by josevalim** [comment]
Oops, good catch! fixed, thank you!

**Comment by rranelli** [comment]
Happy to help :)
