### ISSUE TITLE
import @spec from callback functions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#206]
`@spec` from the callback function should be imported from the `use`d module, if they are not set in the current module.
 
For example
[`Map.equal?/2`](http://elixir-lang.org/docs/master/elixir/Map.html#equal?/2) is a callback of [`Dict.equal?/2`](http://elixir-lang.org/docs/master/elixir/Dict.html#c:equal?/2),
but the specs are not avaible in `Map`

**Comment by eksperimental** [comment]
Well, now that I see the whole `@doc` could be imported.
Is there a decision behind for not importing it, or it just hasn't been implemented yet?

**Comment by josevalim** [comment]
@eksperimental we could import the specs in exdoc but i wouldn't import the docs, i would just keep a link as today. The reason for this is that the docs are often written in abstract way that often doesn't make sense in the implementation code.

**Comment by josevalim** [comment]
I am closing this one. First of all, callbacks may still specify their types in case they expose a larger or a more restrict API. Second of all, implementing this would require rewriting all of the local types in the specs, which will add unnecessary complexity. That said I would rather focus on other features and functionality than this one.

**Comment by eksperimental** [comment]
should we add a similar TAG as in Elixir: `Unresolved` ?
Just in case we want to tackle it in the future

**Comment by josevalim** [comment]
Done.

**Comment by josevalim** [comment]
It has all of the issues above. A callback may refer to a local type defined in the same module as the callback. So we would need to rewrite and said rewrite would still be broken for private types.
