### ISSUE TITLE
Issue with example code containing {:

### ISSUE THREAD

**Issue by slogsdon** [elixir-lang/ex_doc#207]
Hi all,

I'm running into an issue with rendering documentation of a module that contains `{:ok, term}`. Earmark (not sure if this affect other parsers) interprets the `{:` as the start of an HTML attribute for the previous block and raises a `(Earmark.HtmlRenderer.EarmarkError) Invalid Markdown attributes: {ok, [1, 2, 3]}`.

I have no idea if this is truly caused by ExDoc or if Earmark is incorrectly matching that sentinel in code blocks, but the issue doesn't seem to occur normally. If needed, I can forward my issue to the Earmark repo.

###### Context

I'm attempting to generate the docs for the dependencies of a project for offline viewing to easily reference when an Internet connection isn't available and you don't feel like diving into the `deps` directory to look at the source. I made a first pass (https://gist.github.com/slogsdon/a8fbe06de04d414e004e) but would love to clean up the delivery if I can get around this issue.

I'm testing this in a project with Poison, and it seems to fail on [this line](https://github.com/devinus/poison/blob/master/lib/poison.ex#L10). When running `mix docs` for Poison on its own, the exception isn't raised.

Thanks in advance!

**Comment by josevalim** [comment]
Which ex_doc and earmark versions? Have you tried calling earmark directly
 with the faulty string and isolate the bug?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by slogsdon** [comment]
This happens with slightly older versions of Earmark and ExDoc as well, but I'm currently using the latest versions available from Hex. From my mix.lock file:

- `"earmark": {:hex, :earmark, "0.1.15"}`
- `"ex_doc": {:hex, :ex_doc, "0.7.2"}`

Looks like it has something to do with the code samples not being indented properly:

```elixir
iex(2)> Earmark.to_html "#hello\n{:ok, [1,2,3]}"
** (EXIT from #PID<0.146.0>) an exception was raised:
    ** (Earmark.HtmlRenderer.EarmarkError) Invalid Markdown attributes: {ok, [1,2,3]}
        lib/earmark/html_renderer.ex:232: Earmark.HtmlRenderer.expand/2
        lib/earmark/html_renderer.ex:197: Earmark.HtmlRenderer.add_attrs/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

Interactive Elixir (1.0.3) - press Ctrl+C to exit (type h() ENTER for help)

09:37:36.232 [error] Task #PID<0.151.0> started from #PID<0.146.0> terminating
Function: #Function<2.81883626/0 in Earmark.pmap/2>
    Args: []
** (exit) an exception was raised:
    ** (Earmark.HtmlRenderer.EarmarkError) Invalid Markdown attributes: {ok, [1,2,3]}
        lib/earmark/html_renderer.ex:232: Earmark.HtmlRenderer.expand/2
        lib/earmark/html_renderer.ex:197: Earmark.HtmlRenderer.add_attrs/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
iex(1)> Earmark.to_html "#hello\n    {:ok, [1,2,3]}"
"<p>#hello</p>\n<pre><code>{:ok, [1,2,3]}</code></pre>\n"
```

Easy fix would be to simply fix the documentation in Poison as Earmark seems to be interpreting the markdown as intended.

It's strange that this issue happens in this situation, but if I clone the Poison repo and run `mix docs` from the root of the project, there are no errors, even with both using the same versions of Earmark and ExDoc.

**Comment by josevalim** [comment]
Yeah, so it is definitely an Earmark bug? Can you please report it there?
If you can include a way to reproduce it directly, even better!



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by ericmj** [comment]
It's a known issue: https://github.com/pragdave/earmark/issues/12

**Comment by slogsdon** [comment]
Thanks guys. Looks like I'll just catch the exception when it's raised and alert the user.
