### ISSUE TITLE
Escaping escaped HTML in output

### ISSUE THREAD

**Issue by lstor** [elixir-lang/ex_doc#210]
Escaped HTML in example output is incorrectly rendered. See [Phoenix.HTML](http://hexdocs.pm/phoenix/Phoenix.HTML.html).

For example, for `safe_concat/2`, the [source heredoc is](https://github.com/phoenixframework/phoenix/blob/9e94594e256df472ca660034261129e5161965ca/lib/phoenix/html.ex#L126):

- - -
![image](https://cloud.githubusercontent.com/assets/613821/7526282/920f3556-f510-11e4-967c-4ab989b37163.png)
- - -

...which, confusingly, [is rendered as](http://hexdocs.pm/phoenix/Phoenix.HTML.html#safe_concat/2):

- - -
![image](https://cloud.githubusercontent.com/assets/613821/7526291/a56ce788-f510-11e4-9775-dbe673166ab2.png)
- - -

/cc @chrismccord

**Comment by milmazz** [comment]
This issue was resolved in the `Earmark` parser in its version *0.1.16* and the current master depends on *0.1.17* or *2.0*.

**Comment by lstor** [comment]
Damn, @josevalim, you're fast.
