### ISSUE TITLE
function `pretty_codeblock` leaves an end tag for `code` element which is not open

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#214]
The current [`pretty_codeblock`](https://github.com/elixir-lang/ex_doc/blob/7c7365c18f3763482695bf3440fd2c10baa7bc7f/lib/ex_doc/formatter/html.ex#L80) function in `html.ex` generates invalid HTML code, this function leaves an end tag for the `code` element which is not open.

```elixir
iex> bin = "<pre><code>Hello world</code></pre><pre><code class=\"\">Hello world</code></pre>"
"<pre><code>Hello world</code></pre><pre><code class=\"\">Hello world</code></pre>"
iex> Regex.replace(~r/<pre><code\s*(class=\"\")?>/, bin, "<pre class=\"codeblock\">")
"<pre class=\"codeblock\">Hello world</code></pre><pre class=\"codeblock\">Hello world</code></pre>"
```

One way to solve this is updating the *regex*:

```elixir
iex> Regex.replace(~r/<pre><code\s*(class=\"\")?>(.+?)<\/code><\/pre>/, bin, "<pre class=\"codeblock\">\\2</pre>")
"<pre class=\"codeblock\">Hello world</pre><pre class=\"codeblock\">Hello world</pre>"
```

But, if we look further, right now there is no rule for the `.codeblock` CSS class. So, I suggest to delete this `pretty_codeblock` and try to control the look of the `<pre>` and `<code>` tags in the CSS files, because there is where the rules that are in control of the style of HTML blocks belongs.

But, I really want to know your opinion about this matter before I propose a Pull Request.

**Comment by milmazz** [comment]
Hello @tonini, I really want to know your opinion about this issue. Do you remember the [`pretty_codeblock`](https://github.com/elixir-lang/ex_doc/commit/7c7365c18f3763482695bf3440fd2c10baa7bc7f#diff-fc9775865b82e656523d7cbbe16526d2) function purpose?

**Comment by josevalim** [comment]
@milmazz the idea about `pretty_codeblocks` is that "\`\`\`" by defaults adds `<code class="">` and that is not going to be formatted as Elixir. Now that we are enabling "\`\`\`" everywhere, we should fix it by somehow setting the default language for such code blocks to Elixir (it can be with a regex) or by changing highlight.js to use elixir by default when another language was not specified.

Does it make sense?

**Comment by milmazz** [comment]
@josevalim Got it!, I'll try to work on this.

**Comment by milmazz** [comment]
This comment is just a reference of the different outputs per Markdown parser.

<pre><code>
$ cat ~/test/demo.md
line 1
```elixir
iex> max(4, 5)
5
```

line 2
```
iex> max(4, 5)
5
</code></pre>

Output with `earmark ~/test/demo.md`:

```html
<p>line 1</p>
<pre><code class="elixir">iex&gt; max(4, 5)
5</code></pre>
<p>line 2</p>
<pre><code class="">iex&gt; max(4, 5)
5</code></pre>
```

Output with `pandoc -f markdown+fenced_code_blocks -t html ~/test/demo.md`:

```html
<p>line 1</p>
<pre class="elixir"><code>iex&gt; max(4, 5)
5
</code></pre>
<p>line 2</p>
<pre><code>iex&gt; max(4, 5)
5</code></pre>
```

Output with `hoedown --html --fenced-code ~/test/demo.md`:

```html
<p>line 1</p>

<pre><code class="language-elixir">iex&gt; max(4, 5)
5

</code></pre>

<p>line 2</p>

<pre><code>iex&gt; max(4, 5)
5
</code></pre>
```

/me Take this into account when working on the PR :point_left:

**Comment by milmazz** [comment]
This issue was resolve with #217 :+1:
