### ISSUE TITLE
Themes support

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#218]
One improvement that I want to see in `ExDoc` is theme support. So, I've been thinking that after we can resolve the issue #175 and define the default structure for a theme, I can start working on a proposal for themes support in `ExDoc`.

The initial idea is to add a new entry in the Config struct and from there we can select the theme that the user wants, for example, we can provide 2 themes at the beginning:

* `ex_doc/formatter/html/templates/default/*.eex` (the current theme without frames)
* `ex_doc/formatter/html/templates/modern/*.eex` (e.g. theme proposed on #150)

In this case, if the `modern` theme doesn't provide a template we can always fallback to the `default` theme.

I think that one problem with this approach is that the specific theme directory can grow a lot (assets: fonts, images, etc.) and even we can store duplicate files which is a waste of space.

So, I prefer a hybrid approach like [Sphinx](http://sphinx-doc.org/theming.html) does, for example, suppose that `ExDoc` provides only two themes:

* `ex_doc/formatter/html/templates/default/*.eex` (the current theme without frames)
* `ex_doc/formatter/html/templates/modern/*.eex` (e.g. the theme proposed on #150)

If somebody wants a custom theme, they can create a new `Elixir` project and `ExDoc` can *call* or *retrieve* this custom theme via configuration. Something like [sphinx_rtd_theme](https://github.com/snide/sphinx_rtd_theme) for Sphinx.

@josevalim @ericmj Is this hybrid approach possible? How can I accomplish something like this? any suggestion is more than welcome.

**Comment by josevalim** [comment]
@milmazz my biggest trouble with supporting custom themes is that all of ExDoc internals now become public. And today the internals are very specific to the current templates.

For example, a lot of today's code is about gathering all information upfront and then calling the templates. If we need to change the template... we need to change how the information is gathered. So the flow is: gather all information -> invoke template.

However, I think a proper API for ExDoc would be to provide a way to query all this information. So the flow would be: invoke template -> template asks for information it needs. So theme support in my opinion would require a full rewrite of ExDoc. Everything is just too coupled today. :(

**Comment by milmazz** [comment]
@josevalim let me see if I get this right, the proper workflow for you is the following: After define a particular template, the user invoke the template, then that template somehow request for information to the _backend_ (`ExDoc` is this case), and then the _backend_ will provide this information. Right?

Maybe I’m wrong, but I feel that the current workflow is OK. I see `ExDoc` as a static generator for Elixir projects, something like [Jekyll]( http://jekyllrb.com/) but instead of retrieving the information from posts, we retrieve the information from beam files, right? Jekyll uses the Liquid template language to process templates (we use EEx to embed Elixir code and with that we can build our templates, which at the end are functions). Then, we use those functions (or _templates_) in the `ExDoc.Formatter.HTML` module to finally create the HTML (or JS) files. So, for me `Jekyll` and `ExDoc` are very similar, I'm not saying that for this reason the current design for `ExDoc` is OK, but, at least for me the current workflow is very common and it's OK :+1: 

One approach to offer an initial support for themes could be the following:

* `ex_doc/formatter/html/templates/default/*.eex`
* `ex_doc/formatter/html/templates/modern/*.eex` 

And then through the `Config` struct we can control which template the user wants. Also, please keep in mind that shipping `ExDoc` with this structure could help us in the transition to a new template as default, offering a _beta_ version for early adopters.
