### ISSUE TITLE
New ExDoc version is not respecting the index page

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#221]
The index page is not always the "overview" one. For example, for elixir, the index page is meant to be "Kernel". For EEx, it is the "EEx" module itself, not overview. It seems this information is no longer respected.

This is how I am generating it:

    ex_doc/bin/ex_doc "Elixir" "1.0.5" "lib/elixir/ebin" -m "Kernel" -u "https://github.com/elixir-lang/elixir" --source-ref "67501bcddc6105afb8bc8040621e4277d46b7175" -o doc/elixir -p http://elixir-lang.org/docs.html

**Comment by josevalim** [comment]
You can access Elixir docs to see how the generated pages are meant to look like: elixir-lang.org/docs/stable/elixir/

**Comment by milmazz** [comment]
@josevalim Oh, I miss that!, I'll fix it asap. Thanks for the report.

**Comment by milmazz** [comment]
@josevalim @ericmj I think this issue can be closed. Thanks!
