### ISSUE TITLE
New ExDoc version requires double click after search

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#222]
I can reproduce this on Safari and Chrome. Steps:

1. open up index.html
2. search for "agent"
3. Click on the "Agent" link

The third step will act as if another search is being done and it won't redirect to the Agent page. The next click works though. I would expect it to work on the first click.

/cc @milmazz

**Comment by milmazz** [comment]
@josevalim I have reproduced this error, thanks for the detailed report. I'll look into this.

**Comment by milmazz** [comment]
@josevalim I've been able to reproduce this error in the stable version too, so, this means that the error was introduced in a previous version. I took as example this page: http://elixir-lang.org/docs/stable/elixir/

Anyway, I'll try to fix this, as you mentioned that kind of behaviour is not expected.
