### ISSUE TITLE
New ExDoc version is not functional on mobile

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#224]
That's because the sidebar takes all the space. @milmazz, thoughts?

**Comment by milmazz** [comment]
@josevalim I can add certain CSS media queries to solve this inconvenience.
The first thought that comes to my mind is that we can offer something like
a "hamburger button" to toggle the sidebar, do you agree in something like
this?

**Comment by Dignifiedquire** [comment]
How about using this for the navigation http://mmenu.frebsite.nl/ and setting it to be always open on desktop.

**Comment by Dignifiedquire** [comment]
Here is a demo of what I mean: http://mmenu.frebsite.nl/demo/index.html?demo=widescreen

**Comment by josevalim** [comment]
That sounds great! We don't want to take your attention away from the
redesign though. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by Dignifiedquire** [comment]
Maybe I can squeeze that in, that way we don't have to change the menu twice ;)

**Comment by milmazz** [comment]
@Dignifiedquire That plugin is really nice, please let me know if you
can/want to work on this. I have some free time in just 30 minutes, so, I
can work on this issue if you prefer to focus on the new design.

**Comment by Dignifiedquire** [comment]
Sure go ahead, probably won't have a lot of  time today myself.

**Comment by milmazz** [comment]
@Dignifiedquire @josevalim Guys, I must be honest, I prefer the current search field and its current behaviour. The search field offered by [mmenu](http://mmenu.frebsite.nl/) plugin does not substitute the current features (e.g. highlight, search find inner nodes) that we offer in the sidebar. Also, I think that `mmenu` plugin adds more complexity when the user wants to navigate through the nodes (modules, exceptions, protocols).

 Please, see the following example: http://output.jsbin.com/fojodo/2 (please click in the upper-left link)

I'll try to find another way and I'll share with you the results, from there, we can compare both solutions and take a decision. Please let me know what you think.

**Comment by josevalim** [comment]
@milmazz good points. I don't think we need to use their whole menu though. Maybe we should just copy the hamburger menu functionality?

@lucasmazza any ideas on how we could improve this? The latest versions of the docs can be found here: http://elixir-lang.org/docs/master/elixir/

**Comment by Dignifiedquire** [comment]
Yes seeing it in action, it doesn't really work on a desktop machine. I will give it some thought as I wanted to do some tweaks to the menu in my design branch anyway.

**Comment by lucasmazza** [comment]
@josevalim given the layout I think will be hard to go too far from the hamburger style menu :). If the jQuery plugin doesn't match our need, we can easily implement the toggling ourselves and preserve the current search behaviour in the sidebar. But would make sense to wait for the redesign to tackle this.

**Comment by milmazz** [comment]
>  I wanted to do some tweaks to the menu in my design branch anyway

@Dignifiedquire Yes, please. Maybe the following is obvious, but I want to be sure that you have all the required information to accomplish this task.

 * Right now all the nodes required to fill the `#full_list` unordered list are located in the `sidebar_items.js` (sidebarNodes object).  
 * The JavaScript function ` fillSidebarWithNodes` receive the object `sidebarNodes` and then apply a filter to that list and build the “#full_list” unordered list. So, If you want to improve the current structure you should modify the inner function `scope`

Also, I think that we can improve a lot the search process, how? the first step can be done applying the search on the `sidebarNodes` object instead of parsing and modifying all the DOM as we currently do.

Please let me know if you need some help.

**Comment by Dignifiedquire** [comment]
@milmazz if you want to help me the following is the underlying structure change that I would like to see.

* Get rid of the absolute positioning of the sidebar and content elements, so we get one scroll bar for the whole page
* Use an `affix`/`scrollspy` to fix the navigation and make it update on scrolling

In general have a behaviour like the navigation on this page: http://getbootstrap.com/components/ what do you think?

**Comment by milmazz** [comment]
@Dignifiedquire Please let me know if the latest changes in the PR #226 works for you.

**Comment by milmazz** [comment]
@josevalim I think this issue is already fix in master.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
