### ISSUE TITLE
Make backward compatible link to pages in frames

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#230]
We need to make this change (https://github.com/elixir-lang/ex_doc/pull/219/files#diff-6f3ff294b7369383c8be9c35ec910a9bL8) backward compatible with this feature: https://github.com/elixir-lang/ex_doc/pull/188

redirect anything liking
from: /index.html#!Module.html#function
and: /#!Module.html#function
to: /Module.html#function

as discussed in https://github.com/elixir-lang/ex_doc/pull/188#issuecomment-72649651

/cc @milmazz

**Comment by josevalim** [comment]
I know this is a breaking change but ExDoc hasn't reached 1.0 out, so we can afford to do so. :) So I wouldn't fix this, I don't think anybody is using it besides Elixir docs itself (which we are changing soon).

**Comment by eksperimental** [comment]
@josevalim sure, no worries. I just felt the need to report it since I was the one that introduced this feature ;-D
