### ISSUE TITLE
Improve how ExDoc performs with assistive technologies

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#235]
After a few tests with [tota11y](http://khan.github.io/tota11y/) (an accessibility visualization toolkit) I noticed a few things that we can improve:

- _Header hierarchy_: the *Examples* title (inside of the sub-sections: _Functions_, _Macros_, etc.) normally are marked with the `<h2>` element tag and the sub-sections title itself are also marked with the `h2` element tag.
- The `input` element (used as a search field) could be improve if we use the `<label>` element tag to describe the functionality of the search field, is not enough the `placeholder` attribute inside of the `<input>` element tag.
- In the sidebar area there are some empty links.

Some screenshots:

![headers](https://cloud.githubusercontent.com/assets/34700/8415506/cc3d6f22-1e64-11e5-886f-45b8a5b29179.png)
![links](https://cloud.githubusercontent.com/assets/34700/8415505/cc2d533a-1e64-11e5-8b4b-f93788bb16c1.png)

Please notice that if we fix this errors we can improve the experience of people who needs to use screen readers (e.g. GNOME Orca) among others.

**Comment by whatyouhide** [comment]
Great job @milmazz! :+1:

**Comment by eksperimental** [comment]
regarding the Header hierarchy, the code is valid html as well as semantically speaking. The reason behind this is that we shouldn't  rewrite code that was written in markdown.  Have a look at my issue https://github.com/elixir-lang/ex_doc/issues/163

**Comment by josevalim** [comment]
A PR for this would be welcome!

**Comment by josevalim** [comment]
@milmazz let's focus the efforts here with the new design, what do you think? If you agree, just close. If you don't, let's leave it open. :)

**Comment by milmazz** [comment]
@josevalim I agree, the new design will include a better support for assistive technologies.
