### ISSUE TITLE
Generated docs not including custom comments?

### ISSUE THREAD

**Issue by mesosteros** [elixir-lang/ex_doc#236]
I have made a few comments in modules that don't show in the generated docs.
I have written them as:
`@doc """
this is a comment
"""`
And they simply don't show. Isn't this package supposed to document all of these comments for custom documentation?

EDIT: I'm using this with a Phoenix project.

**Comment by ericmj** [comment]
Docstrings will be stored and only those associated with a function, comments will not be stored. Can you show your code?

**Comment by mesosteros** [comment]
I got it working in a new project. Really didn't do anything different. :/
