### ISSUE TITLE
↑ [to the top of the page] internal-links are not working

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#238]
even though the element with id "content" exist, it is not working.

**Comment by josevalim** [comment]
Can you please send a PR once you figure it out?

**Comment by milmazz** [comment]
Hi @eksperimental I can send a PR if you're not working on this. Just let me know. /cc @josevalim

**Comment by milmazz** [comment]
@eksperimental @josevalim This is already fix in `master`.

**Comment by eksperimental** [comment]
great @milmazz.
Sorry for the late reply, I was gone for a little while.
