### ISSUE TITLE
Invitation to the ExDoc team

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#239]
Hello @eksperimental and @milmazz,

You have both been doing a fantastic work to bring ExDoc and Elixir documentation forward so I would like to invite you to be authors and maintainers of the ExDoc project too.

Being part of the team does not change the dynamics, just continue the excellent work you have done so far. I am looking forward for what is coming!

**Comment by josevalim** [comment]
Let me know if you are ok with this and I will add you to the team on Github.  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by milmazz** [comment]
@josevalim Thank you very much for the invitation, I'm so glad that you asked me to join to the ExDoc team, I will make sure to keep having fun hacking with ExDoc and always keep in mind that the goal is to improve the user experience with the Elixir documentation in every possible way.

**Comment by josevalim** [comment]
Thank you! Invitations have been sent!

**Comment by eksperimental** [comment]
@josevalim: Thank you very much for the invitation!
You can count me in ;-D

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
