### ISSUE TITLE
master/docs should not be created from master ex_doc

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#244]
I think it is not a good idea to have the elixir documentation (master), http://elixir-lang.org/docs.html#master
 using the master version of ex_doc,
as we are still developing many times the documentation maybe not usable, I think we should always run on the latest release of ex_doc, but not on master,

Additionally i think we could add a new set of documentions, called maybe "dev"
http://elixir-lang.org/docs/dev/
http://elixir-lang.org/docs/dev/elixir/
and we can add a robot.txt to disallow indexing by the search engines.
and that we only link from this project.

What do you guys think?

**Comment by josevalim** [comment]
I disagree because a bunch of the bugs we have had reported came exactly from the master website. It is much better to test it on master than find out just later on when doing a stable release. :)

**Comment by eksperimental** [comment]
that's true @josevalim 
It's just that with the new changes coming to ex_doc things will not be working optimally, and soft of fell that it maybe be a nuisance for the elixir users who just want to use the docs.

**Comment by josevalim** [comment]
I don't think we need to worry about that because we first link to the stable docs. So if people are running on master, they must be aware that things might not be as polished. :)
