### ISSUE TITLE
Search process never ends if the module type list is empty

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#246]
This issue happens with both, the new and the old menu.

How to reproduce this issue:
- Visit [ExUnit](http://elixir-lang.org/docs/stable/ex_unit/) (stable) or [ExUnit](http://elixir-lang.org/docs/master/ex_unit/) (master) docs
- Select  _Protocols_ in the navigation area.
- Put something in the search bar.

**Result:** Search process never ends.
**Expected:** _No results were found_ message.

**Comment by eksperimental** [comment]
true! Maybe if there are no elements in the tab, it shouldn't shouldn't be a link, if it contains no items. I think having greyed out is a good option.
