### ISSUE TITLE
Menu Issues - Highlighting Selected Function

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#252]
Now that the issues have been fixed, i'm testing ex_doc

There are still a few issues regarding https://github.com/elixir-lang/ex_doc/issues/231

Lets take for example **[Task.Supervisor.children/1](http://elixir-lang.org/docs/master/elixir/Task.Supervisor.html#children/1)**

1. You cannot see where you are in the menu. I think what we need to do is to create an id for each module, and make the browser jump to it,. I have tested it in chrome, and it works, without affecting the position in the Content area. But what we need is not to update the hash in the url.

2. Now when we click on the functions, the area doesn't get highlighted, and only the module name. I like it the way it works in the previous version. Also, it should work when loading the page for a specific function, like the link above.

3. Clickable area. Now it's only the the text, where in the previous version was the whole block.
One thing to improve is that intead of having a cursor and the hand, we should have one same pointer for the whole block (this is not happening in the previous version)

**Comment by milmazz** [comment]
@eksperimental Is this issue still valid? Could you please review the current `new_design` branch?, the sidebar behaviour changed a lot!

**Comment by milmazz** [comment]
Function list in the sidebar area are not available in the new design. I think it's safe to close this issue. Please reopen @eksperimental if you want.
