### ISSUE TITLE
Release goals for v0.9

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#261]
The idea is to define our list of goals for the next release.

* [x] New design #275
* [x] Include a build system to concatenate and reduce the size of our assets. Also this build system must provide a way to check the quality of our JS code
* [x] Include some tests for JS to avoid break previous features.
* [x] Include support for LESS w/Bootstrap

@Dignifiedquire  is already working on some of this tasks, for more details please see #260

@josevalim @ericmj @eksperimental @Dignifiedquire What do you think about this? We should include or remove some tasks for the next release?

**Comment by josevalim** [comment]
I think this is great! :heart: I would move PDF/epub to another release though. A new design is already tons of work on its own. :)

**Comment by Dignifiedquire** [comment]
I agree with @josevalim pdf/epub stuff is tricky to do from my experience so we should focus on the other things first and get that released and then one release focused on new formats

**Comment by milmazz** [comment]
@josevalim I've been testing @Dignifiedquire's work in the `build_system` branch and let me say that it is impressive :+1:

For sure in near future I'll include include more tests for JS with Karma, but the all structure appears to be right, I just add a few things to the README file (below the `assets` directory). I just want to ask you when you think is the right moment to merge the `build_system` branch into `master` (I already merge the latest changes made in `master` into `build_system`). Do you prefer to do a release of the current status of `master` before the merge?

**Comment by josevalim** [comment]
I am closing this since it is all done. :D
