### ISSUE TITLE
Check the commit for non-updated dist files (when apply)

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#268]
Right now in the `build_system` branch you can find the ready to use CSS/JS versions in `lib/ex_doc/formatter/html/templates/dist`

One thing that we need to guarantee is that every time that somebody update a css/js file (located under `assets` directory), the files under the `dist` directory also gets updated.

We can try to guarantee this via a git hook (`pre-commit`)

**Comment by josevalim** [comment]
@milmazz can we do that only if the assets file change? Because remember we don't want to enforce that if people are fixing an Elixir bug.

**Comment by josevalim** [comment]
Is this still relevant? If not, please close it. :)
