### ISSUE TITLE
Index redirection is a bit annoying in practice

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#279]
/cc @eksperimental 

Now that the feature is in master, we can see it working: http://elixir-lang.org/docs.html#master

I am honestly a little annoyed by the redirection. Although we could change the redirection from Elixir, it would be hard to do it for things like hexdocs (right @ericmj?).

If that is the cost, I would prefer to duplicate pages. Another idea is to have an iframe on index that includes the other page. So we don't duplicate contents. Not sure of the practical implications though.

Thoughts?

**Comment by josevalim** [comment]
Yet another idea is to hide the redirection text (we can put it inside a noscript) and only show it with javascript about 3 seconds later. So we get a blank page (which is normal) but without all the busy text in the middle.

**Comment by Dignifiedquire** [comment]
There is a cleaner solution, simply redirect immediately without showing anything. You can see an example of this here: http://karma-runner.github.io redirects to http://karma-runner.github.io/0.13/index.html without any issues.

The source can be found here for this: https://github.com/karma-runner/karma-runner.github.com/blob/master/index.html

**Comment by eksperimental** [comment]
yes, it is very annoying indeed.
@Dignifiedquire's solution worked like a charm.
