### ISSUE TITLE
Issues in third-party libraries affecting out generated docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#283]
This issue is just to list the bugs from third-party libraries but that still affect the docs generated by ExDoc.

The idea is to give more exposure to these bugs, and also save time when looking for that weird behaviour... 

## Indented lines within Lists
- Library: [Earmark](https://github.com/pragdave/earmark/)
- Bug reported: https://github.com/pragdave/earmark/issues/27
- Code being affected: [elixir: lib/elixir/lib/file.ex](https://github.com/elixir-lang/elixir/blob/1d2f074a45a0c8945f860555c2d24df8d1110c1a/lib/elixir/lib/file.ex#L219-L225)
- Live doc: http://elixir-lang.org/docs/master/elixir/File.html#read/1

**Description:**
The problem happens when inside a list (I guess it happens with both ordered and unordered), there is a line that has been indented with 4 spaces or more, the line will be takes as codeblock,
I have checked babelmark2 and the main engines deal with this situation.

**Example:**
The second line will break split the list

```elixir
* `:eacces`  - missing permission for reading the file,
               or for searching one of the parent directories
* `:eisdir`  - the named file is a directory
```

**Comment by josevalim** [comment]
It is a bug in our docs really. We should just fix `file.ex`. Can you please send a PR there? and close this one. :)

**Comment by eksperimental** [comment]
The behaviour is a bit erratic. the list doesn't break until it finds a sixth whitespace in a raw.

https://gist.github.com/eksperimental/b8369ed6b317139218e7
![earmark_bug](https://cloud.githubusercontent.com/assets/9133420/9258291/d7889738-4224-11e5-8195-b49d69c424ac.png)

What is the format that we expect to have in the elixir files?
no spaces, just two to be in line with the text above?

**Comment by josevalim** [comment]
The proper format to use in Elixir is 2 spaces before the bullet, 4 spaces after the line break.

```
  * this is
    an example
```

**Comment by eksperimental** [comment]
we need to add 2 spaces to these values since that's the margin we leave for the all the doc, correct?

**Comment by josevalim** [comment]
We need to add two spaces because the code indent in bullet states with 8
spaces. So 2 + 2 + 4 is how the math works out for everything to be neatly
indented.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
