### ISSUE TITLE
Include a semantic template system for JS

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#284]
This is just a reminder, we need to refactor our JS code and include a minimal template system like [Handlebars ](http://handlebarsjs.com/), one of the functions that we need to improve is `fillSidebarWithNodes`, a previous discussion about this issue can be found in #278

**Comment by Dignifiedquire** [comment]
Done in `new_design`

**Comment by josevalim** [comment]
This looks all awesome. I can't wait to give it a try! :D
