### ISSUE TITLE
Having an outdated version in /doc results in test failures

### ISSUE THREAD

**Issue by Dignifiedquire** [elixir-lang/ex_doc#289]
Checkout an older version, and build the docs of ex_doc into `/doc`. Checkout the latest version and run `mix test`. Some tests will fail. After removing the `/doc` folder all tests pass.

**Comment by eksperimental** [comment]
@Dignifiedquire what version are you running. 
im getting an error when running an older version.
and what command do you use to build the old docs.?
thank you

**Comment by eksperimental** [comment]
ok, I was able to reproduce it.
you need to run `mix clean`
and then `mix test` will pass

**Comment by Dignifiedquire** [comment]
Okay, thanks. But maybe that could be done automatically? (To help newbies like myself that like to forget things like that ;) )

**Comment by josevalim** [comment]
Why what we have in /doc even matters? :S

**Comment by eksperimental** [comment]
@josevalim I thought the same, but it's not what was in /doc but what was in /tmp/ebin/

**Comment by eksperimental** [comment]
by the way, is there  a way to detect the app version used when a beam file was compiled?

**Comment by josevalim** [comment]
@eksperimental ah, there isn't much we can do in this case I think. :(

**Comment by eksperimental** [comment]
:-(
