### ISSUE TITLE
Reduce blockquote size

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#290]
Search for "Note:" here:

http://hexdocs.pm/ecto/0.16.0/Ecto.html

It seems to be caused by bootstrap defaults?

**Comment by Dignifiedquire** [comment]
Does this need to be fixed in master or is it enough in new_design

**Comment by josevalim** [comment]
No need to rush. If @eksperimental or @milmazz can fix it in master, even better.

**Comment by eksperimental** [comment]
I will fix it in master

**Comment by eksperimental** [comment]
@Dignifiedquire how can I build the CSS files now, without having them minified,
so i can look at the uncompressed sourcecode.
and what command should i run before commiting. thanks you!

**Comment by eksperimental** [comment]
has this been fixed, in New Design? if not I will add it to the task list
