### ISSUE TITLE
Hex package does not pull earmark dependency

### ISSUE THREAD

**Issue by jeramyRR** [elixir-lang/ex_doc#295]
Adding :ex_doc to mix.exs does not also pull earmark when executing `mix deps.get`  I'm not sure if this is the appropriate place to put this issue, or if it should be in the Hex github repo.

## Doesn't Work
```elixir
  defp deps do
    [
      { :httpoison, "~> 0.4"},
      { :jsx, "~> 2.0"},
      { :ex_doc, "~> 0.8"} 
    ]
  end
```

## Works
```elixir
  # Type `mix help deps` for more examples and options
  defp deps do
    [
      { :httpoison, "~> 0.4"},
      { :jsx, "~> 2.0"},
      { :earmark, "~> 0.1.17"},
      { :ex_doc, "~> 0.8"} 
    ]
  end
```

**Comment by milmazz** [comment]
According to the `README.md` you need to explicitly indicate `earmark` as dependency, remember that you can use other Markdown parsers, such as: `pandoc` or `hoedown`.

HTH

**Comment by jeramyRR** [comment]
That is somewhat confusing since pulling ex_doc straight from github and running `mix deps.get` pulls earmark.

**Comment by josevalim** [comment]
That's how optional dependencies work. They work on the current project, you need to specify them for your own project. Please follow the README instructions.
