### ISSUE TITLE
Wrong casing on readme link

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#297]
Plug docs doesn't work due to this bug: http://hexdocs.pm/plug/ redirects to http://hexdocs.pm/plug/README.html but should redirect to http://hexdocs.pm/plug/readme.html.

**Comment by eksperimental** [comment]
@ericmj what version of ExDoc are you running,
and what is the command you use to generate that code?
I am looking into that

**Comment by eksperimental** [comment]
Eric, i have added a test and it is working fine (you can see the PR linked above).
So i guess what it could be is that main: "README" is being set,
instead of main: "readme"

**Comment by ericmj** [comment]
I don't know which version it was built with. Looking at the plug 1.0.0 commit it seems ex_doc 0.8.3 is used.

I don't think the test is correct since you do: `main: "readme"` but plug's mix.exs says `main: "README"`. If all files are normalized to lower case you will also need to normalize the links.

**Comment by eksperimental** [comment]
the thing is main: README is understood as that you want to link to the README module.
and since modules cannot start with a lowercase, then readme.html would not collide with any module name, same for index.html

**Comment by josevalim** [comment]
@eksperimental That should not be it. `main: "...."` refers to any page. we should not downcase nor manipulate the main value in any way.

**Comment by ericmj** [comment]
@josevalim The main value is not changed, the README.html filename is changed to lowercase.

**Comment by josevalim** [comment]
@ericmj Yes, we should definitely not do that.

**Comment by eksperimental** [comment]
we are using in "main:" two values in lowercase, for special cases, which is "overview" and "readme", overview is the default one.

**Comment by josevalim** [comment]
@eksperimental the README is uppercase because it mirrors the page default, which is README.md.

**Comment by josevalim** [comment]
The plan, btw, was to support translating multiple `.md` files, like `CHANGELOG.md`, user files and so on. In such cases, it is imperative for us to keep the same case as the original file. That's why an uppercase README makes sense. :)

**Comment by josevalim** [comment]
Fixed in master and 0.8.4 has been released.
