### ISSUE TITLE
One JSON object to rule them all

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#302]
To bring some flexibility in the design process #275, we need to decouple a few things first, most notably the things related with the sidebar area.

* In the new design we want to move this [section](https://github.com/elixir-lang/ex_doc/blob/new_design/lib/ex_doc/formatter/html/templates/module_template.eex#L12-L28) into the sidebar.
* We also want to replace the current `sidebar_items.js` with just one JSON object (almost the same as `sidebarNodes` in the `sidebar_items.js`)
* The JSON object must be useful to build the sidebar items and also for the search functions (which right now relies in the DOM)

So, the idea of this issue is to open a discussion about which JSON structure we want, one proposal could be the next one:

```js
{
    "modules": [
        {
            "id": "EEx",
            "functions": [
                "compile_file/2",
                "compile_string/2",
                "eval_file/3",
                "eval_string/3"
            ],
            "macros": [
                "function_from_file/5",
                "function_from_string/5"
            ],
            "types": [
                "app",
                "key"
            ]
        },
        {
            "id": "EEx.Engine",
            "functions": [
                "handle_assign/1",
                "handle_body/1",
                "handle_expr/3",
                "handle_text/2"
            ],
            "callbacks": [
                "handle_body/1",
                "handle_expr/3",
                "handle_text/2"
            ]
        }
    ],
    "exceptions": [
        {
            "id": "EEx.SyntaxError",
            "functions": [
                "exception/1",
                "message/1"
            ]
        }
    ]
}
```

/cc @Dignifiedquire @josevalim @eksperimental

**Comment by josevalim** [comment]
It looks great to me. Btw, one downside of moving the `[Summary] | [Types] | ...` to the sidebar is that we don't currently highlight the item in the sidebar. For example:

http://elixir-lang.org/docs/master/elixir/Kernel.html

Can we solve this problem? Because if we can't solve this problem reliably, then I am :-1: on moving those links there.

**Comment by Dignifiedquire** [comment]
@milmazz looks good to me
@josevalim yes it is vital that we ar able to highlight the current active module and section in any case

**Comment by milmazz** [comment]
@josevalim @Dignifiedquire Great!, Tonight I'll work on this.

> Btw, one downside of moving the [Summary] | [Types] | ... to the sidebar is that we don't currently highlight the item in the sidebar. For example:

Yes, in the sidebar creation process we can detect if the current element is *Active*, and then with CSS we can apply some magic :grin:

**Comment by Dignifiedquire** [comment]
Closing this, as this is now present in the `new_design` branch
