### ISSUE TITLE
EPUB support

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#305]
Just to let you know that I've been doing some research and some work to include an EPUB formatter for `ExDoc`, also the idea of this message is to inform you about this task and avoid duplication of efforts. 

Of course, I'll give more priority to the issues related with the `new_design`, but I'll keep working whenever it's possible.

I'll keep you posted!

**Comment by eksperimental** [comment]
you may get some ideas from:
https://github.com/jfreeze/elixir-book
It uses a ruby library called softcover
and no elixir code is used, but you may get some ideas

**Comment by milmazz** [comment]
@Dignifiedquire If you have some free time, could you please help me to improve the CSS styles for the EPUB version?

With [Calibre](http://calibre-ebook.com/) you can edit an e-book, there is a guide that explains [how to edit an e-book](http://manual.calibre-ebook.com/edit.html), you can even add new fonts.

[Here](http://milmazz.koding.io/Ecto-v1.0.0.epub) you can find an e-book for [Ecto](https://github.com/elixir-lang/ecto).

Please let me know if you can, in a few days I'll create a new branch here to include all the code. BTW, if you want to test everything by yourself you can try [ex_doc_epub](https://github.com/milmazz/ex_doc_epub)

**Comment by Dignifiedquire** [comment]
Great stuff @milmazz I will take a look at styling for this in the next days

**Comment by josevalim** [comment]
Let's focus on this after 0.9 is out. Once we get this in, let's add a new "Area" to the labels called "EPUB".
