### ISSUE TITLE
Improve template tests

### ISSUE THREAD

**Issue by Dignifiedquire** [elixir-lang/ex_doc#312]
At the moment the tests for the templates are written using regexes mostly, which is brittle and very sensitive to things like space changes, simple addition of a class. 
I suggest we use an html parser like https://github.com/philss/floki to test the html.

For example something like this:

```elixir
assert content =~ ~r{<span><a id="modules_list" href="#full_list">Modules</a></span>}
```

would become

```elixir
modules =  Floki.find(content, "#modules_list")
assert length(modules) > 0
```
or even nicer with some helper methods

```elixir
defp exists(content, selector) do
  assert length(Floki.find(content, selector)) > 0
end

exists(content, "#modules_list")
```

**Comment by milmazz** [comment]
Something like this could help us to avoid the unit tests broken every time we change the layout or some style in general, and this kind of changes are very common in this redesign phase. 

@josevalim What do you think? are you agree with this proposal?

**Comment by josevalim** [comment]
Yes, that sounds good to me.

**Comment by Dignifiedquire** [comment]
Working on this now

**Comment by milmazz** [comment]
@Dignifiedquire Have you work on this lately?

**Comment by Dignifiedquire** [comment]
No not lately

**Comment by milmazz** [comment]
@Dignifiedquire I'll close this for now, the current tests are working fine. If you have some free time time, feel free to reopen this issue.
