### ISSUE TITLE
Allow users to include additional markdown pages

### ISSUE THREAD

**Issue by lpil** [elixir-lang/ex_doc#316]
YARD, a similiar tool for Ruby, allows the user to include additional pages into the generated site, such as this [getting started](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md) page on their site.

I like this feature as it allows me to include documents that detail more general architectural information in my documentation, and I think it would make a strong addition to ExDoc. :)

Thanks,
Louis

**Comment by Dignifiedquire** [comment]
Sounds like a good idea to me.

**Comment by josevalim** [comment]
We should definitely do this. Currently we only support README and supporting other pages are planned. However, I would wait until the new design is ready. :)

**Comment by Dignifiedquire** [comment]
Well I should start to think about the best way to integrate them into the navigation then :)

**Comment by lpil** [comment]
Perhaps we could specify the files like this?

```elixir
# config/config.exs

config :ex_doc, additional_files: ~w(
  docs/getting_started.md
  docs/user_rules.md
)
```

**Comment by josevalim** [comment]
@Dignifiedquire definitely.

@lpil exdoc is usually configured on your mix because it is only a project concern, not an application one. But such a list would be ideal, yes.

**Comment by milmazz** [comment]
I'm agree with this, just for reference, this is related with an old requirement #75, even there is an old proposal #76

Definitely it would be great to have this feature after the redesign.
