### ISSUE TITLE
Modules and functions that are not being linked

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#321]
Needs Fixing:
- [ ] **typespecs** are not getting linked.
- [ ] **Kernel.Specialforms** some being detected as functions
  - [ ] create a test that lists all available special forms in Elixir, and see if all of them get linked.

======
I created a shell script that checks for anything references to Modules that are not actually linked for the elixir project
http://git.io/check_not_linked_exdoc.sh

You can see the output here:
https://gist.github.com/eksperimental/6dc9bce36710a3c8b1d9

What I can see is that we are not linking to:

**1 - functions with arity 0, when the arity is not specificed**, such as in:
```
doc/elixir/Exception.html
108:<code class="inline">System.stacktrace</code> will return the stacktrace for the
```

**2 - functions that were defined with a different arity**, such as in:
```
doc/elixir/Kernel.SpecialForms.html
1228:<p>After the two import calls above, only <code class="inline">List.keyfind/3</code> will be

doc/elixir/GenEvent.html
147:<p>We start a new event manager by calling <code class="inline">GenEvent.start_link/0</code>.
```
I don't know if this is could be considered a mistake in the docs, and/or if this should be allowed.

**3 - typespecs**, such as in:

```
 doc/elixir/Kernel.Typespec.html
115:supported (<code class="inline">list(integer)</code>) and so are remote types (<code class="inline">Enum.t</code>).</p>
```

**4 - some SpecialForms**
```
3983:<p>For more information about structs, please check <code class="inline">Kernel.SpecialForms.%/2</code>.</p>
```
This is because special forms have different rules for what's a valid function.

The rest of what you can see, are mistakes in the elixir documentation.
I will update the script to work with regular elixir projects, so it can be used by other projects

@josevalim if you can give me your input on whether its a bug to link to a function with a different arity that it was defined, I can correct those in the Elixir code

**Comment by ericmj** [comment]
1. Do we ever create links when arity is not specified?

2. User bug.

3. I think arity is required here too.

4. This is a bug.

**Comment by eksperimental** [comment]
@ericmj I have submitted a PR for elixir fixing what had to be fixed from the Elixir side.

but, typespecs did not work when specified the arity, so I didn't touch that.

I will write a test in exdoc that checks for all the existing specialforms so in the future when new ones get added

**Comment by josevalim** [comment]
1. Requires arity
2. ExDoc bug. From the user perspective both List.keyfind/3 and List.keyfind/4 exist. Maybe we should define links for functions with defaults?
3. Requires arity
4. ExDoc bug.
