### ISSUE TITLE
Sidebar - all function links are broken

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#326]
"Undefined" is the name for every function
here's the generated html code.
```html
<a href="System.html#function anchor() { [native code] }" title="System.undefined" class="object_link">undefined</a>
```

this works fine in v0.8.4,
so it has recently been introduced

**Comment by milmazz** [comment]
@eksperimental Could you please give more details about this issue? how can I reproduce this? This behaviour occurs on which branch? `master` or `new_design`?

**Comment by eksperimental** [comment]
@milmazz just run build ex_doc from master, and `make docs`

**Comment by milmazz** [comment]
@eksperimental Are you sure? :confused: 

```bash
$ cd ex_doc
$ mix compile
$ cd ../elixir
$ make docs_elixir
==> elixir (compile)
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.1.0-beta" "lib/elixir/ebin" -m "Kernel" -u "https://github.com/elixir-lang/elixir" --source-ref "3419e0ddc4824859ad5034401a1baa3c2197f153" -o doc/elixir -p http://elixir-lang.org/docs.html
$ cd doc
$ grep -nr -e "System.undefined" *
$ grep -nr -e "function anchor" *
```

**Comment by eksperimental** [comment]
you are right @milmazz ! 
I'm sure what happened was that I checked out to master, and forgot to compile, and it was the beams from another dev branch a previously compiled.

I have to keep remembering to run `ex_doc/mix`, before `elixir/make docs`
