### ISSUE TITLE
[sidebar] Add nesting level for the first level of modules

### ISSUE THREAD

**Issue by dignifiedquire** [elixir-lang/ex_doc#329]
@josevalim do you think you could look into this, or provide some tips on how to implement this?

**Comment by Dignifiedquire** [comment]
@josevalim any chance you can work on this in the next week or so?

**Comment by josevalim** [comment]
I cannot, sorry. Since this at least won't affect Elixir itself, let's focus on the other stuff, and I will put some effort on this after 0.9.1 is out. :)

**Comment by Dignifiedquire** [comment]
Okay

**Comment by milmazz** [comment]
@Dignifiedquire Is this still required? Could you please explain which is the goal here? If @josevalim (assigned) cannot take this task, I can try to solve this issue.

**Comment by Dignifiedquire** [comment]
The idea was to move from something like this:

```
Mix.Tasks.Compile.Phoenix
Mix.Tasks.Phoenix.Digest
Mix.Tasks.Phoenix.Gen.Channel
Mix.Tasks.Phoenix.Gen.Html
Mix.Tasks.Phoenix.Gen.Json
Mix.Tasks.Phoenix.Gen.Model
Mix.Tasks.Phoenix.Gen.Secret
Mix.Tasks.Phoenix.Routes
Mix.Tasks.Phoenix.Server
Phoenix
Phoenix.Channel
Phoenix.ChannelTest
Phoenix.CodeReloader
Phoenix.ConnTest
Phoenix.Controller
Phoenix.Controller.Logger
```

to sth like this:
```
Mix
  - Tasks.Compile.Phoenix
  - Tasks.Phoenix.Digest
  - Tasks.Phoenix.Gen.Channel
  - Tasks.Phoenix.Gen.Html
  - Tasks.Phoenix.Gen.Json
  - Tasks.Phoenix.Gen.Model
  - Tasks.Phoenix.Gen.Secret
  - Tasks.Phoenix.Routes
  - Tasks.Phoenix.Server
Phoenix
  - Channel
  - ChannelTest
  - CodeReloader
  - ConnTest
  - Controller
  - Controller.Logger
```

**Comment by josevalim** [comment]
We are closing this. We may reopen in the future if necessary.
