### ISSUE TITLE
Add image support

### ISSUE THREAD

**Issue by Dignifiedquire** [elixir-lang/ex_doc#330]
@milmazz all yours

**Comment by milmazz** [comment]
@Dignifiedquire Please review the f927a3c commit on the `logo` branch. Notice that in the sidebar now you can see something like this:

```html
<h1 class="sidebar-projectName logo">
  <a href="http://elixir-lang.org/docs.html">Elixir</a>
</h1>
```

This option is available via `---logo Path_to_file.{jpg,png}`

Could you please add all the required CSS or if you want change the `sidebar_template.eex` and "beautify" the all thing :smile: 

/cc @josevalim

**Comment by Dignifiedquire** [comment]
@milmazz could you please pass the path to the logo including the extension as a variable to the sidebar template? As at the moment I can reference the image as I don't know the extension
