### ISSUE TITLE
Search features

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#332]
Search improvements:

* [x] provide a message to the user when there are no results at all
* [x] Ensure the `ESC` key cleans the input element
* [ ] Let's change the URL once you search and ensure it can be sent around. Note it may not work on the file protocol though, so we need to check for window.history
* [ ] Let's ensure the back button works with search (depends on the item above)

**Comment by Dignifiedquire** [comment]
Search url and history support turns out to be much more complicated, I'm afraid we will have to delay that.

**Comment by josevalim** [comment]
No problem. Let's have that pos 0.9. :D

**Comment by Dignifiedquire** [comment]
Closing this then in favor of #341 as the rest I've just fixed
