### ISSUE TITLE
[sidebar] The menu icon disappears in iOS Safari after opening menu

### ISSUE THREAD

**Issue by asonge** [elixir-lang/ex_doc#336]
The menu icon disappears in iOS Safari after opening menu

Screenshot: ![img_2089](https://cloud.githubusercontent.com/assets/90809/9789619/cc268c2e-5796-11e5-9362-70c9299506db.PNG)

**Comment by josevalim** [comment]
Thank you, I was going to open just this. Also, it is worth noting that the button is very "light" instead of black when you just open the page.
