### ISSUE TITLE
[sidebar] Once a module is selected, there is no indication there are other modules above

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#337]
For example, access: http://elixir-lang.org/docs/master/elixir/Kernel.html

There are a bunch of modules above Kernel but there is no indication. I am not sure of what would be the best solution though.

**Comment by Dignifiedquire** [comment]
I haven't found a good way to solve this yet, happy to hear suggestions.

**Comment by josevalim** [comment]
One simple solution: can we scroll to two items above the current item? Then it looks like this:

<img width="264" alt="screen shot 2015-09-10 at 20 54 10" src="https://cloud.githubusercontent.com/assets/9582/9797914/2b001d48-57fe-11e5-81ef-57075eca1825.png">

The only issue is that, on first glance, the menu is too close to the modules lists, so it may not be apparent. Maybe the previous formation, where the search was closer to the modules list, was better.
