### ISSUE TITLE
[content] The functions in the module summary don't look like links

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#339]
This is a twitter feedback. To be clear, he is mentioning the functions here:

http://elixir-lang.org/docs/master/elixir/Kernel.html#summary_details

**Comment by Dignifiedquire** [comment]
Not fully convinced this can be classified as bug. I would say we can discuss it, but to be honest I think the current version is working out pretty good

**Comment by josevalim** [comment]
@Dignifiedquire it is your call. One non-obstrusive idea is that on mouse over an arrow pointing down could appear on the right side. The same way the link icon appears when you mouse over the actual function signature in the docs.

**Comment by paulcsmith** [comment]
FWIF I also thought that the links in the summary did not look clickable. I actually wondered where the summary was for a bit. The docs look great though, just wanted to throw in my 2 cents :)

**Comment by josevalim** [comment]
Closing this. We may discuss changing it in the future but this is one year old and the consensus seems to be no changes.
