### ISSUE TITLE
<code> tags should not be in italic

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#342]
For example, `sigil_r` and friends in the summary here: http://elixir-lang.org/docs/master/elixir/Kernel.html#summary_details

<img width="255" alt="screen shot 2015-09-10 at 18 53 07" src="https://cloud.githubusercontent.com/assets/9582/9794763/431eb2d8-57ed-11e5-916f-9815a9bf8975.png">

Notice the `~r` is in italic. Maybe we should not have code in italic as it can be harder to read? It would look like this:

<img width="268" alt="screen shot 2015-09-10 at 18 52 59" src="https://cloud.githubusercontent.com/assets/9582/9794775/4ff57064-57ed-11e5-8f47-5fc28dfe03ee.png">

Feel free to close if you believe this should stay as is. :)

**Comment by Dignifiedquire** [comment]
@josevalim totally right, these should not be italic.

**Comment by eksperimental** [comment]
:+1:
