### ISSUE TITLE
Accessing the summary details sections directly does not highlight "Summary" in the sidebar

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#343]
Steps to reproduce:

1. Visit http://elixir-lang.org/docs/master/elixir/Kernel.html#summary_details
2. Notice that you have `| Summary` in the sidebar and not `> Summary`

**Comment by Dignifiedquire** [comment]
Resolved in 93fde30896b9a5776fc2827ecb9f3afff32c69a4
