### ISSUE TITLE
Modules summary do not interpret numbered links

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#347]
http://elixir-lang.org/docs/master/elixir/overview.html#modules_summary
it will read:

> Inspect.Algebra
> A set of functions for creating and manipulating algebra documents, as described in ["Strictly Pretty" (2000) by Christian Lindig][0]

this happens because ExDoc only reads the first line, and ignores the rest, and that [0] referenced is declared at the bottom of the module doc https://github.com/elixir-lang/elixir/blob/12f89a30b46279398fc7143e433681c2194b03d9/lib/elixir/lib/inspect/algebra.ex#L135

**Comment by josevalim** [comment]
We should change the docs in Elixir. :)

**Comment by eksperimental** [comment]
I don't think it's a bug in Elixir,
we can expect users to do the same, and to expect it to work. If the links are working in the module itself, why aren't they working in the summary.

I can update the docs in Elixir so we don't have that for 1.1, but I would consider this a bug.

**Comment by josevalim** [comment]
@eksperimental i am fine to say it is a limitation in ExDoc then. Fixing it is going to be annoying and it will be complexity that is not worth for the benefits it brings.

**Comment by eksperimental** [comment]
ok. so, should we document this somewhere?

**Comment by josevalim** [comment]
I am fine with leaving it just as is, but we can wait for others feedback. :)
