### ISSUE TITLE
Backticks are not interpreted inside HEADINGS (Earkmark bug)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#348]
I'm posting this here to bring more attention to the bug.

```md
## Differences from `defmodule`
```

earmark will convert the code above to:

```html
<h2>Differences from `defmodule`</h2>
```

while the rest of the implementations will do:

```html
<h2>Differences from <code>defmodule</code></h2>
```

Full report: https://github.com/pragdave/earmark/issues/30

**Comment by josevalim** [comment]
Closing this as it has been reported to earmark.
