### ISSUE TITLE
Automatic documentation link for defdelegate

### ISSUE THREAD

**Issue by iamvery** [elixir-lang/ex_doc#350]
From irc:
> iamvery> how would you go ahead documenting delegated functions?
> iamvery> Sort of seems like it might be nice for `h` to get the docs from the delegate
> ericmj> iamvery: you can reference other functions in documentation and ex_doc will create links
> ericmj> we do it automatically for callbacks, maybe it should be done for defdelegate as well

**Comment by iamvery** [comment]
:100: :heart: 
> 10:45 AM <iamvery> I was thinking maybe doing something like `@docs "See SomeModule.SomeOtherModule.some_func"`
> 10:46 AM <josevalim> iamvery:  i am not sure i agree here
> 10:46 AM <tkschmidt> quit
> 10:46 AM ⇐ tkschmidt quit (~tkschmidt@188.226.135.129) Client Quit
> 10:46 AM <ericmj> iamvery: `bar/2` `Foo.bar/2` `c:Foo.baz/2` all create links
> 10:46 AM <ericmj> c: is a callback
> 10:46 AM <josevalim> here is the thing: why are you delegating?
> 10:46 AM <iamvery> josevalim: oh, interesting. What are you thinking?
> 10:46 AM → DeadTrickster joined (~dead@62.122.188.214)
> 10:46 AM <iamvery> I'm following the train of thought from the inflex discussion
> 10:46 AM <josevalim> in the inflex case, you are delegating a public function to a private function
> 10:46 AM <josevalim> so it doesn't make sense to link to the private functions
> 10:47 AM <josevalim> people are never meant to call Inflex.Camelize directly
> 10:47 AM <iamvery> all the delegates are actually public
> 10:47 AM <josevalim> yes
> 10:47 AM <iamvery> idk if that's true
> 10:47 AM <josevalim> but not the ones you are delegating to
> 10:47 AM → tkschmidt joined (~tkschmidt@188.226.135.129)
> 10:47 AM <iamvery> I could see using Camelize directly
> 10:47 AM <iamvery> i guess that's up to the lib owner though :/
> 10:47 AM <josevalim> yes, exactly
> 10:47 AM <josevalim> i mean
> 10:47 AM <iamvery> maybe i'm sticking my nose in too far
> 10:47 AM <josevalim> why will you have two functions in your api that does exactly the same thing?
> 10:47 AM <josevalim> *that do
> 10:47 AM <josevalim> so i would add
> 10:47 AM <iamvery> in this case, yes
> 10:48 AM <iamvery> smelly, eh?
> 10:48 AM <josevalim> @moduledoc false to Inflex.Camelize
> 10:48 AM <josevalim> and have the public documentation in inflex above the defdelegate call
> 10:48 AM <josevalim> your feature request makes sense when you are delegating from public to another public documented, often in another library
> 10:48 AM <josevalim> however, i don't find this super common
> 10:48 AM <josevalim> so a default wouldn't make sense
> 10:49 AM <josevalim> in those cases, you should rather just add a tiny doc that explains it
> 10:49 AM <josevalim> possibly explain why you are also delegating
> 10:49 AM <josevalim> so I think the best thing is to not infer docs automatically in this case

**Comment by josevalim** [comment]
Thanks for pasting it here. My IRC client is horrible at pasting stuff!

**Comment by iamvery** [comment]
literally me using irc:

![](http://i.imgur.com/xVyoSl.jpg)
