### ISSUE TITLE
The sidebar is flashing

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#352]
Because we make the sidebar show up after the page is loaded, we get the impression it is flashing:

You can see this by navigating through different modules quickly: http://elixir-lang.org/docs/master/elixir/Kernel.html

I am not sure if we can fix this though.

**Comment by Dignifiedquire** [comment]
Can be fixed, needs some restructuring of how the sidebar works though.

**Comment by Dignifiedquire** [comment]
Basic idea:

* Show/hide sidebar depending on the screen size using css
* JS only overrides those settings when the toggle is pressed

**Comment by Dignifiedquire** [comment]
Done
