### ISSUE TITLE
Make the specs more compact

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#353]
Feedback from Twitter. The specs today take a lot of space, even more than the function signature, we could maybe it a bit more compact: 

https://twitter.com/PaulLamb/status/642449985309679616

**Comment by josevalim** [comment]
To add to this, we should probably add `class="elixir hljs"` to the spec snippets. They currently have no syntax which makes it unreadable in cases like this: file:///Users/jose/OSS/elixir/doc/elixir/GenServer.html#callbacks_details

Also notice some specs have links inside. :) See "from" in handle_call/3.

**Comment by josevalim** [comment]
I am tagging this for fix before 0.9.

**Comment by Dignifiedquire** [comment]
Agreed, the need proper highlighting

**Comment by Dignifiedquire** [comment]
Wrong issue referenced :/
