### ISSUE TITLE
Clean up the classes coming from the sidebar template

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#355]
When we made the sidebar dynamic, we added classes like "node" and "docs". It seems those classes are no longer used and can be :fire:.

**Comment by Dignifiedquire** [comment]
They are actually used for design purposes, but they should be renamed to better match what they are representing.

**Comment by milmazz** [comment]
@Dignifiedquire @josevalim Any suggestion regarding the name of those classes? I'm out of ideas :no_mouth:

**Comment by Dignifiedquire** [comment]
Sorry not really :( that's why I didn't touch it before

**Comment by josevalim** [comment]
Let's close this then. The name is not ideal but without better suggestions we should rather focus on other things. :)

**Comment by milmazz** [comment]
@josevalim Closing... :grinning:
