### ISSUE TITLE
Revisit the need for functions in the sidebar

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#356]
We will release 0.9 without this but we should keep tracking the feedback on this.

**Comment by josevalim** [comment]
I've had one idea on this topic. I don't think folks actually want the functions in the sidebar, they do want, however, a place they can easily see all functions for a given module defined. The question is: do we have such a place in the docs? Actually, we do: the search page!

For example, if we search for something as common as "a", we see a bunch of results and they are all already neatly organized in the search page. So maybe we could use the search page to hold this information. Here is one possible workflow:

1. Clicking on the search (or some button alongside the search) will automatically open up a "page" with *all* the functions listed. This "page" will, however, be scrolled to the current module

2. We need to improve navigation around search: ESC needs to leave the search page and go back exactly to the page+section I was reading

3. Optional: we could also consider moving search out of the sidebar and on the right top side of the page. The position could be static on wide devices so we have it accessible anywhere. This could also give some breathing room to the module listing on the sidebar

One alternative approach is to move the search results back to the sidebar but provide the same workflow described here. Once you click the search or a button on the side of the search input, the whole sidebar lists all functions per module with the listing for the current module selected. This one may be easier to tackle navigation wise. This one is possible better too because we would also be able to click the functions and it would take the module on the right side exactly where we need to be.

Thoughts?

**Comment by Dignifiedquire** [comment]
Thanks @josevalim for the clarification, I have some ideas around this, will hopefully get some mockups in the next days to talk through them
