### ISSUE TITLE
The logo dances when collapsing/expanding sidebar

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#357]
To reproduce:

1. Visit http://elixir-lang.org/docs/master/elixir/GenServer.html#callbacks_details
2. Click on the hamburger menu multiple times. The logo appears in weird places

Browser: Chrome.

**Comment by Dignifiedquire** [comment]
Will be fixed when #352 is resolved (the main issue is that the logo is currently absolute positioned)

**Comment by josevalim** [comment]
Ah, ok. I will remove the v0.9 milestone then. I don't think this is a blocker. :)

**Comment by Dignifiedquire** [comment]
Working on this already, so it will be fixed
