### ISSUE TITLE
Mobile: sidebar completely unusable when screen in landscape view

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#359]
the only scrollable part of the sidebar is the function list (this happens in either portrait or landscape, let me know if I should open a new issue for this)

the thing is when in landscape view, since it is not scrollable, all the sidebar is unusable because there is nothing to scroll. the only thing we can do is type something in the search and scroll it in the main area

Browser: Chrome

**Comment by Dignifiedquire** [comment]
Not sure I understand, that's the idea, that only the function part is scrollable

**Comment by josevalim** [comment]
I think this is the issue:

![img_3211](https://cloud.githubusercontent.com/assets/9582/9833599/b9a7d55a-599c-11e5-9650-a6f2f29193dd.PNG)

The scrolling part is too small, you can't get to it.

**Comment by Dignifiedquire** [comment]
Okay, I see should be easy to fix

**Comment by eksperimental** [comment]
exactly.
on my phone I don't even get to see "Access"

**Comment by josevalim** [comment]
Do you mean you can't access Access? :D

**Comment by eksperimental** [comment]
I mean i cannot see it.
that means, the whole menu is locked since the funtion list is the only scrollable area

**Comment by eksperimental** [comment]
oops.. i didn't get the joke :-P
