### ISSUE TITLE
Large project names are hovering the new menu

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#361]
<img width="638" alt="screen shot 2015-09-12 at 22 43 32" src="https://cloud.githubusercontent.com/assets/9582/9833678/c45062e8-59a0-11e5-9d06-e72cfca9c04d.png">

Large project names may be a good reason to left-align the text. Here is the current docs left-aligned and after removing some of the space between the text and logo:

<img width="347" alt="screen shot 2015-09-12 at 22 48 56" src="https://cloud.githubusercontent.com/assets/9582/9833689/032b5a0e-59a1-11e5-8999-e43e7ac0ccf8.png">

**Comment by Dignifiedquire** [comment]
We could left align when no logo is present and right align with a logo?

**Comment by josevalim** [comment]
Actually, right aligned is fine in both cases can we just:

1. Reduce the horizontal space between the header and the logo
2. While making sure the won't go over the menu when there is no logo or the title is too large?

**Comment by Dignifiedquire** [comment]
Please recheck in `master`

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
Currently:

<img width="375" alt="screen shot 2015-09-12 at 23 53 46" src="https://cloud.githubusercontent.com/assets/9582/9833969/9666bfea-59a9-11e5-8510-b2372fe39fab.png">

**Comment by Dignifiedquire** [comment]
@josevalim not sure where you are seeing this, this is what I got:

![screen shot 2015-09-13 at 00 21 09](https://cloud.githubusercontent.com/assets/790842/9834118/5c8ae374-59ad-11e5-9b8d-44ad1f6f1f17.png)
