### ISSUE TITLE
Hamburger menu is broken on compact views

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#365]
To reproduce:

1. Visit http://elixir-lang.org/docs/master/elixir/Kernel.html#functions_details
2. Reduce your browser window size
3. Click on the menu - nothing happens

I think this is truly the last thing before we ship it! :D

**Comment by Dignifiedquire** [comment]
> I think this is truly the last thing before we ship it! :D

I don't believe you

**Comment by xavier** [comment]
I'm not sure whether this is related to the window size: it seems to work fine on Chrome even with a narrow window but it doesn't work on Safari, not matter what the window size is.  Once hidden, the sidebar cannot be revealed again.  There is no error or warning in the JS console.

**Comment by Dignifiedquire** [comment]
@josevalim should be fixed now :)
