### ISSUE TITLE
Consider giving more space to module names

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#366]
Now that we support custom pages, the space where we show the existing modules is shrinking further and further:

<img width="276" alt="screen shot 2015-09-13 at 12 09 13" src="https://cloud.githubusercontent.com/assets/9582/9836194/6401db86-5a10-11e5-9063-cfe62a71b732.png">

Maybe we could squeeze things a little bit more. Another option is to move the search out and keep it on the right side (possibly static), giving more breathing room altogether. Here is a (poor) attempt at this:

<img width="1222" alt="screen shot 2015-09-13 at 12 19 08" src="https://cloud.githubusercontent.com/assets/9582/9836238/b52fe5f6-5a11-11e5-8ad3-809c459e07af.png">

I made the title left-aligned because removing the search caused us to lose reference on the sidebar about where the left side begins.

Another possible idea is to move Overview + README + Search altogether to the right side, where the search is now. Anyway, just ideas so we can get more navigation space.

**Comment by eksperimental** [comment]
_This comment was originally posted by me, in #374_

1) One thing that we can do to definitely give more room in the sidebar is reduce the size of the version number, and maybe may it bold. I know that area will still be 64px high, because of the size of the logo, This will reduce the size with projects with long names: https://github.com/elixir-lang/ex_doc/issues/361#issuecomment-139825040

2) If no logo is provided, i think we can reduce the size of the header (most projects will not provide a logo I guess)

**Comment by nhu313** [comment]
What if we make the logo and version all on one line? It's definitely not as pretty as before, but it does give more room for the full list.

### Before:
![before](https://cloud.githubusercontent.com/assets/3436429/9897294/89574cd0-5c14-11e5-94be-f0be6703972c.png)

### After:
![after](https://cloud.githubusercontent.com/assets/3436429/9897293/8954a322-5c14-11e5-98f1-961f2f983a46.png)

**Comment by eksperimental** [comment]
@nhu313 I don't think that will work with projects with long names.
https://github.com/elixir-lang/ex_doc/issues/361#issuecomment-139825040

**Comment by nhu313** [comment]
Then we should not let people have project with more than 10 characters ;) Good thing I didn't make the change in the code. 

We might need to fix the long name for the current layout too.

### Current
![event_source_before](https://cloud.githubusercontent.com/assets/3436429/9897715/b05c7d78-5c19-11e5-9dde-f6d975e679ea.jpg)

**Comment by Dignifiedquire** [comment]
First draft

![layout02-v5](https://cloud.githubusercontent.com/assets/790842/9914163/bfd8f3f2-5cb0-11e5-94dd-a9fdde17db7d.png)

**Comment by Dignifiedquire** [comment]
New version:

![layout02-v5](https://cloud.githubusercontent.com/assets/790842/9919153/5177a1d6-5ccb-11e5-9a1b-19a1f14cc3f1.png)

**Comment by josevalim** [comment]
:+1: for the last one

**Comment by milmazz** [comment]
:+1: for the new version

**Comment by eksperimental** [comment]
Beautiful! Last one. I look so pleasant to the eye

**Comment by josevalim** [comment]
Just to update everyone, we have made more progress here with #395. The idea to have a Pages section was two fold:

1. Phoenix is considering using the Pages mechanisms as guides, so we need something that supports a bit more structure
2. In this schema, we are actually parsing the `<h2>` tags out of the markdown and using it for navigation

**Comment by josevalim** [comment]
I will push a couple more improvements and publish new docs for Plug so everyone can give it a try.

**Comment by Dignifiedquire** [comment]
Pages are now under their own category and I've made sidebar a little bit more compact. Closing this for now
