### ISSUE TITLE
Keep the current developement version suffixed with "-dev"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#368]
I would like to propose that after every release, we change the suffix the version to the next minor release + "-dev", so for example, now, it would be "v0.9.1-dev",

I'm using ExDoc in a project where I print the folder version with the current version number, and as of now there's no way to distinguish what's a proper release from a dev version.

**Comment by josevalim** [comment]
@eksperimental please go ahead. :D there is a test you will have to fix as soon as you change it btw ;)

**Comment by Dignifiedquire** [comment]
please use sth like `0.10.0-beta.0` to be semver v2 conform

**Comment by josevalim** [comment]
`-dev` is valid semver too. :) And i think we can stay  a bit on 0.9.0 before going to 0.10.0. Unless we have a large change!

**Comment by eksperimental** [comment]
yes, i was going to say that, if we add small changes, it shouldn't be 0.10,
I think to put an example we should have been 0.8.5-dev after 0.8.4 was releaesed, and when new_design branch was merged in, we should have moved into 0.9.0-dev (or beta), only then.

**Comment by Dignifiedquire** [comment]
Okay :)
