### ISSUE TITLE
2 tests failing when using Elixir 1.1.0-beta

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#370]
tests pass fine in 1.0.5, but fail in 1.1.0-beta
the tests checking for the link to source, fail, the line number is off by one.

https://gist.github.com/eksperimental/c895291a0b262dadc5d8

before digging into this, I would like to know if there were any recent changes in 1.1 that could be the source of this.

**Comment by josevalim** [comment]
They all pass here and I am running on 1.1 for months, please make sure you
cleaned your temp directories and so on. :)

I think the build also uses 1.1


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
I have cleaned everything:
including the temp for the deps and fixtures.

deleted folders:
- test/tmp
- _build/dev
- _build/test

I have tested it with master as well as with 1.1.0-beta and the same issues persist.

travis is using 1.0.2

**Comment by josevalim** [comment]
You are right, sorry, this is due to #334 and I think @lexmag is on it, so I am closing it, it is a dup :D

**Comment by eksperimental** [comment]
good! that's why I asked if there was any issue bc I sort of remembered something like this, now that you mentioned, that was the issue I saw earlier. I just couldn't make the connection.
 thanks for looking into this.

**Comment by lexmag** [comment]
Right, I'm working on it. :smile:
