### ISSUE TITLE
[Feature Request] Double click section titles

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#375]
I would love to be able to directly link to particular fixed sections in the modules, such as the Callbacks

![ex_doc_title_link](https://cloud.githubusercontent.com/assets/9133420/9848303/252c3c3a-5b0a-11e5-8abc-06ed204b7afa.png)

Just by double-clicking the title.I wouldn't change the cursor or the LINK icon such as in functions, just to not to add any distraction (maybe just use the "title" attribute saying "Callbacks"), kind of like an easter-egg. but it will be more intuitive if you are already somewhere in the page, and double click on Callbacks, and it will take you to Access.html#callbacks_details , without the need to go to the sidebar, find the link, and click or copy it.

This will be useful for mobile users who will have no access to the sidebar at all times.
So we double click the TITLE of the section (e.g "Callbacks"), and it takes us to: Access.html#callbacks_details

**Comment by josevalim** [comment]
This is straight-forward to do. For example, in module_template.eex, we just need to add this to every h1:

    <h1 class="section-heading"><a href="#types_details">Types</a></h1>

However, adding the link messes up the styling, so we need @Dignifiedquire to do his magic first. Then I can commit those changes. <3

**Comment by eksperimental** [comment]
Should we add this to milestone v0.10 ?

**Comment by eksperimental** [comment]
I'm reopening this, as the clickable feature has not been implemented.

**Comment by josevalim** [comment]
We have agreed to not add the double click, only to click the header and link it properly. The discussion happened on IRC, my bad, we should have updated here.

**Comment by eksperimental** [comment]
alright, no worries
