### ISSUE TITLE
:extras vs --extra

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#376]
I just found that we are using two different names for the same thing.
>  Use `:extras` in your `mix.exs` file or pass `--extra` / `-e` in the command-line (may be given multiple times)

Well, i found out the hard way, when I used the wrong one in the command line.

I'm all in for using --extra and :extra in mix.exs, and not :extras as it is not consistent, but I want to know if I'm ignoring any reason for choosing this

thanks

**Comment by josevalim** [comment]
Let's rename the one in CLI to `--extras`.

**Comment by josevalim** [comment]
That's because I would like to make it clear that the Mix one is a list.

**Comment by milmazz** [comment]
I don't agree with this proposal :-1: 

When you use the command and you want to add more files, you explicitly indicate *each* element of the list (can be more than one), so, for this reason to me sound more proper to use a singular term. In the `mix.exs` file you explicitly indicate the list of elements.

**Comment by josevalim** [comment]
@milmazz that's what I was also thinking originally but the fact we call `--extras` in the command line can be a good indication that it can be given more than once. Specially given that folks will most likely use `-e` rather than `--extras`. What do you think?

**Comment by eksperimental** [comment]
yes, my only objection to that is that `--extras README.md --extras CONTRIBUTING.md` is weird.

Is this valid in the CLI: `--extras "README.md" "CONTRIBUTING.md"` ?

maybe the other options is support both behind the scenes --extras

but still will be confusing to give two different names for the same thing.

**Comment by josevalim** [comment]
Now that you have mentioned it it is confusing indeed. I think we should leave it as is then.

> Is this valid in the CLI: --extras "README.md" "CONTRIBUTING.md" ?

No. :(

**Comment by Dignifiedquire** [comment]
I think it would be ideal to support something like this:

```
--extras *.md # expands via bash to README.md CHANGELOG.md 
--extras README.md CHANGELOG.md
--extras README.md
```

**Comment by Dignifiedquire** [comment]
> No. :(

Why is that not possible? I know a lot of cli tools that can do that

**Comment by eksperimental** [comment]
Can we then give a warning and exit, when people call "--extras", and say it should be "--extra"
right now it silently ignores it.

in fact i think that should be the default behaviour for any unrecognized option.

**Comment by josevalim** [comment]
@Dignifiedquire it is not possible with the currrent OptionParser today. We could add it but even though I am not a big fan because it often imposes order between arguments and switches in the command line. Imagine you have this:

    mix do_something --opt value arg

Once you allow multiple values to be given, you can two possible combinations:

    mix do_something --opt value arg
    mix do_something --opt value1 value2

They are the same arguments but interpreted differently depending on the order, which i am not a big fan of.

It wouldn't hurt to warn on unknown options though.

**Comment by adamu** [comment]
For anyone reading this and wondering where `--extra` is, it was removed and replaced with a config file in aa3cf1e34eff4e67854e3fe6419c921cadc9e286.
