### ISSUE TITLE
Search result links are escaped, linking to a non-existent id

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#378]
if you search for ">"
It will link to:
http://elixir-lang.org/docs/master/elixir/Kernel.html#&gt;/2

but that element doesn't exist, 
it should link to
http://elixir-lang.org/docs/master/elixir/Kernel.html#>/2

**Comment by Dignifiedquire** [comment]
@eksperimental should be good in master :)

**Comment by eksperimental** [comment]
@Dignifiedquire I have reopened this one as there are still some issues. and some links are not working.

because now we are validating html5, so I cannot use `< > & ' "` as part of the ID,
Links containing these characters are not working.
so they should be encoded.

I am using the `enc_h` function to encode the URIs.
you can see what is does here https://github.com/elixir-lang/ex_doc/blob/6c4f09c7227cd839e8c5472747d0e32b94f12e0a/lib/ex_doc/formatter/html/templates.ex#L59-L70

so we can mimic the steps, 
let me know if you have any questions.

/cc @milmazz

**Comment by josevalim** [comment]
@eksperimental this may be an issue on Elixir's side. @eksperimental can you tell us exactly with IDs are being leaked?

**Comment by eksperimental** [comment]
@josevalim could be. maybe we should use the same method to encode them before generating the json.
I think it's all functions that use the chars mentioned about.
for example the on I reported in this issue.

`http://elixir-lang.org/docs/master/elixir/Kernel.html#>/2`

**Comment by eksperimental** [comment]
I saved the html tree generated by Chrome, as an html page. and run the validators,
it's saying this.

```
$ html5validator
"sidebar.html":1.6-1.6: error: Start tag seen without seeing a doctype first. Expected “<!DOCTYPE html>”.
"sidebar.html":394.49-394.49: error: Bad value “#^^^/2” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
"sidebar.html":415.49-415.49: error: Bad value “#|||/2” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
"sidebar.html":2413.55-2413.55: error: Bad value “#|&gt;/2” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
"sidebar.html":2416.48-2416.48: error: Bad value “#||/2” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
"sidebar.html":2479.47-2479.47: error: Bad value “#%/2” for attribute “href” on element “a”: Percentage ("%") is not followed by two hexadecimal digits.
"sidebar.html":2482.49-2482.49: error: Bad value “#%{}/1” for attribute “href” on element “a”: Percentage ("%") is not followed by two hexadecimal digits.
"sidebar.html":2500.47-2500.47: error: Bad value “#^/1” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
"sidebar.html":2560.48-2560.48: error: Bad value “#{}/1” for attribute “href” on element “a”: Illegal character in fragment: not a URL code point.
```

**Comment by josevalim** [comment]
Thanks @eksperimental but we are not going to fix this for now. That's because those are their proper names after all. The only fix is if we done some weird alias but given it works in browsers, we will leave it as is for now.

**Comment by eksperimental** [comment]
well, the thing is they don't work.
http://elixir-lang.org/docs/master/elixir/Bitwise.html#&lt;&lt;&lt;/2

**Comment by eksperimental** [comment]
in addition to the ones reported by html5validator, if you look at the [generated html](https://gist.github.com/eksperimental/a189ecd8f7df137d648d) any function using the escaped version of symbols with &ampersand, will not work. ex. `#&amp;lt;&amp;gt;/2`

**Comment by josevalim** [comment]
Yes, I have fixed this in master. :) It was some other cause. I think the validator will still complain though.
