### ISSUE TITLE
Rename internal links to sections

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#379]
I'm working on replacing all the elements with "_",
and I realize we don't actually need to link to 
http://elixir-lang.org/docs/master/elixir/Kernel.html#summary_details
http://elixir-lang.org/docs/master/elixir/Kernel.html#functions_details
http://elixir-lang.org/docs/master/elixir/Kernel.html#macros_details

because we can link to:
http://elixir-lang.org/docs/master/elixir/Kernel.html#summary
http://elixir-lang.org/docs/master/elixir/Kernel.html#functions
http://elixir-lang.org/docs/master/elixir/Kernel.html#macros

It's more concise and easy to remember in case want to add the internal link by hand.

this simplifies the implementation of https://github.com/elixir-lang/ex_doc/issues/375 if we decide to do so.

If you guys are ok, I can submit it in the same PR.

**Comment by josevalim** [comment]
Much better. :+1:

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Dignifiedquire** [comment]
Yes please, I thought about that when implementing the current behaviour, but didn't want to change yet another thing :100:

**Comment by josevalim** [comment]
@eksperimental ping.

**Comment by eksperimental** [comment]
this is done since a day ago. I will update this soon and other changes.
