### ISSUE TITLE
Extra pages: checking for extension

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#382]
I realized we are only allowing files with only the `.md` extension.
to begin with github allows .markdown as well.

and digging deeper, i realize that markdown does not officially have any extension,
and pretty much everybody is doing their own implementation (as everything that revolves around markdown).

http://superuser.com/questions/249436/file-extension-for-markdown-files
please do read the accepted answer.

the compiled lists of possible extensions goes like:
- .markdown
- .mdown
- .mkdn
- .md
- .mkd
- .mdwn
- .mdtxt
- .mdtext
- .text

and I would expect a file with no extension to use markdown as well.

So my questions are:

1. Should we restrict the extensions used in the extra files?
2. What will happen if a .txt file is provided with a format that the markdown engine interprets as markdown code?
3. What if people want to add their own styled html page?

**Comment by josevalim** [comment]
Honestly, I would keep it simple and go with ".md". If people need anything else that you suggested, they can open up an issue, explain their use case, and we will discuss. Simple is better than trying to guess future use cases. :)

**Comment by eksperimental** [comment]
well, one thing that I just realized i overlooked is that from mix, we are create .md pages.
