### ISSUE TITLE
Release v0.10.0 before Elixir v1.1.0 is out

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#384]
Hey guys,
I propose to have a release before Elixir v1.1.0 is out (due to September 25th).

Also we need to keep in mind that from this release on the documentation will be uploaded to the [Releases Page](https://github.com/elixir-lang/elixir/releases).

Some bugs have been fixed, and more are on the way.

If you guys are OK with it, I propose to have a list of pending tasks that we consider important to have them shipped before for this new minor release.

**Comment by Dignifiedquire** [comment]
Sounds good to me :+1:

**Comment by Dignifiedquire** [comment]
Created a milestone: https://github.com/elixir-lang/ex_doc/milestones/v0.9.1

**Comment by josevalim** [comment]
Because we are changing quite some things, including the location of the extras files and links (#functions_details => #functions), the next release should be 0.10. I will update the milestones accordingly. :)

**Comment by eksperimental** [comment]
makes sense...

**Comment by josevalim** [comment]
Let's focus on fixing the remaining bugs and usability issues for 0.10.0. Don't forget to add the milestone to issues that fit this criteria but don't worry and no rush. We still have a week for Elixir v1.1. :)

**Comment by josevalim** [comment]
Folks, we only need to solve #404, #415 and #420 so we can ship 0.10.0. @eksperimental, two of them are PRs you own, so we should either just close or merge them.

@Dignifiedquire I tried to fix #415 but for some reason I couldn't make it work. If you can give it a try it is appreciated. :D

**Comment by eksperimental** [comment]
sounds great @josevalim 
I'm done with my changes,
i will send one more PR though.

**Comment by eksperimental** [comment]
alright @josevalim I have submitted a couple of PRs and  there are new more bugs (not serious ones).
I will work on the licenses, so we can include them as well.
Let me know if there is anything else.

the other thing is that if earmark get a new version (since i have submitted some PRs and they have been merged), we should update mix.exs

**Comment by josevalim** [comment]
Folks, Elixir v1.1.0 will be released this friday. @eksperimental has a PR that fixes two of the remaining bugs, @Dignifiedquire please merge them if they look good.

The other two bugs are regarding with top and scrolling to the top. Then we are ready to go! :D

**Comment by Dignifiedquire** [comment]
sorry guys you'll have to do this one without me, I'm in bed with a bad cold.

**Comment by josevalim** [comment]
@Dignifiedquire no problem. Get better soon!

**Comment by eksperimental** [comment]
sorry to hear that @Dignifiedquire. 
We can take care of this, do not worrie.
please take a rest.

**Comment by eksperimental** [comment]
@josevalim i have created a new issue https://github.com/elixir-lang/ex_doc/issues/433
I think it's quiet important since we cannot rely on linking directly.

**Comment by josevalim** [comment]
We have fixed all issues  and we are ready for release. I will let this sit through the night, so we get a new build, and tomorrow I will release. :heart:

**Comment by eksperimental** [comment]
beautiful :heart: !!!
thanks for fixing those last few bugs.

**Comment by josevalim** [comment]
And it is out! We did it folks! The best exdoc ever is out :)

**Comment by eksperimental** [comment]
yaaaaaaaaaaaaaaaaayyyyyyyy!! :tada: 

thank you @Dignifiedquire @milmazz @josevalim for pulling this one out together.
