### ISSUE TITLE
Hightlight.js bugs (some fixed in dev version)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#385]
@Sannis has been working on fixing the current 3 issues we have in posted some time ago in https://github.com/isagalaev/highlight.js/issues/730

He has submitted  a PR https://github.com/isagalaev/highlight.js/pull/927#issuecomment-139193837

He has fixed the issue with the regular expression that broke some of our pages (https://github.com/elixir-lang/elixir/issues/3670), but still is working on  the one with the string interpolation`#{ }` and comments inside sigils.

his PR has not been merged yet. If it finally is, Should we considered building it ourselves?
The author of the library has provided instructions https://github.com/isagalaev/highlight.js/issues/730#issuecomment-139274101

Version 8.8.0 has been released last week, and it will be another 5 weeks until the next one comes out.

**Comment by josevalim** [comment]
There is no reason to rush IMO. It has been broken for all months. A couple weeks won't hurt anyone.
