### ISSUE TITLE
Update highlight.js to v8.8.0

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#386]

**Comment by josevalim** [comment]
@eksperimental do we have anything we need from 8.8.0? If so, can you please take care of updating it?

**Comment by Dignifiedquire** [comment]
Updating is as simple as

```bash
$ npm update
$ gulp build --type production
```

**Comment by eksperimental** [comment]
@Dignifiedquire that's great, but... we are using a custom version of the highlight.vs, with only a small sets of languages. I don't know if this has been taken into account,
if not, i will take care of this @josevalim

**Comment by josevalim** [comment]
We definitely don't need to bring all of highlight.js, if we are doing so, we should go back to the previous style. It will in fact help us reduce the size of the generated .js file.

**Comment by Dignifiedquire** [comment]
No at the moment we are using the version published on npm, which is a bundle of everything. For using a custom bundle we should change the the dependency to the github repo (a git tag preferably) and then set as part of our build task 

```
node node_modules/webpack/tools/build.js -n elixir
```

**Comment by josevalim** [comment]
@Dignifiedquire I have no idea how to do it but  let's do that then. It will help shrink the js size.

**Comment by josevalim** [comment]
@eksperimental can you provide a list of the things we actually need from highlight.js?

**Comment by eksperimental** [comment]
It looks like can do our own custom version
https://github.com/isagalaev/highlight.js/blob/master/tools/build.js#L69-L71

 *   Bash, CoffeeScript, CSS, Diff, Elixir, Erlang, Erlang-REPL,
 *   HTML/XML, HTTP, JavaScript, JSON, Markdown, SQL.

**Comment by eksperimental** [comment]
yay! no more manually updating!!! thank you @Dignifiedquire
