### ISSUE TITLE
[search] Unexpected behaviours / Usability issues

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#390]
__I have found a few glitches.__

1) __a new search should always take you to the top of the page.__
Replicate:
visit http://elixir-lang.org/docs/master/elixir/Kernel.html
go to the bottom of the page.
Now search for "a" in the sidebar.
and you are at the bottom of the search results.

2) __clicking on a menu item (summary, functions, macros) should close the search results automatically__
Continue where you left-off in Issue 1.
Click on the sidebar menu Kernel > Summary
and you are still at the bottom of the search results and you cannot see the close button.

3) __Closing the search doesn't take you to where you were in the previous page, but to the top of it__
I don't know if this is a the expected desire.
Replicate:
visit http://elixir-lang.org/docs/master/elixir/Kernel.html#alias!/1
search for "ffoofofofofof", 
no matches returned, so hit CLOSE to close the search.
your url is http://elixir-lang.org/docs/master/elixir/Kernel.html#alias!/1 and you are the top of http://elixir-lang.org/docs/master/elixir/Kernel.html

4) __Back botton doesn't work as expected__
Replicate:
visit http://elixir-lang.org/docs/master/elixir/Kernel.html
search in your browrser for string "flatten"
click on that link.
Once the page is loaded, hit back in your browser.
and you are at the top of visit http://elixir-lang.org/docs/master/elixir/Kernel.html
not at where you were before clicking.
_Another way to replicate it:_
visit http://elixir-lang.org/docs/master/elixir/Kernel.html#--/2
and do the same,
when you hit back you are taken to http://elixir-lang.org/docs/master/elixir/Kernel.html#--/2
not to where you were.
which shows us that it is reading the url in the address bar.

**Comment by josevalim** [comment]
Related to #341.

**Comment by Dignifiedquire** [comment]
Back button is a lot of work because we have to support the `file://` protocol and check for a lot of things, the rest I'm spinning off into their own issues.

**Comment by Dignifiedquire** [comment]
Closing, as this is now being tracked in other issues

**Comment by eksperimental** [comment]
thanks a lot or looking into this @Dignifiedquire ! :+1:
