### ISSUE TITLE
[Discussion] Project Title and Logo : Where should they link to

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#391]
I would like to talk about one issue that I think it is a bit important from the usability point of view. I would like like to discuss it with you guys.
 
There is a feature of ExDoc that – to be honest –  I find a bit obtrusive.

Which is the behaviour of the whole section "Project Title, version number and logo"
When I see something like that I expect to click on the big name and logo and take me to the main page, but what is does it to take me to an user defined page.

Let's take for example elixir.
that will take you to.: http://elixir-lang.org/docs.html
It could make sense for elixir, when viewing the documentation online, 
that maintains different versions and also different docs for different apps. 

but I don't think it will work for most of the projects that that will be the documentation page itself.
If no link is provided, it will take you to the project homepage (github project, for example)

We could also say that "it's up to the user to where he wants to link" and he could link to the index page if he wanted. but what i expect when i read an ExDoc documentation is to all of them have the same behaviour.

The other issue, and I think [Elixir Docs](http://elixir-lang.org/docs/master/elixir/) are a good example.
that the main page, the most important page in that project is http://elixir-lang.org/docs/master/elixir/Kernel.html
once you leave that page. 
there is no way to go back, other than hitting the back button as many times as needed, using the search bar. or finding "Kernel" in the middle of the long list of Modules in the sidebar.

I think the Project Title, version and logo should link to wherever index.html redirects to,
in the previous example. Kernel.html

and We should add more information about the project, in the overview page, such as home page, docs page, etc.

maybe a home icon somewhere (?)

The question is. how many times I wanted to go to http://elixir-lang.org/docs.html and I did it by clicking the Title of the project. and how many timed I ended up there by mistake.
and how many times i wanted go to the Kernel page, and I had to click on the address bar and hit the backspace key and hit "enter"

What do you guys think about this issue?

**Comment by Gazler** [comment]
Perhaps the version should link to https://hex.pm/packages/phoenix so that other versions of the documentation can be found easily.

This does link ex_doc with hexdocs however.

**Comment by josevalim** [comment]
@eksperimental Luckily today this can already be configured :D So if your proposal is to make the default be whatever index.html links to, I completely agree. That's a better default.
