### ISSUE TITLE
[search] Search is broken when one of the subsections is empty

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#392]
To reproduce:

1. Visit: http://hexdocs.pm/phoenix_html/Phoenix.HTML.html
2. Try to search anything. Notice the menu item doesn't do anything when clicked too.

**Comment by Dignifiedquire** [comment]
This was already fixed in ea0adbbf8e76099fce617436d0824da06875035d

**Comment by josevalim** [comment]
@Dignifiedquire I will push a fix that ensures we always emit all nodes, so you don't need to `|| []` in the JS side.

We should also fix the markup for exceptions. Currently we generate this:

```elixir
<li role="presentation" class="disabled">Exceptions</li>
```

Notice the disabled class, but we don't style it. We should either style it or make it functional and render an empty list when clicked. :D

**Comment by Dignifiedquire** [comment]
@josevalim sounds good

**Comment by josevalim** [comment]
@Dignifiedquire another option is to hide the Exceptions thing altogether. It is already hidden from the Overview page:

http://hexdocs.pm/phoenix_html/overview.html

**Comment by Dignifiedquire** [comment]
@josevalim I like that better

**Comment by josevalim** [comment]
Fixed in master.
