### ISSUE TITLE
Docs get stuck loading when offline

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#396]
I was offline for a while.
I turned off my network connection,
It became a nightmare to check the docs.

the pages wouldn't load becuase it tries to download the fonts,
I think this one was quiet fast, 8 second!

![ex_doc_offline](https://cloud.githubusercontent.com/assets/9133420/9941254/420481aa-5d9e-11e5-8d80-79fedca1c23d.png)

**Comment by eksperimental** [comment]
@Dignifiedquire @milmazz  is there a way we can generate the same file that google provides, and load it locally if we are offline, or loading from file:// (something like this https://github.com/elixir-lang/ex_doc/pull/257).

**Comment by milmazz** [comment]
@eksperimental If we really want to provide everything locally we need to install more *npm* packages (which definitely will increase the ExDoc distribution package at the end). AFAIK right now the only font installed locally is [Font Awesome](http://fontawesome.io/). After a quick review of the [variables.less](https://github.com/elixir-lang/ex_doc/blob/eb602f92f0e3880aa3c4250a038ff9e2fd1e43f2/assets/less/variables.less#L22-L24) file we can assume that we need to install at least 3 new font families:

```less
@serifFontFamily: 'Merriweather', serif;
@sansFontFamily: 'Lato', sans-serif;
@monoFontFamily: 'Inconsolata', Menlo, Courier, monospace;
```

There are some npm packages for this fonts: [lato-font](https://www.npmjs.com/package/lato-font), [inconsolata](https://www.npmjs.com/package/inconsolata), [connect-fonts-merriweathersans](https://www.npmjs.com/package/connect-fonts-merriweathersans) (I haven't tested any of this packages), I think we can follow the same procedure as for *Font Awesome*, but I prefer to wait for @Dignifiedquire's opinion on this matter.

BTW, this kind of things can be useful for offline users or even when they are behind of firewalls (e.g. [China's Great Firewall](http://chineseseoshifu.com/blog/google-fonts-instable-in-china.html)) where Google Fonts Service and others CDNs maybe cannot work properly.

**Comment by eksperimental** [comment]
@milmazz it is a great point the one about the great firewall of china,

**Comment by eksperimental** [comment]
I have downloaded all the fonts,
```sh
curl "http://fonts.googleapis.com/css?family=Lato:400,300,700,900|Merriweather:300italic,300,700,700italic|Inconsolata:400,700" | \
grep -oP 'https?://[^)]+' | \
xargs -n 1  curl -O;
```

It's 20 fonts, 504kb
```sh
$ du -h --all | sort -nr
504K	.
40K	./BjAYBlHtW3CJxDcjzrnZCI4P5ICox8Kq3LLUNMylGO4.woff2
36K	./tI4j516nok_GrVf4dhunkg.woff2
36K	./H2DMvhDLycM56KNuAtbJYA.woff2
36K	./EsvMC5un3kjyUhB9ZEPPwg.woff2
36K	./1YwB1sO8YE1Lyjf12WNiUA.woff2
32K	./AIed271kqQlcIRSOnQH0yYlIZu-HDpmDIZMigmsroc4.woff2
28K	./EYh7Vl4ywhowqULgRdYwIHM1hBkL4m68a-ReB_y0NYc.woff2
28K	./EYh7Vl4ywhowqULgRdYwIEcqRxak6Wc5LUVz-l064SE.woff2
24K	./ZvcMqxEwPfh2qDWBPxn6nnNuWYKPzoeKl5tYj8yhly0.woff2
24K	./ZvcMqxEwPfh2qDWBPxn6nk4GofcKVZz6wtzX_QUIqsI.woff2
24K	./EYh7Vl4ywhowqULgRdYwIOR3LJ09PnibSpWhv21tZ8w.woff2
24K	./EYh7Vl4ywhowqULgRdYwIJpID8tihKRMKfpfDQ5OzSE.woff2
24K	./BjAYBlHtW3CJxDcjzrnZCCYE0-AqJ3nfInTTiDXDjU4.woff2
20K	./AIed271kqQlcIRSOnQH0yejkDdvhIIFj_YMdgqpnSB0.woff2
16K	./UyBMtLsHKBKXelqf4x7VRQ.woff2
16K	./R4a6fty3waPci7C44H8AjvY6323mHUZFJMgTvxaG2iE.woff2
16K	./ObQr5XYcoH0WBoUxiaYK3_Y6323mHUZFJMgTvxaG2iE.woff2
16K	./dPJ5r9gl3kK6ijoeP1IRsvY6323mHUZFJMgTvxaG2iE.woff2
12K	./ZvcMqxEwPfh2qDWBPxn6nuIaMZP5eRGvEWe_CNIU_oY.woff2
12K	./ZvcMqxEwPfh2qDWBPxn6nhLwFvNxpkIoVzlXSkPSYkA.woff2
```

I guess we can give the option to people to choose "CDN" to reduce the file sizes of their docs.

Maybe give the option to not to include any font, in case people want their docs to load fast, not use CDN, and also create a doc package as small as possible. Then we should do a good job at degrading fonts... if it's not already done (i haven't checked)

**Comment by josevalim** [comment]
500k is a lot to take in. Are we using all of those?

**Comment by Dignifiedquire** [comment]
We can't reduce the size of the actual fonts, we use them all. @eksperimental what's being displayed while they are trying to load? There are default fonts set to be used when google fonts are not loading, so this should just work but not as pretty.

**Comment by eksperimental** [comment]
the whole page is blank, i think I can only see the title in the title bar.

**Comment by Dignifiedquire** [comment]
@eksperimental okay that shouldn't happen :(

**Comment by Dignifiedquire** [comment]
@eksperimental should be fixed now, please test on master

**Comment by eksperimental** [comment]
same. it took 40sec the first try, and 15 seconds the second try. I see now you are loading it via css. sam problem ;-(

**Comment by eksperimental** [comment]
im test it with chrome console. DISABLE CACHING on.

**Comment by eksperimental** [comment]
I have cleared the cache, and tested it in firefox and chrome, and it never loads. firefox it never loaded the page (longer than a minute)

**Comment by Dignifiedquire** [comment]
@eksperimental It shouldn't load, it should simply show the content with system fonts instead of the custom fonts

**Comment by eksperimental** [comment]
but "never loads"i am talking about the page, not the fonts.

**Comment by Dignifiedquire** [comment]
Are you sure you rebuilt the docs correctly? (make sure to run mix clean && mix before building) I just tested on two different machines with two different browsers and all work fine offline

**Comment by eksperimental** [comment]
yes. tested it again, same story

**Comment by Dignifiedquire** [comment]
I don't understand :( can you show me a screenshot of the network request panel + the content please

**Comment by eksperimental** [comment]
![ex_doc_not_loading](https://cloud.githubusercontent.com/assets/9133420/9969543/463624fa-5e79-11e5-8600-f83f5cde9f74.png)

**Comment by eksperimental** [comment]
![ex_doc_contents](https://cloud.githubusercontent.com/assets/9133420/9969567/6d1bf1e4-5e79-11e5-8345-d21f35d98ff3.png)

**Comment by Dignifiedquire** [comment]
@eksperimental but that looks fine. That's what I meant it works and shows the content without the custom fonts, the request simply fails.

**Comment by Dignifiedquire** [comment]
My point is you can use it offline, it just looks not as pretty with the custom fonts.

**Comment by eksperimental** [comment]
it looks great, but the issue is not about how it looks but how long it takes to load, it becames unsuable

**Comment by eksperimental** [comment]
for 17 seconds i saw a blank screen. and in firefox i don't know how long. but it was a minute.

**Comment by Dignifiedquire** [comment]
Okay, can you show me a screenshot of the `Elements` panel while it's showing a blank screen?

**Comment by eksperimental** [comment]
![ex_doc_elements](https://cloud.githubusercontent.com/assets/9133420/9969777/f468fe34-5e7a-11e5-82c4-05d245aacb95.png)

**Comment by eksperimental** [comment]
should we load them at the bottom of the page, same way we did with javascript in the older version of exdoc?

**Comment by Dignifiedquire** [comment]
Hmm.. I don't understand it, why is it taking 17s for your browser to determine it can't reach the server. This is how it looks for me: (it's taking 6ms to fail the request)

![screen shot 2015-09-18 at 22 05 45](https://cloud.githubusercontent.com/assets/790842/9969849/73409e58-5e51-11e5-8bf7-b16e8d47638d.png)

how are you disabling the internet?

**Comment by eksperimental** [comment]
by choosing "Enable networking", maybe it is my computer...
i think what is does is disables the network manager.

**Comment by Dignifiedquire** [comment]
@josevalim @milmazz could you guys test this on your machines please, so we know if it's just @eksperimental machine

**Comment by eksperimental** [comment]
@Dignifiedquire I just found it it was my DNS SERVER.
not it loads in 16ms. so sorry about this. i had no idea it could be that,

**Comment by Dignifiedquire** [comment]
@eksperimental no prob, happy it works now :)
