### ISSUE TITLE
[Discussion] Think of ways to pack a smaller highlight.js file

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#400]
We need to think of ways to improve the size of the generated highlight.js file.

One way I think it will be pretty straighforward, is to detect what languages were actually used,
and based on that deliverd a precompiled version of it.
Since now we can build it ourselves, we could provide two or more "flavours"

what i proposed it to have:
1) vanilla: just support elixir language . This will be the most common file used, since the majority of the projects only use elixir and iex.
2) medium: elixir, bash, erlang, erlang-repl, markdown
3) web: elixir, bash, css, xml (html), http, javascript, json, markdown, sql
4) common: all the ones we currently support
5) full: all versions supported by highligh.js (I am not too sure about this, more on this later.)

We don't need to worry about how many options we create, because the user doesn't need to deal with this. 
We pre-compiled the minified version of this file, and based on what language is actually used in the Elixir project, only the smallest one that covers all the languages, will be used. 

regarding using the full version, i 'm not really keen on this one, but... I think we need to think of a way to let people choose other languages if they want to.
an alternative way would be to let them set their own highlight version. that will be pretty cool i think. since they can go to https://highlightjs.org/download/ and generate  themselves. Or should we do it just by using curl?

again, all ideas.
what do you guys think?

**Comment by milmazz** [comment]
@eksperimental After a few tests, between *vanilla* and *medium* there is not so much difference.

```bash
$ du -sh *.js | sort
 12K	vanilla.js
 16K	medium.js
 28K	web.js
```

**Comment by eksperimental** [comment]
what about common,
Also this will be useful as we support more language (by the way I am sending a PR for that)

**Comment by eksperimental** [comment]
great fine @milmazz: I think medium can be merged into vanilla.

**Comment by josevalim** [comment]
Given there is no difference between common and vanilla: I am :-1:.

We should not guess which features will be useful, that's the path to a complex codebase. If someone needs a custom highlight.js, they can:

1. Replace the generated one in their scripts
2. Open up an issue so we can discuss it

But supporting a customization option before we are even sure we need one is work we don't need to do. :)
