### ISSUE TITLE
[Discussion] Privacy: Loading external files

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#402]
I think we should give the option, to not to load any file from any external server like from CDN.

Personally i think if we are loading from file, localhost, 127.0.0.1 we should not do that anyways, because it is not needed.

This will be particularly important for projects or individuals concerned about privacy, surveillance, etc.
It won't make sense to create a project that integrates with TOR, and the doc pages of the project load fonts from google cdn.

I think providing an option when building the project will be good. something like --no-cnd , or --no-load-external

**Comment by milmazz** [comment]
Related with #396

**Comment by eksperimental** [comment]
in fact, now that I look at it, and think this should be the opt-in,
and if users want to user cnd, they should choose --cdn

**Comment by josevalim** [comment]
If we are talking about extra 20KB, I am ok with no CDN at all. Again, the best course for ExDoc is if we *don't need to add options to the CLI and the codebase at all*. However, if we are talking about 500k, CDN is a must.

**Comment by eksperimental** [comment]
the index page for mix. downloaded 188kb from the CDN
![ex_doc_fonts_loaded](https://cloud.githubusercontent.com/assets/9133420/9953817/61fb3376-5e0e-11e5-874e-51bb4ae709e2.png)

**Comment by josevalim** [comment]
Yes. Now imagine I am working with Phoenix, going through phoenix, plug, ecto... and every time downloading new 200kb. If we want to proceed with this, the first step is to validate if we can reduce the fonts size in the first place.

**Comment by eksperimental** [comment]
yes, that's s concern. but we can always allow people to choose to use cdn, and public websites like hexdocs.pm can take advantage of it.

We do need to also reduce the size of font-awesome. see how many icons we are using there and do something like we did for the elixir website. (I will create a new issue for this).

**Comment by Dignifiedquire** [comment]
Not a big fan of this to be honest, it adds a lot of complexity maintaining and building the fonts ourselves. If you are offline you can still use the docs just with the fallback fonts, that's what they are for.

**Comment by josevalim** [comment]
> We do need to also reduce the size of font-awesome. see how many icons we are using there and do something like we did for the elixir website. (I will create a new issue for this).

That's a great idea @eksperimental. please open up a new issue and let's close this one then.

**Comment by eksperimental** [comment]
@josevalim but I see they are different issues.
we can reduce the usage of the fonts we load from google, but that will still not solve the issue of loading them.

**Comment by eksperimental** [comment]
@josevalim or you mean we can continue it in https://github.com/elixir-lang/ex_doc/issues/396 ?

**Comment by josevalim** [comment]
Yes, exactly. The first step for this, anyway, is to see how much we can reduce the font size, and complex would that be. So we need to open up an issue for reducing the size of font-awesome and we will continue the rest in #396.

**Comment by eksperimental** [comment]
great. no worries, i will close this one as soon as the new one is created
