### ISSUE TITLE
Clicking on sidebar (#content) does not take you back to the top

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#407]
if you visit http://elixir-lang.org/docs/master/elixir/Kernel.html#content
you will think it does.
so. scroll to the middle of the page, and click on the menu "Kernel",
it will not take you anywhere.
I have tried removing the id="content" from section and put it under the div under it, and it does work.
for some reason it doesn't work when it's on div. (Chrome)

by @eksperimental

**Comment by eksperimental** [comment]
I propose to create a new element, called "top" or something better and short, which will be the div with the class "inner-content"


And I think the sidebar menu shouldn't be linking to the top of the page, but to the `H1` of the module, so it will be consistent with this behaviour https://github.com/elixir-lang/ex_doc/issues/375

**Comment by josevalim** [comment]
It definitely should go to the top because going to the h1 will be weird considering all other times we click on it, we go to the top. To be more precise: if we go to the `h1`, the content padding won't be shown, and I think we should show it.

**Comment by josevalim** [comment]
I have fixed this here: 70627480796b9e5a0d7f2980d422a580509d1ddf

@Dignifiedquire, if you think the fix above is OK, please close this issue. It is a bit weird though that it does not work when the ID is in a section.

**Comment by Dignifiedquire** [comment]
@josevalim looks good to me, as long as it's finally working :)

**Comment by eksperimental** [comment]
@josevalim im not too sure about this change, that' why i suggested creating a new id,
I haven 't seen live the changes. but from looking at this line I can see it could create conflicts
https://github.com/elixir-lang/ex_doc/blob/master/assets/less/layout.less#L41-L52

**Comment by eksperimental** [comment]
sorry, forget about my previous message. I thought it was #content, not .content.
