### ISSUE TITLE
[assets] Generate hashed assets to ensure cache busting on cdns

### ISSUE THREAD

**Issue by Dignifiedquire** [elixir-lang/ex_doc#408]
When running `gulp build --type production` it should generate 

```
app-<hash>.js
app-<hash>.css
```
and the elixir process needs to pic up those names to insert them correctly into the templates

cc @josevalim

**Comment by josevalim** [comment]
I will take this out of v0.10 milestone because it has worked like this since ever, so it can wait a bit more. In any case, @Dignifiedquire if you change gulp in a branch to emit `app-<hash>` and send a pull request, I can take care of the rest. :)
