### ISSUE TITLE
Update LICENSE file

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#413]
ref https://github.com/elixir-lang/ex_doc/pull/394/files#r39771829

We need to update [LINCENSE](https://github.com/elixir-lang/ex_doc/blob/master/LICENSE) with all the software/fonts we are shipping ExDoc with

## Tasks
- [ ] Remove github.com style https://github.com/elixir-lang/ex_doc/blob/master/LICENSE#L49-L56
- [ ] Add Tomorrow (highlightjs)
- [ ] Fonts Awesome

What else?

**Comment by josevalim** [comment]
From the Elixir side, nothing changed.

**Comment by Dignifiedquire** [comment]
According to https://fortawesome.github.io/Font-Awesome/license/ we do not need to add font awesome to the license

**Comment by eksperimental** [comment]
> Attribution is no longer required as of Font Awesome 3.0 but is much appreciated: "Font Awesome by Dave Gandy - http://fontawesome.io".

So i would personally add it, just to recognize his work.

**Comment by josevalim** [comment]
Yeah, since we already keep tons of things in License, why not? :)

**Comment by eksperimental** [comment]
so to sum up. is this all?

just to be clear, we don't need to list all the tools to we use as node_modules,
but any pice of code that goes into theminified app.js files.
Is this correct?

so what is that. I think webpack is there, what else.
