### ISSUE TITLE
Javascript Error: Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#423]
originally posted: https://github.com/elixir-lang/ex_doc/commit/2d3c9fbadaeea9d532cb614726ef8d1cbd82ee44#commitcomment-13331577

@Dignifiedquire [this line](https://github.com/elixir-lang/ex_doc/commit/2d3c9fbadaeea9d532cb614726ef8d1cbd82ee44#diff-e9cc8298549e98be96351e6176bc85d5R21
) is giving me a JS error,
```
Uncaught TypeError: Cannot read property 'top' of undefined
scrollTo
@ helpers.js?415c:21identifyCurrentHash
@ events.js?0bbb:151initialize
@ events.js?0bbb:166(anonymous function)
@ app.js?113f:20jQuery.Callbacks.fire
@ jquery.js?27d9:3099jQuery.Callbacks.self.fireWith
@ jquery.js?27d9:3211jQuery.extend.ready
@ jquery.js?27d9:3417completed
@ jquery.js?27d9:3433
```

**Comment by Dignifiedquire** [comment]
On which page/action?

**Comment by eksperimental** [comment]
It happens when the element in the #hash in the url doesn't exist.
for example http://elixir-lang.org/docs/master/elixir/Kernel.SpecialForms.html#%/2

**Comment by eksperimental** [comment]
I will try to fix this one myself. if no one else wants to jump in

**Comment by josevalim** [comment]
Please go ahead, ping me on IRC if you want to chat.
