### ISSUE TITLE
Close Search button not working

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#428]
now i get a javascript error about MetaKey

**Comment by josevalim** [comment]
How come? Which browser are you using? It is supposed to be supported on all of them: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

**Comment by eksperimental** [comment]
sorry, it is not when i use the metakey, but when i click on the button. 
the error is about the metakey

> Uncaught TypeError: Cannot read property 'metaKey' of undefined

**Comment by josevalim** [comment]
I got that. The question is the same: How come? Which browser are you using? `metaKey` exists on all mouse events on all browsers: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey

**Comment by eksperimental** [comment]
Chromium 43 / Ubuntu

**Comment by eksperimental** [comment]
firefox gives me this:
> TypeError: event is undefined

**Comment by josevalim** [comment]
I have no idea, the event is received explicitly:

https://github.com/elixir-lang/ex_doc/blob/93ee626aef65b56557914c05630f738dc6410ba0/assets/js/search.js#L117-L118

Maybe change both to `e` and see if it works?
