### ISSUE TITLE
Search has javascript errors on newly generated docs

### ISSUE THREAD

**Issue by drewolson** [elixir-lang/ex_doc#431]
I recently generated new docs for [Scrivener](http://hexdocs.pm/scrivener/Scrivener.html). If I type in a search term and hit "enter", nothing happens and I see the following javascript error in chrome's console:

<img width="1358" alt="screen shot 2015-09-23 at 3 27 51 pm" src="https://cloud.githubusercontent.com/assets/3536/10057830/e56eee3a-6207-11e5-8f04-db132c3699c6.png">

I was able to recreate this bug locally, even with a fresh `doc` folder.

**Comment by josevalim** [comment]
This has been fixed in ExDoc master.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
