### ISSUE TITLE
[Mobile] No sign of what project's documentation we are reading

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#435]
If you follow the link for the main page for the documentation:
http://elixir-lang.org/docs/master/elixir/

there is no sign of what is the documentattion project we are reading about.

![img_20150920_141614 small](https://cloud.githubusercontent.com/assets/9133420/10096049/a315dcd2-6398-11e5-8ea8-8831d25ccdf8.jpg)

the same for the default page (API reference) if no landing page is specified.
![img_20150925_151456 small](https://cloud.githubusercontent.com/assets/9133420/10096068/cf5a8176-6398-11e5-89cb-13e7ea5ebd8c.jpg)

**Comment by josevalim** [comment]
Do we have title in mobile browsers? Shouldn't the title have this information?

**Comment by eksperimental** [comment]
I don't think we do, that would take too much space. at least neither firefox nor chrome have it.

I'm thinking we could have only for the mobiel a little bar at the top with the logo and the title of the project, and the version number.
