### ISSUE TITLE
[Mobile] clicking on menu option should close menu for currrent page

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#436]
This is to keep a consistent behaviour,
when I open the menu, and select modules > and click on any of the modules (except the one  i'm reading), it opens a new page with the menu closed.

but when i'm clicking on link that takes me to the current page, no action seems to happen in the front end (it does in the back when i close the menu).

I think as soon as an element is clicked, the menu should be closed

**Comment by josevalim** [comment]
Fixed.
