### ISSUE TITLE
[Discussion] API reference should be always one click away

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#437]
I realized one thing with the new design, is that you need to click twice to read the API reference.
one click in PAGES, and then again in API references.

What I would like to propose is have API References always in the menu, at the top of the list.

Note that this breaks with the behaviour of the rest of those links that do not load a new page

I think most of the times documentations will not include any extra page, so instead of having PAGES only with API References, and being this page so important, I think We should have it at all times and if there are extra pages, we only create that menu for those.

**Comment by josevalim** [comment]
We have discussed this somewhat extensively and we decided to try the current approach. If a lot of people are complaining about it, we can revisit it.
