### ISSUE TITLE
Borks on `#{}` in doc string?

### ISSUE THREAD

**Issue by henrik** [elixir-lang/ex_doc#440]
Did not verify this against master, but https://hexdocs.pm/phoenix_html/Phoenix.HTML.html#sigil_E/2 (built against 0.9.0) shows the below.

Note how the bits after "interpolate with" are borked.

![screenshot 2015-09-27 11 52 10](https://cloud.githubusercontent.com/assets/216/10122148/3b056d52-650e-11e5-8a7d-bf7a36dcf217.png)

The input docstrings are:

```
  @doc """
  Provides `~e` sigil with HTML safe EEx syntax inside source files.
  
  Raises on attempts to interpolate with `#{}`, so `~E` should be preferred.
  … 
  """
  …

  @doc """
  Provides `~E` sigil with HTML safe EEx syntax inside source files.
  
  Does not raise on attempts to interpolate with `#{}`, but rather shows those
  characters literally, so it should be preferred over `~e`.
  …
  """
```

(From: https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html.ex#L63)

**Comment by eksperimental** [comment]
I know. there is a bug that doesn't catch a few things, I'm working on it.
It doesn't catch uppercase, nether %,

same bug as item 4, in https://github.com/elixir-lang/ex_doc/issues/321

thanks for the report.

**Comment by henrik** [comment]
@eksperimental :thumbsup: Thank you!

**Comment by ericmj** [comment]
I don't think it's related to #321 since it doesn't have anything to do with links. The bug is in phoenix_html, it should use `@doc ~S""" ... """` to avoid interpolation.

**Comment by josevalim** [comment]
@ericmj got it. We just need to use sigils in phoenix html docs.

**Comment by henrik** [comment]
Aah, makes total sense now. An interpolation bug in interpolation docs :D I believe I introduced it – sorry about that. @ericmj @josevalim Thank you!
