### ISSUE TITLE
Reloading an address with url with hash, dones't work on Chrome

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#442]
Browser: Chromium 43, Ubuntu (it does not happen in Firefox)
I'm creating an issue for this because it is starting to become annoying.

linking to a particular section of the page works
http://elixir-lang.org/docs/master/elixir/Enum.html#drop/2

but when you reload a page with a hash in the address, it still shows the same address in the url, but you are at the top of the page.

i don't know if this has to do with the fact that the address in the url gets rewritten by javascript or what (I remember reading something like that in the source code)

Related to: 
- https://github.com/elixir-lang/ex_doc/commit/ac55cdbb66f682a653a3defe271804a76217916e
- https://github.com/elixir-lang/ex_doc/issues/433

**Comment by josevalim** [comment]
Fixed.
