### ISSUE TITLE
`mix help docs` should be featured more prominently in README

### ISSUE THREAD

**Issue by ghitchens** [elixir-lang/ex_doc#443]
Currently, the only way to find the guideline to use `mix help docs` to find out more about ex_doc is to read the entire README and find the recommendation buried at the bottom of the section called "Changing the Markdown tool".   

This is confusing for new users.   I read the README 3 times and missed it because I didn't care about changing the markdown tool. 

I think `mix help docs` should be mentioned in Using ExDoc with Mix.

**Comment by milmazz** [comment]
@ghitchens I agree with you, could you please send a Pull Request with your suggestion?
