### ISSUE TITLE
Allow linking to all Headers/Sub Headers 

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/ex_doc#444]
When helping people its handy to be able to "link directly" to a section in the docs. 
<img width="1021" alt="screen shot 2015-10-03 at 11 13 59 am" src="https://cloud.githubusercontent.com/assets/100886/10263791/d71ad30c-69bf-11e5-93ef-b037acecd071.png">
Here it would be handy to have the little "link" icon popup and allow me to deep link to something like `http://hexdocs.pm/phoenix/Phoenix.Controller.Pipeline.html#section_guards` or similar. Could even be `http://hexdocs.pm/phoenix/Phoenix.Controller.Pipeline.html#section_h2_guards` or similar to namespace.

**Comment by jeregrine** [comment]
Feel free to kill this if duplicate, I noticed several issues about linking but they seemed specific to certain areas of the docs.

**Comment by eksperimental** [comment]
I think this one should be posted to earmark. I think it falls into a the category of a plugin request.
I can't  remember If i posted myself a request like this one there.
But I think it's not easy to solve
think of the heading titles, where many there will be many "examples" heading in one page, how do you identify the one you want to link to in particular. maybe with prefixing it wiht the id of the function it belogs to.

I would love this feature. We just need to think about how to solve it, but I personally thinking it will work as a plugin for earmark if we come up with something.

**Comment by jeregrine** [comment]
@eksperimental I'm thinking we could probably just do an incrementing id for each of these?

**Comment by jeregrine** [comment]
@eksperimental also what other projects do is prefix these specific cases with `label-#{dasherize(h.text)}`
ex: `http://sequel.jeremyevans.net/rdoc/files/doc/migration_rdoc.html#label-The+migration+extension`

**Comment by eksperimental** [comment]
@jering the latter solution will not work when you have two sections called "Examples", and the former one, will not work when you add a new function and #label-examples-2 becomes #label-examples-3
maybe the solution prefixing it with the funtion-id is a good one.
incrementing the id sounds reasonable for sections with the same title within the same function.

**Comment by josevalim** [comment]
I am going to close this because it is a lot of work and we already have a quite big list of things to do we which we would rather prioritize. Thanks @jeregrine  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
