### ISSUE TITLE
ExDoc.Retriever.docs_from_dir fails with modules with @moduledoc false

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#446]
I'm trying to create a fixture that lists all the functions in the Elixir project, to find out which are the functions/modules that are not being linked by the HTML formatter.
I am mimicking what ExDoc.generate_docs does, but I cannot figure out why generate_docs is working and my function is failing.

Here's the code: https://gist.github.com/eksperimental/e715af4c5c208103d1a1
It give me this error.

```elixir
iex(14)> ElixirFunctions.all                  
** (ExDoc.Retriever.Error) module String.Normalizer is not defined/available
    (ex_doc) lib/ex_doc/retriever.ex:114: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    (ex_doc) lib/ex_doc/retriever.ex:53: ExDoc.Retriever.docs_from_modules/2
```

**Comment by milmazz** [comment]
@eksperimental I think that the current behaviour is the expected, look:

```elixir
# file: lib/ex_doc/issue446.ex
defmodule ExDoc.Issue446 do
  @source_root File.cwd!

  def run(name, relative_path) do
    ExDoc.Retriever.docs_from_modules(name, relative_path |> doc_config)
  end

  defp doc_config(relative_path) do
    %ExDoc.Config {
      project: "Elixir",
      version: "1.2.0-dev",
      source_root: @source_root,
      source_beam: Path.expand relative_path
    }
  end
end
```

The following example retrieve docs from the `CustomBehaviourOne` module

```elixir
iex(1)> ExDoc.Issue446.run [CustomBehaviourOne], "_build/test/lib/ex_doc/ebin/"
[%ExDoc.ModuleNode{docs: [%ExDoc.FunctionNode{arity: 1,
    doc: "This is a sample callback.\n", id: "hello/1", name: :hello,
    signature: "hello(integer)", source: nil,
    specs: [{:::, [line: 7],
      [{:hello, [line: 7], [{:integer, [line: 7], []}]},
       {:integer, [line: 7], []}]}], type: :callback}],
  id: "CustomBehaviourOne", module: CustomBehaviourOne, moduledoc: nil,
  source: nil, type: :behaviour, typespecs: []}]
```

Also, this little helper works for Elixir:

```elixir
iex(2)> ExDoc.Issue446.run [Kernel, IO], "../elixir/lib/elixir/ebin"
[%ExDoc.ModuleNode{docs: [%ExDoc.FunctionNode{arity: 2,
    doc: "Reads `count` characters from the IO device, a whole\n`:line` or the whole device with `:all`.\n\nIt returns:\n\n  * `data` - the input characters\n\n  * `:eof` - end of file was encountered\n\n  * `{:error, reason}` - other (rare) error condition;\n    for instance, `{:error, :estale}` if reading from an\n    NFS volume\n\nIf `:all` is given, `:eof` is never returned, but an\nempty string in case the device has reached EOF.\n\nNote: do not use this function on IO devices in unicode mode\nas it will return the wrong result.\n",
...
```

HTH

**Comment by milmazz** [comment]
@eksperimental Ups, you use `docs_from_dir`, let's fix my previous answer:

```elixir
# file: lib/ex_doc/issue446.ex
defmodule ExDoc.Issue446 do
  @source_root File.cwd!

  def run(relative_path) do
    ExDoc.Retriever.docs_from_dir(relative_path, relative_path |> doc_config)
  end

  defp doc_config(relative_path) do
    %ExDoc.Config {
      project: "Elixir",
      version: "1.2.0-dev",
      source_root: @source_root,
      source_beam: Path.expand relative_path
    }
  end
end
```

Docs from ExDoc:

```elixir
iex(1)> ExDoc.Issue446.run "_build/test/lib/ex_doc/ebin"
[%ExDoc.ModuleNode{docs: [%ExDoc.FunctionNode{arity: 2, doc: "Some example",
    id: "example/2", name: :example, signature: "example(foo, bar \\\\ Baz)",
    source: nil, specs: [], type: :def},
   %ExDoc.FunctionNode{arity: 0, doc: "Another example", id: "example_1/0",
    name: :example_1, signature: "example_1()", source: nil, specs: [],
    type: :defmacro},
...
iex(2)> ExDoc.Issue446.run "../elixir/lib/elixir/ebin"
...
```

**Comment by eksperimental** [comment]
Yes , but you are giving the names of the modules. This issue happens when i try to retrieve all the docs from a directory. Same as when u execute exdoc in a project. Wht docs-from-dir dies when it finds a module with @moduledoc false, and exdoc when run on the elixir project doesnt die. If generate-docs is calling docs-from-dir same way im doing it. Thanks for looking into this @milmazz

**Comment by milmazz** [comment]
@eksperimental Please notice that my [second comment](https://github.com/elixir-lang/ex_doc/issues/446#issuecomment-146741402) use `docs_from_dir` instead of `docs_from_modules`.

Another example, in this case with some modules with `@moduledoc false`:

```bash
$ grep -nr -e "@moduledoc false" test/fixtures/*.ex
test/fixtures/function_module.ex:2:  @moduledoc false
test/fixtures/nested.ex:18:  @moduledoc false

$ MIX_ENV=test iex -S mix run
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.2.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ExDoc.Issue446.run "_build/test/lib/ex_doc/ebin"
[%ExDoc.ModuleNode{docs: [%ExDoc.FunctionNode{arity: 2, doc: "Some example",
    id: "example/2", name: :example, signature: "example(foo, bar \\\\ Baz)",
    source: nil, specs: [], type: :def},
   %ExDoc.FunctionNode{arity: 0, doc: "Another example", id: "example_1/0",
    name: :example_1, signature: "example_1()", source: nil, specs: [],
    type: :defmacro},
   %ExDoc.FunctionNode{arity: 0, doc: nil, id: "example_without_docs/0",
    name: :example_without_docs, signature: "example_without_docs()",
    source: nil, specs: [], type: :def}], id: "CompiledWithDocs",
  module: CompiledWithDocs,
...
```

**Comment by milmazz** [comment]
@eksperimental I'll close this because there is no more feedback about this issue.

**Comment by eksperimental** [comment]
sorry about the delay @milmazz , but I have been pretty much absent. that's why.
I run your code in the second example.
But I'm still getting the same error that I reported initially.

```sh
$ MIX_ENV=test iex -S mix run
iex(1)> ExDoc.Issue446.run "../elixir/lib/elixir/ebin"
```

No idea why i get that "** (ExDoc.Retriever.Error) module String.Normalizer is not defined/available"

String.Normalizer has @moduledoc false, https://github.com/elixir-lang/elixir/blob/94a07df8d3879f8555b75ba4326bc593cc0361b7/lib/elixir/unicode/unicode.ex#L414-L415

the only thing that is different about this module is that it is located outside of lib/ and under /unicode/ dir.

the beam is generated, 
```sh
$ ls ebin/ | grep String.Normalizer
Elixir.String.Normalizer.beam
```

**Comment by eksperimental** [comment]
@milmazz I will reopen it, as the still cannot find a solution for my problem, which will help me solve issue #321

**Comment by josevalim** [comment]
I still don't understand what is the issue here. `docs_from_dir` is a private function, it should not be called externally. Do you have a project where running `mix docs` crashes due to this issue?

**Comment by josevalim** [comment]
In other words, I don't know what is wrong nor what needs to be fixed.

**Comment by eksperimental** [comment]
@josevalim I don't think it's the function itself that is wrong, but something is not working as expected.
What I'm trying to do is list all the functions in all the modules in Elixir, and once I've got that I create a doc listing all these functions and see the ones that are not being linked by ExDoc.

**Comment by josevalim** [comment]
This should be fixed after we added the feature to always traverse all modules.
