### ISSUE TITLE
RFC: More options for extra pages

### ISSUE THREAD

**Issue by bitwalker** [elixir-lang/ex_doc#450]
So my only issue with ExDoc (and it's a small one), is that I can't seem to control the way extra pages are named and ordered in the sidebar. I would really like the ability to override those. Thoughts?

**Comment by josevalim** [comment]
Thanks @bitwalker. They should be ordered by the order they are defined in your mix.exs file with the same name as in the filesystem. So ordering should not be an issue... and can't you name the files as you want them to show up?

**Comment by bitwalker** [comment]
@josevalim The seem to alphabetically sorted, because they show up in a different order than I defined them. As far as naming goes, let's say I have `getting_started.md`, this is translated to `GETTING_STARTED.html` and displays as `GETTING_STARTED` in the sidebar. Perhaps I'm doing something wrong, but I'd like to be able to name it more naturally, i.e. "Getting Started".

**Comment by josevalim** [comment]
I will take a look at the ordering thing. About the naming, just call the file "Getting Started.md" and you will be fine. :)

**Comment by bitwalker** [comment]
@josevalim What about something like "Upgrades/Downgrades" or anything which uses special characters? I mean, there are workarounds obviously (like choosing a different name), but having the ability to explicitly define the name in `mix.exs` decouples the naming from how the files themselves are organized on disk.

**Comment by bitwalker** [comment]
I am of course coming from the perspective of not knowing how complicated the ask is here, so maybe this is a lot of added complexity for little benefit?

**Comment by josevalim** [comment]
I just checked and in 0.10.0 I used this:

    extras: ["guides/README.md", "guides/Getting Started.md"]

The order kept was the one I defined. Regarding the naming, pls just pick a different character for now. I know it is not ideal but there are other things we would rather focus (like supporting custom assets and so on). :)

**Comment by bitwalker** [comment]
@josevalim Ah damn, didn't check my mix.lock, I was on 0.9.0. Sorry about that!

**Comment by wsmoak** [comment]
I ran into this as well.  Perhaps ExDoc could use the text of the first `<h1>` as the menu item?  I see that it already makes sub-menu items out of the `<h2>`'s. (Lines beginning with `#` and `##`, respectively.)

**Comment by wsmoak** [comment]
Can this be reopened please?

I've got my idea of taking the text of the first `<h1>` as the menu item working in this branch:
https://github.com/wsmoak/ex_doc/tree/h1-as-title

I need help with the tests if someone has time... apparently I've broken the bit where if you configure _only_ `[main: "README"]` then README.md magically gets added to the 'extras' and the page is generated.  I don't see where that is happening though. :(

These are failing:
1) test run generates empty listing files only with extras (ExDoc.Formatter.HTMLTest)
2) test run generates the readme file (ExDoc.Formatter.HTMLTest)

I'm probably stepping on some of @milmazz's changes for removing the "extras-" prefix as well... I will rework this if that lands on master.

**Comment by milmazz** [comment]
@wsmoak I already merge #468 into `master`. Please let me know if you need some help with you proposal.

**Comment by wsmoak** [comment]
I'm re-working the "first h1 as menu item" after https://github.com/elixir-lang/ex_doc/pull/468 (to remove of the extras- prefix and allow configuring the output filename) was merged.

We have to defer calculating the title text until after the content is available, so I took title out of the config map.  If there is no `<h1>` then it falls back to the _input_ filename (current released behavior.)

I'll wait to see the outcome of https://github.com/elixir-lang/ex_doc/pull/469 (Do we want them to be able to configure the output filename? Or just the menu title? Or... add another element to the tuple and let them specify BOTH?)

Changes so far, not ready for PR yet:
https://github.com/elixir-lang/ex_doc/compare/master...wsmoak:h1-as-menu-item

**Comment by josevalim** [comment]
Thanks @wsmoak! Regarding #469, I think we should just allow both to be configured.

**Comment by josevalim** [comment]
It is important to notice that the changes in your PR make the filename reflect the path and I think it should still reflect the title (i.e. we should call title_to_filename) even if we are reading the title almost always from h1. The reason is that it is always easy to go from title to filename (API Reference -> api-reference) than the opposite.

But honestly, I think we can ignore the title from h1 for now if we add the features in #469 (allowing both url and title to be configured). If someone wants to extract it from H1, they can always do it themselves if we support #469.

**Comment by milmazz** [comment]
Fixed via #470
