### ISSUE TITLE
doctest formatted code requires four space indentation

### ISSUE THREAD

**Issue by pdilyard** [elixir-lang/ex_doc#456]
I noticed that doctests require four space indentation to be correctly formatted when you build the docs. For example, these are valid doctests that run and pass:
```
@doc """
  Returns a string where every other word has been uppercased

    iex> Schizo.uppercase "foo bar"
    "foo BAR"

    iex> Schizo.uppercase "a b c d"
    "a B c D"

  """
```
However, they will be formatted as plain text:
![image](https://cloud.githubusercontent.com/assets/1459456/10803803/850b219a-7d9a-11e5-9f83-47d035e15802.png)
If you indent the `iex>` lines with four spaces, like so:
```
  @doc """
  Returns a string where every other word has been uppercased

      iex> Schizo.uppercase "foo bar"
      "foo BAR"

      iex> Schizo.uppercase "a b c d"
      "a B c D"

  """
```
The docs will be properly formatted:
![image](https://cloud.githubusercontent.com/assets/1459456/10803842/ba99bc36-7d9a-11e5-8176-c85062c4b979.png)

Shouldn't two spaces work as well? Most Elixir code I've seen is indented by two spaces, and if they are valid doctests, it would make sense that they get properly formatted with ex_doc.

Not sure if this behavior is defined in ex_doc or in earmark, but I think it'd be nice to be able to use two spaces.

**Comment by josevalim** [comment]
We follow markdown and markdown is four spaces.

**Comment by josevalim** [comment]
Therefore, we have no plans to change. :)

**Comment by eksperimental** [comment]
Doctests do not require indentation at all.
Btw.. When u say most of the elixir code uve see uzes 2 spaces.. Which code is this?

**Comment by pdilyard** [comment]
@josevalim got it, thanks for the clarification!
@eksperimental for example, the [elixir standard lib](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/enum.ex)

**Comment by eksperimental** [comment]
Which line? All i see is four spaces

**Comment by pdilyard** [comment]
I think we're just misunderstanding each other..I was referring to the actual source code, not the `@doc`. The code itself (e.g. https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/enum.ex#L193-L195) is two spaces, which is why I thought that the `@doc`s should be two spaces as well. But I didn't realize that the Markdown specification clarified four spaces, so @josevalim's explanation makes perfect sense.

**Comment by loganhenson** [comment]
Absolutely understand the why on this, but it was unexpected and made me do a double take, luckily this issue existed 😄 

Thoughts on something like this being in the readme?

# Doc Formatting FAQ

> Q: How do I create an iex code block?
> A: Indent `4` *spaces* from the docs left margin

```
  @doc """
  This is my description...

      iex> %{ "one" => 1 ,  "fish" => 4 ,  "two" => 1 ,  "red" => 1 ,  "blue" => 1 }

  """
```

**Comment by eksperimental** [comment]
@loganhenson you are right. this is not mentioned anywhere that I know of.
Places where it should be mentioned is:

https://github.com/elixir-lang/elixir/blob/1c3a3bde539bc96c80d917fbcf3c9dc9e123860b/lib/elixir/pages/Writing%20Documentation.md#doctests
it should give an example of a test using `iex>` rather than only mention it how to do it.

https://github.com/elixir-lang/elixir/blob/a519165bbe48b52a2f50d5478d2c3ae3579ed463/lib/ex_unit/lib/ex_unit/doc_test.ex
should examplain the thing about the 4 spaces
