### ISSUE TITLE
[Mobile] entering a term in search should close menu after "ENTER" is hit

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#465]
this is similar to https://github.com/elixir-lang/ex_doc/issues/436

In my mobile browser, when I enter a search term and hit ENTER or GO in my keywboard, the menu should be closed and display automatically the search results.

**Comment by sheharyarn** [comment]
I'd like to take a shot at this. @josevalim can you point me to the commit that closes #436? It would really help me since both of them are very similar.
