### ISSUE TITLE
Add support for gettext

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#466]
I was just wondering if add support for `gettext` in ExDoc makes any sense.

@josevalim @eksperimental @Dignifiedquire What do you think?

**Comment by josevalim** [comment]
I wouldn't say so? As in other situations, I would rather wait until somebody actually needs it, then we will better know the requirements. :)

**Comment by alchexmist** [comment]
I would like to know if there is any possibility of adding support for "gettext".
I need to generate documentation for a project: English & Spanish & Galician.

A too complex solution:
[https://elixirforum.com/t/ex-doc-spanish-language-support/23140](url)

Thanks in advance for any help you are able to provide.
