### ISSUE TITLE
Hovering the function title with the mouse moves screen

### ISSUE THREAD

**Issue by edmz** [elixir-lang/ex_doc#472]
How to reproduce:

- click on any function
- scroll window so that function title is at the center of window
- hover function title with the mouse, as if you were to click on view source

**Comment by eksperimental** [comment]
What are your Browser, OS and ExDoc Versions?

**Comment by josevalim** [comment]
If you can link us to the documentation that reproduces the issue, it would be ideal. :)

**Comment by edmz** [comment]
I was browsing this function when I saw the behaviour, using latest Chrome:

http://elixir-lang.org/docs/master/elixir/Kernel.html#get_in/2

**Comment by eksperimental** [comment]
I cannot reproduce, but I know what you mean, working on a feature for the hex.pm website, i could see this happening,... but there only when I zoomed the page at a specific % it was only when it was happening.

**Comment by edmz** [comment]
Ok, this happened in my work's computer and also on my home's. Both in Chrome. I disabled some extentions and the behaviour was still there. Noticed there was a Chrome update, and restarted it. 

The behaviour disappeared and everything is fine now. 

Closing this.
