### ISSUE TITLE
Night mode version for docs

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#474]
Tim created a night-mode version of the docs: https://twitter.com/seven1m/status/664998295291359232

If I remember correctly, one of the original version of the docs by @Dignifiedquire was all black. @Dignifiedquire, do you think it is worth having a night-mode version? We could have a tiny button to flip the configuration (for example: `?mode=black`) and store the value in a cookie when no mode is set.

**Comment by milmazz** [comment]
It would be great to have that option :+1:

**Comment by pdilyard** [comment]
I'd like to take a shot at this one if no one else is working on it yet

**Comment by josevalim** [comment]
Please go ahead! You can even consider pinging Tim on Twitter for a head start. We can ask @Dignifiedquire to do a quick review once we have a PR. :)

**Comment by Dignifiedquire** [comment]
I like the idea, let's see some code ;)

**Comment by zhongwencool** [comment]
Any configuration for setting default mode?

just like
```elixir
doc_mode: night(day)
```

**Comment by lpil** [comment]
It seems this can be closed.

**Comment by pdilyard** [comment]
👍
