### ISSUE TITLE
Visual hierarchy issue with examples

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/ex_doc#475]
When viewing docs that have examples I see some visual hierarchy issues that make it more difficult for me to read the docs.
![drawing 2](https://cloud.githubusercontent.com/assets/18524/11180442/d14189c2-8c28-11e5-9c64-4bcc6a8019c0.png)

1. start of a function
1. code example for the first function
1. start of a new function

Due to the size of the `h2` element my eye is naturally drawn to the **Example** rather than the function definition as the start of a given context. To better demonstrate this, here is how I am visually breaking down the page
![drawing 3](https://cloud.githubusercontent.com/assets/18524/11180490/11ae911c-8c29-11e5-992a-a90b800704ca.png)

Scanning the docs is difficult for me because of this. I'm not sure if anyone else is having the same issue.

Possible solutions would be to reduce the visual hierarchy of the `h2` element and/or increase the visual hierarchy of the function definition.

**Comment by eksperimental** [comment]
hi @bcardarella, this specific issues has been addressed in https://github.com/elixir-lang/ex_doc/issues/419
please feel free to contribute with any comments to it.
I will close this issue as it's a duplicate

**Comment by bcardarella** [comment]
@eksperimental great! Glad to see its already on the radar :smile:
