### ISSUE TITLE
Code syntax highliter consider `fun!/n` and `fun?/n` as regexes

### ISSUE THREAD

**Issue by mememori** [elixir-lang/ex_doc#486]
Code:
```elixir
      &bar!/1
      &baz/2
```

Expected:
```html
&amp;bar!/<span class="hljs-number">1</span>
&amp;baz/<span class="hljs-number">2</span>
```

Got:
```html
&amp;bar!<span class="hljs-regexp">/1
&amp;baz/</span><span class="hljs-number">2</span>
```

Reason: When the JS matches something that starts with `!/` or `?/` it thinks that it is the start of a regex

**Comment by josevalim** [comment]
Thank you. This is an issue on highlight.js though, we just rely on it. Would you mind posting it there and likely sending a fix too? Thank you!

**Comment by mememori** [comment]
Sorry, i tought the highlight library was tailored for ex_doc :stuck_out_tongue_closed_eyes:
