### ISSUE TITLE
Functions headers should stand out more

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#487]
This issue is related to the original issue https://github.com/elixir-lang/ex_doc/issues/419

While it definitely  looks much better now after the changes introduced in #479, I think we still have the issue of having the function heading not clearly distinguishable.
As I mentioned before, having the same color as the code style, makes it difficult to stand out on its own. Specially when the previous function ends in code example as it is with most of the cases in the Kernel module. And I'm not to sure if indenting would suffice.

@Dignifiedquire proposed earlier:
> I think the solution is two fold. First reduce the size of headers like Examples to the same size as Specs, second add some indentation of the content inside the function block so the function header stands out more

@eksperimental's mockup:

![indented](https://cloud.githubusercontent.com/assets/9133420/11274507/c5805b3c-8f0b-11e5-98de-1ad7c0dccb5e.png)

/cc @Dignifiedquire @milmazz @edmz @mupkoo @josevalim @endersstocker

**Comment by eksperimental** [comment]
@edmz commented https://github.com/elixir-lang/ex_doc/issues/419#issuecomment-158102564:

+1 on the indentation.

Also, I think that the colors (the light blue and the gray) are inverted. At least for me, the blue stands out more, thus, giving more importance to the spec and the code example while the function name seems secondary.

Example of inverting colors:

<img width="771" alt="screen shot 2015-11-19 at 10 05 52 am" src="https://cloud.githubusercontent.com/assets/18996/11275898/5590fe50-8ea5-11e5-9c3e-2f8dee7f8ffd.png">'

(also, some vertical space between functions might help a bit too)

**Comment by eksperimental** [comment]
@endersstocker  commented https://github.com/elixir-lang/ex_doc/issues/419#issuecomment-158104163:
> @eksperimental Your last screenshot looks good. I would increase the vertical gap though.

**Comment by eksperimental** [comment]
So multiple solutions  that I see to help solve this issue are:
- **Indent all the text** under the function heading (as show in the first mock-up)
- **Use colors** for the heading and the code samples that will make the heading stand out more than the code
- **The vertical bar** in the function heading can be a **stronger color** so it will catch attention of the the eye easily.
- **Increase the vertical gap** between above the function heading
- **Increase the font size/weight** of the heading

**Comment by mupkoo** [comment]
I think inverting the colors + indenting the text is the best looking solution. 

Adding `margin-left: -19px;` to `.content-inner .detail-header` aligns the function name with the documentation.

![screen shot 2015-11-21 at 12 52 57](https://cloud.githubusercontent.com/assets/1788571/11318152/d8bf63a2-904e-11e5-9714-aa6a10b1e5b2.png)

**Comment by josevalim** [comment]
I like the alignment, I think it will solve the issues once and for all. What are your thoughts @Dignifiedquire?

**Comment by Dignifiedquire** [comment]
I agree the alignment changes seem to work quite well, but I disagree with switching the colors.

**Comment by josevalim** [comment]
Thank you @Dignifiedquire. @eksperimental can you please send a PR with the alignment changes? :)

**Comment by josevalim** [comment]
Those are all solved since v0.14.0.
