### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by johnhamelink** [elixir-lang/ex_doc#488]
It'd be really nice if this library could be used to generate Swagger JSON, which can then be used with various code generators and API viewers.

**Comment by josevalim** [comment]
@johnhamelink that's out of scope for this project as we have other priorities. There are some projects though that aim to bring this functionality, like phoenix_swagger: https://github.com/xerions/phoenix_swagger

**Comment by johnhamelink** [comment]
Thanks Jose, keep up the great work :+1:
