### ISSUE TITLE
Incorrect title for README.md in the sidebar

### ISSUE THREAD

**Issue by alco** [elixir-lang/ex_doc#489]
See here http://hexdocs.pm/porcelain/2.0.1/readme.html, it shows `</div>` as the title for the README page in the sidebar.

Project's [mix.exs](https://github.com/alco/porcelain/blob/7789047c949711df8ef18d4fe667f1f88fb4d67c/mix.exs#L23-L27) and [README.md](https://raw.githubusercontent.com/alco/porcelain/7789047c949711df8ef18d4fe667f1f88fb4d67c/README.md).

Changing this

```
Porcelain
=========
```

to this

```
# Porcelain
```

fixes the issue. However, this is a basic feature in markdown, so I would expect both formats to work.

**Comment by wsmoak** [comment]
That's odd... it should take the text from the first `#` or else use the filename if you haven't specified a title in the configuration.  

It does not understand the === format, it's actually looking for the `#` with a regular expression:
https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html.ex#L171

**Comment by alco** [comment]
I didn't know about the title option, I can use that.
