### ISSUE TITLE
Links to special forms with a `%` don't work in side bar

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ex_doc#490]
If you visit http://elixir-lang.org/docs/v1.1/elixir/Kernel.SpecialForms.html#%25/2 then you will not you are taken directly to the `%` macro.

If you click the same link on the sidebar it will take you to http://elixir-lang.org/docs/v1.1/elixir/Kernel.SpecialForms.html#%/2 which does not link correctly.

**Comment by pdilyard** [comment]
Has this already been fixed?

I tried to replicate the issue by creating pasting the macro from `Kernel.SpecialForms` and running ex_doc on it, but the sidebar seems to be encoding the link properly (although I can't find anywhere in the handlebars template that this is happening).

I'm not sure how often the Elixir docs get built, but it is possible that this problem will go away next time that happens.

**Comment by pdilyard** [comment]
Yeah, I can confirm that the master branch of ex_doc properly encodes the `%` character in the sidebar and in the function title.

I could see where this was going wrong at some point, as the individual parts of the sidebar are generated from a handlebars template, and the function headers are generated from an EEx template that uses: `<a href="#<%=enc_h link_id(node) %>" ...`

**Comment by ericmj** [comment]
> I'm not sure how often the Elixir docs get built, but it is possible that this problem will go away next time that happens.

The master docs: http://elixir-lang.org/docs/master/elixir are built once every day from ex_doc master.
