### ISSUE TITLE
Opportunistically Expand Sidebar Width

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/ex_doc#492]
Current state: 

![Sidebar horizontal bar showing with main content whitespace taking up 2/3 of main content](http://i.imgur.com/qnO9vmA.png)

Expected: Given the extreme amount of whitespace around the main content, the sidebar would have a max-width that takes it into account so the horizontal scrollbar isn't necessary.

**Comment by pdilyard** [comment]
I think this is a good idea, considering it could help eliminate horizontal scrolling on a lot of screens. If others agree, I'd love to make a PR for this one.

**Comment by milmazz** [comment]
I agree if the idea is just to remove the horizontal scroll in the sidebar area. Please go ahead :)
