### ISSUE TITLE
Hovering on buttons jumps you back to the #link

### ISSUE THREAD

**Issue by pdilyard** [elixir-lang/ex_doc#493]
If you have an in-page anchor (`#MY_ID`) in the URL, e.g. `http://hexdocs.pm/plug/Plug.Test.html#content`, the browser will jump back to that element ID if you hover over some buttons, such as a function header. This happens for me on Chrome for OSX only (I also tested on Firefox and Safari, but the bug didn't occur). 

Hopefully my explanation makes sense. Let me know if anyone else can replicate.

**Comment by ericmj** [comment]
I have also seen the jumping back to anchor behaviour.

**Comment by pdilyard** [comment]
I'll try taking a look into this later.

**Comment by pdilyard** [comment]
Found a thread about this in Chrome: https://code.google.com/p/chromium/issues/detail?id=561013&q=status%3Aunconfirmed&sort=-id&colspec=ID%20Stars%20Area%20Feature%20Status%20Summary%20Modified%20OS

It's been fixed in Chrome 47.0.2526.73 (stable channel of Chrome just got bumped to this last night/today), and I confirmed that this is no longer an issue.

(You do have to restart your browser for this update to occur).
