### ISSUE TITLE
Documenting how the compiler infers function arguments.

### ISSUE THREAD

**Issue by bordeltabernacle** [elixir-lang/ex_doc#498]
After a conversation with @ericmj on IRC, I learnt that argument names for functions are inferred by the compiler.  And that this can be changed by naming the argument in the code: `def func(%HashDict{} = _dict)`. (I also tried `@spec func(dict :: HashDict.t)` and variants, without success.)

This originated from the differences in functions in the, soon to be deprecated, HashDict module, where `put`, `fetch` & `size` take the argument `hash_dict` where all other functions take the argument `dict`.

It would be good to have this compiler inference, and how to work with it, documented.  I have opened an issue rather than submitting a PR as I don't know where would be best to document this, or what exactly would need to be documented.

**Comment by ericmj** [comment]
It should probably be documented on elixir since it's the compiler that does the inference.

**Comment by josevalim** [comment]
We honestly need an Elixir document about writing good documentation. It is missing and it would be the perfect place to add this. @true_droid @lexmag any idea where we could put this document?

**Comment by alco** [comment]
Can we add it as a page in Elixir docs? We currently have a single page there and it's `API Reference`. A documentation guide would fit there nicely. Having a few other things there would be nice as well, e.g. [FAQ](https://github.com/elixir-lang/elixir/wiki/FAQ),

**Comment by josevalim** [comment]
@alco beautiful idea.

**Comment by josevalim** [comment]
Moved to Elixir. Thanks everyone.

**Comment by lexmag** [comment]
As an another option we can make `Kernel.Docs` by analogy with `Kernel.Typespec` (and move `Module.add_doc/6` there).

**Comment by josevalim** [comment]
@lexmag I would even advocate making Kernel.Typespec private again and move the typespec to a page as well.

**Comment by lexmag** [comment]
@josevalim :+1: for it.

**Comment by bordeltabernacle** [comment]
Wow, I wish this is what it was like at work. :smiley: 
:heart: Elixir!

**Comment by alco** [comment]
The new page about [writing documentation](http://elixir-lang.org/docs/master/elixir/writing-documentation.html) does not address this issue still.

**Comment by bordeltabernacle** [comment]
I'd be happy to have a go at putting this in after Christmas?

**Comment by josevalim** [comment]
Thank you for the PR. :)

**Comment by bordeltabernacle** [comment]
Most welcome! :)
