### ISSUE TITLE
Include a canonical link element to avoid multiple versions in search results

### ISSUE THREAD

**Issue by vanstee** [elixir-lang/ex_doc#499]
Currently, if you search for something like "elixir enum join", you'll see a few results from different versions of the documentation, like this: 
![screen shot 2015-12-16 at 9 13 44 pm](https://cloud.githubusercontent.com/assets/228734/11859562/20010654-a43a-11e5-87de-49806b939d25.png)

To fix this we'll need to add a canonical link element to the head of each page that points to the stable version (or most recent version) of the docs. For example, we'd include this element on the Enum page of the Elixir 1.0 version of the docs `<link rel="canonical" href="http://elixir-lang.org/docs/stable/elixir/Enum.html">`. Old versions of the docs will still be searchable, but if the content your searching is also found in the stable version, that'll be returned in the search results instead.

To implement this, I'm guessing we'll want to add a config option named `canonical_root`, which is combined with the current page and included as a canonical link tag when set.

If that all sounds good I can go ahead and get started on it.

**Comment by ericmj** [comment]
We need to make sure this works with hexdocs, I suggest making it a command line option instead so `mix hex.docs` can pass it to the docs task.

**Comment by milmazz** [comment]
@vanstee Are you currently working on this feature?

**Comment by vanstee** [comment]
@milmazz Oh nope. I'll try to get around to doing it at some point. But if anyone wants to go ahead and take it, feel free.
