### ISSUE TITLE
Add special notation to defprotocol and defimpl

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#5]
We should detect if a module is a defprotocol or defimpl and use a special notation for it.

**Comment by MaSven** [comment]
So, what was the outcome of this?

**Comment by wojtekmach** [comment]
For `defprotocol` we have this:

<img width="775" alt="image" src="https://user-images.githubusercontent.com/76071/150121783-a7b42572-3126-4a2c-9c23-2fe20c8b7f7a.png">

I don't think we have anything for `defimpl` as these tend to not to be documented.
