### ISSUE TITLE
Can't keep the sidebar at a narrow screen

### ISSUE THREAD

**Issue by niku** [elixir-lang/ex_doc#505]
At a narrow screen, we can open the sidebar by clicking button.

We can keep the sidebar on [v1.1 docs](http://elixir-lang.org/docs/v1.1/elixir/Kernel.html).
We can't keep the sidebar on [master docs](http://elixir-lang.org/docs/master/elixir/Kernel.html), the sidebar close soon without any operation.

![untitled](https://cloud.githubusercontent.com/assets/10890/12040092/39959cfa-aea9-11e5-9023-9f6c9b0779e7.gif)

**Comment by josevalim** [comment]
Thank you for the report! This may have been caused by #492. @Havvy can you please investigate? We will do a new release as soon as this is fixed. :)

**Comment by Havvy** [comment]
CC @pdilyard who wrote the patch.

**Comment by nscyclone** [comment]
I suppose this issue is not reproducible anymore after [the latest changes to sidebar animation](https://github.com/elixir-lang/ex_doc/pull/544) and thus should be closed.

**Comment by josevalim** [comment]
Thank you @nscyclone!
