### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dayvsonlima** [elixir-lang/ex_doc#506]
Hi,
It would be nice with it's possible translate the elixir-guide guide. I'm member from [phoenixframework-Brazil](https://github.com/phoenixframework-Brazil). We are translating the phoenix guide and we can help translate this style guide for portuguese.

**Comment by victorlcampos** [comment]
+1 =)

**Comment by josevalim** [comment]
Thank you @dayvsonlima! The Elixir guides are hosted here: http://github.com/elixir-lang/elixir-lang.github.com - You are free to translate them and host them. :) Bom ano novo!
