### ISSUE TITLE
Generate anchors for subtitles

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#508]
Currently anchors are only generated for sections and functions. It would be great if they could be also generated for subtitles. This is especially important for moduledocs, as sometimes they are quite long and it's hard to point someone to a specific point.

**Comment by RobertDober** [comment]
I agree with the usefulness of this feature but forgive a, maybe stupid, question. Subtitles, are they not part of the verbatim text passed to Earmark? And if that is the case that would be an Earmark issue, right?

**Comment by RobertDober** [comment]
Ah I understand now, you post process the HTML so that you do not depend on the underlying conversion library.

**Comment by joshprice** [comment]
I've been also wanting this for a while, for exactly the reason you mention. It often comes up that you need to reference a specific section within a moduledoc from other documentation.

Happy to take a look into this, if nobody else has.

**Comment by josevalim** [comment]
:+1: for generating them for module docs!

**Comment by joshprice** [comment]
Would love some feedback on my solution for this #559
