### ISSUE TITLE
Anchor for <<>> is not working in Firefox

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#509]
In the documentation for [`Kernel.SpecialForms.<<>>/1`](http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#%3C%3C%3E%3E/1) the generated anchor is not linking to the correct section in Firefox 43.0.4.

**Comment by milmazz** [comment]
@michalmuskala Could you please try the following: In the sidebar area, click `Macros` under `Kernel.SpecialForms` and then follow the `<<>>/1` link. This procedure works for you?

**Comment by michalmuskala** [comment]
Yes, this does work.

**Comment by josevalim** [comment]
@michalmuskala can you please confirm if this is still a bug?

**Comment by michalmuskala** [comment]
I can confirm this is a bug with firefox 49.0.1 on macOS 10.12

**Comment by jparise** [comment]
These symbols appear to exhibit the same problem:

- `%/2`
- ` %{}/1`
- `^/1`
