### ISSUE TITLE
modules with :atoms for names are not included when generating docs

### ISSUE THREAD

**Issue by talentdeficit** [elixir-lang/ex_doc#514]
```elixir
defmodule :example do
  @moduledoc """
  this module will not be included when generating docs for a project
  """  
  def ex(), do: true
end
```

i believe the pattern [here](https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/retriever.ex#L48) is the culprit. changing it to "*.beam" solves this issue but i am unsure of the implications of including all beam files when generating docs

**Comment by milmazz** [comment]
I think that the pattern `Elixir.*.beam` tries to avoid some clashes with Erlang's modules, which certainly do not follow the same documentation syntax that we use in Elixir.

**Comment by allyraza** [comment]
modules with `:atom` name does not compile under default Elixir namespace this is going to be bit tricky

**Comment by allyraza** [comment]
I have had the time to look into this, I think converting the pattern to `*.beam` should fix the problem I don't think it will conflict with erlang modules since all the deps are compiled in separate dir

**Comment by allyraza** [comment]
It actually does conflict with erlang modules
