### ISSUE TITLE
specs should be displayed in the same order as they have been defined

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#519]
See the example of Elixir.Range.range?/1

https://github.com/elixir-lang/elixir/blob/b6dc389f5e3eb2286885c172009333ef414d7860/lib/elixir/lib/range.ex#L73-L74
```elixir
@spec range?(%Range{}) :: true
@spec range?(term) :: false
```

and how it's showed in the docs
http://elixir-lang.org/docs/master/elixir/Range.html#range?/1
```
Specs:
range?(term) :: false
range?(%Range{first: term, last: term}) :: true
```

the order changes the meaning.

**Comment by ericmj** [comment]
The order of specs does not change it's meaning, they do not work like match patterns. The spec is actually wrong here.

To quote the erlang docs:

> A current restriction, which currently results in a warning (not an error) by the compiler, is that the domains of the argument types cannot overlap.

We need to figure out why this warning isn't triggered for elixir.

The order of specs should probably be preserved for documentation though.

**Comment by eksperimental** [comment]
thanks @ericmj I will submit an issue to elixir then.
I leave this issue still open as we should preserve the order, as you mentioned.

**Comment by bjfish** [comment]
There is a dialyzer warning produced:
```
lib/range.ex:73: Overloaded contract for 'Elixir.Range':'range?'/1 has overlapping domains; 
such contracts are currently unsupported and are simply ignored
```

**Comment by ericmj** [comment]
Seems like the spec is still not fixed. Would you be willing to send a PR to elixir fixing it @bjfish?

**Comment by bjfish** [comment]
@ericmj I think a PR with a fix just got merged in here: https://github.com/elixir-lang/elixir/pull/4432

**Comment by eksperimental** [comment]
Thank you @bjfish for fixing both issues
