### ISSUE TITLE
DuckDuckGo Docs Implementation Question

### ISSUE THREAD

**Issue by pjhampton** [elixir-lang/ex_doc#522]
I'm currently implementing the docs as a [FatHead IA](https://duck.co/ia/view/elixir) into the DuckDuckGo search engine so people can have a quick reference that maybe don't have access to their command line, like this PHP example:

![screen shot 2016-03-16 at 11 13 10](https://cloud.githubusercontent.com/assets/8960296/13810712/142688f6-eb69-11e5-92eb-1cc2ba3231d8.png)

I'm just going to parse the master folder in github.com/elixir-lang/docs nightly (i think). I'm confused as to what hexbob is doing? Would there be a better place to retrieve the information from?

Thanks! :cake: :cake: :cake: :cake: :cake:

**Comment by ericmj** [comment]
Hexbob simply generates nightly docs from the elixir master branch. Wouldn't it be better to show the stable docs though?

**Comment by pjhampton** [comment]
I suppose you are right - this would be easier to maintain. Many thanks :+1:
