### ISSUE TITLE
Generator blindly wipes directory

### ISSUE THREAD

**Issue by seancribbs** [elixir-lang/ex_doc#530]
On https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html.ex#L18, the `File.rm_rf! output` call wipes the `doc` directory regardless of contents. This is an annoyance when the directory contains a git repository for publishing docs to Github Pages, because the `.git` directory is removed as well.

It would be nice if the generator only deleted files and directories it might have created.

**Comment by josevalim** [comment]
Good point. Any suggestions? We could try to find out what was generated but it may be error prone. For example, we could add a new file in the future and forget to list it for removal. Maybe we could erase everything except dot files/directories?

**Comment by seancribbs** [comment]
Perhaps it could just be an whitelist option? Like `docs: [keep: [".git"]]`

**Comment by seancribbs** [comment]
I'm also ok with ignoring dotfiles by default.

**Comment by ericmj** [comment]
I think we should just ask the user if we should clean `doc`.

**Comment by josevalim** [comment]
If we don't clean we leave stale modules, stale static pages and friends
around.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
There can be good reasons for developers to keep files in `doc`, for example including extra documentation.

**Comment by milmazz** [comment]
@seancribbs @josevalim @ericmj I think that `ExDoc` can create a new file (e.g. `#{output}/.build`), in that file `ExDoc` keeps track of all the files generated, then, at the beginning of another build process `ExDoc` just delete all the files listed in `#{output}/.build`, if that file does not exist `ExDoc` will delete `#{output}` directory. Wdyt?

**Comment by josevalim** [comment]
@milmazz sounds good to me!
