### ISSUE TITLE
Left-side navigation menu is broken on small screens (mobile)

### ISSUE THREAD

**Issue by austinsmorris** [elixir-lang/ex_doc#532]
For some libraries, if your screen is small enough (small on desktop, always on mobile), the left side menu will not stay open. If you click the hamburger to expand the menu, it slides out and disappears, making it unusable.

For example, these are broken:
https://hexdocs.pm/absinthe/Absinthe.html
https://hexdocs.pm/absinthe_relay/Absinthe.Relay.html

But others, like Ecto, work ok:
https://hexdocs.pm/ecto/Ecto.html

The problem occurs on any browser width below 768px.

I previously opened an issue at hexpm/hex_web#321, but since this issue seems to be content specific, they suggested I open the issue here.

**Comment by bruce** [comment]
@austinsmorris Thanks for reporting this for https://github.com/absinthe-graphql/absinthe. We appreciate it!

**Comment by michalwarda** [comment]
@bruce, @austinsmorris I built it using the current master branch with the sidebar animation rewritten https://github.com/elixir-lang/ex_doc/tree/8a2345cd63b5b4e83d688599103bcee5427e129e and it's working a-ok! I guess the issue should stay until the next release but just so you know on master It's working fine now.

**Comment by josevalim** [comment]
If you have verified it, we can close this and reopen if the issue persists. Thank you!
