### ISSUE TITLE
[Search] Results should include PAGES names

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#534]
Search should be consistent and inclue PAGES (same as for the other main elements in the menu)

If you search for "typespecs" it should list the [Typespecs](https://hexdocs.pm/elixir/typespecs.html) page but it doesn't: https://hexdocs.pm/elixir/search.html?q=typespecs

**Comment by josevalim** [comment]
Fixed as we know have full text search.

**Comment by wojtekmach** [comment]
Should we include page titles in autocomplete suggestions? E.g. it would show "Operators" here (maybe with a "Page" subheading or something)

<img width="508" alt="image" src="https://user-images.githubusercontent.com/76071/55543030-88cb8d00-56c8-11e9-95a6-49ca9b79f1dd.png">


Spoken with @archdragon and it should be relatively straightforward, what do you think @josevalim?

**Comment by josevalim** [comment]
I thought about this and I think that, in contrast to modules and functions, most people won't know the exact name of the page, nor we want to guarantee the titles stay the same, so I think using the full text search or the menu is best.
