### ISSUE TITLE
Improving sidebar animation.

### ISSUE THREAD

**Issue by michalwarda** [elixir-lang/ex_doc#540]
At the moment the sidebar animation is handled via jQuery updating the width/flex-basis of sidebar.
It causes unnecessary repainting of the page while the animation is occurring. 
Moreover currently implemented animation causes content of the sidebar to stutter while it's opening / closing.

Although trying to change this on the desktop version of the page doesn't give too much performance gain(because `width` transition requires repainting), on mobile the gain is stable 60 fps even on the slower devices.

I have a working implementation of the animations and the statistics show arround 10 fps gain on desktop (from 30 to 40) and super stable 60fps on mobile (Macbook Pro 13 Early 2015).

If there will be any interest in improving the animation I would be pleased to submit a PR changes.

**Comment by eksperimental** [comment]
My opinion is go for it!

**Comment by michalwarda** [comment]
Unfortunately as I now tested the master build I noticed that on some screens the sidebar is not entirely covered by the content background. I prepared a fix for it on a new branch. I'm sorry for the inconvenience but I didn't notice it previously :/
