### ISSUE TITLE
Search results color in night mode is hard to read.

### ISSUE THREAD

**Issue by michalwarda** [elixir-lang/ex_doc#546]
Currently in _night mode_ the visited search result links and top right `x` are in black just like on screen:
![night_mode_colors](https://cloud.githubusercontent.com/assets/8479334/15799678/8b0918b4-2a64-11e6-9394-59eb0d0a22dc.png)
_from https://hexdocs.pm/absinthe/Absinthe.html_

Because of that the contrast is too small to easily read the content.

I think it would be much nicer if we had different colors for the links and `x` in _night mode_. 
For example `#d2d2d2` just like other links:
![night_mode_colors_suggestion](https://cloud.githubusercontent.com/assets/8479334/15799740/5551dfb0-2a66-11e6-93ca-5acd32be757a.png)

This won't show which links have been **visited** but it already doesn't on the _daily mode_.

I can make a PR implementing the new font colors later today or tomorrow if you think it's a good idea.

**Comment by josevalim** [comment]
Looks good to me!

**Comment by eksperimental** [comment]
just off-topic but still worth mentioning:
it looks weird the search results with the screen is really wide.
Woudln't it look better left aligned?
/cc @dignifiedquire
