### ISSUE TITLE
Night Mode on Elixir 1.3 docs seems broken

### ISSUE THREAD

**Issue by thorsten-mueller** [elixir-lang/ex_doc#556]
Not sure if this is actually an issue with ExDoc. But for the Elixir v1.3 documentation night mode has light grey text on a white background. Only the sidebar and code sections still have dark background. (It was built with ExDoc v0.11.4)

Right now for the old docs v1.2 (ExDoc v0.11.4) and master docs v1.4.0-dev (ExDoc v0.12.0) night mode works as it should.

The reason as far as I can see is that in the `<section id='content'...>` the following `<div class='content-outer'>` is missing. So the CSS for `body.night-mode .content-outer {background: #212127;}` isn't active. If I add this div with the browser tools everything seems to work as it should.

**Comment by josevalim** [comment]
It is my fault, I generated them using an old ex_doc version, I will fix it. :) Thank you!

**Comment by josevalim** [comment]
Done!
