### ISSUE TITLE
Formatting of function names are visually deceiving

### ISSUE THREAD

**Issue by tzveeJ** [elixir-lang/ex_doc#557]
I have visual trouble with every set of docs and I finally decided to think about why. It is because the highlighting and formatting of function names do not follow standard practices for titles. A few "rules" are broken which make it hard to understand that each function name is a title.

1. Function names are indented but they should not be.
2. Each function name appears in a box, which implies that it is an independent component of information, even though it is a title (boxes are great for code samples but not for titles!)
3. The font size of function names is the same as the font size of the description below, but generally titles should be a larger font.

I would love to see someone more involved at the formatting come up with a solution.

**Comment by josevalim** [comment]
> I would love to see someone more involved at the formatting come up with a solution.

If someone believes they can improve the current layout, please do send proposals and PRs. Other than that, I am closing this issue since otherwise it is very easy to end-up on a discussion of "how we think the layout should be" without anyone working on actual samples. :)
