### ISSUE TITLE
Make night mode switch link more obvious

### ISSUE THREAD

**Issue by joshprice** [elixir-lang/ex_doc#558]
Night mode is awesome. As discussed in #491 the night mode switch ended up right at the bottom. 

However I had no idea it was there though, as I'd never noticed the link. The positioning is usually not obvious because most module docs are quite long. This means a lot of scrolling to get to the bottom of the docs to find the toggle eg. http://elixir-lang.org/docs/stable/elixir/String.html

It'd be nice to move this to the top to make this more obvious, and show that it's available (I only found out about it when reading through ex_doc PRs).

**Comment by joshprice** [comment]
I've made a twitter poll to understand how people currently use this, whether they've discovered it and whether they think they would use the feature: https://twitter.com/joshprice/status/745762336145760256

**Comment by josevalim** [comment]
It is really tricky because it is a button you need to learn about it once
and press once, so once you find out it doesn't warrant first class space
at the sidebar or at the top, but we need to make it somewhat more
discoverable.

On Thursday, June 23, 2016, Josh Price <notifications@github.com> wrote:

> I've made a twitter poll to understand how people currently use this,
> whether they've discovered it and whether they think they would use the
> feature: https://twitter.com/joshprice/status/745762336145760256
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/ex_doc/issues/558#issuecomment-227949182>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbgTkVrVSitnNdrWN2M-72Z1exp13ks5qOhB8gaJpZM4I8U5a>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
I would create a night mode icon (crescent moon with a start) at the right bottom of the left menu, and when the menu is collapsed, aligned with the hamburger icon,.

but only visible when you roll over.

on night mode the moon changes to a sun.

and still show the text at the bottom of the page, as we are doing right now.

**Comment by joshprice** [comment]
@eksperimental I like this approach, seems to have some dependency on what is happening in #564

**Comment by joshprice** [comment]
Transcribing the result of the [twitter poll](https://twitter.com/joshprice/status/745762336145760256) back in here for reference. From 226 respondents:

- **16%** Yes, I use regularly
- **20%** Yes, but never use
- **41%** No, I want this
- **23%** No, but don't care

Summarising the findings:

- **36%** Had already found night mode  
- **64%** Did not know about night mode

Of those who knew of night mode:
- **44%** Use it regularly
- **56%** Don't use it

Of those who were not aware of night mode:
- **64%** Would like to use it
- **36%** Don't think they would use it

#### Conclusions

- The night mode feature is hard to find with ~2/3rds of users not finding it
- Roughly half of users who know about night mode do use it regularly
- Almost 2/3rds of users who did not know about night mode want to use it (41% of total respondents)
- There may be a potential over-reporting of future usage, when compared to actual usage but even accounting for this there is still significant user benefit

#### Learnings

- Twitter polls are an interesting way to data drive Feature/UX decisions. A++ would poll again.

#### Actions

- This issue clearly needs to be solved (@eksperimental's solution seems like a good option and it's the only one so far)

**Comment by eksperimental** [comment]
Thank you for the survey. It's very useful stats.
Just to mention that my solution does have one drawback and it is when the is fully expanded, then the icon will get on the way if we try to reach for the items at the very bottom of the list. May be we should place it agains the scroll bar of the menu, where it wouldn't get on the way. or find a better spot.
