### ISSUE TITLE
Search results should differentiate functions from callbacks and types

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#560]
I 'm not sure if we should do this all the time, but when more than one result with the same are displayed, we are not telling the user which one is which.

search for "handle_body" in the Elixir docs.

![ex_doc_funs_callbacks](https://cloud.githubusercontent.com/assets/9133420/16322643/badc5d5c-39ce-11e6-95cc-9191eed7d7b2.png)

**Comment by josevalim** [comment]
Good catch!

**Comment by eksperimental** [comment]
so should we write in parenthesis `(callback)` and `(type)` in all search results, or only when they share the same name with another function/callback/type within the same module?

**Comment by josevalim** [comment]
I think we can write (callback) and (type) for those always as they should not be super common.

**Comment by antipax** [comment]
Going to grab this, lemme know if not OK
