### ISSUE TITLE
Markdown errors cannot indicate source location (Earmark related)

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/ex_doc#561]
We have been fixing issue https://github.com/pragdave/earmark/issues/66 and face https://github.com/pragdave/earmark/issues/77 now, which is quite normal. In order to close the later some joint effort would be needed. Earmark would need to add the `start_linenumber` value to the `%Options{} struct` and ex_doc would need to adapt the call accordingly.

On the same token it would be nice to use the `filename` option too.

**Comment by josevalim** [comment]
Thank you @RobertDober. In Elixir we use the options `:line` and `:file`. Would you be ok with sticking with those or do you prefer `filename` and `start_linenumber`?

**Comment by RobertDober** [comment]
https://github.com/pragdave/earmark/issues/77 updates accordingly

**Comment by eksperimental** [comment]
thank you @RobertDober for looking after this issue.

**Comment by RobertDober** [comment]
@eksperimental glad I could help, unfortunately we still need to integrate the fix on the ex_doc side.

I am afraid my PR will just not cut it, as my understanding of ex_doc is very superficial.

There is one other issue though (please refer to https://github.com/pragdave/earmark/issues/79)

as long as we do not flood the `mix hex.docs` with thousands (of unjustified) warnings you will never know where you really forgot your backquotes in the file. I have therefore opened an issue https://github.com/pragdave/earmark/issues/79 in Earmark which would allow you to force these warnings. Not sure if it worth it though, your and anybody else's opinon would be appreciated.

**Comment by eksperimental** [comment]
thank you @RobertDober,
I will start try to get my hands on this and see if we can come up with something, i had been busy with other PRs, thank you so much for looking after this, I will get back to you whenever i get my hands on it

**Comment by RobertDober** [comment]
Sure thanx!

**Comment by crertel** [comment]
Hey folks!

Just pinging to see what the progress on this was--I see an open PR from @RobertDober as #565.

Anything else needing to be done?

**Comment by josevalim** [comment]
This is in master! :heart:
