### ISSUE TITLE
Hamburger icon is not clearly visible when left menu is hidden

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#562]
![ex_doc_humburger_not_visible](https://cloud.githubusercontent.com/assets/9133420/16343482/945119dc-3a61-11e6-9b68-271564ae2fed.png)

and the wider your screen resolution, the more lost it gets.

I don't know if we should have a different icon with darker lines,
or if we should put it a dark purple circle.

another issue to take into consideration while fixing this is https://github.com/elixir-lang/ex_doc/issues/434

**Comment by milmazz** [comment]
@eksperimental Right now I don't have a machine where I can test this commit https://github.com/milmazz/ex_doc/commit/92bf78dbf2159a2b5d41324d29502742d06011c5. But, if you can run a quick test, please let me know what do you think.

/cc @dignifiedquire

**Comment by eksperimental** [comment]
@milmazz could you please tell me how can i create a branch from your commit into my local repo?

**Comment by josevalim** [comment]
Closing in favor of the PR.
