### ISSUE TITLE
Improve callback typespecs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#563]
There's a situation, when you want to define variable names in a `@calback` definition

`@callback init(opts :: Keyword.t) :: Macro.t` will generate

> **init(opts)**
> Specs
> init(opts :: Keyword.t) :: Macro.t

which is fine

`@callback init(_opts :: Keyword.t) :: Macro.t` will generate

> **init(_opts)**
> Specs
> init(_opts :: Keyword.t) :: Macro.t

I think the arg should be "opts" in the function description.
and Ideally i would hope to "_opts"  to not show up and leave the spec as for the rest of the functios,
> init(Keyword.t) :: Macro.t

as of now there is not way I can think of of generating 
> **init(opts)**
> Specs
> init(Keyword.t) :: Macro.t

**Comment by ericmj** [comment]
What's the reason for using underscore in type variables `@callback init(_opts :: Keyword.t) :: Macro.t`?

**Comment by eksperimental** [comment]
I would expect it to work in a similar way was with functions.

I would like to have a way to show a variable name in the callback definition, and not to show any variable in the specs

**Comment by ericmj** [comment]
> I would expect it to work in a similar way was with functions.

But as it is right now there is no reason for it in callbacks. There is a reason for having underscores in function arguments though. If someone sees `_foo :: bar` they are going to wonder why `_foo` is underscored and there would be no reason for it.

> I would like to have a way to show a variable name in the callback definition, and not to show any variable in the specs

So `_opts :: foo()` is your proposal for doing that? It's not really clear in the issue.

It seems like an arbitrary rule that no one is going to know about unless they read it in some docs somewhere. We already have the issue that people don't really know how signatures are generated in docs, this would make it even more complicated.

I don't think there's a problem with including the argument name in the typespec. It's useful if you have many arguments to quickly see which type maps to which argument. If you don't have many arguments it's not that much extra noise.

**Comment by eksperimental** [comment]
well, true
maybe we should write the specs in a different way.
so instead of having 
```elixir
handle_expr(buffer :: Macro.t, marker :: String.t, expr :: Macro.t) :: Macro.t
```

we can have something more readable as 
```elixir
handle_expr(buffer, marker, expr) :: Macro.t when buffer: Macro.t, marker: String.t,  expr: Macro.t
```

**Comment by ericmj** [comment]
To me the first one is more readable, but I am guessing that may depend on the formatting of the latter and will be different for everyone.

The erlang docs are an example of where I think this looks good. http://erlang.org/doc/man/lists.html

**Comment by josevalim** [comment]
I think the current approach is fine because the types do not necessarily should follow the same naming as the function definitions.

**Comment by whatyouhide** [comment]
I'm on @ericmj's side when it comes to this, no reason to use `_opts` in the callbacks instead of `opts`, so I think we shouldn't support this. Also, I always found Erlang types a bit "dispersive" 😛
