### ISSUE TITLE
Add ability to generate top-level docs in umbrella project

### ISSUE THREAD

**Issue by noam87** [elixir-lang/ex_doc#567]
Currently in an umbrella project, docs will be recursively generated for sub directories. However, sometimes it would be useful to generate top level documentation for the whole umbrella project.

**Comment by josevalim** [comment]
@noam87 yup, I think this is fair and it should not be hard. If someone would like to contribute it, please go ahead. :)

**Comment by josevalim** [comment]
For those interested in implementing it, we would need to make the ExDoc task non-recursive and then get the compilation path for all umbrella children.
