### ISSUE TITLE
Add titles of custom pages to search

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#569]
It might even make sense to add second-level subtitles in custom pages and moduledocs.

An example is searching for "typespecs" in elixir docs that yields currently no results, but before was giving the `Kernel.Typespecs` module - the documentation was moved to a separate "Typespecs" page.

This is partially related to https://github.com/elixir-lang/ex_doc/issues/508

**Comment by eksperimental** [comment]
Hi @michalmuskala, this is a duplicate of #534

**Comment by michalmuskala** [comment]
I'm so sorry. I should improve my search-fu.
