### ISSUE TITLE
Autogenerated README.md title contains raw markdown

### ISSUE THREAD

**Issue by deadtrickster** [elixir-lang/ex_doc#571]
Take a look here: https://hexdocs.pm/prometheus_plugs/readme.html. Apparently badges in header cause  this.

**Comment by eksperimental** [comment]
It also affect the items in the menu.

this is the offending code:
https://github.com/deadtrickster/prometheus-plugs/blob/master/README.md

`# Prometheus Plugs [![Hex.pm](https://img.shields.io/hexpm/v/prometheus_plugs.svg?maxAge=2592000?style=plastic)](https://hex.pm/packages/prometheus_plugs)`

**Comment by antipax** [comment]
I'm not sure how we should fix this. It is not appropriate to include an image or link in the title, for sure, but what about the sidebar?

**Comment by josevalim** [comment]
@antipax currently we generate the sidebar based on the markdown or html?

**Comment by antipax** [comment]
@josevalim it's based on the markdown: https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html.ex#L179

**Comment by josevalim** [comment]
@antipax one option is to make it based on the h2 (html) and then prune other tags although I am not sure.

**Comment by antipax** [comment]
@josevalim I'm not sure how we would do that from Elixir? It seems like it would be error-prone and complex. I'm thinking it might be better to recommend using the `:title` option to override the extracted title for these cases.

**Comment by josevalim** [comment]
Sounds good to me!

**Comment by antipax** [comment]
So then we can close the issue, I suppose?

**Comment by josevalim** [comment]
Yes, if a solution isn't trivial, I think closing is the best. The only other option I can think is filtering on the HTML side of things.
