### ISSUE TITLE
Switching between night mode and day mode changes position in page

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#572]
You can clearly see this if you go to the bottom of a really long page [Enum](http://elixir-lang.org/docs/stable/elixir/Enum.html) module page. Scroll all the way to the bottom, and click SWITCH TO NIGHT MODE. You will see that the page moved.
You need to scroll again to be able to see the SWITCH TO DAY MODE link.

This affects the usability of the page.
You can barely see if in small pages, but as you scroll down you can see it's a pixel or two off, and at the end of a long page it has accumulated to a considerable amount of pixels.

I'm not sure if this could be the highlightjs theme for night mode used, because from the CSS I haven't seen code that changes the sizes deliberately.. but i haven't had the time to look thoroughly though. 
but we need to guarantee that everything shares the same size in night mode as in day mode. 

/cc @pdilyard

**Comment by pdilyard** [comment]
A good test to do would be to remove all the code examples from a long page and see if it still happens. If the issue goes away, it therefore must be due to the highlightjs theme, otherwise, it's something else.

**Comment by eksperimental** [comment]
I found an easier way, 
I replaced this line in `night.less`
`@import 'npm://highlight.js/src/styles/tomorrow-night';`
with
`@import 'npm://highlight.js/src/styles/tomorrow';`

the problem remains.
so it's somewhere else.

**Comment by nscyclone** [comment]
I've found the reason of such a behavior. It's the `border: none;` rule in the `.content-inner .specs .specs-list pre code` selector.
Now the question is how should we fix it? Probably the simplest way is to show the border again in the day mode (suggested in the 2nd screenshot below) or remove it from the night mode (suggested in the 4th screenshot below).
Here are the screenshots:
* [day mode without border](http://i.imgur.com/INH2pnQ.png?1) (used now);
* [day mode with border](http://i.imgur.com/9P8xQz6.png?1);
* [night mode with border](http://i.imgur.com/Re1dPRd.png?1) (used now);
* [day mode without border](http://i.imgur.com/PUwZ9T8.png?1).
I can open a PR once it will be decided.

**Comment by josevalim** [comment]
@nscyclone awesome catch!

@dignifiedquire which approach do you prefer? I think you decided to remove the border so we call less attentions to specs?

**Comment by aphillipo** [comment]
My practice it just to set such a border to be 'transparent' in such situations meaning the the area taken up will be identical but it won't be displayed.

**Comment by eksperimental** [comment]
I was about to recommend same thing that @aphillipo, to set border as same color as background, but I wasn't aware of border being transparent, so I would go with that then!

**Comment by eksperimental** [comment]
thank you @nscyclone for finding this

**Comment by nscyclone** [comment]
Thanks, @aphillipo! At first I thought about this and even tried it but somehow I decided that it would be considered a dirty fix.

**Comment by aphillipo** [comment]
If you are setting border-color: transparent; it's 100% clear you are overriding a border, making it invisible and keeping the space.  I'd argue it's the opposite of dirty :-)

**Comment by dignifiedquire** [comment]
I think the dark mode should have a border, and the light mode should not. I know that is inconsistent as such, but visually it would achieve the best results I feel. 
You can remove the border by either setting its color to either transparent or the same as the background color when needed, so no content moving around happens.

**Comment by nscyclone** [comment]
Thanks, @dignifiedquire, I've just a sent a PR with the fix.
