### ISSUE TITLE
Can't get any CSS to be generated.

### ISSUE THREAD

**Issue by craig-day** [elixir-lang/ex_doc#573]
It looks like the CSS assets are failing to be generated, and I have very little configuration so I don't think that is the issue.

You can check out my [`mix.exs`](https://github.com/zendesk/cldrex/blob/master/mix.exs) to see if I've messed something up.  The resulting documentation can be seen on [hexdocs](https://hexdocs.pm/cldrex/0.0.1-dev.3/CLDRex.html).

**Comment by josevalim** [comment]
Can you look at the doc directory and see if the CSS files are there? What
about the link to CSS files in the HTML files?

On Tuesday, July 5, 2016, Craig Day <notifications@github.com> wrote:

> It looks like the CSS assets are failing to be generated, and I have very
> little configuration so I don't think that is the issue.
>
> You can check out my mix.exs
> <https://github.com/zendesk/cldrex/blob/master/mix.exs> to see if I've
> messed something up. The resulting documentation can be seen on hexdocs
> <https://hexdocs.pm/cldrex/0.0.1-dev.3/CLDRex.html>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/ex_doc/issues/573>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbntlOBADCYFJDKBz8kMKjl-onrkwks5qShvwgaJpZM4JE57u>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by craig-day** [comment]
There is no CSS in `doc/dist`, the only file there is `sidebar_items.js` and the link in the HTML is empty...

`<link rel="stylesheet" href="" />`

**Comment by craig-day** [comment]
I'm not sure what the issue was, but I remove the ex_doc dependency, cleaned up the doc, and added it again. It all seems to be fine now... *shrug*
