### ISSUE TITLE
Update Earmark dependcy

### ISSUE THREAD

**Issue by crertel** [elixir-lang/ex_doc#575]
Hey folks!

Earmark finally hit 1.0, so now would be a great time to [update the version](https://github.com/elixir-lang/ex_doc/blob/master/mix.exs#L24) ex_doc depends on.

Also, as an aside, where are the docs for the different dependency modes (`~>`, `>=`, etc.)?

**Comment by eksperimental** [comment]
@pragedave already submitted a PR,
https://github.com/elixir-lang/ex_doc/pull/574

those docs can be found in the `Version` module

**Comment by eksperimental** [comment]
thanks for the update anyway! ;-)
