### ISSUE TITLE
Code linking always goes to master --> links are off if master has changes

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/ex_doc#578]
Hi there and thank your for all your great work! I really love how ex_doc looks and how it works :)

One of my favourite features of rubydoc is the _View Source_ as it can often be immensely helpful if you are looking for something very specific or an undocumented feature.

ex_doc links to github, which is cool. However it seems to always link to master (or have I misconfigured it?). As master changes, especially links for older versions are off or while you are working on the new version on master, the links are off.

Point in case, [benchee_csv 0.2.0 docs](https://hexdocs.pm/benchee_csv/0.2.0/Benchee.Formatters.CSV.html).  The code link of `format/1` links [to output/1](https://github.com/PragTob/benchee_csv/blob/master/lib/benchee/formatters/csv.ex#L27) as it has occupied that line number now. :(

Of course, this gets even worse when files are renamed/deleted.

I have 2 possible solutions in mind:

* imo embedding the code in the docs would be best, it should be from the time of package publish and it's right there - no extras needed
* otherwise an option to tell ex_doc to link to the corresponding version tag would be cool, [that lands at the right spot](https://github.com/PragTob/benchee_csv/blob/0.2.0/lib/benchee/formatters/csv.ex#L27)

Thanks a lot :)

**Comment by antipax** [comment]
Hey @PragTob :) you can specify a git tag for your docs to use for a particular version like so in mix.exs:

```elixir
  @version "0.2.0"

  def project do
    [...
     docs: [
       source_ref: "v#{@version}"
     ]]
  end
```

hope that helps! :)

**Comment by antipax** [comment]
@PragTob forgot to mention, you'll also have to set your project's "source_url" like so:

```elixir
source_url: "https://github.com/username/project"
```

**Comment by josevalim** [comment]
Yes, that's the way to go. I am thinking maybe we should change Mix to put
the version in a module attribute by default because it may make it easier
to handle cases like this?

On Monday, July 11, 2016, Eric Entin <notifications@github.com> wrote:

> Hey @PragTob <https://github.com/PragTob> :) you can specify a git tag
> for your docs to use for a particular version like so in mix.exs:
>
>   @version "0.2.0"
>
>   def project do
>     [...
>      docs: [
>        source_ref: "v#{@version}"
>      ]]
>   end
>
> hope that helps! :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/ex_doc/issues/578#issuecomment-231829236>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbnLmjQ5MKdsxP9sl2ZUKyEpzZlU4ks5qUpDngaJpZM4JJqek>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by antipax** [comment]
@josevalim I would be in support of that change, all of my published Hex packages have the version as a module attribute like that, and I think many others do as well.

**Comment by PragTob** [comment]
@antipax thanks! I'll use that for the 0.3.0 release :)

@josevalim version as a module attribute sounds wonderful!

**Comment by antipax** [comment]
@PragTob just so you know, you can actually update your hex.docs at any time, so you could regenerate/upload your docs with the source_ref/source_url configs for the existing versions, as well. :)

**Comment by PragTob** [comment]
@antipax I did know... in the back of my head :) Thanks for reminding me, I'll put that on the todo agenda then!

**Comment by PragTob** [comment]
I'll close this one then, as option 2 I asked for is already present. Thanks a lot. When I get around to it I might look to see how I missed this and take a stab at improving the docs to make this easier to learn for others :)

**Comment by whatyouhide** [comment]
@josevalim still 100% of my packages have git tags like `vx.x.x` but Hex version like `x.x.x`, so putting the version in a module attribute still means I have to explain to ExDoc that it has to prefix the Hex version with `v` to find the Git tag. Makes sense? 😕

**Comment by josevalim** [comment]
@whatyouhide yes. you will be just one step closer. :D It will also make it easier for things like ExDoc README, where we can show `docs: [source_ref: "v#{@version}"]` by default.

**Comment by whatyouhide** [comment]
I am not convinced on this feature, because right now all info is in the kw list returned by `project/0` and I am a fan of that consistency 😄But we can see how it looks and take a decision then.
