### ISSUE TITLE
ex_doc fetches too many fonts

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#579]
The docs for GenStage makes 10 http requests to fetch fonts. Including the initial css request that is 75% of all requests to load the page.

Do we really need all these fonts?
```
https://fonts.googleapis.com/css?family=Lato:400,300,700,900|Merriweather:300italic,300,700,700italic|Inconsolata:400,700
```

**Comment by joshprice** [comment]
Unless I missed something, it seems like we could remove 4 of those fonts as they aren't used.

1. `Lato 900` isn't used at all:

        ✪ git grep -n "font-weight: 900" *.less 
        No results

2. `Merriweather 700` and `Merriweather 700 italic` aren't used at all (`Lato 700` is used for most headings).

        ✪ git grep -n "font-weight: 700" *.less 
        assets/less/sidebar.less:48:    font-weight: 700;

3. `Lato 400` can be removed as it's only used for `h2`s which end up being overridden

Using the updated font URL drops the number of fonts down to a more reasonable 6:

    https://fonts.googleapis.com/css?family=Lato:300,700|Merriweather:300italic,300|Inconsolata:400,700

Some other candidates for removal:

- `Merriweather 300 italic` looks lovely, but it does tend to be harder to read and is already distinguished by colour. It's used for the footer (one line if the day/night mode switch is made into an icon #558), and the function summary synopsis.

- Also in Chrome the icon font is quite slow to load (even when 304ed) not sure what is causing this? Would it be worth inlining these as SVGs?

**Comment by ericmj** [comment]
This all sounds good.

> Also in Chrome the icon font is quite slow to load (even when 304ed) not sure what is causing this? Would it be worth inlining these as SVGs?

Do you know how many distinct icons we use?

**Comment by joshprice** [comment]
@ericmj 6 or 7 depending on whether the first one counts https://raw.githubusercontent.com/elixir-lang/ex_doc/master/priv/ex_doc/formatter/html/templates/fonts/icomoon.svg

**Comment by joshprice** [comment]
On my machine in Chrome it appears to be loading the `.ttf`rather than the `.woff` not sure what difference that would make though.

**Comment by josevalim** [comment]
It looks good to me. /cc @dignifiedquire?
