### ISSUE TITLE
Local callback links don't work

### ISSUE THREAD

**Issue by alfert** [elixir-lang/ex_doc#588]
Referencing a locally defined callback `fun/2` via `c:fun/2` does not work. An example for that can be found at https://hexdocs.pm/propcheck/PropCheck.FSM.html, in section callbacks. 

A pull request for that will arrive shortly.

**Comment by eksperimental** [comment]
Shouldn't we should we allow the same for local types (`t:`) as well?
For what I can see it's not in the regex, excuse me if i'm wrong and this is already covered.

**Comment by alfert** [comment]
@eksperimental, yes we should, because it is defined in the specs/docs for documenting Elixir. But it is not as simple since type have a different syntactical structure than functions. Thus the regex looks different. My PR is in construction.

**Comment by eksperimental** [comment]
that's great. thanks a lot for looking after this @alfert
