### ISSUE TITLE
Making it explicit the sections with Types / Functions / Macros are expandable

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#601]
Take this screenshot:

<img width="263" alt="screen shot 2016-09-20 at 10 38 52" src="https://cloud.githubusercontent.com/assets/9582/18663592/62de8ff8-7f1f-11e6-9d10-515051be9ae4.png">

There is nothing in there indicating that we can actually click on Functions so it is expanded and we see a list of all functions. Maybe we should add `v` like thing before or after the words Types, Functions and Macros?

/cc @dignifiedquire

**Comment by dignifiedquire** [comment]
We could do something similar as we do with one level down: 

![screen shot 2016-09-28 at 15 53 37](https://cloud.githubusercontent.com/assets/790842/18916161/c968a496-8593-11e6-99e4-cbf67033d9d4.png)

**Comment by josevalim** [comment]
@dignifiedquire that would work. However, would it be possible to expand the list functions WITHOUT clicking on the #functions section? Today those actions are coupled with each other.

**Comment by dignifiedquire** [comment]
@josevalim do you mean auto expanding the `Functions` when clicking the section is selected? What about `Summary` and other items in this list?

**Comment by josevalim** [comment]
@dignifiedquire we need to have two actions:

1. Clicking on "Functions" can lead us to the Functions header and list all functions

2. Clicking only on the icon should list all functions *without* navigating away to the Functions header

**Comment by dignifiedquire** [comment]
Ahh now I understand, that should be doable.

**Comment by josevalim** [comment]
@dignifiedquire ok, I will get into this soon.

Before I start, another option if we want to distinguish from the `>` used later on, would be to use something like `[+]` or `+`, which is also used for listing. Can you think of other more explicit approaches rather than a single `>`?

**Comment by josevalim** [comment]
@dignifiedquire unfortunately I was not able to implement this. In fact, I think the problem is more wide-spread. Even though we have the access to all modules and functions, it is only possible to explore a given function or a given module by moving away.  For example, if you access [the Kernel module](http://elixir-lang.org/docs/master/elixir/Kernel.html), it is not possible to access the functions for the Access module without navigating away from the Kernel page. So I think each level in the sidebar as well as the summary/types/functions/modules should be expandable without navigating away.

One option is to prepend `>` to both modules and summary/types/function/modules... but that sounds too much? Another option is to allow developers to freely navigate the menu and have a "Top" section on each link that links to the top. So for example:

```
Access
    Top
    Summary
    > Functions
    > Macros
    > Callbacks
       Top
       | callback1
       | callback2
```

Thoughts?

**Comment by josevalim** [comment]
Ok, I was able to implement this. There is a live version in Elixir master: http://elixir-lang.org/docs/master/elixir/Kernel.html

With the changes above, we can now navigate the whole Elixir documentation without moving away from the current page. Each top-level item can be expanded and from then on each expandable item is marked with a `+`.

Over the next days I will be collecting some feedback on the design aspect of things, specially if there are places we could add more hints.

**Comment by dignifiedquire** [comment]
Happy to hear you were able to do this, it seems to work great. 

I'm not a big fan of the `+` and `-` but I haven't gotten a better idea yet.

**Comment by josevalim** [comment]
@dignifiedquire I hear you. My first try was to use `>` but it didn't work well with the `|` and `>` used for each function/macro/callback/type right below. That's when I decided to use `+` and `-` (and also because I could not figure out a way to add new icons to the current icon font export. I am not sure if the icons we currently use are documented but this may also be a problem in the future).

Here is one of the things that I read when doing this: http://ux.stackexchange.com/questions/37686/how-should-you-show-that-an-accordion-is-expanded. One option would be to use up and down arrows. Another option is to use `>` and `v` but have it after the link, such as `Functions >`.

I will be glad to implement something better once we reach a decision.

**Comment by josevalim** [comment]
I am closing this as this is up and running. I am still looking forward to feedback if there is interest in changing/improving this.
