### ISSUE TITLE
Remove italic summaries

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#605]
A concern has been raised regarding readability of summaries in Elixir due to the use of italic. Here is a current screenshot:

<img width="879" alt="screen shot 2016-09-28 at 11 26 59" src="https://cloud.githubusercontent.com/assets/9582/18908161/d1c227d6-856e-11e6-9892-0bb6d58841b7.png">

Here is the screenshot without italics which does seem more readable:

<img width="907" alt="screen shot 2016-09-28 at 11 26 28" src="https://cloud.githubusercontent.com/assets/9582/18908147/c6467916-856e-11e6-86c3-068f86e18e8b.png">

@dignifiedquire should we remove the italics from summaries?

**Comment by dignifiedquire** [comment]
I personally like the current version with italics better, but if there are multiple people who have problems with readability due to the italics we can of course drop it.
