### ISSUE TITLE
Modules with no functions cannot be navigated to in the sidebar

### ISSUE THREAD

**Issue by christopheradams** [elixir-lang/ex_doc#609]
If a module defines no functions but just has a `@moduledoc` (which may be common for the root module in a library), there is no way to navigate to it from the sidebar.

Clicking the module name toggles the `"open"` class on the module name, but then there is no sub-menu to click on. It should at least include the "Top" link for each module, even if it has no functions.

**Comment by josevalim** [comment]
@christopheradams yes, it has been fixed on master and released on v0.14.1. Please let me know if the problem persists after updating. :)

**Comment by christopheradams** [comment]
@josevalim oh wow, you fixed this faster than I got around to reporting it. nicely done.
