### ISSUE TITLE
elixirc_paths: elixirc_paths(Mix.env) doesn't work in umbrella projects

### ISSUE THREAD

**Issue by boxxxie** [elixir-lang/ex_doc#610]
in my inner mix.es project files including `elixirc_paths: elixirc_paths(Mix.env)` (needed for compiling ex files for tests) will break my documentation generation.

when i comment out the line the doc generation works fine.

versions:
```
ex_docs: 0.14
elixir: 1.3.2
erlang: 19
```

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by boxxxie** [comment]
https://github.com/boxxxie/broken_ex_doc_example

**Comment by boxxxie** [comment]
In my example file
```
defp elixirc_paths(:test), do: ["lib","test/support"]
defp elixirc_paths(_),     do: []
```
the second line is causing the problem.

```
defp elixirc_paths(:test), do: ["lib","test/support"]
defp elixirc_paths(_),     do: ["lib"]
```
the above fixes the problem

**Comment by josevalim** [comment]
Yes, otherwise you have no paths, and no compiled artifacts, so nothing to generate the documentation for. We will make sure to provide a better error message for such cases.
