### ISSUE TITLE
Dividing line to delineate scrollable area

### ISSUE THREAD

**Issue by andyl** [elixir-lang/ex_doc#611]
In the scrollable list, very often the top word is cut off at the element border.  My brain processes this as a bug, and it causes a moment of distraction to understand why the word is cut off.  Here's how it looks:

![cutoff](https://cloud.githubusercontent.com/assets/90030/19121582/eab070b4-8adb-11e6-89f0-eb9f6d656020.png)

Suggestion: add a thin top border to the scrollable list:

![with_border](https://cloud.githubusercontent.com/assets/90030/19121626/076295a2-8adc-11e6-8cd9-37048a19b175.png)

**Comment by josevalim** [comment]
This is fixed on 0.14.x where we use a gradient to avoid a sudden cut: http://elixir-lang.org/docs/master/elixir/Kernel.html (you may need to do a hard refresh).

**Comment by andyl** [comment]
The gradient is an improvement: 
![fuzzy](https://cloud.githubusercontent.com/assets/90030/19123749/b2073406-8ae4-11e6-889b-d1b599426984.png)

For comparison - to my eye, this is cleaner:
![distinct](https://cloud.githubusercontent.com/assets/90030/19123758/bd752410-8ae4-11e6-8831-2b597c3b9c31.png)

**Comment by eksperimental** [comment]
I agree. I am not a big fan of that gradient either, specially when it fades the scroll bar.

What other possible solutions do we have for this?

**Comment by andyl** [comment]
Another approach would be to use contrasting background colors - somethings like this:
![contrast](https://cloud.githubusercontent.com/assets/90030/19128719/6041b0e6-8af9-11e6-953e-b01bdb233d1e.png)

**Comment by eksperimental** [comment]
@andyl i tried that one in my browser and I was not happy with the results. :-(

**Comment by andyl** [comment]
Another mockup showing a more subtle contrast in background colors:
![subtle](https://cloud.githubusercontent.com/assets/90030/19129270/934dad80-8afb-11e6-859c-154e67658819.png)
