### ISSUE TITLE
Use triangles instead of + and - for functions menu

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#614]
@dignifiedquire: [Instead of the current solution with `+` and `-`](http://wsmoak.net/phoenix/Phoenix.Channel.html#content):

<img width="287" alt="screen shot 2016-10-10 at 20 57 39" src="https://cloud.githubusercontent.com/assets/9582/19247599/377dcc94-8f2c-11e6-86eb-01d478dc7865.png">

Would you prefer the following:

<img width="291" alt="screen shot 2016-10-10 at 20 52 22" src="https://cloud.githubusercontent.com/assets/9582/19247571/174fc9a4-8f2c-11e6-9444-e3ad491f0a0b.png">

**Comment by josevalim** [comment]
Or with the border aligned to the triangle:

<img width="289" alt="screen shot 2016-10-10 at 21 00 57" src="https://cloud.githubusercontent.com/assets/9582/19247695/b55a8cce-8f2c-11e6-9c2a-30debb5c5e2a.png">

**Comment by eksperimental** [comment]
I like the one with the border aligned. Could u send a screen capture when u hove an item showing the ">"

**Comment by josevalim** [comment]
@eksperimental it would be the same as today, both the text and the icon get lighter/"whiter".

**Comment by josevalim** [comment]
Here is a screenshot showing the triangles with mouseover and the border aligned under the C:

<img width="290" alt="screen shot 2016-10-10 at 21 12 07" src="https://cloud.githubusercontent.com/assets/9582/19248100/66d176e2-8f2e-11e6-9d88-69a717911781.png">

Here is a screenshot of using + and - with the border aligned under the C:

<img width="291" alt="screen shot 2016-10-10 at 21 13 05" src="https://cloud.githubusercontent.com/assets/9582/19248109/6f7f771c-8f2e-11e6-8ff5-3430fc09eb77.png">

**Comment by josevalim** [comment]
FWIW, I think I prefer the last one the most. The triangles are bulkier and that's looks more distracting.

**Comment by ericmj** [comment]
> FWIW, I think I prefer the last one the most. The triangles are bulkier and that's looks more distracting.

I agree, last one is best. Also prefer the border aligned under the C.

**Comment by eksperimental** [comment]
sorry jose, i was not clear enough, I would like to see wehn you hover let's say: "handle_info/2", i'm intgerested in how it will look like with the "> " symbol.

I'm concerned about two things: 
1. if we leave margin, it will be too wide for functions with a relatively long name.
1.a.  there's a bug when the ">" symbol and function name don't fit in the same like (PR coming soon)
2. the ">" symbol is another icon that comes into play, and that could generate even more distraction / bulkiness.

**Comment by josevalim** [comment]
@eksperimental it would work the same as today. It becomes lighter on mouseover and a `>` appears when it is clicked on.

**Comment by eksperimental** [comment]
@josevalim i know. i was asking for a screenshot to have a visual representation of everything at one glance ;-p

**Comment by josevalim** [comment]
@eksperimental can I own you this one? :) Given I am convinced the last one is best and we have another discussion on that other issue, I would like to wait before putting more work on this. :)

**Comment by eksperimental** [comment]
yes. sure. once we decide which one, we can see if there's a particular issue with the width... no worries
