### ISSUE TITLE
Font Awesome: are we still using this one?

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#617]
I think we are using IconMoon only.
just to confirm, if that's the case. 
1. we need to remove Font Awesome from the license

regardless of 1.
2. we need to add IconMoon to the license

**Comment by josevalim** [comment]
I don't think we are using anymore. We moved away from it when we minimized assets size. PR?

**Comment by eksperimental** [comment]
I will update the license file then

**Comment by eksperimental** [comment]
@josevalim how does the thing that automatically closes the issues when a PR is merged?

**Comment by josevalim** [comment]
You need to say in the commit or in the PR that it closes or fixes issue #...

**Comment by eksperimental** [comment]
https://github.com/elixir-lang/ex_doc/pull/623 mentioned this issue.
but i had the feeling it was not closed automatically, was it?

**Comment by josevalim** [comment]
It was:

> josevalim closed this in #623 30 minutes ago

**Comment by eksperimental** [comment]
oh. great. i got a notification about this issue being closed way after you merged the PR. thank you

**Comment by josevalim** [comment]
@eksperimental sometimes it happens to me too. :)
