### ISSUE TITLE
Fix bugs in EPUB format

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#619]
- [x] Mimetype file entry is missing or is not the first file in the archive.
- [x] Delete `OEBPS/assets/logo.png` at the end of the process, is still remaining.
- [ ] Fix missing assets in the header section: `<link type="text/css" rel="stylesheet" href="" />` or `<script src=""></script>`.
- [ ] Declare all the assets (images, JS, CSS) in the OPF manifest.
- [ ] Support the `:group` option from extras

**Comment by josevalim** [comment]
I have fixed the first today morning and the second yesterday when I added support for assets copying. :)
