### ISSUE TITLE
FIlter the modules

### ISSUE THREAD

**Issue by mrkaspa** [elixir-lang/ex_doc#628]
Is there a way to generate the documentation for a set of modules i.e. the ones beginning with Core.Models or the ones that have the Command word?

**Comment by ericmj** [comment]
What's the use case? Does `@moduledoc false` not work to filter the modules?

**Comment by mrkaspa** [comment]
I need to create a separate kind of documentation with the modules inside in some specific folders

**Comment by josevalim** [comment]
@mrkaspa should they be separate apps?

In any case, a patch that supports the `--filter-prefix` option would likely be welcome. Then you could do `mix docs --filter-prefix="Core." --output=core`.

**Comment by mrkaspa** [comment]
That would work
