### ISSUE TITLE
Add sytle for keyboard key: <kbd>

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#629]
I would like to be able to style the `<kbd></kbd>` tag, and make it look like a keyboard key, same as Github does.. for example: <kbd>Tab</kbd>

**Comment by josevalim** [comment]
Theoretically you can use `<kbd>Tab</kbd>` in your docs. We could support it in markdown too... but we would need to find an engine that supports it or if there is a conversation to support it.

**Comment by eksperimental** [comment]
sorry i was not clear enough. I'm just talking about the HTML tag.
choosing to support it in markdown would be difficult since it is not a common tag (i think it has been proposed as an extension in commonmark).

Currently "it works" in ExDoc, but it just looks like plain test, therefore we need to add a style to support this feature.

**Comment by josevalim** [comment]
Ohhhhhhhhh. Sure! Please go ahead, we can use GitHub's style.

**Comment by eksperimental** [comment]
ok. the other thing is how not to show the html code in IEx

**Comment by eksperimental** [comment]
If we want an example to work on, IEx module documentation, **Autocomplete** section.

```elixir
  ## Autocomplete

  To discover all available functions for a module, type the module name
  followed by a dot, then press tab to trigger autocomplete. For example:

      Enum.
```

**Comment by josevalim** [comment]
@eksperimental no idea. We could strip tags in IEx but I am afraid it would be non trivial to support it.

**Comment by ericmj** [comment]
I'm not against adding extra styles to the default CSS but I think we should avoid using HTML in the elixir docs.

**Comment by josevalim** [comment]
@ericmj yup.

**Comment by josevalim** [comment]
Closing this so we don't promote using HTML in the docs.
