### ISSUE TITLE
Make links in night mode more obvious

### ISSUE THREAD

**Issue by sheharyarn** [elixir-lang/ex_doc#631]
When generating documentation with links in `ex_doc`, they look fine in Day mode, but in Night mode they are almost indistinguishable from the normal text.

Here are screenshots for comparison:

![screenshot from 2016-10-31 02-45-47](https://cloud.githubusercontent.com/assets/2355108/19840395/7cf36f6e-9f16-11e6-9e23-1d44e902af59.png) ![screenshot from 2016-10-31 02-45-20](https://cloud.githubusercontent.com/assets/2355108/19840394/7ced701e-9f16-11e6-9404-91e520540346.png) 
### Suggestion

Make the links purple in Night mode like links to code, or underline them like in Day mode:

![screenshot from 2016-10-31 03-05-20](https://cloud.githubusercontent.com/assets/2355108/19840420/52cb5d0e-9f17-11e6-854b-18f59cfdeb21.png) ![screenshot from 2016-10-31 03-07-06](https://cloud.githubusercontent.com/assets/2355108/19840421/52cf0350-9f17-11e6-8431-613b722e010c.png)

**Comment by josevalim** [comment]
We should definitely underline them.

**Comment by sheharyarn** [comment]
I can do this and send in a pull request by tomorrow.
