### ISSUE TITLE
Need instructions on how to configure dependent documentation links

### ISSUE THREAD

**Issue by scouten** [elixir-lang/ex_doc#633]
In https://github.com/elixir-lang/ex_doc#auto-linking, it says ...

> By referring to a module, function, type or callback from any of your dependencies, such as `MyDep`, ExDoc will automatically link to that dependency documentation on hexdocs.pm (the link can be configured with the :deps option in your mix.exs)

... but when I read the documentation for [Mix deps](http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.html), I see no such instructions. Please add instructions either here or there for how to do this.

(Or, alternatively, if the umbrella-project changes in #625 were released, I might no longer have this need. 😄 )

**Comment by scouten** [comment]
Or … if I was looking in the wrong place, please provide a link to where I _should_ have been looking for how to use the `:deps` option in mix.exs.

**Comment by josevalim** [comment]
Thank you, i have improved the docs in the readme.
