### ISSUE TITLE
Can't run local.hex because of some crypto failure

### ISSUE THREAD

**Issue by craig-day** [elixir-lang/ex_doc#636]
I have a docker image, which is starting from a base alpine 3.4 image and then I install elixir using `apk`.  Everything is fine until I add `ex_doc` as a dependency, then I can't build my docker image anymore because of some weird dependency here. 

```
Step 17 : RUN mix local.hex --force
** (MatchError) no match of right hand side value: {:error, {:crypto, {'no such file or directory', 'crypto.app'}}}
    (mix) lib/mix/utils.ex:356: Mix.Utils.read_httpc/1
    (mix) lib/mix/utils.ex:301: Mix.Utils.read_path/2
    (mix) lib/mix/local.ex:107: Mix.Local.read_path!/2
    (mix) lib/mix/local.ex:86: Mix.Local.find_matching_versions_from_signed_csv!/2
    (mix) lib/mix/tasks/local.hex.ex:30: Mix.Tasks.Local.Hex.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

**Comment by ericmj** [comment]
You did not install erlang correctly on your machine. If you are on linux you are probably missing a package such as `erlang-ssl` or `erlang-crypto`.

Closing this issue since it's not related to ex_doc.

**Comment by craig-day** [comment]
FWIW, it was `erlang-crypto` if anyone stumbles across this. Thanks for the help.

**Comment by shdblowers** [comment]
I also ran into this issue and got to here via a google search.

My problem was when I was installing Erlang 21 through asdf

This is the error I got:

```
Building Erlang/OTP 21.0.9 (asdf_21.0.9), please wait...
APPLICATIONS DISABLED (See: /Users/steven/.asdf/plugins/erlang/kerl-home/builds/asdf_21.0.9/otp_build_21.0.9.log)
 * crypto         : No usable OpenSSL found
 * ssh            : No usable OpenSSL found
 * ssl            : No usable OpenSSL found
```

I fixed it through updating asdf and my asdf plugins.
