### ISSUE TITLE
Have to click twice to get to documentation

### ISSUE THREAD

**Issue by jcelliott** [elixir-lang/ex_doc#637]
Recently something changed so that I have to click twice in the sidebar to get to actual documentation. It used to go to the relevant page on the first click, and it would also expand the navigation in the sidebar. Now the first click expands the navigation for that section and you have to click on "Top" to actually see the documentation.

It seems like this was a deliberate change. What are the arguments for more clicking?

(I did find one issue that seemed relevant but it was from more than a year ago, so I assume that was something else?)

**Comment by eksperimental** [comment]
its to allow users to navigate the whole of the options in the sidebar, without having to reload every page to know what's under a certain module.

**Comment by josevalim** [comment]
Yes, it was by design due to what @eksperimental said. There are discussions to have both the navigation aspects and single click but we haven't reached a conclusion yet.

**Comment by michalmuskala** [comment]
I believe we should have single click at least on pages with a single title. It's silly when you click on the page, it opens the submenu, and there's a single "Top" link with nothing else.

**Comment by jcelliott** [comment]
> its to allow users to navigate the whole of the options in the sidebar, without having to reload every page to know what's under a certain module.

Couldn't we have both behaviors? Have a :plus: next to the headings to expand it, but if you click on the actual heading it takes you to the page.

**Comment by josevalim** [comment]
I won't have any coding cycles to put on ExDoc soon, so whoever is interested on this, please make some mockups or some live examples so we can move the discussion forward. :)

**Comment by jcelliott** [comment]
Thats fine, just want to make sure that something like this wouldn't be shot down.
