### ISSUE TITLE
Long specs should be broken up into lines, besides by " |  " 

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#647]
I think we need to break really long structs, or tuples like this one

http://elixir-lang.org/docs/stable/elixir/Inspect.Opts.html#t:t/0

**Comment by josevalim** [comment]
Unfortunately to fix this we would need to introduce algebra documents for `Macro.to_string/2` too given the current solution for `|` is mostly a workaround which won't scale for more complex data structures. And right now there are no plans to add inspect algebra to the AST.

**Comment by nscyclone** [comment]
Can we use [CSS white-space](https://developer.mozilla.org/ru/docs/Web/CSS/white-space) as a temporary solution?
It would look like this in the given [test case](http://elixir-lang.org/docs/stable/elixir/Inspect.Opts.html#t:t/0):
![specs](https://cloud.githubusercontent.com/assets/5345029/23120508/06cbc8fa-f776-11e6-8520-5f58ea0887fe.png)

**Comment by josevalim** [comment]
That sounds like a good compromise until we have a more permanent solution in place (which would require a large refactor in Macro.to_string).
