### ISSUE TITLE
Markdown Pandoc test fails (Pandoc 1.19.1)

### ISSUE THREAD

**Issue by jparise** [elixir-lang/ex_doc#654]
The expected output for the fenced code block test isn't being satisfied:

```
  1) test pretty Markdown fenced code blocks for Pandoc (ExDoc.Markdown.PandocTest)
     test/ex_doc/markdown/pandoc_test.exs:34
     Assertion with == failed
     code: Markdown.to_html(pandoc_with_language_specified, []) == expected
     lhs:  "<div class=\"sourceCode\"><pre class=\"sourceCode elixir\"><code class=\"sourceCode elixir\">mix run <span class=\"op\">--</span>no<span class=\"op\">-</span>halt path<span class=\"op\">/</span>to<span class=\"op\">/</span>file<span class=\"op\">.</span>exs</code></pre></div>\n"
     rhs:  "<pre><code class=\"elixir\">mix run --no-halt path/to/file.exs</code></pre>\n"
     stacktrace:
       test/ex_doc/markdown/pandoc_test.exs:37: (test)
```

This is using Pandoc 1.19.1 from homebrew:

```
pandoc 1.19.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, highlighting-kate 0.6.3
```

It would be easy to revise the expected content string with the output above, but I'm not sure if the difference has to do with this pandoc version, my pandoc configuration, or some other factor. The test itself might need to become more flexible in terms of expected output to satisfy all supported configurations.

**Comment by josevalim** [comment]
FWIW, we are running pandoc on travis, and there the tests pass: https://travis-ci.org/elixir-lang/ex_doc/jobs/186013829#L186

**Comment by josevalim** [comment]
And FWIW2, I have installed the latest pandoc via brew and I see the same failure as you.

**Comment by milmazz** [comment]
@josevalim @jparise I haven't checked Pandoc's changelog recently, but maybe they change the fenced code block format in newer versions of Pandoc. Please remember that for TravisCI we're using Pandoc 1.15.0. Maybe we should update our `.travis.yml`, wdyt?

**Comment by jparise** [comment]
I looked at this a bit more, and it also appears like the `pretty_codeblocks/1` helper function is no works (or is no longer relevant). It originally moved the class attributes from the `<pre>` tag to the `<code>` tag, but pandoc is now emitting class attributes for both tags.

`pretty_codeblocks/1` could be updated to always strip the class attributes from `<pre>` and only re-add them to `<code>` if they're missing there. Would that be in-line with the original intent of this code?

**Comment by josevalim** [comment]
@jparise I would say so given that the original intent was to align it to the output of other tools. :) Alternatively, we can just drop support for pandoc. I doubt anyone uses it given we have plenty of options in Elixir today? If someone needs it, it could be tackled in a separate project.

**Comment by jparise** [comment]
@josevalim Dropping pandoc sounds like an ideal solution given the variability of its output across versions. I also have a close-to-finished patch to "normalize" (read: massage using multiple regex's) the output across versions. Let me know the project's preference, and I'm happy to help move this issue forward accordingly.

**Comment by josevalim** [comment]
@jparise my vote is to remove it then, it is less code, but let's wait a bit to see if someone else has reasons against removing it.

**Comment by jparise** [comment]
For purposes of the discussion, here's what `pretty_codeblocks/1` could become to support both pandoc output formats:

```elixir
  defp pretty_codeblocks(bin) do
    bin = Regex.replace(~r/<pre\s+class=\"(?:sourceCode\s+)?([^\"]+)\"><code[^>]*>/,
                        bin, ~S(<pre><code class="\1">))
    bin = Regex.replace(~r/<div[^>]*>(.*)<\/div>/, bin, ~S(\1))
    bin
  end
```

Not very "pretty". 😉

**Comment by milmazz** [comment]
+1 to remove support for Pandoc, most of the time I use `earmark` as Markdown parser and in a few cases I've been using `devinus/markdown`

**Comment by josevalim** [comment]
Beautiful, let's go ahead then!
