### ISSUE TITLE
Parameterized type in function spec generates an extra anchor tag

### ISSUE THREAD

**Issue by sschneider1207** [elixir-lang/ex_doc#657]
I have something similar to the following defined:
```Elixir
@type t :: term
@opaque finger_tree(t) :: ...

@spec append(finger_tree(t), t) :: finger_tree(t)
def append(arg, y) do
 ...
end
```
When docs are generated for this, the entry for `append` looks like

![image](https://cloud.githubusercontent.com/assets/16026066/21530000/9af0bd96-cd0b-11e6-906f-8deeb3727c63.png)

It appears that it is trying to add another link to the entry for type `t`

**Comment by ymtszw** [comment]
@ericmj I think you mentioned about docs for "type definition" in which it's true that parameters in parameterized types can be arbitrary so not to be linked even if it is named as `t` (or any other names identical to existing local types). 

On the other hand, in docs for "function typespecs", actual, concrete types can be specified as parameters in parameterized types, so they are to be linked.
I think @sschneider1207 meant about that, and I agree with that.
Current handling of parameterized types in typespec doc generation escapes links generated for type parameters where it should not. Resulting in situations like [the image in first post](https://cloud.githubusercontent.com/assets/16026066/21530000/9af0bd96-cd0b-11e6-906f-8deeb3727c63.png).

For instance,
```ex
@type t :: term
@type parameterized_t(t) :: {:ok, t} | {:error, term}

@spec fun(t) :: parameterized_t(t)
def fun(val) do
  # some logic returning parameterized_t/1
end
```

The above code should generate docs for `fun/1` typespec in HTML like this:
```html
fun(<a href="#t:t/0">t</a>) :: <a href="#t:parameterized_t/1">parameterized_t</a>(<a href="#t:t/0">t</a>)
```

I have PR'ed the fix achieving the above behavior, so please review it ❤️  => https://github.com/elixir-lang/ex_doc/pull/694
