### ISSUE TITLE
Logger error when running Mix command in 1.3.2

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#659]
I'm running ExDoc with the lowest supported version (v1.3.2),
and everytime I run a mix command within the ExDoc project itself, I get this error.

```
=INFO REPORT==== 7-Jan-2017::20:48:24 ===
    application: logger
    exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
```

everything works fine, it's just annoying.

**Comment by josevalim** [comment]
That's an incompatible Erlang version. You are probably running 1.3.2 with Erlang 19.

**Comment by eksperimental** [comment]
yes, I am. So how should we proceed? I didn't know 1.3 would be incompatible with Erlang 19.
in the README it states it works with Erlang  18 or later, and in the changelog it mentions some features that work only with Erlang 19, so I assume this version is supposed to work with Erlang 19

**Comment by josevalim** [comment]
@eksperimental if an Elixir version was released before Erlang 19, then there is no guarantee it actually works when Erlang 19 is out. Ideally it just works but sometimes it doesn't. In this case, we were calling an undocumented gen_event API, which was on us. Ideally it shouldn't happen.
