### ISSUE TITLE
Generating docs breaks with argument error.

### ISSUE THREAD

**Issue by fcevado** [elixir-lang/ex_doc#662]
I've got this error while generating docs:
```
** (ArgumentError) argument error
    (ex_doc) lib/ex_doc/retriever.ex:401: ExDoc.Retriever.find_actual_line/3
    (ex_doc) lib/ex_doc/retriever.ex:166: ExDoc.Retriever.generate_node/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:115: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:73: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:131: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Evaluating the error message and the function `ExDoc.Retriever.find_actual_line/3`, what happened is that `abst_code` was an empty list. I did a small change(`find_actual_line/3` returns false if `abst_code` is an empty list) and it  works fine locally, I'm creating this issue just to confirm that the bug is real before opening a pr.

**Comment by josevalim** [comment]
Do you have a scenario that reproduces why find_actual_line is having abst_code as an empty list?

**Comment by fcevado** [comment]
I was publishing a release for this lib: https://github.com/fcevado/phone
Environment:
```
Elixir 1.4.0
Erlang/OTP 19
Linux Kernel: x86_64 Linux 4.9.3-gentoo
```
