### ISSUE TITLE
Consider leveraging typespecs for argument names

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#664]
There's recently a lot of PRs to various projects that add additional bodyless function clauses to provide better argument names in the documentation generated by ex_doc for functions that pattern match on the arguments directly without naming them. Very often, though, a better naming source (than the default arg0, arg1) already exists for those functions in the typespecs - usually using the variable `bar` for a thing typed as `Foo.bar`, and `foo` for a thing typed `Foo.t` will do the right thing.

There's already some code to figure out names from types for callbacks, so I think it should be possible to reuse it.

**Comment by josevalim** [comment]
The figuring out of signatures today currently happens on Elixir, so if something is changing, we would likely change it there.

**Comment by josevalim** [comment]
Unless we want to keep Elixir the same and use the specs to override what Elixir infers. However, one of the advantages of doing Elixir is because it would also help other documentation consumers, such as IEx.

**Comment by michalmuskala** [comment]
Should I reopen on https://github.com/elixir-lang/elixir?

**Comment by josevalim** [comment]
I would wait for now because we are working on something that may completely obsolete this request. We will keep it in mind though.

**Comment by michalmuskala** [comment]
No problem. Thanks for the information.
