### ISSUE TITLE
Prettify struct documentation

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/ex_doc#667]
Related to https://github.com/elixir-lang/elixir/pull/5718. I noticed that the `Task` module in the Elixir stdlib was documenting the `%Task{}` struct by using `@doc` above `defstruct`. This caused the [`Task.__struct__/0`](https://hexdocs.pm/elixir/Task.html#__struct__/0) function to be documented; however, I don't think this is a nice way to document structs as `__struct__/0` is more of an internal tool used for working with structs. As the first step to fix this, we could treat `__struct__` specially and show it as documentation for `%MyStruct{}` instead.

@josevalim would it look the same as `__struct__/0` visually for things like positioning in the functions list and so on? Or should we treat this differently, for example by giving structs their own section?

**Comment by josevalim** [comment]
Due to #646, I would keep it all together. You may change the annotation to `(struct)` though. We should probably have it always come on the top as well.

**Comment by whatyouhide** [comment]
I'll look into implementing this.

**Comment by whatyouhide** [comment]
Closed by #670.
