### ISSUE TITLE
Markdown link markup containing image gets mangled

### ISSUE THREAD

**Issue by njonsson** [elixir-lang/ex_doc#668]
Consider the following Markdown (which I believe to be valid — at least GitHub handles it), contained in [the readme for *example_files*](https://github.com/njonsson/example_files/blob/master/README.md):

```markdown
[![Travis CI build status]][Travis-CI-build-status]
[![Hex release]           ][Hex-release]

[Travis CI build status]: https://secure.travis-ci.org/njonsson/example_files.svg?branch=master
[Hex release]:            https://img.shields.io/hexpm/v/example_files.svg

[Travis-CI-build-status]: http://travis-ci.org/njonsson/example_files "Travis CI build status for ‘example_files’"
[Hex-release]:            https://hex.pm/packages/example_files       "Hex release of ‘example_files’"
```
---

I expect ExDoc to produce the HTML:

```html
<p>
  <a href="http://travis-ci.org/njonsson/example_files" title="Travis CI build status for ‘example_files’">
    <img src="https://secure.travis-ci.org/njonsson/example_files.svg?branch=master" alt="Travis CI build status" />
  </a>
  <a href="https://hex.pm/packages/example_files" title="Hex release of ‘example_files’">
    <img src="https://img.shields.io/hexpm/v/example_files.svg" alt="Hex release" />
  </a>
</p>
```

which renders as:

[![Travis CI build status]][Travis-CI-build-status] [![Hex release]][Hex-release]

[Travis CI build status]: https://secure.travis-ci.org/njonsson/example_files.svg?branch=master
[Hex release]:            https://img.shields.io/hexpm/v/example_files.svg

[Travis-CI-build-status]: http://travis-ci.org/njonsson/example_files "Travis CI build status for ‘example_files’"
[Hex-release]:            https://hex.pm/packages/example_files       "Hex release of ‘example_files’"

---

Instead, as shown at https://hexdocs.pm/example_files/about.html, ExDoc v0.14.5 produces:

```html
<p>
  <a href="https://hex.pm/packages/example_files" title="Hex release of ‘example_files’">!<a href="http://travis-ci.org/njonsson/example_files" title="Travis CI build status for ‘example_files’">Travis CI build status]</a>
[<img src="https://img.shields.io/hexpm/v/example_files.svg" alt="Hex release" title=""/>           </a>
</p>
```

which renders as:

<p>
  <a href="https://hex.pm/packages/example_files" title="Hex release of ‘example_files’">!<a href="http://travis-ci.org/njonsson/example_files" title="Travis CI build status for ‘example_files’">Travis CI build status]</a>
[<img src="https://img.shields.io/hexpm/v/example_files.svg" alt="Hex release" title=""/>           </a>
</p>

**Comment by josevalim** [comment]
I believe you need to report this to the underlying markdown project, which is likely https://github.com/pragdave/earmark in your case. :) Thank you!
