### ISSUE TITLE
localStorage error when third-party site data is blocked

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#678]
This only happens for me when I view docs locally and I have this chrome flag enabled: https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document.

**Comment by josevalim** [comment]
This is the error with a fix: http://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failted-to-read-localstorage-from-window-access-den

**Comment by josevalim** [comment]
Fixed in master.
