### ISSUE TITLE
Automatically link to Special Forms

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#679]
Linking to a special form function such as `alias/2`, does not autolink.
I guess from a user perspective, it is not necessary to know whether it's a Kernel function, macro, or a special form. ExDoc should automatically determine this and link to it.

WDYGT?

**Comment by josevalim** [comment]
Yes, definitely.

**Comment by eksperimental** [comment]
> [for](`for/1`)
is outputting the following link
> <a href="[%60for/1%60](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#for/1)"><code class="inline">for</code></a>

so i need to use
> [`for`](`Kernel.SpecialForms.for/1`)
to get the right link
> <a href="Kernel.SpecialForms.html#for/1"><code class="inline">for</code></a>

**Comment by wojtekmach** [comment]
@eksperimental I was only handling `[M.f/a]` by design, but yeah it shouldn't produce such output. I'll look into supporting this use case.
Ref https://github.com/elixir-lang/ex_doc/issues/622

**Comment by wojtekmach** [comment]
Custom links to special forms work now, thanks @eksperimental. The only thing left is custom links to modules which are still missing, I'll open a separate issue.

**Comment by eksperimental** [comment]
thank you so much @wojtekmach 
I will have a look whenever I get the chance
