### ISSUE TITLE
Table cells should vertically align content

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#681]
Now that I am working on the Deprecations page in the Elixir project, 
Example: you can see it in first and third raw

![deprecations](https://cloud.githubusercontent.com/assets/9133420/23562741/61f0ae5e-0076-11e7-8349-ad9361d30972.png)

**Comment by josevalim** [comment]
@eksperimental yes, that doesn't look like nice.

I know this is unrelated to this particular issue but maybe we should merge the 3rd and 4th columns? They are repeating information in many cases. I would suggest:

```
REPLACED BY (AVAILABLE SINCE)
Atom.to_char_list/1 (v1.3)
```

**Comment by eksperimental** [comment]
@josevalim thank you for the suggestion. done!
