### ISSUE TITLE
Soft deprecate :formatters option in favor of :formatter

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#683]
[`:formatters` option in the `docs` task](https://github.com/elixir-lang/ex_doc/blob/05eb89e93559e129744cf021d580f14cf6fff313/lib/mix/tasks/docs.ex#L51-L52) is used, where in the [CLI](https://github.com/elixir-lang/ex_doc/blob/2228073feabda52136aed345208c8af8ea74b596/lib/ex_doc/cli.ex#L16) and in [`%ExDoc.Config{}`](https://github.com/elixir-lang/ex_doc/blob/2228073feabda52136aed345208c8af8ea74b596/lib/ex_doc.ex#L19)) it is called `:formatter`.
The rest of the options share the same name but this one is the exception.

**Comment by josevalim** [comment]
This is by design. Internally we want to support the ability of running multiple formatters but because we don't have it yet, it was never exposed at the upper levels.
