### ISSUE TITLE
Night mode broken on 0.15.0

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#685]
Night mode does not work after page reload on ex_doc 0.15.0.

Working page (with 0.14.5) https://hexdocs.pm/elixir/1.4.2/Kernel.html.
Broken page (with 0.15.0) https://hexdocs.pm/elixir/master/Kernel.html.

**Comment by milmazz** [comment]
@ericmj Which browser (and version) are you using?

I don't see the error on Chrome (56.0.2924.87), IE 10, and Firefox Developer Edition.

**Comment by nscyclone** [comment]
@milmazz It seems to be reproducible in FF 51, Chrome Canary 59 and Edge 38.
Here are the steps:
* Visit https://hexdocs.pm/elixir/master/Kernel.html;
* Click on `Switch to night mode`;
* Press <kbd>F5</kbd>;
* The page switches to the day mode.

Might be related to [this](https://github.com/elixir-lang/ex_doc/commit/feaff64bd91066f6d4895175069e59a8381b7003) but it requires some investigation.

**Comment by ericmj** [comment]
Chrome 56 and Safari 10.0.3 on macOS 10.12.3.

**Comment by milmazz** [comment]
@nscyclone @ericmj Yes, it should be related with that change:

![image](https://cloud.githubusercontent.com/assets/34700/23618482/0d8f5e32-0256-11e7-9685-f2a15ee50dc9.png)

**Comment by ericmj** [comment]
I don't think it's related to that change since v0.15.0 was released before and the bug seems to be on that version also: https://hexdocs.pm/ecto/Ecto.html

**Comment by nscyclone** [comment]
@ericmj @milmazz I guess I found a potential cause. If I am right it seems to be my fault.

**Comment by nscyclone** [comment]
@ericmj @milmazz Yeah, I was right, it was caused by the recent updates I made to the sidebar.
I am really sorry for that. #686 should fix this issue.

**Comment by josevalim** [comment]
@nscyclone no problem at all. Thank you for all of your contributions to ExDoc!
