### ISSUE TITLE
Provide source maps for JS

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/ex_doc#687]
When debugging errors like #685 is almost impossible to use the *Developer Tools* and put breakpoints in the `app-*.js` minified version, even with the *pretty print* feature from Chrome or other browsers is difficult to understand the application workflow:

![image](https://cloud.githubusercontent.com/assets/34700/23620196/aa052698-025b-11e7-8c52-f04e9bd7f437.png)

One way to do this task a little easier is providing a source map. We should add a new task in our current `gulpfile.js` workflow. wdyt?

**Comment by josevalim** [comment]
Yes please!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
