### ISSUE TITLE
Fix warning: index.html redirects to README.html, which does not exist

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#688]
I cannot tell what is the test that is causing this line, but it is really annoying, and I thought it was the change I was working on but it was not.

**Comment by lalo2302** [comment]
Could you describe the process you followed, so I can reproduce it

**Comment by eksperimental** [comment]
simply run `mix test` you will see it.
for example
https://travis-ci.org/elixir-lang/ex_doc/jobs/220122262#L1894
