### ISSUE TITLE
Project name that is too long wraps weirdly

### ISSUE THREAD

**Issue by Nicd** [elixir-lang/ex_doc#696]
It seems #621 breaks wrapping of a project name that is too long, since it wraps on any character. This is what it looks like on my project:

https://files.nytsoi.net/NFyT.png

This is what it looks like if you remove `word-break: break-all`:

https://files.nytsoi.net/iFNw.png

If I remove the break-all and make my browser window smaller, I cannot see any wrapping issues. But maybe the issue fixed in #621 reproducible only on certain mobiles?

**Comment by Nicd** [comment]
Ah, I see now that the problem is if the project name is one long word like `VeryLongWordThatDoesNotFit`. But I think adding `word-wrap: break-word` is a better solution than `word-break: break-all`, since the former tries to wrap the name normally first and then falls back to wrapping on any character, whereas the latter will always wrap on any character.

With `word-wrap: break-word`:

![](https://files.nytsoi.net/sQ10.png) ![](https://files.nytsoi.net/WIKc.png)

With `word-break: break-all`:

![](https://files.nytsoi.net/S1tp.png) ![](https://files.nytsoi.net/t0ER.png)

Without any rule:

![](https://files.nytsoi.net/wT3E.png) ![](https://files.nytsoi.net/LXNA.png)

**Comment by josevalim** [comment]
Good catch. Can you please send a PR?
