### ISSUE TITLE
Nested type links are rendered incorrectly

### ISSUE THREAD

**Issue by dm1try** [elixir-lang/ex_doc#698]
https://hexdocs.pm/logger/Logger.html#t:metadata/0 :bowtie:
![image](https://cloud.githubusercontent.com/assets/486807/25089945/422cb348-2389-11e7-9de9-ca46bcbcfbcb.png)

**Comment by josevalim** [comment]
This is probably related to #694. /cc @ymtszw

**Comment by ymtszw** [comment]
Yes it is.

I'm not familiar with standard libraries' (like Logger's) doc generations but now with ex_doc v0.15.1 released,
when Logger's doc is re-generated using ex_doc v0.15.1 or newer, this should be resolved I presume.

**Comment by dm1try** [comment]
Okie 👍
