### ISSUE TITLE
Ability to exclude files from generated documentation 

### ISSUE THREAD

**Issue by balena** [elixir-lang/ex_doc#700]
ExDoc should have a way to exclude files from the documentation.

There are several cases where certain parts of the implementation are not relevant for a library user. For instance, in GenServer implementations, functions like `init/1`, `handle_call/2`, `handle_cast/2` and `handle_info/2` correspond generally to "internal implementation", and could be removed from the generated documentation without sacrificing understanding.

**Comment by balena** [comment]
OK, `@moduledoc false` is a fair option. Please ignore my request.

**Comment by eksperimental** [comment]
To excluse functions but not the whole module use
"@doc false"

**Comment by raarts** [comment]
In Phoenix I have XXX.Router.Helpers show up in the documentation. That's an auto-generated module, and I can't find how to set a @moduledoc false on that. So an exclude option might still be useful. Or do I need to raise this with the Phoenix project?

**Comment by josevalim** [comment]
It should be in the Phoenix project.
