### ISSUE TITLE
Link `<h3>` headings in generated documentation

### ISSUE THREAD

**Issue by kevinlitchfield** [elixir-lang/ex_doc#701]
Currently, only `<h2>` headings are linked in generated documentation (see `ExDoc.Formatter.HTML.Templates.link_headings/3`). It would be useful to be able to link to `<h3>` headings as well (for example, "Term ordering" under "[Comparison operators](https://hexdocs.pm/elixir/operators.html#comparison-operators)" in the Elixir docs).

Would the maintainers consider a PR making this change?

**Comment by josevalim** [comment]
Yes, that does sound like a reasonable change assuming it won't introduce a lot of code to the codebase.

**Comment by kevinlitchfield** [comment]
Cool, thanks. Will give it a go.

**Comment by josevalim** [comment]
@kevinlitchfield if you ever get to this, please let us know! For now we are closing the issue. Thank you!
