### ISSUE TITLE
h2 header with `link` breaks generation navi part without any warning/error?

### ISSUE THREAD

**Issue by DoumanAsh** [elixir-lang/ex_doc#705]
I didn't notice it immediately, but when i published my package i noticed that navi part of my docs has nothing https://hexdocs.pm/elivndb/EliVndb.html

It seems to happen due to me putting following header in README:
```md
## `EliVndb.Client` types
```

There is no error or warning.
But all other pages are generated without issues. And if i remove quotes then navi part will have content:
```md
## EliVndb.Client types
```

[README.md](https://raw.githubusercontent.com/DoumanAsh/EliVndb/bc007c7c3638d11402494c5414a6ea531446729a/README.md) of commit which got published to hex.pm

Should there be warning\error on invalid header?

**Comment by josevalim** [comment]
@DoumanAsh definitely sounds like a bug. Could you please investigate? Let us know if you have any questions regarding ExDoc codebase.

**Comment by DoumanAsh** [comment]
Ok, i tried to compare produced `sidebar-items-<digest>.js` and it turns out that my README.md causes ex_doc to create invalid JS Object:

Normal case:
```js
    {"id":"readme","title":"EliVndb","group":"","headers":[
        {"id":"Documentation","anchor":"documentation"},
        {"id":"EliVndb.Client types","anchor":"elivndb-client-types"},
        {"id":"Available commands","anchor":"available-commands"},{"id":"Installation","anchor":"installation"}
    ]
    }
```

Broken case:
```js
    {"id":"readme","title":"EliVndb","group":"","headers":[
        {"id":"Documentation","anchor":"documentation"},
        {"id":"<a href="EliVndb.Client.html"><code class="inline">EliVndb.Client</code></a> types","anchor":"types"},
        {"id":"Available commands","anchor":"available-commands"},{"id":"Installation","anchor":"installation"}
    ]
    }
```

It seems like attempts to put quotes forces ex_doc to turn ID into actual link
```html
"<a href="EliVndb.Client.html"><code class="inline">EliVndb.Client</code></a>
```

Problem most likely somewhere in `Templates.create_sidebar_items`
I'll try to look there

**Comment by josevalim** [comment]
Awesome, great find!

**Comment by DoumanAsh** [comment]
Ok, looking into code. Each header gets id from regex `@h2_regex  ~r/<h2.*?>(.+)<\/h2>/m`
Since its intended to capture all stuff and by this point content is already converted fully to HTML, you get full link as ID.

The question is what to do with that?

Should ex_doc be able to handle this cases?
Most likely we need to determine what kind of header we get, before actually processing it.
Another problem is that you potentially can have any kind of markup inside `<h2>` so regex alone might not handle it
From markdown point of view it is valid markup...

**Comment by josevalim** [comment]
@DoumanAsh I think we decided to work on HTML to unify all mechanisms that we have for generating titles. I know the way to hell is paved with regexes but maybe we should use a regex for stripping HTML tags?

**Comment by DoumanAsh** [comment]
Yes, i'll try to play around.
Actually now i think we can strip it with something simple as `&(String.replace(&1, ~r/<[^>]+>/, ""))`

I'll be back with PR later on

**Comment by eksperimental** [comment]
@DoumanAsh please if you are going to this, try with a well tested regex, as it is a common problem.
I tried looking for one tha strips html tags and come up with this one
http://stackoverflow.com/a/17668453
`<(?:[^>=]|='[^']*'|="[^"]*"|=[^'"][^\s>]*)*>`
I haven't tested it myself though
