### ISSUE TITLE
warning: redefining module Mix.Tasks.Docs (current version defined in memory)

### ISSUE THREAD

**Issue by DoumanAsh** [elixir-lang/ex_doc#707]
When just building as dependency
```
==> ex_doc
Compiling 15 files (.ex)
warning: redefining module Mix.Tasks.Docs (current version defined in memory)
  lib/mix/tasks/docs.ex:1

Generated ex_doc app
```

Should it be addressed?

**Comment by josevalim** [comment]
I cannot reproduce it. Are you using master from your dependency?

**Comment by DoumanAsh** [comment]
No, it is current stable `0.15.1`
I can see the same in Travis tests when running `mix do local.hex --force, deps.get, test && mix coveralls.travis`

**Comment by josevalim** [comment]
@DoumanAsh yes, i can reproduce it now. Investigating...

**Comment by josevalim** [comment]
The bug comes from earmark that loads a docs test in there. I will send a PR there.

**Comment by josevalim** [comment]
And before I forget, thank you for reporting! :+1:
