### ISSUE TITLE
Malformed h2 link_headings when using a markdown processor that outputs minimised/packed HTML

### ISSUE THREAD

**Issue by ScrimpyCat** [elixir-lang/ex_doc#710]
When using a markdown processor that outputs minimised HTML (no newlines between tags) the h2 link_headings end up malformed. This issue also applies to the sidebar links.

### Example

```elixir
iex(1)> ExDoc.Formatter.HTML.Templates.link_headings "<h2>Foo</h2><h2>Bar</h2>"
"<h2 id=\"foobar\" class=\"section-heading\">\n  <a href=\"#foobar\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Foo</h2><h2>Bar\n</h2>\n"
iex(2)> ExDoc.Formatter.HTML.Templates.link_headings "<h2>Foo</h2>\n<h2>Bar</h2>"
"<h2 id=\"foo\" class=\"section-heading\">\n  <a href=\"#foo\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Foo\n</h2>\n\n<h2 id=\"bar\" class=\"section-heading\">\n  <a href=\"#bar\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Bar\n</h2>\n"
```

The first `<h2>Foo</h2><h2>Bar</h2>` produces the malformed output, while the second `<h2>Foo</h2>\n<h2>Bar</h2>` variant produces the correct output.

**Comment by eksperimental** [comment]
what processor in particular are you using and with what options?

**Comment by ScrimpyCat** [comment]
The processor is my own toy library. Regardless the fix should be fairly simple, I believe it should only require changing the two `@h2_regex` at lines 146 and 226 to: `@h2_regex ~r/<h2.*?>(.*?)<\/h2>/m`

e.g.
```elixir
iex(1)> ExDoc.Formatter.HTML.Templates.link_headings "<h2>Foo</h2><h2>Bar</h2>", ~r/<h2.*?>(.*?)<\/h2>/m
"<h2 id=\"foo\" class=\"section-heading\">\n  <a href=\"#foo\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Foo\n</h2>\n<h2 id=\"bar\" class=\"section-heading\">\n  <a href=\"#bar\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Bar\n</h2>\n"
```

Whilst still works for empty h2.

```elixir
iex(2)> ExDoc.Formatter.HTML.Templates.link_headings "<h2></h2><h2>Bar</h2>", ~r/<h2.*?>(.*?)<\/h2>/m
"<h2></h2><h2 id=\"bar\" class=\"section-heading\">\n  <a href=\"#bar\" class=\"hover-link\"><i class=\"icon-link\"></i></a>\n  Bar\n</h2>\n"
```

**Comment by josevalim** [comment]
Can you please send a PR? Note that this has been recently changed in master, so it may be fixed there.

**Comment by ScrimpyCat** [comment]
Sure, I'll make one now. And yes this still affected master (those iex sessions were from the master branch).
