### ISSUE TITLE
Generate a separate section for mix task documentation

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#712]
Today, mix tasks are documented as regular modules. This is fine, but in some cases creates a lot of noise in the documentation. For example this is what we see when we open phoenix docs
<img width="289" alt="screenshot 2017-05-16 17 47 58" src="https://cloud.githubusercontent.com/assets/477062/26115287/d778918c-3a5f-11e7-9914-3a7551cc0aba.png">
Only the tasks!

I propose we document tasks separately in a new "tab" - this way we'd have "Guides", "Modules", "Tasks", "Exceptions" and "Protocols". We could also name the task modules after the task name instead of the module name. This should make the docs much clearer and less cluttered.

**Comment by whatyouhide** [comment]
I am 👍 on this given exceptions are modules as well but we document them in a separate section. The  only thing to note is that all other things (protocols, exceptions, modules) are Elixir concept while Mix is slightly "external" to Elixir, but I don't think that should be a problem.

**Comment by milmazz** [comment]
@michalmuskala There was a proposal from @dignifiedquire some time ago #329 to add a nesting level for the first level of modules, that proposal at least to me seems more generic than to create a new tab called "Tasks". wdyt?

**Comment by michalmuskala** [comment]
I'm not sure we need something as general. Grouping things wouldn't also solve the issue with the tasks being listed before real modules. Separating tasks from modules also solves this issue.

**Comment by josevalim** [comment]
:+1: for a tasks group.

**Comment by josevalim** [comment]
Closing in favor of the PR
