### ISSUE TITLE
Multiple extra files that share the same filename overwrite each other.

### ISSUE THREAD

**Issue by blaketan** [elixir-lang/ex_doc#714]
I'm currently using ex_doc in the root directory of an umbrella project with multiple applications, each having it's own README.md file.  The following is from the `mix.exs` of the project root:

```
  defp docs do
    [
      main: "README",
      extras: ["README.md", "apps/app1/README.md", "apps/app2/README.md"]
    ]
  end
```

When I run the `mix docs`, the headings from each of respective files show up in the sidebar, however they are all linked into the last defined extra file with the same name (`apps/app2/README.md` in this instance.)

**Comment by josevalim** [comment]
I believe we log in this case, don't we?

The solution here is to fully specify your extras, as the default mechanisms use only the last part of the path and changing this would be backwards incompatible.

    "apps/app1/README.md": [filename: "app1-readme", title: "App1 README"]

**Comment by blaketan** [comment]
You're correct, it's logged as: 
`warning: file doc/readme.html already exists`

Managed to get it working by fully specifying extras as suggested, thanks @josevalim !

**Comment by josevalim** [comment]
awesome!
