### ISSUE TITLE
Allow http:// when guessing URL pattern

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#717]
I coudln't figure out what was wrong with a test, and it was because source_ref was set to "http://github.com/elixir-lang/ex_doc/" and not "https://..."
https://github.com/elixir-lang/ex_doc/blob/8269ca8/lib/ex_doc.ex#L145-L159

GitHub, GitLab and BitBucket will redirect you to https if you try to fetch a project via "http://"

My proposal is to accept http:// and return the guessed address with http://

WDYGT?

**Comment by josevalim** [comment]
> My proposal is to accept http:// and return the guessed address with http://

Isn't this what we do? If you are proposing to rewrite http to https I don't think we should rewrite it. Users can fix on their side.

**Comment by milmazz** [comment]
I'm with @josevalim here, I don't think we should rewrite from `http` to `https`. @eksperimental Is that what are you suggesting?

**Comment by eksperimental** [comment]
@milmazz no! that's not :open_mouth: 

As of now, if you pass `source_url: "http://github.com/elixir-lang/ex_doc"`
the guess url pattern will be "http://github.com/elixir-lang/ex_doc" and not "http://github.com/elixir-lang/ex_doc/blob/master/%{path}#L%{line}"

What I meant by:
> My proposal is to accept http:// and return the guessed address with http://

...was that if you provide `source_url: "http://github.com/elixir-lang/ex_doc"`, it should set  `source_url_pattern: "http://github.com/elixir-lang/ex_doc/blob/master/%{path}#L%{line}"`

Sorry If i was not clear enough

**Comment by eksperimental** [comment]
@josevalim nope. that's not precisely what we are doing now. it only accepts "https://"

**Comment by milmazz** [comment]
@eksperimental Thanks for your explanation! Now I understand what's your goal here, but, in order to keep things simple I would say that we leave the current behavior as is, because otherwise we also should support URLs like this:

* `source_url: "http://www.github.com/elixir-lang/ex_doc"` -> `source_url_pattern: "http://www.github.com/elixir-lang/ex_doc/blob/master/%{path}#L%{line}"`
* `source_url: "https://www.github.com/elixir-lang/ex_doc"` -> `source_url_pattern: "https://www.github.com/elixir-lang/ex_doc/blob/master/%{path}#L%{line}"`
* ... and so on.

**Comment by eksperimental** [comment]
but https is really easy to mistake for http, more than www.
We had a test including http as source_ref in ExDoc itself, and it made me waste some of my time trying to figure out that one.  I just corrected it in my last commit.

**Comment by josevalim** [comment]
In this case let's do a previous pass and rewrite  to https for the cases
we attempt to guess the pattern. Basically let's do the thing I originally
said we should not do :P
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by milmazz** [comment]
@josevalim @eksperimental We could cover both transformations in just one step:

```elixir
String.replace("http://www.github.com/elixir-lang/ex_doc", ~r{https?://(www\.)?(github.com|gitlab.com|bitbucket.org)/(.*)}, "https://\\2/\\3")
```

And then guess the URL.

**Comment by josevalim** [comment]
Let's go with only http -> https for now.

**Comment by josevalim** [comment]
We will add more complexity with we need later on.

**Comment by josevalim** [comment]
Closing in favor of the PR.
