### ISSUE TITLE
Getting error message when configuring :ex_doc Markdown parser according to README

### ISSUE THREAD

**Issue by lee-dohm** [elixir-lang/ex_doc#735]
After adding the following to my `config.exs`:

```
config :ex_doc, :markdown_processor, ExDoc.Markdown.Cmark
```

I'm getting the error message:

```
You have configured application :ex_doc in your configuration
file, but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :ex_doc exists or remove the configuration.
```

when I run `mix test` now after following the instructions to configure the Markdown parser that ex_doc uses. Changing the dependency entry in `mix.exs` to the following seems to be a workaround:

```
{:ex_doc, "~> 0.16", only: [:dev, :test], runtime: false}
```

I assume that I'll get the same error message in production? Is there some better way to configure this for my project?

**Elixir Version:** v1.4.4
**ex_doc Version:** v0.16.1

**Comment by lee-dohm** [comment]
I moved the configuration item to my `dev.exs` and that fixed the problem :+1:

**Comment by josevalim** [comment]
Why are you configuring it under `config :ex_doc, ...`? ExDoc is not a runtime application, the configuration should be in mix.exs rather.

**Comment by lee-dohm** [comment]
I guess I'm not understanding [the part of the README](https://github.com/elixir-lang/ex_doc#cmark) that states: "Update your project configuration to use Cmark". I took that to mean that I should put the line `config :ex_doc, ...` shown there in my application's `config/config.exs`.

**Comment by josevalim** [comment]
Apologies, you are correct. :)

**Comment by lee-dohm** [comment]
😅 Thank you for the quick response and the great tools :bow:
