### ISSUE TITLE
Increase contrast of backticks background

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#739]
I have to get really close to the screen to be able to determine weather there had been used backticks or not (I mostly can determine this because of the typeface rather than the background color. Particularly when it's plain text (not a link).
Here's what I mean

![backticks](https://user-images.githubusercontent.com/9133420/26859473-25b73ce6-4b62-11e7-8f85-decae98fccb8.png)

/cc @dignifiedquire

**Comment by josevalim** [comment]
I am particularly fine with how things look like, especially because we also change the font. Having a strong visual distinction would make it rather distracting than readable, no?

**Comment by eksperimental** [comment]
I don't have sight problems and it is really hard for me to determine whether backticks have been used, specially when reviewing documents, we either need to change the color of the font inside, change the background, add a border, or a combination of them.
I don't have a problem when there is a link inside, so maybe changing the color of the font would help.
I think @milmazz was working on correcting things like this related to accessibility and color contrasts, I think we don't need to sacrifice style and still make it user-friendly to everyone.

**Comment by aphillipo** [comment]
I personally think that blue-grey on 80% of computers is very difficult to see and for people with poor eyesight even more so.  If it's there at all it should be a little visible to most users; if the font is enough as Jose implies we shouldn't have the background.  Not everyone has a Mac that has great colour differentiation and IPS panels.  I would just put a border around it:

<img width="879" alt="screen shot 2017-06-07 at 21 46 03" src="https://user-images.githubusercontent.com/52347/26879284-80a58450-4bcb-11e7-8ddc-187df1099d5f.png">

Colour here is 15% darker than the background; #e4e6e9

And in night mode at 15% lighter I get: #3b3b40:

<img width="880" alt="screen shot 2017-06-07 at 21 49 30" src="https://user-images.githubusercontent.com/52347/26879302-91868350-4bcb-11e7-86ac-e33ff342dc34.png">

I think it looks great on all code blocks, not just inline ones?

<img width="870" alt="screen shot 2017-06-07 at 21 50 05" src="https://user-images.githubusercontent.com/52347/26879324-a16abe08-4bcb-11e7-9b64-4290fe48d055.png">

Thoughts?  Happy to provide this minimal pull request if a decision is made...

**Comment by josevalim** [comment]
Please do!

**Comment by eksperimental** [comment]
Regarding relying on the font itself, symbols don't change, for example in my screenshot `===` looks exactly the same as regular font,

Thank you @aphillipo, that will be great if you can do that.

**Comment by milmazz** [comment]
@eksperimental We certainly decrease the number of accessibility errors recently but we still have a lot of work to do on this subject, especially in the contrast area as you noticed. Sadly I don't have too many spare cycles now to invest on this, but please go ahead @aphillipo, every contribution is more than welcome. I think that we can improve our docs accessibility without sacrificing the current look & feel which is great.

BTW, a great tool to check is [WAVE](http://wave.webaim.org/) (Web Accessibility Evaluation Tool)

![capture](https://user-images.githubusercontent.com/34700/26883758-aeffb126-4b63-11e7-8239-7165fe9690ee.PNG)

HTH
