### ISSUE TITLE
earmark dependency requires Elixir 1.4

### ISSUE THREAD

**Issue by mcherep** [elixir-lang/ex_doc#743]
The project requires Elixir v1.3 or above, but earmark requires Elixir v1.4 or above

**Comment by josevalim** [comment]
@mcherep you can specify an earlier earmark version in your `mix.exs`.

**Comment by eksperimental** [comment]
ex_doc requires `{:earmark, "~> 1.1"}`, which is the last minor version to use Elixir v1.2

**Comment by mcherep** [comment]
My bad. Thanks guys
