### ISSUE TITLE
Sidebar toggle misaligned

### ISSUE THREAD

**Issue by profil** [elixir-lang/ex_doc#745]
The recently added "Toggle Sidebar" text next to the hamburger menu is misaligned vertically to the icon, and also partially covered by the sidebar background when opened. I also think that the color of the button should be inverted when shown on top of the sidebar to increase contrast.

![closed_misalignment](https://user-images.githubusercontent.com/412048/27429110-632bef52-5744-11e7-9182-241ad5d71b9a.png)
![misalignment](https://user-images.githubusercontent.com/412048/27429123-6986dce0-5744-11e7-9f81-228c12de48a6.png)

**Comment by josevalim** [comment]
Hrm, I don't see any text. Maybe it depends on your accessibility configuration or such?

**Comment by profil** [comment]
I guess it has to be built with a later version, I haven't specified any special accessibility options and I can see it on the [gen_stage](https://hexdocs.pm/gen_stage/GenStage.html) docs.

**Comment by josevalim** [comment]
It was a bug when publishing the docs. It is fixed now, thank you!
