### ISSUE TITLE
Nested links generated when using `Module` inside of a link

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ex_doc#750]
When working on the Phoenix Guides, I wrote the following line:

    There are many functions defined in the endpoint module for path helpers, channel subscriptions and broadcasts, instrumentation, and  endpoint configuration. These are all covered in the [Endpoint API of the `Phoenix.Endpoint` docs](Phoenix.Endpoint.html#module-endpoints-api).

Which rendered as 
![exdoc-nested-link](https://user-images.githubusercontent.com/477511/27819453-48e35f84-6092-11e7-8a07-bae93ef05aa5.png)

I think if a module name is used inside of a link, we should render it in monospace, but not interpret it as a link (That should be how GitHub handles it in this comment).

**Comment by ivanovaleksey** [comment]
I wanted to fix the issue and generated documentation with the provided text. 
But now it is looking totally fine.
![image](https://user-images.githubusercontent.com/11523473/29476897-bd2fe182-846e-11e7-9353-da502f2552a7.png)

Seems like the issue can be closed.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
