### ISSUE TITLE
[Build] Do not include generated assets in source control

### ISSUE THREAD

**Issue by aphillipo** [elixir-lang/ex_doc#751]
To avoid endless conflicts we really shouldn't have to add the generated app*.* in source instead build them as part for a release.

- [ ] Make sure travis.yml includes nodejs, npm, gulp and less
- [ ] Understand the release process a bit better
- [ ] Generate CSS as part of a release
- [ ] Generate JS as part of a release
- [ ] Generate CSS as part of travis build
- [ ] Generate JS as part of travis build
- [ ] Update README

**Comment by josevalim** [comment]
I am a :-1: on here because then it means ex_doc is no longer usable out of the box as a git dependency and i don't want to impose users of ex_doc to have all of that tooling.

**Comment by josevalim** [comment]
In other words, I would rather have us deal with the pain than push that to everybody else. :)

**Comment by aphillipo** [comment]
Sure, fair points. Really do wonder some days how you became so good at this, most of the decisions in this community are the correct ones.
