### ISSUE TITLE
[Testing] Setup Javascript Integration Testing

### ISSUE THREAD

**Issue by aphillipo** [elixir-lang/ex_doc#752]
The Search History functionality is by it's nature very easy to break.  I'd feel much more comfortable having it tested with something like hound.

https://github.com/HashNuke/hound

- [ ] Add Hound as only: test dependancy (maybe with Chrome Headless support?)
- [ ] Setup build to include Chrome or phantomjs 
- [ ] Write tests for Search History functionality
- [ ] Discuss other Javascript that could be tested

**Comment by josevalim** [comment]
Shouldn't be using javascript tests instead?

**Comment by aphillipo** [comment]
I think using a real browser (or several) is vital because unit testing (which I presume you mean) won't really give us any idea of the truth. Unfortunately the browser is still a hostile environment compared to   Elixir and only integration tests will really show us if the browser hasn't decided that it doesn't like adding history in weird edge cases (for example).

**Comment by aphillipo** [comment]
Okay I need to concentrate on finishing my current project.  This is not sign to happen any time soon.
