### ISSUE TITLE
MathJax Wanted!

### ISSUE THREAD

**Issue by SchrodingerZhu** [elixir-lang/ex_doc#757]
Why there is no original MathJax support? I am begging for it!

**Comment by josevalim** [comment]
Can you please provide some examples and use cases of what you are trying to achieve? It is most likely you will have to implement it yourself but we can provide some guidance depending on what you want to build.

**Comment by milmazz** [comment]
@josevalim I bet @SchrodingerZhu is working with some mathematical formulas and also wants to see a good-quality typography for them in the Web Browser. Something like this:

![screenshot_20170730-161014](https://user-images.githubusercontent.com/34700/28757135-261a824c-7542-11e7-9164-60d7d752747d.png)

@SchrodingerZhu As a workaround, you should include the MathJax CDN in the header template.

**Comment by SchrodingerZhu** [comment]
Yes, as I am writing some data structures, time and space complexities of my methods require me to write formula in my docs. Of course I can add support on my own, but it is of great inconvenience. So I suggest that ex_doc should add MathJax or other form of formula plugin.

**Comment by josevalim** [comment]
@SchrodingerZhu I am worried about adding something that will affect the page load of all projects when very few projects will need the feature. I believe we should make this as easy as possible but I don't think we will provide this experience out of the box.

**Comment by SchrodingerZhu** [comment]
OK, in that case, I may add it by myself. And I suppose that you can add it as an optional feature which can be chosen in 'mix'.

**Comment by SchrodingerZhu** [comment]
You can close this issue now.

**Comment by tmbb** [comment]
A little offtopic, but try KaTeX. It supports almost everything Mathjax does and is much faster.

**Comment by josevalim** [comment]
Issue #761 should make this possible.
