### ISSUE TITLE
Should we always include source map files ( .map) in generated docs?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#758]
Or only if we include a flag such as --dev?

/cc @ericmj @milmazz @eksperimental @nscyclone

**Comment by ericmj** [comment]
I don't think it's necessary for production doc builds because it's usually pretty easy to regenerate the same docs by getting the library and ex_doc versions. But it's a very small thing to include anyway so for me either works :)

**Comment by josevalim** [comment]
It is 1.4mB per project. In Elixir, with 6 projects, it is a noticeable
increase on file size.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
> It is 1.4mB per project. In Elixir, with 6 projects, it is a noticeable
increase on file size.

In that case I would not recommend to include it by default.

**Comment by josevalim** [comment]
I put it behind a --debug flag in master.
