### ISSUE TITLE
Bugs in the new search history

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#760]
Hi @aphillipo!

I have been running your new PR on master and it works great. We were also able to catch some bugs. Some of those have been fixed in master:

* 3e8f16db75df1a183f752726851151817779d57c
* 050591baff102a4ddb426f27674c791e4fafc45e

But some were not. Those are described below:

## It breaks usual navigation

To reproduce:

1. Open up the documentation of any module
2. Click on any function on the sidebar
3. You will notice the page is briefly reloaded because of the `document.location.reload(true)` call

I understand why the reload call is needed since I was able to reproduce the original issue locally based on your very well detailed comments. However, given that calls is breaking the regular use of the docs, I have commented it out for now.

## The "close" search button is broken when we go "Back" to the search page

To reproduce:

1. Search any term where you can find a match for, such as "atom" in the Elixir docs
2. Click on any result
3. Press the "back" button in the browser to go back to the search
4. Now click the "X" to close the search - it won't go back to the page you were - it will look forever on the search page. This happens because the searchCount is zero.

## Solutions

I am not sure what is the best way to solve those problems. The first one is caused because clicking a fragment, such as `#id`, triggers popstate. The second one is caused because `searchCount` is zero when you go back to the page. So it seems we need more flags and checks around this particular feature.

At first it feels like relying on the global variable `searchCount` is very error prone. One option is to include the number of times you should go back in history directly in the URL:

    search.html?q=foo&h=2

The example above means that, if you click on the X, you should go back in history two times. This should fix the second issue. To solve the first issue, you will likely need to track if you are in the search page right now. This can be done, for example, by checking if you have the searchResults diff around (or if you keep some sort of global variable around as well).

**Comment by aphillipo** [comment]
I will take a look now...

**Comment by aphillipo** [comment]
I'll do them both as one commit for brevity - I chose ```&s=2``` rather than ```&h=2``` - can easily change it I thought you'd put ```s```.

I'll fix 1.  by checking the URL doesn't contain search.html?

**Comment by josevalim** [comment]
@aphillipo Any variable name is fine.

> I'll fix 1. by checking the URL doesn't contain search.html?

I think it is fair to only enable the pophandler stuff if you are in search.html, yeah.

**Comment by aphillipo** [comment]
Haha, it's more complicated that even that!  What a mess!  Please take a look (I'll push a new pull request shortly) - there has to be something I'm missing around this bug?  Why does Safari handle things perfectly without this unnecessary reload?

**Comment by josevalim** [comment]
@aphillipo here is an approach that should solve both problems. Whenever a search is done, you always go to the search page. No more history mangling, we let the browser do the job.

This has the following implications:

  1. The close button on the top right side corner is gone
  2. But what to select on sidebar? One option is to select nothing and show the search icon in purple, implying it is the one currently selected.

Then we could do the following usability improvements:

  1. We could make the search icon clickable such that I can use Cmd+Click on the icon to search on a new tab
  2. We could make sure Cmd+Enter on the search also opens up on a new tab

What do you think?

This should allow us to remove code and still provide the features we need.

**Comment by aphillipo** [comment]
I was actually thinking of going the other way and making search a modal overlay where history makes much less sense but this works fine too.  Shall I start a new pull request and remove mine?

**Comment by josevalim** [comment]
Hi @aphillipo! I have pushed 3b2dcc7b88d6d31830299a2ce01f47d16b36796d to master. Please give it a try, it implements the changes I suggested above by making search its own page. Elixir master docs should also be hosting it tomorrow for anyone who wants to give a try on some actual docs.
