### ISSUE TITLE
ExDoc assumes too much about the markdown modules

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#762]
The function `ExDoc.Markdown.as_html/2` (https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/markdown.ex#L31) assumes that the markdown implementation will generate code blocks eant to be highlighted by javascript. It calls `pretty_codeblocks/1` which mangles the resulting code blocks. This should be handled by the `as_html/2` function in the markdown modules themselves (`ExDoc.Markdown.{Cmark, Earmark, Hoedown}`), which you alreade define. People who want to use custom implementations shoud render the code you want themselves.

I have a markdown implementation that highlights code using HTML and CSS (no javascript) and messing with the class of the code block is not very good in that case (I have my own css classes).

**Comment by tmbb** [comment]
PS: my "custom markdown implementation" is just earmark with a custom code highlighter.

**Comment by tmbb** [comment]
I'm aware that this is a breaking change for people who use their own markdown implementations (I don't think this is a thing, though) and might depend on you changing the code block class. If tou think it's best, I can simply output code that deals with your postprocessing step.

**Comment by josevalim** [comment]
Moving it to the markdown engine is the way to go, definitely. Can you please send a PR? We can move the convenience function to `ExDoc.Markdown` and the engines can call it as appropriate.

**Comment by josevalim** [comment]
Btw ExDoc has not reached 1.0 yet, so it gives us a bit more flexibility in regards to breaking changes.

**Comment by tmbb** [comment]
Done. #763

**Comment by ericmj** [comment]
Fixed in #763.
