### ISSUE TITLE
Configure markdown throught a docs: [...] options instead of the application config

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#765]
As discussed here: #761

**Comment by josevalim** [comment]
Reading from the environment is really straight-forward, I don't think we will need to deprecate it.

**Comment by tmbb** [comment]
Ok, no deprecation. If set in both ways, which one has priority? Do we raise an error?

**Comment by tmbb** [comment]
My suggestion is that if set both ways we should raise an error. Otherwise, just use the one the user supplied (or the default).

**Comment by josevalim** [comment]
The rule is always local > global. So the app environment should come after the mix.exs one.

**Comment by tmbb** [comment]
Ok, that's even simpler. I'm planning on the following:

* Try to read from the app environment
  * if found, that's the processor
  * if not, look in the docs options
    * if found, use that
    * if not, look for a markdown processor the usual way

**Comment by josevalim** [comment]
It should be the opposite please. Something like: `opts[:markdown_processor] || Application.get_env(:ex_doc, :markdown_processor, DEFAULT)`.

**Comment by tmbb** [comment]
Yes, sorry -.- Mixed it up
