### ISSUE TITLE
There's no way of turning turning off highlightjs

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#767]
I have a markdown implementation that highlights elixir code using HTML and not javascript.  It's almost compatible with ExDocs except for a little detail.

Highlightjs mangles my rendered output in a visible way.

I wonder if you could add an option to disable Highlightjs. My suggestion is to do something like this:

```javascript
$(() => {
  // Setup Highlight.js
  hljs.configure({
    tabReplace: '    ', // 4 spaces
    languages: []       // disable auto-detect
  })

  initNightMode()
  initSidebar()
  initEvents()
  if (typeof DISABLE_HIGHLIGHTJS == 'undefined') {
    hljs.initHighlighting()
  }
})
```

This way the user could use the new `:before_closing_head_tag` option to initialize the variable (`<script>DISABLE_HIGHLIGHTJS = true;</script>`).

I have a demo page here: https://tmbb.github.io/exdocs_makedown_demo/api-reference.html. It's the Elixir standard library documentation, but with the code rendered with my tools instead of using  highlightjs.  For an example of how the highlighted code looks like you can see [here](https://tmbb.github.io/exdocs_makedown_demo/Agent.html#module-examples). I believe the output is much, much better than what Highlightjs produces and it properly recognizes the iex prompt (unlike the highlightjs lexer).

This is only working because I've manually edited the minified javascript generated by ExDoc to remove the call of `hljs.initHighlighting()`.

EDIT: remove some wrong information

**Comment by tmbb** [comment]
I can't submit a PR mysef because I ca neither install the required npm packages on my Windows computer nor on any Linux VM...

**Comment by tmbb** [comment]
Well, nevermind, I've found a workaround for this. Basically I just render code blocks as

```html
<code class="myclass">...</code>
```

Where:

```css
code.myclass { white-space: pre }
```

**Comment by tmbb** [comment]
Actually, there is an edge case I don't think I can deal with without disabling Highlight.js

**Comment by josevalim** [comment]
@tmbb shouldn't we instead change highlight.js rules so it applies only to snippets with certain attributes and not all of them?

**Comment by tmbb** [comment]
I've just looked at the highlight.js docs again and that apprently if your code block has the "nohighlight" class (`<pre><code class="nohighlight">...</code><pre>`) then it won't be highlighted. That will probably solve my problem. Unfortunately I won't be able to test it during the weekend because I've forgotten my laptop's charger at home. But it will probably work.

I'd missed this option when reading it for the first time, sorry.

**Comment by tmbb** [comment]
I am now adding `<pre><code class="nohighlight">...</code><pre>` to the code blocks I don't want Highlightjs to highlight and it's working.
