### ISSUE TITLE
Provide full text search

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#769]
To provide full text search, we can use a tool such as [lunr.js](https://lunrjs.com).

We can build an index off-line [when we generate the docs](https://github.com/slashdotdash/jekyll-lunr-js-search/issues/7) and just use the index on the website - this has the downside of requiring the person generating the docs to have node installed (we can fallback to the old search if they don't have one).

Thoughts?

**Comment by josevalim** [comment]
@ericmj has mentioned that Elixir docs have 700kb which would very likely make the index very large. There is a chance this approach is not viable at all.

**Comment by aphillipo** [comment]
I think this would excellent and was looking at the same solution.

700kb for search of all of Elixir isn't too bad, we could choose to load it and cache it after a first interaction with the search bar?

**Comment by josevalim** [comment]
it is very likely the tool already caches it for us. But given we have concerns with the size, the next step is probably to generate the index and see how long does it take and how large it is.

**Comment by ericmj** [comment]
700kb is the size of the markdown sources and it only includes module and function docs. I would imagine that the index is larger than the data it indexes. But we need to measure to be sure.

**Comment by aphillipo** [comment]
I'm knocking up a nasty bit of JS to give us a rough index size.  Will let you know the results for full Elixir docs in a bit...

**Comment by aphillipo** [comment]
Ah... Eric is correct, the output is probably too large at 4089864 bytes for elixir/doc/elixir/ (i.e. no ex_unit or ex_doc etc).  Gzipped it's 452kb which is still a bit large.

**Comment by ericmj** [comment]
@aphillipo Thanks for investigating.

We shouldn't gzip when building because we want this to work locally also and we can configure the CDN to gzip. 205kb isn't beyond the realm of possibility, how long does it take to for lunr to parse the index and return the search result?

Loading https://hexdocs.pm/elixir/Kernel.html fetches 209kb so it would double the page size but only when searching and I guess we can lazy load it?

**Comment by josevalim** [comment]
Master has already changed to have a specific search.html page so we will
only load it when needed.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tmbb** [comment]
Maybe it makes more sense for hex.pm to provide a search API instead? Just dumping the text into a PostgreSQL database and using the native search function is probably good enough

**Comment by ericmj** [comment]
@tmbb We are looking into that approach as well and one does not eliminate the other. Javascript search is a lot less development work and will work for offline docs. Search powered by hexdocs.pm can be more powerful because you can search across multiple packages and versions and we can use better search engines. But it also requires more work and requires infrastructure to support it.

Help on either approach would be much appreciated.

**Comment by olivernn** [comment]
Let me know if you have any questions on getting Lunr to work for you. It sounds like index size is the main question at this point, maybe I can help trying to make that smaller?

The issue of requiring node at build time for docs sites like this has come up before. There is nothing stopping someone from creating a backend for Lunr in something other than JavaScript, it just needs some time. A WIP schema for the generated index is [published](https://github.com/olivernn/lunr-schema) and I'd be happy to work with anyone wanting to take on an Elixir backend.

**Comment by peillis** [comment]
I've been doing some research with this to get an idea of the time it takes lunr.js to generate the index.
First I've generated a json with the contents. Basically extending the actual sidebar_items-(digest).js file, adding a "content" key with the docs. I've done a very crappy and basic extraction using Poison to encode the contents, this can be surely improved a lot.
In one of the Elixir docs pages (the biggest docs I've found), I've indexed the whole json object in lunr and get the times in the console.
It takes around 1 second in my laptop, which is a MBP 3.3GHz and using Chrome v63.
I don't know how much time could it take in a slower computer, but I think it's a very reasonable time. Besides, once the index is done it could be serialized and stored in a sessionStorage object.

**Comment by josevalim** [comment]
@peillis thanks. Assuming we can do it only when search is actually used, I do agree it is quite reasonable.

At the same time, if we can store it in the sessionStorage, we should also be able to precompute it. If that's the case, then I would definitely prefer it, as it yields a better user experience.

**Comment by peillis** [comment]
Before going any further with this. Is it ok to add Poison as a dependency of ExDoc?

**Comment by josevalim** [comment]
While that would be OK, I am more inclined to generate the index offline,
if possible. This means we would need node installed (or a js runtime) when
generating the docs... although I think it would be the best user
experience.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by peillis** [comment]
Anyway the json is needed to index the contents. Maybe an option could be to generate the index offline if node is available, and do it online when no index is found.

**Comment by josevalim** [comment]
> Anyway the json is needed to index the contents.

I see. Yeah, that makes sense. 

> Maybe an option could be to generate the index offline if node is available, and do it online when no index is found.

Seems to be more code to maintain though. :) Let's start with the offline one for now and see how it goes!

**Comment by aphillipo** [comment]
Seems to work great and gave me awesome results (the most correct things were first!). How big is the index size here? Would be worth checking the indexing on the Elixir codebase due to it being likely to be the largest index! Ta.

**Comment by josevalim** [comment]
This looks really great @peillis! :heart:

A couple of things, sometimes the markdown gets mixed up: http://demo.doofinder.com.s3.amazonaws.com/enrique/doc/search.html?q=example

I am afraid this is not an easy problem to solve? Unless we print to HTML and then we strip the tags? Or maybe the earmark engine has a mechanism to strip only text.

Btw, how should we show the overall information? Should it be something like:

    MODULE (OR PAGE)
    Entry name (section, type, function, macro, callback, etc)
    ...part where we matched...

Looking forward to this!

**Comment by tmbb** [comment]
Stripping the HTML tags seems simpler than messing with the Markdown

**Comment by peillis** [comment]
I hadn't noticed the markdown issue, I'll try to find a solution for that.
About how to show the information, what I've done so far is:
If there is a match in module, type, function, etc, then show just:
```
Module.Function
```
If the match is in the docs, sections, etc, then:
```
PAGE (or MODULE.FUNCTION...)
...parts with match...
```
If anyone has a better idea about this please tell me.

**Comment by josevalim** [comment]
@peillis I found the current match to not have enough information, that's why I proposed the other one:

```
MODULE (OR PAGE)
Entry name (section, type, function, macro, callback, etc)
...part where we matched...
```

We treat "MODULE / PAGE" as the title, we treat the "section / function" name as the subtitle and the matched part if any. Would that be possible?

**Comment by josevalim** [comment]
Examples:

```
KERNEL
is_atom/1 (function)
...matches an atom...
```

```
NAMING CONVENTIONS
Function names (section)
...starts with underscore...
```

**Comment by peillis** [comment]
I see. Ok, I think it's possible yes.

**Comment by peillis** [comment]
Hi, here is a new version with the commented improvements: http://demo.doofinder.com.s3.amazonaws.com/enrique/doc2/readme.html

**Comment by DeLongShot** [comment]
I became aware that this issue was being worked on last week. I'd like to help. If there is something I can do to help, let me know.  Otherwise, I'll jump in where I can.

**Comment by eksperimental** [comment]
hi @peillis,
One thing I noticed, is the If i type the name of the Module ending with a period. let's say "Enum." it should list all the functions under that module, but here it will give me no matches

**Comment by peillis** [comment]
Hi, I don't see why people would search with a period at the end. If you search using just the module, for example "Plug.Test" in the Plug example you'll see all the functions of that module. 
Anyway, I don't think the point of the search is to show all the functions of a module, for that I would go to the module page in question. I think the search should return the most relevant results.

**Comment by josevalim** [comment]
@peillis sorry for the delay on this. I think this looks excellent! :heart:

Here is some feedback:

1. The snippets we are showing in the search are not very helpful:

    ![screen shot 2018-07-11 at 14 50 17](https://user-images.githubusercontent.com/9582/42572428-cbad9982-8519-11e8-9af6-020f2e9d871e.png)

    Should we show only a single snippet and increase the radius?

2. Should we include the URL under the match? I think it can help developers decide if they got the correct match. Here is an example (please ignore the style, it is just an example):

    ![screen shot 2018-07-11 at 15 04 23](https://user-images.githubusercontent.com/9582/42573230-cbcc2e68-851b-11e8-88df-375e201479ec.png)

3. For the pages (such as API reference), you are using the page id ("api-reference") as the header in the search results instead of the page title ("API Reference"). You can see this in the screenshot above since we have "readme" and not "README"

4. As you can see in the screenshot above in the readme results, it seems we are showing unescaped expressions in results, such as `&quote`

5. If you [search for Plug.Conn](http://demo.doofinder.com.s3.amazonaws.com/enrique/doc2/search.html?q=Plug.Conn), you can see the `Plug.Conn` module appears twice, one for the moduledoc match and later one including each of its functions. Maybe if we the reason of a match is the module name (or the moduledoc), we do not need to show one entry for each function? Just the module itself?

6. [If you have an exact match on the subtitle, such as the function name, no snippet is shown](http://demo.doofinder.com.s3.amazonaws.com/enrique/doc2/search.html?q=async_assign). Maybe we could show the first sentence of the doc? Would this be possible?

I am really excited about this!

**Comment by milmazz** [comment]
@peillis Hi, are you still working on this? Do you need some help?

**Comment by peillis** [comment]
Hi, I couldn't work on it lately. Any help would be very much appreciated. Here is my work so far https://github.com/peillis/ex_doc/tree/full-text-search

**Comment by peillis** [comment]
Another step with this issue. 

See demo here: http://demo.doofinder.com.s3.amazonaws.com/enrique/doc3/readme.html

I've decided not to group the results under modules for multiple reasons: 
- complexity
- many times the results of a module where scattered due to different scorings
- this new way of displaying the results seems more informative, showing also the type of result (function, module, macro, callback...)
- a filter could be added in the future to display only one of those types, i.e. filter by 'functions'

@josevalim about your suggestions:

> 1. The snippets we are showing in the search are not very helpful:
>    Should we show only a single snippet and increase the radius?

It's done. Tell me if you think the radius should be bigger.

> 2. Should we include the URL under the match? I think it can help developers decide if they got the correct match. 

I've tried and imho doesn't seem to be very helpful. Usually it's just the title with some .html# chars.

> 3. For the pages (such as API reference), you are using the page id ("api-reference") as the header in the search results instead of the page title ("API Reference"). You can see this in the screenshot above since we have "readme" and not "README"

I've changed that. Actually it's not README what it's displayed but the title, "Plug" in this case.

> 4. As you can see in the screenshot above in the readme results, it seems we are showing unescaped expressions in results, such as `&quote`

I think those expressions come from code examples, but I'm not completely sure yet, and I'm not sure if we should clean the code examples from the search either.

> 5. If you [search for Plug.Conn](http://demo.doofinder.com.s3.amazonaws.com/enrique/doc2/search.html?q=Plug.Conn), you can see the `Plug.Conn` module appears twice, one for the moduledoc match and later one including each of its functions. Maybe if we the reason of a match is the module name (or the moduledoc), we do not need to show one entry for each function? Just the module itself?

This is solved with the new disposition of results. It could be argued that the functions of the module shouldn't be results of that search, but if I remove the module name from those items I think we lose accuracy in many other kind of queries, specially in projects with many modules and with queries with multiple terms.

> 6. [If you have an exact match on the subtitle, such as the function name, no snippet is shown](http://demo.doofinder.com.s3.amazonaws.com/enrique/doc2/search.html?q=async_assign). Maybe we could show the first sentence of the doc? Would this be possible?

This is done as well.

**Comment by josevalim** [comment]
@peillis this is awesome.  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:  I have no further notes! What is the next step? :)

**Comment by axelson** [comment]
Here is a link to the merged PR: https://github.com/elixir-lang/ex_doc/pull/974

:confetti_ball: :tada:
