### ISSUE TITLE
defdelegate with default values: confusing documentation link to private module

### ISSUE THREAD

**Issue by davidsulc** [elixir-lang/ex_doc#770]
ExDoc generates confusing documentation when functions are `defdelegate`d with default values. Example:

```elixir
defmodule Foo do
  defmodule Bar do
    @moduledoc false

    def hello(name, _options) do
      IO.puts "Hello, #{name}"
    end
  end

  @doc """
  Prints a welcoming message
  """
  defdelegate hello(name, options \\ []), to: __MODULE__.Bar

  @doc """
  Prints hi
  """
  def hi(name, options \\ []), do: IO.puts "Hi!"
end
```

In the above, I would like to have `Foo.Bar` as a private module (hence `@moduledoc false`), and expose the functionality via the public `Foo` API.

In this situation, ExDoc will generate the following docs:

> 
> ### hello(name)
> 
> Prints a welcoming message
> 
> ### hello(name, options)
> 
> See `Foo.Bar.hello/2`.
> 
> ### hi(name, options \\\\ [])
> 
> Prints hi

Note how the generated `defdelegate` docs differ from the docs for `hi/2` in cases that are similar. This is particularly confusing, as the reader is told to refer to `Foo.Bar.hello/2` which isn't publicly documented.

I would instead expect the documentation to yield a single documented function for `hello/2`:

> 
> ### hello(name, options \\\\ [])
> 
> Prints a welcoming message

**Comment by josevalim** [comment]
@davidsulc can you please open up this issue in elixir-lang/elixir? The root cause is there. :) Thank you!

**Comment by davidsulc** [comment]
@josevalim Done: https://github.com/elixir-lang/elixir/issues/6487

Please feel free to close this issue.
