### ISSUE TITLE
Allow configurable filename

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/ex_doc#773]
Currently the filename is defined in https://github.com/elixir-lang/ex_doc/blob/e47a52572883ded94af3af979178ba506dcdcb14/lib/ex_doc/formatter/epub.ex#L54

To prevent having to keep this in sync with any documentation that links to the file, it is desirable to not have the version in the filename.

Please see https://github.com/phoenixframework/phoenix/pull/2481

If we want this to be configurable, what do you suggest as a config option? `filename`, `epub_filename`, `output_filename`? If we do `output_filename` then it could work for other formats in the future e.g .`output_filename: "phoenix"` could generate:

 * phoenix.epub
 * phoenix.mobi
 * phoenix.pdf
 * phoenix.zip

**Comment by josevalim** [comment]
`epub_filename` sounds great to me!
