### ISSUE TITLE
Publish this package itself to hexdocs

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/ex_doc#783]
Hey! I'm a little curious why [`ex_doc`](https://hexdocs.pm/ex_doc) itself doesn't have its own documentation published anywhere? Seems a little ironic 😂 

In general I'm looking for the answers to a few questions, namely:

- Does the new `groups_for_modules` option honor your group ordering or arrange it alphabetically? (My understanding is that it was the former and is now the latter, deduced through commit message history.)
- Do identically named groups in `groups_for_modules` and `groups_for_extras` merge, and if so how are the entries of different types arranged within the group? Haven't figured this out yet.
- What does the module passed to the `retriever` option do and when might I want to override it outside of dependency injection during the ex_doc test suite? I expected to find the answer in the [moduledocs for `ExDoc.Retriever`](https://github.com/elixir-lang/ex_doc/blob/f5fd932f63576eeda85ba6ce7294d6dd7d7660fa/lib/ex_doc/retriever.ex#L82) but didn't get as much info as I'd hoped.

Answers to my questions aside, it seems like there should be an entry at https://hexdocs.pm/ex_doc to begin digging for these answers, if not also a link to them in the [main lang docs index](https://elixir-lang.org/docs.html) or at least a link to them from the [core documentation writing guide](https://hexdocs.pm/elixir/writing-documentation.html) that this repo's readme links to.

**Comment by josevalim** [comment]
I will publish some docs today but the docs are partially treated like a black box. So the ones available are the ones behind `mix help docs` and `bin/ex_doc`.

**Comment by josevalim** [comment]
Published.

**Comment by christhekeele** [comment]
The black box reasoning makes sense to me, but on the other hand I do appreciate the resource. Thanks!
