### ISSUE TITLE
0-arity types consistency with Code.Formatter

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#788]
Currently on Elixir `master`, formatter adds parens for 0-arity remote types.

```elixir
iex> Code.format_string!("@spec foo(String.t) :: String.t") |> IO.iodata_to_binary()
"@spec foo(String.t()) :: String.t()"
```

`ex_doc` master does not:

```elixir
iex> ExDoc.Formatter.HTML.Autolink.typespec(quote(do: to_string(integer) :: String.t), [], [])
"to_string(integer) :: <a href=\"https://hexdocs.pm/elixir/String.html#t:t/0\">String.t</a>"
```

---

As discussed on IRC, we should change ex_doc to add parens for 0-arity type specs.

Btw, should we also add parens for 0-arity _local_ type specs, e.g.:

`@spec foo(t) :: t` should be `@spec foo(t()) :: t()`?

**Comment by josevalim** [comment]
> @spec foo(t) :: t should be @spec foo(t()) :: t()?

Yes I think the same code that removes it from local also removes it from remote.

**Comment by wojtekmach** [comment]
@josevalim sorry, forgot to ask. Regarding local types formatter _does not_ add parens:

```elixir
iex> Code.format_string!("@spec foo(t) :: t") |> IO.iodata_to_binary()
"@spec foo(t) :: t"
```

so should we change it in Elixir as well?

Happy to send PR for both changes.

**Comment by josevalim** [comment]
We can't change the formatter because the formatter doesn't change the semantics of the code. We could special case @spec/@callback but that's usually a no-no. /cc @whatyouhide 

We can/should change ExDoc though since it knows for certain it is a spec/callback/etc.

**Comment by ericmj** [comment]
I agree with @josevalim. Don't change formatter, special case in ex_doc and change the rule in the style guide https://github.com/lexmag/elixir-style-guide#parens-in-zero-arity-types.

**Comment by whatyouhide** [comment]
We can start by not having the formatter change this, but change the style guide, as @ericmj said :).

**Comment by josevalim** [comment]
Done on 8ac4516414f59baf1d82aba096cb4e91acdf58f4.
