### ISSUE TITLE
Make types linkable

### ISSUE THREAD

**Issue by yordis** [elixir-lang/ex_doc#793]
I notice that I can link functions in the documentation when I use back quotes but I can't link types.

For example

`Module.function_name/1` works

`Module.t` do not works

**Comment by wojtekmach** [comment]
for types, use: `t:Module.t`. See: https://hexdocs.pm/ex_doc/readme.html#auto-linking

**Comment by yordis** [comment]
@wojtekmach my bad! I didn't know that doc exists. Completely my fault to assume something! Sorry!
