### ISSUE TITLE
Broken link to MySQL guide

### ISSUE THREAD

**Issue by manju16832003** [elixir-lang/ex_doc#795]
In the following link, Link to **Using MySQL Guide** is broken.

https://hexdocs.pm/phoenix/ecto.html#content

![screen shot 2017-11-03 at 12 07 46](https://user-images.githubusercontent.com/5035624/32360319-a244a026-c08f-11e7-8060-065281e43cea.png)

![screen shot 2017-11-03 at 12 19 25](https://user-images.githubusercontent.com/5035624/32360493-42093eea-c091-11e7-96fe-9c3e97fcfc75.png)

**Comment by josevalim** [comment]
Please report that to the Phoenix repository. Thank you!

**Comment by josevalim** [comment]
Here is the link: github.com/phoenixframework/phoenix :)
