### ISSUE TITLE
Complex types formatting

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#799]
Currently it's only broken on `|`, and so e.g. on complex structs it looks like this:

<img width="847" alt="zrzut ekranu 2017-11-26 o 18 36 35" src="https://user-images.githubusercontent.com/76071/33242651-c8c8737a-d2d8-11e7-9f2b-28d4ceb9a277.png">

(https://hexdocs.pm/ecto/Ecto.Changeset.html#t:t/0)

Ideally, we'd get back something similar to what formatter can do:

```
iex> IO.puts Code.format_string!("t() :: %Ecto.Changeset{action: action, changes: %{optional(atom) => term}, constraints: [constraint], data: Ecto.Schema.t | map | nil, empty_values: term, errors: [{atom, error}], filters: %{optional(atom) => term}, params: %{optional(String.t) => term} | nil, prepare: [(t -> t)], repo: atom | nil, repo_opts: Keyword.t, required: [atom], types: nil | %{optional(atom) => Ecto.Type.t}, valid?: boolean, validations: Keyword.t}")
t() :: %Ecto.Changeset{
  action: action,
  changes: %{optional(atom) => term},
  constraints: [constraint],
  data: Ecto.Schema.t() | map | nil,
  empty_values: term,
  errors: [{atom, error}],
  filters: %{optional(atom) => term},
  params: %{optional(String.t()) => term} | nil,
  prepare: [(t -> t)],
  repo: atom | nil,
  repo_opts: Keyword.t(),
  required: [atom],
  types: nil | %{optional(atom) => Ecto.Type.t()},
  valid?: boolean,
  validations: Keyword.t()
}
```

**Comment by josevalim** [comment]
Yeah, we can start using the formatter if it available but we may lose
cross linking.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
Yup, bringing in formatter without auto linking is pretty trivial. To have it both ways though: do you think it should be approached from the angle of parsing ast or constructing some special algebra docs or something entirely different?

**Comment by josevalim** [comment]
@wojtekmach no idea. We may be able to do this:

1. Convert the AST with `Macro.to_string` and convert each function we want to link to a unique id. For example, autolink_1, autolink_2. The result is AST as a string and a map with function names (autolink1 and friends) as keys and the link as values.

2. Format the result if the formatter is available

3. Use a regex to convert function names back to autolinks.

**Comment by wojtekmach** [comment]
@josevalim brilliant, that should work. `autolinkX` is definitely a good start. Possible next step to consider is to have these unique ids have the same length as the identifiers that they're replacing so that formatter works as if on the real thing. Generating such ids should be fine for long identifiers, but for short identifiers it's easy to get a conflict so I'm thinking that some weird unicode code points could be used there :)

**Comment by wojtekmach** [comment]
@josevalim so far so good, stay tuned!

<img width="848" alt="zrzut ekranu 2017-11-27 o 00 24 44" src="https://user-images.githubusercontent.com/76071/33245527-7230b3de-d309-11e7-8f72-457e5c054e8f.png">

**Comment by josevalim** [comment]
> Generating such ids should be fine for long identifiers, but for short identifiers it's easy to get a conflict so I'm thinking that some weird unicode code points could be used there

I think we can go with a minimum and that should be fine for most purposes as the nesting doesn't need to be exact. Maybe just a bunch of `t`s followed by a number with a minimum of 3 `t`s (it doesn't need to be `t`, you get the idea). :)

The end result looks great btw.

**Comment by wojtekmach** [comment]
yup, I ended up making placeholders in the form of `_p000_` for now :)
