### ISSUE TITLE
Support for .erl and .hrl files

### ISSUE THREAD

**Issue by enilsen16** [elixir-lang/ex_doc#804]
I was wondering what it would take to support `.erl` and `.hrl` files in mix(maybe even rebar projects). 

WRT rebar3 support:
As I am sure you know a large portion of erlang projects either user readme.io(paid) or just write their docs inside the readme. Would be cool for all docs to be hosted on the same site with a familiar style.

**Comment by josevalim** [comment]
Handling those files would be completely different from how ExDoc is implemented, therefore we have no plans to support it. We are discussing with the OTP team ways to standardize how documentation is stored but it may take a while before it happens.

**Comment by enilsen16** [comment]
Ok thanks José. Glad to hear that some work is being done in this area 👍
