### ISSUE TITLE
Update to earmark 1.2.5

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/ex_doc#805]
This is just a note (mostly to myself; I don't expect anyone else to attend to it) to update `ex_doc` to use [earmark 1.2.5]() when it is published so that `h2` headers defined with the 'underline' style `------` decorations are properly recognized when immediately following lists (instead of rendering as text and an `hr` as it does [currently](https://github.com/pragdave/earmark/issues/168)).

**Comment by josevalim** [comment]
I don't think we need to force an update from ex_doc. People can get latest earmark in their projects by doing `mix deps.update ex_doc` or `mix deps.update earmark`. Thanks!

**Comment by RobertDober** [comment]
thank you for your close collaboration.
Hopefully I have not missed a point here, Earmark 1.2.5 is **not released yet**.

I can ask Dave anytime, ex_doc is kinda our Killerapp, right? 😄

**Comment by christhekeele** [comment]
:D Sorry I missed this, @RobertDober. The point of the issue was to make a to-do reminder for myself to submit a PR to update ex_doc to earmark 1.2.5 when it *does* get released. José made a good point that ex_doc users can get the fix, when it does go live, quite easily; which is probably preferable to a patch bump just for an out-of-project bugfix in a dependency.

Thanks for implementing the upstream fix! I see a few other easy open issues on the 1.2.5 milestone, if I can steal some time this weekend I might take a stab at them to give back and help the release on its way. 💜

**Comment by RobertDober** [comment]
Happy New Year @christhekeele and do not worry I went there (ex_doc) and realized the situation.
Good luck with your issues.
