### ISSUE TITLE
Improve documentation of Callbacks

### ISSUE THREAD

**Issue by yordis** [elixir-lang/ex_doc#806]
> Right now when I generate the documentation of my project I noticed that there is no typespec on my functions in the generated documentation.
I am not sure if this belongs to here, which probably means we have to add the typespec inside the macro?! or should belong to ex_doc where they should detect is a callback and add the typespec to the documentation, either way I am expecting to have the typespec on my repo module.

Related to https://github.com/elixir-ecto/ecto/issues/2349

**Comment by wojtekmach** [comment]
@josevalim WDYT about solving this on Elixir side, e.g. whenever we `@impl true`  a function we'd copy specs from the callback? (unless function already has `@spec`) The benefit would be we'd have it for IEx too

**Comment by josevalim** [comment]
@wojtekmach I don't think it is a good idea because you don't need to define @callbacks with specs in order to have a behaviour. You just need to implement `behaviour_info(:callbacks)`. Everything else specific to typespecs is a convenience.

**Comment by wojtekmach** [comment]
@josevalim if someones creates such behaviour then it won't have typespecs in beam and so we won't copy these - that's fine. Unless I'm missing something.

But yeah, not touching core and starting with doing a bit extra work in ex_doc (and iex to have similar feature) and maybe revisiting it later - sounds reasonable too!

**Comment by wojtekmach** [comment]
As explained in https://github.com/elixir-lang/ex_doc/pull/815 it gets tricky when callback uses local types, so closing this for now.

**Comment by yordis** [comment]
@wojtekmach but what happen with having the types on the generated doc? Could you just bring the same documentation from the callbacks?


Something like https://github.com/elixir-lang/ex_doc/pull/641#issue-189163842 mentioned ?

**Comment by wojtekmach** [comment]
@yordis the documentation from callback is already copied (per #641), but we can't simply copy the types because of edge cases mentioned in #815.

**Comment by yordis** [comment]
@wojtekmach @josevalim I would love to share a thought about this topic

From the following code

```elixir
defmodule Parser do
  @callback parse(String.t) :: {:ok, term} | {:error, String.t}
  @callback extensions() :: [String.t]
end

defmodule JSONParser do
  @behaviour Parser

  @impl Parser
  def parse(str), do: {:ok, "some json " <> str} # ... parse JSON
  
  @impl Parser
  def extensions, do: ["json"]
end
```

Why can't we do what `defdelegate` does?

We use `@impl Parser` which means we know which module we suppose to point to and then use the function name to figure out the callback name.

No?

**Comment by josevalim** [comment]
The reason why @impl hides docs is because it can also be used for
GenServer and similar, where you don’t want the callback implementation to
be part of the documentation. So you have to do it explicitly.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by yordis** [comment]
@josevalim I know we tried to fix this and we didn't find any viable solution, but, can we give a second try to this issue?

I keep coming back to this issue and I would love to mitigate the misinformation from the documentation.

I am not sure what do you mean by being used for GenServer since I thought this `@impl` was used for defining implementations of `@callback` from a Behaviors. I would love to understand what is the issue with the GenServer.

From official release note:
> This release also allows developers to mark which functions in a given module are an implementation of a callback.

**Comment by wojtekmach** [comment]
@yordis imagine you implement a GenServer with a handle_call function (without marking it as `@impl true`) and generate docs for it, say with ExDoc. Now your module docs will have a huge wall of text which is the handle_call docs, which aren't relevant at all to your module's docs, they're by definition implementation details.

**Comment by yordis** [comment]
@wojtekmach got it, that is why we decided to hide the docs automatically 😢 

What about

```
@impl MyModule, some_key_here_link_to_behavior: true 🤷‍♂ 
# or +
@doc true
def my_callback do end
```

I guess the issue is that we made the decision to hide the doc is now problematic to fix.

**Comment by wojtekmach** [comment]
> `@impl MyModule, some_key_here_link_to_behavior: true 🤷‍♂`

if you want to highlight the fact that something is a, say, GenServer, you can do it explicitly today:

```elixir
@moduledoc """
(...)

See `GenServer` docs for more information.
"""
```

> I guess the issue is that we made the decision to hide the doc is now problematic to fix.

This is my personal opinion, but I just don't see the problem here, given callbacks are implementation details it makes a lot of sense to me to hide them.

**Comment by wojtekmach** [comment]
btw, regarding copying callback docs to functions that are implementing them, while I originally really liked this feature, it does suffer from the same problem as copying specs would (which we didn't implement), which is, if said docs refer to some local functions/types/etc, these links would be broken when copied.

For this reason, I'd given go as far as not _copying_ callback docs, but instead basically generate:

```
@doc "Callback implementation for `c:GenServer.handle_all/3`."
```

(cc @josevalim)

I think we may even had (or still have) something like this at some point.

**Comment by wojtekmach** [comment]
Just to be clear, on one hand I'm arguing that we shouldn't show callback docs in the first place, but on the other that if we do, instead of copying the docs we should create minimal ones instead, so what's the deal, right?

One particular use case for copying callback docs is when `use Mod` defines functions that are documented as callbacks and are defoverridable, like `use Ecto.Repo` for example does. And so by copying the callback docs (or creating minimal docs with just a link like I'm proposing) we can do:

```
iex> h MyApp.Repo.insert
```

which is an important use case.

**Comment by yordis** [comment]
> given callbacks are implementation details it makes a lot of sense to me to hide them.

Right, I totally agree, but I am losing the ability to have a nice documentation in non-genserver behaviors.

> @doc "Callback implementation for `c:GenServer.handle_all/3`."

I really like this idea! It makes the typespec simple and we get documentation linking which is even better/
