### ISSUE TITLE
Make opaque types more obvious

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/ex_doc#808]
Right now, opaque types are rendered as:

<img width="424" alt="screenshot 2017-12-16 23 29 46" src="https://user-images.githubusercontent.com/477062/34074885-0a46ed82-e2b9-11e7-9914-eaea9aea0db5.png">

Which is not very useful - it's not obvious what's going on. I think there should be some indication that the type is opaque. It probably also doesn't make much sense to link to the type itself from the definition.

This is with ex_doc 0.18.1

**Comment by wojtekmach** [comment]
maybe similar how we do `(macro)` on the right, we'd do `(opaque)` for this?

autolinking to itself is definitely a bug.

**Comment by josevalim** [comment]
We could either do (opaque) on the right side or right after the type definition.

About the autolinking I am fine with it, don't we link to itself on all types?

**Comment by wojtekmach** [comment]
Implementation-wise it's trivial to put it on the right side so I'd like to start there :)

> About the autolinking I am fine with it, don't we link to itself on all types?

Not anymore as of: https://github.com/elixir-lang/ex_doc/pull/626; btw, this is why we have a [few](https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/formatter/html/autolink.ex#L221) [shenanigans](https://github.com/elixir-lang/ex_doc/blob/5b7afcaf01d917bd4a26898160403b2c490176ac/lib/ex_doc/formatter/html/autolink.ex#L192)
