### ISSUE TITLE
Option :source_root doesn't work properly

### ISSUE THREAD

**Issue by bpiepiora** [elixir-lang/ex_doc#814]
Hi, I tried the :source_root option and it seems to be broken. I have configured the :elixirc_paths option in my mix project like

    ...
    elixirc_paths: ["lib", "test/xsd_output"],
    ...

and now I want to exclude the test folder with the :source_root option.
I tried it within the docs "section"

    ...
    docs: [
      source_root: "./lib"
    ],
    ...

and within the project itself
    
    ...
    source_root: "./lib"
    ...

but none of them works.

**Comment by josevalim** [comment]
The source root is not used to find BEAM files. It is used to generate links to the repository. It is used mostly for ex_doc via the command line (and not via the mix task).

If you want to exclude the test folder, you need to conditionally define elixirc_paths. Try including the test directory only if Mix.env is :test.

**Comment by bpiepiora** [comment]
Thanks, that's even a better solution to my problem!
