### ISSUE TITLE
Generated web pages print poorly

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/ex_doc#818]
I've been unable to print clean copies of ex_doc's generated web pages (using Chrome on OSX). Basically, I'd like the sidebar to disappear, so that the text (including code sections) can use the full width of the paper. I find reading extended documentation online to be very difficult, so this is quite important to me.

**Comment by josevalim** [comment]
It is unlikely we will be able to make those docs nicely printable. It is
preferable to use the different formats that ex_doc can generate, such as
ePub.

More info can be found here:
https://elixirforum.com/t/is-it-possible-to-download-elixir-phoenix-docs-as-pdf-or-mobi/5766/7
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by aphillipo** [comment]
I can probably look at this if people are interested in a pull request?

**Comment by josevalim** [comment]
If it is possible, then a PR is definitely appreciated.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by aphillipo** [comment]
It'll just a be a separate print style sheet that overrides stuff and makes things look right.  Will have to checkout how ex_doc looks on a kindle at some point, never thought about this until now! Will look before the end of the week. Thanks.

**Comment by wojtekmach** [comment]
@aphillipo there's already a file for print-related styles: https://github.com/elixir-lang/ex_doc/blob/master/assets/less/print.less, however it doesn't seem like it's working.

**Comment by RichMorin** [comment]
FWIW, I'd be the last person to argue against ePub, given that I wrote an ePub reader for a blind friend of mine. However, having a print style that leaves off the sidebar (etc) seems like a shorter path.

**Comment by aphillipo** [comment]
@wojtekmach Yes, it uses an ID instead of a class to hide the sidebar.  I'll work in that file and make sure it looks nice when printed.

**Comment by RichMorin** [comment]
You guys rock!

**Comment by RichMorin** [comment]
Any progress on this issue?

**Comment by nscyclone** [comment]
Thanks, @RichMorin!
I've proposed a couple of small changes to the `print.less` to make it readable. Please take a look at #824, there are some examples of printed pages with those changes applied.
