### ISSUE TITLE
UX request: Automatically go to "Top"

### ISSUE THREAD

**Issue by dogweather** [elixir-lang/ex_doc#826]
I'm not sure if this is the right place to post this — I experience this problem on the hexdocs.pm website.

I have a frequently frustrating experience that I click on a topic, E.g. **Up and Running**:

https://hexdocs.pm/phoenix/overview.html

And then I have a micro-pause while I wait for the content to appear. It doesn't, so I look back to see if I "did something wrong". I look back to the left and see that the tree opened up, exposing **Top**. 

![screen shot 2018-02-04 at 9 11 37 pm](https://user-images.githubusercontent.com/150670/35789282-031d987c-09f0-11e8-9c65-fdce8b78d9c5.png)

Then I remember — on this one site, I must always click, navigate the mouse, then click again to read a topic.

Expected Behavior:
Clicking a topic automatically opens **and displays** the Top section.

**Comment by josevalim** [comment]
That's how it worked in the past but people got upset that they could navigate the documentation without moving away from the current page.

This has been discussed in the past and the offer still stands: if someone wants to do some mockups on how we can have both navigation and a single click, we will be glad to discuss it. Meanwhile, we don't plan to personally work on it. :)

**Comment by dogweather** [comment]
Thanks! Understood, and it makes sense.
