### ISSUE TITLE
Dark theme nav bar background colour not complementary to main panel background

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/ex_doc#828]
I know this is really picky so I'm prepared for this issue to close in record time. 

I really like the dark theme.  

But the black background really clashes with the deep blue of the navigation panel.  If there's any support for looking at alternatives I'm fine to experiment and present some for discussion.

**Comment by josevalim** [comment]
@kipcole9 discussing other alternatives doesn't hurt. :) But keep in mind that you may work on those alternatives and no change may come out of them. It is up to you.

**Comment by josevalim** [comment]
Closing this since it is something we are not tackling ourselves but we do welcome discussions on.
