### ISSUE TITLE
Rollback underlines for top level links

### ISSUE THREAD

**Issue by tompave** [elixir-lang/ex_doc#829]
Commit https://github.com/elixir-lang/ex_doc/commit/d86ad659cd0c806a8fd50dbc0f58bbfe1f63cd74 introduced `text-decoration: underline;` for the top-level links in each module page.

With `ex_doc 0.18.1`:

<img width="571" alt="screen shot 2018-02-10 at 00 25 24" src="https://user-images.githubusercontent.com/2141406/36056058-06df7d56-0df9-11e8-972e-832b37473fa1.png">

Now, with `ex_doc 0.18.2`:

<img width="580" alt="screen shot 2018-02-10 at 00 21 55" src="https://user-images.githubusercontent.com/2141406/36056061-0fe73560-0df9-11e8-8b88-1f0d8a863757.png">

This is arguably less than ideal for source code and a monospace font, as it can be difficult to distinguish between the underline and the underscore characters.

Would it be possible to revert that change?

**Comment by josevalim** [comment]
Reverting. /cc @LostKobrakai

**Comment by josevalim** [comment]
Done!

**Comment by tompave** [comment]
Whoohooo! Thanks! 👍
