### ISSUE TITLE
ExDoc v0.18.2 Elixir v1.6.1 typespec causes crash on mix docs

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/ex_doc#831]
The following module compiles fine but will cause a crash on `mix docs`:

    defmodule ExDocTestA do

      @moduledoc "An ExDoc Test"

      @type map42 :: any

    end

The error:

> ** (EXIT from #PID<0.74.0>) an exception was raised:
    ** (KeyError) key "p42" not found in: %{"pp1" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">any</a>"}
        (stdlib) :maps.get("p42", %{"pp1" => "<a href=\"https://hexdocs.pm/elixir/typespecs.html#basic-types\">any</a>"})
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:301: anonymous fn/2 in ExDoc.Formatter.HTML.Autolink.replace_placeholders/2
        (elixir) lib/regex.ex:666: Regex.apply_list/5
        (elixir) lib/regex.ex:661: Regex.apply_list/5
        (elixir) lib/regex.ex:603: Regex.do_replace/4
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:138: anonymous fn/5 in ExDoc.Formatter.HTML.Autolink.all_typespecs/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_doc) lib/ex_doc/formatter/html/autolink.ex:137: ExDoc.Formatter.HTML.Autolink.all_typespecs/3

**Comment by wojtekmach** [comment]
Thanks for the report, I’ll look into it
