### ISSUE TITLE
Streamline the menu navigation

### ISSUE THREAD

**Issue by nurges** [elixir-lang/ex_doc#837]
Currently the left menu bar always opens a submenu, even if it only contains the 'Top' item.
You have to click two times to get to the actual content.

Maybe it would be better to open the actual content page on menu selection.
Also the 'Top' item serves no purpose if it's the only item in the submenu.

[Ecto tasks](https://hexdocs.pm/ecto/Mix.Tasks.Ecto.html) is a good example of single item submenus.

**Comment by josevalim** [comment]
This has been opened a couple times so I recommend reading previous issues. When we opened the content on click a lot of people complained. If we simply revert it, then half of the people will be happy and the other half will start complaining.

We would appreciate if somebody would tackle this and provide a mechanism that could integrate both ways of navigating.

**Comment by Gazler** [comment]
@josevalim I saw this recently which might be a solution?

https://amberframework.org/guides/getting-started/README.md#getting-started

![amber-docs](https://user-images.githubusercontent.com/477511/37332558-f2f511ac-269e-11e8-9d8f-d8afc3eebaf4.png)

**Comment by josevalim** [comment]
Yeah, that looks good. Although I would prefer a general way of solving this, that would allow people to expand the menu item or go directly to the page. It could be as simple as having a `+` in front of each element.

If the element has no children, then no `+`. :)
