### ISSUE TITLE
Hamburger icon is too close to Night mode icon

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#847]
I was reading the docs in my phone, and literally I had to hit like 5 times until I manage to activate the menu, and not the day/night mode. They need to be spaced out a bit, anyway there's all the vertical room on the screen to do that
just a quick note for myself or for whoever feels like fixing this

**Comment by nscyclone** [comment]
@eksperimental @dignifiedquire Does this look comfortable enough?

<details>

<summary>Desktop</summary>

![icons](https://user-images.githubusercontent.com/5345029/39233204-602e47fc-4878-11e8-95c1-cc065e3c6ac2.gif)

</details>

<details>

<summary>Mobile</summary>


![mobile](https://user-images.githubusercontent.com/5345029/39233209-64398a00-4878-11e8-8e16-1fa8d54158a1.gif)

</details>

**Comment by josevalim** [comment]
@nscyclone I feel like the spacing is too much now in a way it looks like they are disjoint. But I am not a designer. Thoughts?

**Comment by aphillipo** [comment]
Yes, the spacing between the items should not be more than the spacing around them. I have the feeling that everyone actually moves to their preferred state with night mode then never changes it. Docs should ask you the first time you visit then never again IMO and the Icon should be text in the footer like it was before - then the burger can be larger.

**Comment by josevalim** [comment]
I am not a big fan of asking. There is no reason to interrupt the user flow. :)

**Comment by OvermindDL1** [comment]
> I have the feeling that everyone actually moves to their preferred state with night mode then never changes it.

I'd be entirely for it defaulting to dark mode as light mode is eye-gougingly painful...  ^.^;

**Comment by aphillipo** [comment]
I do think we should show nightmare by default as it looks awesome to me and the whole point of moving it was to make the option more visible. My guess is 80% of people want nightmode and mostly people don't change so it definitely shouldn't babe interfering with opening the sidebar on mobile.

Therefore we could just default to night mode and put the switch in the footer only on mobile?

**Comment by josevalim** [comment]
If we enable night mode by default and move the switch back to the footer, then in a month everyone who prefers the day mode will come up and say that they prefer the day mode and complain that the button is hidden.

So I don't think changing the defaults and moving the button back is an option.

**Comment by aphillipo** [comment]
Just on mobile though? Fair enough I can understand, it just seems like mobile and desktop have very different requirements for changing the night mode setting, never mind the battery saving of darker screens on mobile - I was half joking when I said this but the battery drain seems fairly meaningful: https://www.greenbot.com/article/2834583/how-much-power-does-a-black-interface-really-save-on-amoled-displays.html

**Comment by josevalim** [comment]
And yet the same site that wrote the report opened up in white background in my phone. :) This is useful information to help on the decision process but I don't think it is critical. I would prefer to keep everything consistent and reduce the amount of work.

**Comment by josevalim** [comment]
Folks, we haven't had progress here, so I will close this issue. The buttons are indeed close but keeping them to far away looks awkward. So far it is a pick your poison kind of deal so we will keep things as is to avoid churn.
