### ISSUE TITLE
bug when linking to `Kernel.//2`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#849]
`Kernel.//2`

create a link to `%60Kernel.//2%60`

**Comment by josevalim** [comment]
There is no Kernel.//2 function? Also, how to reproduce this? Can you
please give more information?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment]
https://hexdocs.pm/elixir/master/Kernel.html#//2

**Comment by eksperimental** [comment]
The error appeared in the guards page, in the Elixir project

I see that its using the new way to linking to functions, maybe is that
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Guards.md

     * arithmetic binary operators ([`+`](`Kernel.+/2`), [`-`](`Kernel.-/2`), [`*`](`Kernel.*/2`), [`/`](`Kernel.//2`))

**Comment by eksperimental** [comment]
Thank you
