### ISSUE TITLE
Crash on typespec and callback

### ISSUE THREAD

**Issue by Shakti213** [elixir-lang/ex_doc#852]
Trying to document the following causes a crash, tried both 0.18.3 and master
```Elixir
defmodule Math do
    @moduledoc """
    Provides math-related functions
    ## Examples
        iex> Math.sum(1,2)
        3
    """
    @spec sum(number, number) :: number
    def sum(a,b) do
        a+b
    end
end
```

Also the following causes a crash:
```Elixir
defmodule Math do
    def sum(a,b) do
        a+b
    end

    @callback mul(number, number) :: number
end
```

The following is the log output:
```
** (EXIT from #PID<0.73.0>) an exception was raised:
    ** (ArgumentError) argument error
        lib/ex_doc/formatter/html/autolink.ex:244: anonymous fn/7 in ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
        (elixir) lib/macro.ex:277: anonymous fn/4 in Macro.do_traverse_args/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:243: Macro.do_traverse/4
        (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/macro.ex:243: Macro.do_traverse/4
        lib/ex_doc/formatter/html/autolink.ex:227: ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
        lib/ex_doc/formatter/html/autolink.ex:217: ExDoc.Formatter.HTML.Autolink.format_typespec/4


10:03:08.923 [error] Task #PID<0.76.0> started from #PID<0.73.0> terminating
** (ArgumentError) argument error
    lib/ex_doc/formatter/html/autolink.ex:244: anonymous fn/7 in ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
    (elixir) lib/macro.ex:277: anonymous fn/4 in Macro.do_traverse_args/4
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:243: Macro.do_traverse/4
    (elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:243: Macro.do_traverse/4
    lib/ex_doc/formatter/html/autolink.ex:227: ExDoc.Formatter.HTML.Autolink.format_and_extract_typespec_placeholders/4
    lib/ex_doc/formatter/html/autolink.ex:217: ExDoc.Formatter.HTML.Autolink.format_typespec/4
Function: #Function<30.37719060/0 in ExDoc.Formatter.HTML.Autolink.all/3>
    Args: []
```

**Comment by josevalim** [comment]
@Shakti213 what is your Elixir version? I cannot reproduce the issue. If you can push a simple application that reproduces it, it would help a lot.

**Comment by josevalim** [comment]
Rather a small project on github that I can clone and reproduce the error.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Shakti213** [comment]
I simply compiled either of the examples with elixirc and ran ex_doc to document it afterwards but I can try to upload a project to reproduce it. 

Or can it be something with my system or setup that causes it?

**Comment by wojtekmach** [comment]
Have you added ex_doc to your project or were you using an archive? Maybe you have archive with old version?

The reason I am asking is we had similar failure that was fixed in 0.18.3.

**Comment by Shakti213** [comment]
I use a package in opensuse but it reports as version 0.18.3 (ex_doc -v). It should be noted that I invoke it manually from cli.

**Comment by josevalim** [comment]
@Shakti213 the best would be for you to `mix new some_project`, add `ex_doc` as a dependency and try to reproduce the issue. Or push a project to github with ad-hoc files and a shell script that reprodues it.

**Comment by Shakti213** [comment]
The following project crashes ex_doc when i run `mix docs`:
https://github.com/Shakti213/elixir-ex_doc-crash

**Comment by josevalim** [comment]
Thanks @Shakti213. Unfortunately I still cannot reproduce the issue. I tried the following combinations:

  * Elixir v1.6.5 and Erlang/OTP 19
  * Elixir v1.6.5 and Erlang/OTP 20
  * Elixir master and Erlang/OTP 19
  * Elixir master and Erlang/OTP 20

Maybe you can configure travis in that repo in a way that it shows the failure?

**Comment by Shakti213** [comment]
Ok, I tried travis and that showed no issues, so I made a complete reinstall of my development environment and that fixed the issue. Sorry for taking up your time :(
