### ISSUE TITLE
@typedoc false not honored

### ISSUE THREAD

**Issue by chevinbrown** [elixir-lang/ex_doc#857]
In a child package of a package I'm developing, `@typedoc false` has been set, but ex_doc is not honoring that value.

I've glanced the source, and haven't been able to grok the issue. 

Context: https://elixirforum.com/t/typedoc-false-is-not-an-acceptable-value/14653

Does this look correct?

**Comment by josevalim** [comment]
Sounds like a bug indeed! Thanks.

**Comment by chevinbrown** [comment]
For sure. I'll take a deeper dive here later, but I'm not competing for a PR. 😸

**Comment by chevinbrown** [comment]
Perhaps here...? https://github.com/elixir-lang/ex_doc/blob/master/lib/ex_doc/retriever.ex#L509

**Comment by arkgil** [comment]
I'm happy to take on this one, if no one has started yet 🙂

**Comment by josevalim** [comment]
Please go ahead!
