### ISSUE TITLE
Add links back to Hex package page and source repository

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/ex_doc#859]

**Comment by voughtdq** [comment]
So, I mentioned this in the thread. Maybe providing "replaceable comments" in the generated docs would allow sites like hexdocs to extend ex_doc without adding complexity to ex_doc itself. 

i.e.
```
<!--EX_DOC_JS_INCLUDES-->
<!--EX_DOC_ADDITIONAL_LINKS-->
```

**Comment by ericmj** [comment]
> So, I mentioned this in the thread. Maybe providing "replaceable comments" in the generated docs would allow sites like hexdocs to extend ex_doc without adding complexity to ex_doc itself.

This is what I had in mind, it means we have to change hexdocs to instead of serving files directly from S3 we need to now have a server that looks for these comments in html files and injects the content. Is a string replace enough or would we need a html parser?

**Comment by michalmuskala** [comment]
@ericmj what about something that replaces that on upload and then serves static files from s3? That wouldn't require changing the serving pipeline, just the upload one.

**Comment by ericmj** [comment]
Replace on upload would only work for static content. If we would like to include a version selector we would have to inject javascript that makes a separate request to fetch the versions, we already make 11 requests on a single page load.

**Comment by michalmuskala** [comment]
When loading https://hexdocs.pm/elixir/Kernel.html I get just 6 things, and 5 of them are cached (the only thing that is not cached are google fonts).

If load speed is a concern, maybe there should be a away for ex_doc to mark the js & css so that HTML headers requiring no validation are set? It seems that should work just fine since they include the content sha in the file name. I believe this should decrease the load time.

**Comment by ericmj** [comment]
Everything should be cached, including the font files should. Maybe they are being served directly from disk?

**Comment by michallepicki** [comment]
I played with this when implementing the versions dropdown ( #970 ). See [this comment](https://github.com/elixir-lang/ex_doc/issues/964#issuecomment-460482152) for links to code and demo.

**Comment by josevalim** [comment]
@michallepicki just a quick follow up: did you start the work discussion on Hex side of things? Are you planning to? Is there anything we can do to help? Thanks! :heart:

**Comment by michallepicki** [comment]
@josevalim There's an old ticket in the hexpm repo: https://github.com/hexpm/hexpm/issues/682 - maybe we should close it and open a new one in the hexdocs repo.

I haven't pushed this any further, sorry about that! I tried reading through the hex and hexdocs source to propose a solution but I couldn't figure it out and I forgot about it.

**Comment by josevalim** [comment]
New issue opened here: https://github.com/hexpm/hexpm/issues/795

**Comment by josevalim** [comment]
@michallepicki I have included a bit more of details on the new issue but I don't know exactly where on the Hex repo the changes should happen. :) I asked for clarifications from a Hex team member. :) If you can find time to contribute, either there or on ExDoc, it will definitely be welcome!

**Comment by michallepicki** [comment]
Is this something we still could do? For linking back to hex, the javascript config file could be leveraged.

The javascript config is already in place and being generated by hexdocs for the versions dropdown. A link back to hex could be added there, and `ex_doc` javascript could render it when a javascript global is present (similar to how the versions dropdown works).

One more thought, a mix package also has a more general `links` config. It is used on hex.pm and often contains current links to Github or maintainer or project or company website. All of those links could be automatically kept in sync for even old docs versions through the javascript config. I looked at that and they seem to be present on hex side in project metadata and could be passed to hexdocs to be saved in the javascript config in a new global next to the versions list.

One concern around exposing those links is not making the sidebar too noisy. A link could have an icon url attribute, and when present, it could be shown under that icon.

**Comment by josevalim** [comment]
One of the things we discussed is to add this to the version drop down as The infrastructure is there
