### ISSUE TITLE
groups_for_extras to allow array to match against

### ISSUE THREAD

**Issue by smorin** [elixir-lang/ex_doc#863]
Feature request: groups_for_extras to allow array to match against

Today this is possible:
```elixir
groups_for_extras: [
  "Introduction": Path.wildcard("guides/introduction/*.md"),
  "Advanced": Path.wildcard("guides/advanced/*.md")
]
```
Extend groups_for_extras: to accept an array
```elixir
groups_for_extras: [
  "Introduction": [Path.wildcard("guides/introduction/*.md"), "README.md"],
  "Advanced": Path.wildcard("guides/advanced/*.md")
]
```

**Comment by josevalim** [comment]
@smorin I would prefer if folks used concatenation then:

    Path.wildcard("guides/introduction/*.md") ++ ["README.md"]

If we allow nested lists, this can be an issue in the future if we choose to support things such as nested groups.

Thanks!

**Comment by smorin** [comment]
@josevalim So what would your suggestion be to support future nested groups and multi-matches for groups?  Does this request have to be closed, or maybe better just update the proposal?

**Comment by smorin** [comment]
@josevalim The problem I am trying to solve is to have a group "Introduction" that will match Path.wildcard("guides/introduction/*.md") ++ ["README.md"] both of these sets of files.  Is there a better way to do that.  I am not for blocking arbitrary nested lists for other use-cases.  

So seems like there can be a way to accommodate both multiple matches and nested/subgroups.

I wasn't thinking of nested groups.  What did you have in mind for that?  What would that look like to you and we can see if we can do both.

**Comment by josevalim** [comment]
I feel like I am missing something then. Why wouldn't `Path.wildcard("guides/introduction/*.md") ++ ["README.md"]` work then?

**Comment by smorin** [comment]
@josevalim sorry, I miss-understood this piece of code and didn't realize Path.wildcard returned a list.  You suggestion works.  This is my mistake, I'll drop this topic.
