### ISSUE TITLE
Clicking parent topic in the sidebar list should redirect automatically to Top page

### ISSUE THREAD

**Issue by halian-vilela** [elixir-lang/ex_doc#866]
Maybe there is a good reason for that not being this way, but I feel that when clicking in `Endpoint` here, it should automatically open the `Top` page instead of just expanding the collapse menu.

I always feel that something went wrong, and then I remember that I need to click in `Top` to go to that section.

Makes sense?

![endpoint_ _phoenix_v1_3_3](https://user-images.githubusercontent.com/1423653/42415415-c287e5ea-8223-11e8-8fe6-53db771850fe.png)

**Comment by wojtekmach** [comment]
This topic has been brought up several times, most recently here: https://github.com/elixir-lang/ex_doc/issues/837. Its unclear whats the best solution, please read previous issues, thanks!
