### ISSUE TITLE
Allow app to be excluded from umbrella app docs

### ISSUE THREAD

**Issue by aaronrenner** [elixir-lang/ex_doc#867]
I've been generating docs for my phoenix-based umbrella apps, but I'd really like my_app_web to be excluded from the docs since it's not part of my app's public API. Ideally, I'd like to be able to whitelist or blacklist applications in an umbrella from the documentation build. This would allow me to only build docs for the apps that I wish for other developers to know about. I know I can generate docs for each project individually, but I do like how all of the docs for an umbrella are compiled into one. Is this possible?

**Comment by josevalim** [comment]
@aaronrenner we can support a configuration on your Mix.Project that allows that, as I believe we don't support this right now. A pull request is welcome!

**Comment by aaronrenner** [comment]
Thanks for being open to adding a config like this! I'll try to find some time to work on a PR.

**Comment by leonardobork** [comment]
I'm actually working on a PR for this.

Thought something like 

In `/lib/ex_doc/retriever.ex`.

```elixir
def docs_from_files(files, config) when is_list(files) do
    files
    |> Enum.filter(&valid_files(&1, config))
    |> Enum.map(&filename_to_module(&1))
    |> docs_from_modules(config)
end

defp valid_files(name, config) do
    name = Path.basename(name, ".beam")
    [project | _] = String.split(name, ".")
    !Enum.member?([config.ignored_apps], project)
end
```
Might do the trick... But I don't know if it is the best way to do it.

Any suggestions?

**Comment by josevalim** [comment]
@leonardobork for umbrellas it should be a matter of filtering the application names here and not adding them to the compilation list in the first place: https://github.com/elixir-lang/ex_doc/blob/master/lib/mix/tasks/docs.ex#L263-L265 :)

**Comment by lackac** [comment]
@josevalim, I think this can be closed now as #871 has been merged. Or is there anything else to be done for this?

**Comment by aaronrenner** [comment]
@lackac Thanks for building this. I'm looking forward to using it!

**Comment by lackac** [comment]
@aaronrenner the work was done by @leonardobork in #871, he deserves the praise. I was just helping with keeping the issue tracker tidy. :)
