### ISSUE TITLE
Highlighter stylesheet improvements

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#872]
Add the following improvements to the highlighter stylesheet:

1. Color the funcion name in `def f(...)` in a different color

2. Highlight escape chars (e.g. `"\'"`)

3. Highlight string interpolation markers (e.g. `#{something}`)

4. Highlight regexes in a different color from normal sigils

### Examples (note: these examples don't use the current stylesheet)

Escape character:

![image](https://user-images.githubusercontent.com/2668874/42708194-6ed4a360-86d4-11e8-8ffe-bc7f6b2491b8.png)

Function Names and String interpolation:

![image](https://user-images.githubusercontent.com/2668874/42708218-8a70d9f4-86d4-11e8-8680-0a2650ee3f3c.png)

**Comment by josevalim** [comment]
Yup, please do send a PR!

**Comment by tmbb** [comment]
## Mockups

Here are the colors I've picked. Please tell me what you think about them:

### 1. Color the funcion name in `def f(...)` in a different color

![def_green_atoms](https://user-images.githubusercontent.com/2668874/42718248-3e9e5c92-86ff-11e8-9733-f73621313d50.png)

![def_green_atoms2](https://user-images.githubusercontent.com/2668874/42718251-40268d64-86ff-11e8-9e27-3eae2f88eb61.png)

![def_green_atoms3](https://user-images.githubusercontent.com/2668874/42718252-47334cfa-86ff-11e8-9890-b464d1f58cf7.png)

![def_green_atoms4](https://user-images.githubusercontent.com/2668874/42718254-49369cfa-86ff-11e8-85f5-4b5d8ce9eb7f.png)

### 2. Highlight escape chars (e.g. `"\'"`)

![escape chars](https://user-images.githubusercontent.com/2668874/42718338-df2da0b4-86ff-11e8-9ad7-e2a09de0e005.png)

![regex_with_escape_chars](https://user-images.githubusercontent.com/2668874/42718300-a74a7064-86ff-11e8-9232-08d94e68f6c9.png)

![regex_with_escape_chars_brown_atoms](https://user-images.githubusercontent.com/2668874/42718304-a99314d4-86ff-11e8-9265-9c83e9390848.png)

![regex_with_escapes_and_interpolation](https://user-images.githubusercontent.com/2668874/42718307-ac2ec1e8-86ff-11e8-9eb2-4466a1860ec9.png)

### 3. Highlight string interpolation markers (e.g. `#{something}`)

![regex_with_escapes_and_interpolation](https://user-images.githubusercontent.com/2668874/42718318-c1b3011e-86ff-11e8-94cb-726580c455f6.png)
![escape chars](https://user-images.githubusercontent.com/2668874/42718327-c9657c8e-86ff-11e8-8318-a15c262a938d.png)
![escape chars](https://user-images.githubusercontent.com/2668874/42718334-d66fba66-86ff-11e8-92dd-ee9f925a6a88.png)


### 4. Highlight regexes in a different color from normal sigils

### 5. Atoms in brown (instead of green like the strings)

@josevalim has said the previous theme was too colorful, but this one is more subdued, and in that case, making atoms have thir own color might be nice:

![def_brown_atoms3](https://user-images.githubusercontent.com/2668874/42718286-843fe194-86ff-11e8-8f52-8f190f5884bd.png)

![regex_with_escapes_and_interpolation_brown_atoms](https://user-images.githubusercontent.com/2668874/42718287-8b7b1172-86ff-11e8-91e5-8e7f5b1352e6.png)

![atom_with_stacktrace](https://user-images.githubusercontent.com/2668874/42718346-eae041dc-86ff-11e8-89ed-42eae4cb5adc.png)

![regex_with_escape_chars_brown_atoms](https://user-images.githubusercontent.com/2668874/42718348-f201a762-86ff-11e8-87c9-180d1718e070.png)

## Bugs

I've found 2 "bugs" in makeup (not seen in the mockups above because they are mockups):

1. Makeup doesn' recognize unicode escape sequences yet (i.e. `"\u0000"`). This is a genuine bug.

2. Makeup tries to highlight escape characters inside a string as if they were a charlist (this behaviour was copied without much thought from the Pygments Elixir lexer). Because we're coloring charlists as if they were strings (green), we eithe make escape characters invisible or we must color charlists in blue instead of green. This is not what we want. This means that I'll have to update makeup_elixir so that it uses a different CSS class for escape characters and charlists.

**Comment by josevalim** [comment]
@tmbb looks good to me. Just one question: can you please make `true`, `nil` and `false` the same color as atoms? They are all atoms too and to me this is the most consistent. Thanks.

**Comment by tmbb** [comment]
> Just one question: can you please make true, nil and false the same color as atoms?

Sure. I'll do it right away.

Highlighting Elixir is not very easy and inherently "subjective"...  The values `true`, `nil` and `false` are just atoms, but in the head of the user they are booleans.

Also, `def` is "just" a function/macro call (depending on whether I override the kernel or not), but it is also the "keyword"  that defines functions...

Or even, is `@doc "hey!"` just setting an attribute or a piece of documentation?

This is a mismatch between the rich syntax and the simple AST (which is awesome, by the way) and in no way a criticism of the language itself.

**Comment by tmbb** [comment]
In any case, overwriting the stylesheet is easy using some config options I added to ex_doc a long time ago. I should add that to the documentation.

Those config options became unused when the extra CSS became included in the ex_doc_makeup markdown module and later when the highlighter CSS became included in the assets generated by gulp.

**Comment by tmbb** [comment]
I'm undecided on the coloring of datetime literals. Should I...

Leave them in black?

![image](https://user-images.githubusercontent.com/2668874/42729061-ddb741ee-87c3-11e8-896c-3ddffe21cfbd.png)

Color them green like normal sigils?

![image](https://user-images.githubusercontent.com/2668874/42729056-c2105462-87c3-11e8-8203-a3480def912c.png)

Color them red like regexes?

![image](https://user-images.githubusercontent.com/2668874/42729045-9522a45a-87c3-11e8-9b19-85146ef3d5fb.png)

**Comment by josevalim** [comment]
I would say red. I even think regexes should remain green, as they are
textual like strings. But I can see the argument for red too.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by tmbb** [comment]
Addressed here: https://github.com/elixir-lang/ex_doc/pull/875

**Comment by tmbb** [comment]
Don't close this yet. I still haven't looked at the night mode stylesheet in enough detail.

**Comment by josevalim** [comment]
We did not perform any changes to the night theme from the default one.

**Comment by josevalim** [comment]
Closing this as the release is coming out soon. :) I am happy with the night mode as is, but if you feel we can improve those, a PR is welcome!
