### ISSUE TITLE
Application docs doesn't autolink to Mix.Tasks.Compile.App

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#874]
<img width="884" alt="screen shot 2018-07-15 at 12 03 38" src="https://user-images.githubusercontent.com/76071/42732761-20f7611a-8827-11e8-812b-14528eb7cc7e.png">

https://hexdocs.pm/elixir/master/Application.html#module-the-application-resource-file

I think it's because Elixir app doesn't depend on Mix app so that's why we can't autolink.

**Comment by wojtekmach** [comment]
I think we already are special casing but seems we're missing a spot or something. In any case, OK to special case this in ex_doc, right?

**Comment by josevalim** [comment]
@wojtekmach yeah. all elixir applications should be especially handled because we always link to stable.

**Comment by wojtekmach** [comment]
OK this only happens when running ex_doc as escript (as mentioned [here](https://github.com/elixir-lang/ex_doc/pull/841/files#diff-4cca810c5bca54191f6de3e9b8edafb0R559)) as Mix etc are not available there.

Currently we generate Elixir docs with this command:

```
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.8.0-dev" "lib/elixir/ebin" (...)
```

if we allow passing a wildcard it should work:

```
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.8.0-dev" "lib/**/ebin" (...)
```

For it to work for other projects that use ex_doc escript we'd need to support multiple paths and wildcards so something like `"_build/dev/lib/myproject/ebin:/path/to/elixir/lib/**/ebin"` but in that case they probably should have used just `mix docs` in the first place, so let's skip that for now.

Thoughts?

**Comment by josevalim** [comment]
This is a bit weird because when running `bin/elixir`, it should still find the mix files. This is not an escript per se, it is just an executable. Although it definitely won't work for escripts since in escripts the elixir itself is inside the escript. Thoughts?
