### ISSUE TITLE
Arbitrary grouping of functions with `@doc group: :some_group`

### ISSUE THREAD

**Issue by lackac** [elixir-lang/ex_doc#876]
The new documentation metadata and specifically the `@doc keyword()` construct opens up new possibilities for enriching the ExDoc UI and providing better ways to navigate and explore.

ExDoc is already making use of the `guard: true` metadata to group guards together in `Kernel` and other modules. It could similarly allow arbitrary grouping of functions:

``` elixir
defmodule Flow do
  @doc group: :mappers
  def each(flow, each)

  @doc group: :mappers
  def filter(flow, filter)

  @doc group: :reducers
  def reduce(flow, acc_fun, reducer_fun)

  @doc group: :reducers
  def group_by(flow, key_fun, value_fun)
end
```

The code above would instruct ExDoc to create two new groups in the sidebar: "Mappers" and "Reducers". The same grouping would also be used on the main content side. The behaviour would be exactly the same as the existing "Callbacks" and "Types" grouping. Optionally we could also introduce a way to toggle grouping.

This is mostly useful for modules that define a high number of functions where separating them conceptually would provide a better experience for the reader. (e.g. documentation of Flow, or some ExAws packages with larger footprints)

Some details of how this would behave still needs to be worked out and can be discussed if this finds support.

**Comment by josevalim** [comment]
I like this, although some people had reservations around groups. /cc @ericmj @benwilson512 @michalmuskala

**Comment by josevalim** [comment]
@lackac btw, it may be better to have a bit of indirection here and allow groups to be created based on the metadata. This means that we would do:

    @doc mapper: true
    @doc reducer: true

Or

    @doc flow_type: :mapper

And then we tell ExDoc how to build this:

```elixir
groups_for_functions: %{
  Mappers: & &1[:flow_type] == :mapper
}
```

Similar approach could be done for `groups_for_modules`. But in the `groups_for_modules` case I like that all information is in a single place (the mix.exs). This is much harder to do for functions.

**Comment by benwilson512** [comment]
I like this idea. A good example would be ExAws.S3 which has a reasonably large surface area, and the main AWS docs categorize the actions into "Actions on Buckets", "Actions on Objects" etc. Being able to reproduce that structure in ExDoc would definitely improve the doc experience.

**Comment by lackac** [comment]
I wouldn't mind working on this, but I might not be able to get to it in the next couple weeks. In other words, don't wait on me if you prefer to have this sooner. :)

**Comment by josevalim** [comment]
No worries, take your time! There is no rush.

**Comment by English3000** [comment]
Just saw this issue, after [posting this](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/elixir-lang-core/TxDvKFwltZU) in the elixir-core group.

**Comment by English3000** [comment]
Also, I'd suggest along with guards, splitting macros off into their own dropdown.

**Comment by josevalim** [comment]
We had macros as their own dropdown and it caused more confusion than helped, as it made searching and finding functionality harder. I think grouping is generally useful but grouping too granularly can make accessibility worse in some cases. Other projects can group macros if they want to, but we don't plan to do so in Elixir.

**Comment by English3000** [comment]
I realize 'macros' is a bit vague. I mean the `def*`s (or, more generically, reserved keywords that are macros). If it doesn't cause a hassle, they could be moved to `Kernel.SpecialForms`

If you still disagree, could you link me to the thread(s) you are referring to?

**Comment by josevalim** [comment]
`def` and friends in Elixir are not keywords. They are just regular macros. They are also not special forms because special forms are special macros implemented by the compiler.
