### ISSUE TITLE
Modules in the sidebar should render without Javascript

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#877]
Currently, modules in the sidebar are rendered by Javascript. In my opinion they should use static HTML when possible.

**Comment by josevalim** [comment]
We use javascript because the sidebar is huge and embedding that on every page would increase the website load. We tried iframes but the experience is not good. Other things like search requires the sidebar metadata anyway, so this is the most efficient way. We currently have no plans to change it.

**Comment by OvermindDL1** [comment]
I also noticed that the menu entries are not accessible in text browsers, although I usually navigate to direct URL with those, at times I would like to navigate internally and that is very hard to do without actual links...

And how it is really that huge?  A simple html5 list of something as massive as Elixir's sidebar would still only add a kb or two, which is trivial compared to the size of the rest of the page.  How is this good user interaction...  >.>

**Comment by josevalim** [comment]
One thing does not imply the other. We mostly likely can improve navigation while keeping the JS sidebar.

**Comment by OvermindDL1** [comment]
In text mode I don't really need the anchor jumps in a page (though that would be useful), but at the very least having the links that jump 'between' pages would be highly useful (and trivial in size as well).  And the supposed 'links' like "Modules" that do nothing in text mode is really irritating and really bad web design...  >.<

**Comment by tmbb** [comment]
I think adding a `<noscript>` tag with a flat list of links to the modules might be a good compromise? I'm not even that invested in this thing, as I normally browse with JS turned on. I only noticed when I tried to implement some kind of workaround for "nested modules" and found out the whole thing was rendered in JS
