### ISSUE TITLE
Error to generate documentation

### ISSUE THREAD

**Issue by joaothallis** [elixir-lang/ex_doc#887]
When execute mix docs in the Ecto:
```elixir
➜  ecto git:(master) ✗ mix docs
** (Mix) The task "docs" could not be found. Did you mean "do"?
```
I noticed that mix.exs is in `only: :docs`, in this context, `:docs` is it a kind of environment? How can I make it work? `mix docs`?

**Comment by milmazz** [comment]
@joaothallis Did you follow the instructions mentioned in [How to use ExDoc with Mix](https://github.com/elixir-lang/ex_doc#using-exdoc-with-mix)? Could you provide us with a link to the project that you're working on?

**Comment by milmazz** [comment]
@joaothallis In that case, have you read the [Building docs](https://github.com/elixir-ecto/ecto#building-docs) section from Ecto? You just need to use `docs` as `MIX_ENV`, something like this: `MIX_ENV=docs mix docs` should work in your case.
