### ISSUE TITLE
Support source_url for relative links in extra files

### ISSUE THREAD

**Issue by jparise** [elixir-lang/ex_doc#889]
The ability to include extra markdown files is very nice for including supplemental guides in the rendered output.

It's sometimes useful for these extra markdown files to include relative links to other files in the source repository. When rendered in the context of the repository, this works well (either on the local file system or via Git{Hub,Lab}'s web interface). When rendered as part of ex_doc's output, this only works if the entire document tree is included as extras, and only if they all exist in a flat structure (with no sub-directory references).

One partial solution is to avoid relative links and instead use absolute, repository-aware links (e.g. `github.com/user/repo/tree/master/document.md`). The downside to this approach is that these links are hard coded to a single ref (e.g. `master`), which may not match the originating document's current branch.

ex_doc solves this problem with `:source_url` for source links, and I think it (or something similar to it) could be useful for this document linking use case.

If an extra markdown file contains a link that **(1)** is relative and **(2)** does not refer to another extra document, we can assume it is meant to refer to another file in the source repository, and ex_doc could then expand it to an absolute URL based on `:source_url`.

This could be controlled via a new keyword (e.g. `:source_url` or `:base_url`) in the existing `extras` list alongside `:filename` and `:title`.

**Comment by josevalim** [comment]
Hi @jparise. Can you please provide a more concrete example? For example, assuming you have two pages and you want to link between them, how would you write those links in markdown and what is the output you would expect from ExDoc?

**Comment by jparise** [comment]
In our [elixir-thrift](https://github.com/pinterest/elixir-thrift) project, we have an [`example/README.md`](https://github.com/pinterest/elixir-thrift/blob/master/example/README.md) file that we're including in our rendered documentation as:

```elixir
"example/README.md": [filename: "example", title: "Example"]
```

Inside of `example/README.md`, we want to link to some source files and directories within the repository:

```markdown
For client usage, you should consult the [test cases][tests] to see how to make requests to a Thrift service.

[tests]: https://github.com/pinterest/elixir-thrift/tree/master/example/test/calculator_test.exs
```

We're currently using an absolute GitHub URL for `[tests]` because it renders correctly in both [the GitHub web interface](https://github.com/pinterest/elixir-thrift/blob/master/example/README.md) and within the ex_doc-generated HTML documentation. The disadvantage is that it must include the hard-coded `tree/master` branch reference.

Ideally, we would define the `[tests]` target as `test/calculator_test.exs`. This works nicely in the GitHub web interface and reflects the relative filesystem path, but it doesn't produce a working link in the ex_doc output because there is no `test/calculator_test.exs` file there.

There are also cases where we might want to link between extra pages, such as between `README.md` and `example/README.md`. That also isn't currently possible with relative link targets because of the `example/` path component.

**Comment by jparise** [comment]
Yes, I agree this would be new (different) linking behavior. I think adding a new keyword to the `extras` list would allow each page to opt-in. Perhaps something like:

```elixir
"example/README.md": [filename: "example", title: "Example", base_url: :source_url]
```

**Comment by josevalim** [comment]
Hi @jparise, unfortunately to go in this direction we would need to process the links, which is something that ExDoc does not do right now and it would add a lot of complexity. We agree with the issue but we can't think of any solutions. Since we didn't have progress on this for a while, we are going to close it to reorganize the house. But if you have other concrete suggestions on how to tackle it we would love to hear. Thanks!
