### ISSUE TITLE
Can't build Makeup package with Elixir 1.7 because only ExDoc 0.19 supports Elixir 1.7 and ExDoc 0.19 deppends on MakeupElixir which depend on Makeup...

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#894]
Is there any way around this other than publishing with Elixir 1.6 or using some kind of escript instead of depending on ExDoc?

**Comment by josevalim** [comment]
@tmbb copy what we are doing in nimble_parsec. It is the simplest approach IMO: https://github.com/plataformatec/nimble_parsec/blob/master/mix.exs#L36
