### ISSUE TITLE
Exclude Prefix

### ISSUE THREAD

**Issue by zapient** [elixir-lang/ex_doc#897]
It would be nice to be able to exclude certain modules that are added via a nested `use` macro.

[Guardian](https://github.com/ueberauth/guardian/blob/master/lib/guardian.ex#L337) for example:

```
module Foo do
  @moduledoc false
  use Guardian, otp_app: :my_application
end
```

`@moduledoc false` will prevent `Foo.Guardian` from showing up in the documentation but not the nested `Foo.Guardian.Plug` module.

# Proposal
Add in an `exclude_prefix` option

**Comment by josevalim** [comment]
You need to ask that as a feature to Guardian. Something like `use Guardian, otp_app: :my_application, moduledoc: false`. :) Thanks!

**Comment by zapient** [comment]
Then all packages that have nested `use` macros would need to implement that sort of functionality. It would be nice to have this configurable at a higher level. 

Phoenix: https://github.com/phoenixframework/phoenix/issues/2580

**Comment by josevalim** [comment]
Yes, I understand. But I generally dislike the programming pattern where we are undoing work that should not have been done in the first place. So I would prefer to tackle this at the source, even if it means asking a couple different packages to provide this feature.
