### ISSUE TITLE
Allow disabling of `api_reference`

### ISSUE THREAD

**Issue by skwerlman** [elixir-lang/ex_doc#898]
I'm generating different subsets of my docs depending on the Mix.env; in dev i'm generating docs for all modules, while in prod i only want to generate docs for a set of guides i've written.

This means that all applications are ignored, so I wind up with an empty `api-reference.html` linked from all my pages, and there seems to be no way to remove it.

Ideally, I'd like a config option like `api_ref: false` or similar that i could specify in `mix.exs` to prevent that page from being generated. Alternatively, if the page were not generated if it would be empty, that would also solve my issue.

**Comment by josevalim** [comment]
Yes, please do send a PR.

**Comment by skwerlman** [comment]
How do we want to handle cases like `not_found_template.eex` when `api-reference` is disabled? just remove the text referencing it? or do we want to link somewhere else?

**Comment by josevalim** [comment]
Closing in favor of #899.
