### ISSUE TITLE
Help making my first contribution

### ISSUE THREAD

**Issue by English3000** [elixir-lang/ex_doc#903]
Currently, `:ex_doc` organizes functions using the navigation hierarchy:

> Module > Alphabet

I [proposed](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-core/TxDvKFwltZU/wXf_T2_PBwAJ) adding functionality for:

> Category > Module > Alphabet

For starters, I looked at a [similar pull request](https://github.com/elixir-lang/ex_doc/pull/879) by @lackac 

Taking a closer look, it appears I could add `@doc category: :data` in a file,

```elixir
# mix.exs, project/0
docs: [
  groups_for_functions: [
    Data: & &1[:category] == :data
  ]
]
```

and this would generate a `+ Data` dropdown tab (once the next release of `:ex_doc` comes out), creating the nav hierarchy:

> Module > Category > Alphabet

In all honesty, there's a lot going on in `retriever.ex`, where I believe the "action" happens--setting up structs which are used to render the UI--and I'm having a hard time understanding.

If there's the bandwidth, it would be helpful to get a high-level overview (or guidance on how I'd add control over the navigation hierarchy to the codebase). In addition, this would reduce the barrier for others in making a contribution.

**Comment by josevalim** [comment]
Hi @English3000!

The ExDoc team is quite time constrained. When we have extra time, our priority is to focus on fixing existing issues. You may have better luck getting help with more specific questions somewhere like the ElixirForum.

Regarding the feature, note that the `groups_for_modules` already allows you to specify groups -> modules -> alphabet, so make sure to expand what is the difference in the feature you are requesting with the one you have right now, with its benefits.

Also, keep in mind there is no guarantee a contribution will be accepted, especially if it will make the retriever much more complex (as you already noted it is complex today).

Thanks!

**Comment by English3000** [comment]
[image: image.png]

English3000.org: *A data-driven approach to language learning.*

**Comment by English3000** [comment]
![image](https://user-images.githubusercontent.com/29601050/46077900-518f8880-c147-11e8-9e25-3e6121f5440c.png)
