### ISSUE TITLE
Rewrite Autolink suite to go exclusively through project_doc

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/ex_doc#904]
See discussion here: https://github.com/elixir-lang/ex_doc/pull/896#issuecomment-427563081

**Comment by eksperimental** [comment]
I will tackle this. Thank you

**Comment by eksperimental** [comment]
So what is next? Should we remove the {elixir, erlang}_{function, module}, and locals?

**Comment by josevalim** [comment]
@eksperimental I have already removed the other functions and I pushed. :)

**Comment by josevalim** [comment]
I don't think so! <3

>
