### ISSUE TITLE
Custom links to modules

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#909]
Ref: https://github.com/elixir-lang/ex_doc/issues/679#issuecomment-385320830

```elixir
     assert project_doc("[`Registry docs`](`Registry`)", %{docs_refs: []}) ==
       "[`Registry docs`](https://hexdocs.pm/elixir/Registry.html)"
```

```
     Assertion with == failed
     code:  assert project_doc("[`Registry docs`](`Registry`)", %{docs_refs: []}) == "[`Registry docs`](https://hexdocs.pm/elixir/Registry.html)"
     left:  "[[`Registry`](https://hexdocs.pm/elixir/Registry.html)](https://hexdocs.pm/elixir/Registry.html)"
     right: "[`Registry docs`](https://hexdocs.pm/elixir/Registry.html)"
     stacktrace:
       test/ex_doc/formatter/html/autolink_test.exs:262: (test)
```

**Comment by fertapric** [comment]
This kind of syntax doesn't work well with command line tools like IEx. This is how the given example would appear in IEx:

![screen shot 2018-10-25 at 08 50 13](https://user-images.githubusercontent.com/651203/47481281-5ffabe00-d833-11e8-95ae-fd90c4d23679.png)

And this is how it would appeared if we do not support this syntax:

![screen shot 2018-10-25 at 08 53 44](https://user-images.githubusercontent.com/651203/47481320-7ef95000-d833-11e8-9a16-e1ddf48c8344.png)

I would favor readability of the documentation in all formats 🙂

**Comment by fertapric** [comment]
As a side note, I would have written it as:

```
`Registry` docs
the documentation for `Registry`
```

which is auto-linked by ExDoc and rendered in IEx as:

```
Registry (https://hexdocs.pm/elixir/Registry.html) docs
the documentation for Registry (https://hexdocs.pm/elixir/Registry.html)
```

**Comment by wojtekmach** [comment]
not sure, I thought that IEx doesn't know about hexdocs.pm and can't generate these links.

But I think you're right, we probably don't need custom links for modules we should just write, I thought it could be an intermediate step to https://github.com/elixir-lang/ex_doc/issues/910 which I think would be nice.

**Comment by fertapric** [comment]
@wojtekmach You are right. I edited my previous comment :)

**Comment by eksperimental** [comment]
> This kind of syntax doesn't work well with command line tools like IEx. This is how the given example would appear in IEx:
> 
> ![screen shot 2018-10-25 at 08 50 13](https://user-images.githubusercontent.com/651203/47481281-5ffabe00-d833-11e8-95ae-fd90c4d23679.png)
> 
> And this is how it would appear if we do not support this syntax:
> 
> ![screen shot 2018-10-25 at 08 53 44](https://user-images.githubusercontent.com/651203/47481320-7ef95000-d833-11e8-9a16-e1ddf48c8344.png)
> 
> I would favor readability of the documentation in all formats

I have mixed feelings about this. While in theory, you will be able to see the URL in IEx, in practice you will still see the Module name, because people will not rememeber that you can use Custom links for everything but for  Mix tasks and modules names.
If that's the case we should drop custom links all together.

As I am working in another PR, I wanted to write:

```elixir
Some tasks are automatically reenabled such as: [`cmd`](`mix cmd`),
  [`do`](`mix do`), [`loadconfig`](`mix loadconfig`),...
```
But I realize Mix tasks does not support custom links, so what should I do here? use the URL?
