### ISSUE TITLE
Autolink mix tasks

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#910]
When https://github.com/elixir-lang/ex_doc/issues/909 is done we'd do:

```markdown
Run [`mix test`](`Mix.Tasks.Test`).
```

however we could create the same link with just writing:

```markdown
Run `mix test`.
```

Thoughts?

**Comment by fertapric** [comment]
I like the idea 👍

**Comment by wojtekmach** [comment]
Closing in favour of PR.
