### ISSUE TITLE
Text in Search box is hard to read

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#920]
Chrome

when no text is entered, the color is fine:
![hard_to_read_chrome](https://user-images.githubusercontent.com/9133420/48307731-b41cd680-e585-11e8-9234-be3bd3c0772f.png)

but when you enter text, It used be be whitish, but not any more
![hard_to_read](https://user-images.githubusercontent.com/9133420/48307685-ac106700-e584-11e8-9580-5948ca7fbef4.png)

**Comment by eksperimental** [comment]
Firefox is even worse.
See that in Chrome the SEARCH text is white, but in Firefox is a light grey the text SEARCH and what you type in, and the grey color is different than in Chrome 

![hard_to_read_ff1](https://user-images.githubusercontent.com/9133420/48307725-75871c00-e585-11e8-9008-05250a7f31cd.png)
![hard_to_read_ff2](https://user-images.githubusercontent.com/9133420/48307723-6d2ee100-e585-11e8-929d-a1a95d013836.png)

**Comment by josevalim** [comment]
Fixed. It seems it was an update in the bootstrap version which made it no longer inherit the style.

**Comment by wojtekmach** [comment]
@eksperimental you can use `mix build`, it's a custom alias useful that builds assets, recompiles ExDoc etc, useful for testing if everything works correctly.

**Comment by eksperimental** [comment]
@wojtekmach Isn't it supposed to be unnecessary, since @josevalim ran it before submitting his PR? Why wouldI have to rebuild the assets if not changes were made?

**Comment by wojtekmach** [comment]
@eksperimental AFAIR we need to recompile ex_doc after asset changes as we don't keep track (with `@external_resource` etc), I think I looked at it at some point and it seemed tricky.
