### ISSUE TITLE
Increase bottom margin in sidebar (in Firefox)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#921]
This only happens in Firefox
when you scroll to the very bottom of the sidebar,  there is no bottom-margin, and it looks ugly.

![sidebar_bottom_ff](https://user-images.githubusercontent.com/9133420/48307761-9603a600-e586-11e8-8220-af292623b8dc.png)

and in Chrome it looks just fine
![sidebar_bottom_chrome](https://user-images.githubusercontent.com/9133420/48307760-9603a600-e586-11e8-86d2-270f90cfa996.png)

**Comment by josevalim** [comment]
Fixed on 0d42f7559bcdefefdd0ed262dfe68a6607d17f65.

**Comment by eksperimental** [comment]
Thank you
