### ISSUE TITLE
Restructure HTML 

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#923]
Originally posted here: https://github.com/elixir-lang/ex_doc/issues/730#issuecomment-433669048

I have noticed a big semantical mistake in the HTML structure,
the name of the function should be a HEADER element, `<h2>` to be precise.
As of now, It is just a span, and then if there is a section inside this functions, this receives `<h2>`.
We should use `<h2>` for the function name, and them push up +1 all the headers within the function.

**Comment by josevalim** [comment]
I wouldn't like to change the user markdown. Why can't we make it a h1? :)

**Comment by eksperimental** [comment]
Because there should be Only one H1 per page, or at least per <section>

**Comment by josevalim** [comment]
I think we wrap each function in a section or article, no? If not, we
should.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#Defining_sections it's fine to have multiple `<h1>` as long as they're in nested sections so if we put it content inside `<section>` we should be good.

**Comment by eksperimental** [comment]
Sorry my previous message was cut off. It meant to say "per page or oer section".
Thank you Wojtek
