### ISSUE TITLE
Reloading a page with a hash link doesn't take you to the ID, (only in Chrome)

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#925]
Kernel.html#to_string/1

let's say you open that page, it does take you to the to_string/1 functions, but if you hit reload, it doesn't.
It does work as expected in Firefox, but it doesn't in Chrome

**Comment by josevalim** [comment]
As a long time Chrome user, this is unfotunately a Chrome behaviour. Just as two examples, it also happens [here](https://elixir-lang.org/install.html) and [here](https://cyphon.readthedocs.io/en/latest/modules/distilleries.models.html#distilleries.models.Distillery.get_date).
