### ISSUE TITLE
Quotes are sometimes rendered incorrectly

### ISSUE THREAD

**Issue by axelson** [elixir-lang/ex_doc#928]
In the Phoenix 1.4.0 documentation we have the following [snippet](https://github.com/phoenixframework/phoenix/blob/v1.4.0/lib/phoenix/socket.ex#L294):

`for example "room:*", "users:*", "system"`

Which is rendered in [html](https://hexdocs.pm/phoenix/Phoenix.Socket.html#channel/3) as `“room:<em>“, “users:</em>”, “system”`

Note that the second smart quote is "incorrect", which is possibly because the `<em>` tag was inserted between them, although I would expect that the quote after `users:` would have the same issue (abut maybe this is just a browser rendered oddity).

After looking at the generated code I'm not sure that this is necessarily an ex_doc issue since the documentation should either be escaping the `\*` or enclosing them in backticks. I will file a PR on Phoenix to fix the generated docs.

Also in my opinion, it would be better for ex_doc not to automatically convert double quote characters to smart quotes (but that's probably a different discussion)

Edit: Phoenix PR filed: https://github.com/phoenixframework/phoenix/pull/3191

**Comment by josevalim** [comment]
@axelson that's down to the markdown renderer. It is probably a configuration in earmark. Maybe we can just disable it.

**Comment by axelson** [comment]
@josevalim It looks like the configuration option in earmark is `smartypants` which is on by default and it `Turns on smartypants processing, so quotes become curly, two or three hyphens become en and em dashes, and so on. True by default.`

Ideally for ex_doc I think it would make sense to disable the smart quotes only (and I think that makes sense as an option for earmark) so I've raised an issue: https://github.com/pragdave/earmark/issues/210

But possibly it makes sense to disable `smartypants` by default for ex_doc.

**Comment by josevalim** [comment]
I agree. Let’s disable it and we can bring it back as an option if some
folks want it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
