### ISSUE TITLE
Function instead of variaable

### ISSUE THREAD

**Issue by RaymondLoranger** [elixir-lang/ex_doc#931]
The following spec:

```
@spec start_link({game_name :: String.t(), pos_integer} | game :: Game.t()) ::
          GenServer.on_start()
  def start_link(tuple_or_game)

  def start_link({game_name, size}),
    do: GenServer.start_link(Server, {game_name, size}, name: via(game_name))

  def start_link(game),
    do: GenServer.start_link(Server, game, name: via(game.name))
```

generates:

```
start_link(tuple_or_game)
start_link(
  {game_name :: String.t(), pos_integer()} | game() :: Buzzword.Bingo.Game.t()
) :: GenServer.on_start()
```

Why am I getting game() instead of game?

**Comment by wojtekmach** [comment]
this spec declaration is invalid and warns on Elixir master:

```
warning: invalid type annotation. When using the | operator to represent the union of types, make sure to wrap type annotations in parentheses: {game_name :: String.t(), pos_integer} | game :: Game.t()
```

I believe we can't assign a variable immediately at the right side of `|`.

This should work:

```elixir
@spec start_link(game :: {game_name :: String.t(), pos_integer} | Game.t()) ::
        GenServer.on_start()
```

or more succinctly:

```elixir
@spec start_link({game_name :: String.t(), pos_integer} | Game.t()) ::
        GenServer.on_start()
```

**Comment by RaymondLoranger** [comment]
Hi Wojtek,

 

Thanks! Parens did it.

start_link(tuple_or_game)

start_link(

  {game_name ::  <https://hexdocs.pm/elixir/String.html#t:t/0> String.t(), size ::  <https://hexdocs.pm/elixir/typespecs.html#basic-types> pos_integer()}

  | (game ::  <https://hexdocs.pm/buzzword_bingo_game/0.1.0/Buzzword.Bingo.Game.html#t:t/0> Buzzword.Bingo.Game.t())

) ::  <https://hexdocs.pm/elixir/GenServer.html#t:on_start/0> GenServer.on_start()

Spawns a new game server process to be registered under game_name or restarts a game server process to be registered under game.name.
