### ISSUE TITLE
Release new version depending on makeup 0.6.0

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/ex_doc#939]
so that people wont download a version of makeup that will pull a wrong version of nimble_parsec.

**Comment by wojtekmach** [comment]
Hey @tmbb, we're gonna need some more time to get new release out as there are some features in progress.

Could you release makeup v0.5.6 (which is gonna be exactly the same as v0.6.0)? This way, for latest stable ex_doc that makeup version will be picked up and everything should be fine.

**Comment by wojtekmach** [comment]
ExDoc depends on [makeup_elixir](https://hex.pm/packages/makeup_elixir) which has `makeup ~> 0.5.5`, so if you ship `makeup_elixir` that depends on `~> 0.6.0` I think that would work too.

**Comment by wojtekmach** [comment]
I see makeup v0.5.6 is out and I can confirm everything is working on a new project. Thanks for a quick turnaround @tmbb!
