### ISSUE TITLE
Support more language syntax highlight

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/ex_doc#941]
Currently ExDoc explicitly lists languages to use for highlightjs - [src](https://github.com/elixir-lang/ex_doc/blob/c393cae07a35d891177be0b5f47ed31bf67c2213/assets/js/app.js#L46)

Can we turn on all languages? If makeup_elixir processes the content first, then we may not see conflicts.

I'm writing "extra" page with Ruby to help out Ruby dev.. so at least I need to add "ruby" there :)

I tried to turn on "autoload" of highlightjs, but failed to do that.

**Comment by josevalim** [comment]
The reason why we don't support all is because that would increase the .js size. We should provide a way to make this extensible though.

**Comment by chulkilee** [comment]
If it's (relatively) straightforward to convert highlightjs rules to makeup rules, then I think that would be better in long term.. however I'm not sure that's "easy". Also I guess the current dependency does not allow to add additional `makeup_*` and auto-discover by earmark or makeup.

Or we may add config to `ex_doc`, to list languages to use from highlightjs, and let `ex_doc` include those files from HTML separately. That means all pages now include individual files, not one bundle - but this won't be a problem by HTTP cache and HTTP2.

**Comment by tmbb** [comment]
Makeup will get auto discover for custom lexers relatively soon.

**Comment by josevalim** [comment]
To clarify, the way to add new languages is to contribute to makeup. :+1:
