### ISSUE TITLE
Missing specs for protocol functions

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#942]
<img width="857" alt="screenshot 2018-12-18 at 11 58 38" src="https://user-images.githubusercontent.com/76071/50149745-4ff3dd80-02bc-11e9-93f3-9470729efe5c.png">

(https://hexdocs.pm/elixir/Enumerable.html#functions)

```elixir
  @spec count(t) :: {:ok, non_neg_integer} | {:error, module}
  def count(enumerable)
```

(https://github.com/elixir-lang/elixir/blob/v1.7.4/lib/elixir/lib/enum.ex#L152:L153)

**Comment by wojtekmach** [comment]
Actually, it looks like a missing feature in Elixir:

```
iex(14)> b Enumerable.slice
@callback slice(t()) ::
            {:ok, size :: non_neg_integer(), slicing_fun()} | {:error, module()}

# no docs
```

```elixir
iex> h Enumerable.slice

                             def slice(enumerable)

Returns a function that slices the data structure contiguously.

# no specs
```

cc @josevalim

**Comment by josevalim** [comment]
It seems we may not define the specs at all in this case? Should we define
both then?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
This is an issue in Elixir. @wojtekmach will send a PR.
