### ISSUE TITLE
Searching for an automatically defined function with default arguments should show up in search results

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#946]
Originally posted in #937

This issue https://github.com/elixir-lang/elixir-lang.github.com/pull/1195 has showed me that we need to improve ExDocs.

Taking the example of `GenServer.call/3` which automatically defines `GenServer.call/2.
If I search "call/2", it should appear `GenServer.call/3` as a search result.

**Comment by josevalim** [comment]
We are getting a whole new search that is full text based, so this is no longer relevant.
