### ISSUE TITLE
Autolink function call examples

### ISSUE THREAD

**Issue by jparise** [elixir-lang/ex_doc#947]
We have good autolinking support for "formal" function references, such as `integer/2`. It would also be nice to autolink "example" function calls, such as `integer(min: 1)`.

Here's a good example [from the NimbleParsec docs](https://hexdocs.pm/nimble_parsec/NimbleParsec.html#optional/2):

```elixir
  @doc """
  Marks the given combinator as `optional`.

  It is equivalent to `choice([optional, empty()])`.
  """
  @spec optional(t, t) :: t
```

The proposal is that `choice([optional, empty()])` would be rendered as a link to the `choice/2` documentation.

**Comment by josevalim** [comment]
This is really hard to do as it would require us to try to parse all of the
code and then try to see if it is a function call. In this case, the better
is to expand the docs a bit more and also add a reference to the function
directly.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
I contemplated this possibility when we were adding the autolinking function for Mix tasks, but I after some evaluation I considered it could generate a lot of noise and distraction linking every time we mention a function call.

**Comment by josevalim** [comment]
Closing for the reasons above. :)

**Comment by eksperimental** [comment]
Thank you for the suggestion @jparise 
You can always use a custom link
