### ISSUE TITLE
Make themes extensible

### ISSUE THREAD

**Issue by Serkan-devel** [elixir-lang/ex_doc#948]
According to [this issue](https://github.com/hexpm/hexpm/issues/765), one needs to modify the `ex_doc`-package itself to change the theme.

However, other documentation-sites, like sphinx or jekyll do have external theming support.

Maybe there could be something like an endpoint for a custom theme on the `mix.exs`-file. Something like this:

```elixir
  def project do
    [
      ...
      docs: [
        logo: "priv/static/static/logo.png",
        extras: ["README.md", "docs/config.md", "docs/intro.md"],
        main: "readme",
        output: "priv/static/doc"
        theme: "solarized-dark"
      ]
     ...
    ]
  end
...


  defp deps do
    [
     ...
      {:ex_doc, "~> 0.19", only: :dev, runtime: false},
      {:ex_solarized_doc, "~> 0.1"}
     ...
    ]
  end
```

**Comment by josevalim** [comment]
Hi @Serkan-devel. We currently have no plans for themes support. If someone is interesting in working on this and submitting a proposal, then we would love to hear, but it is not something the ExDoc team per-se has in mind. Thanks!
