### ISSUE TITLE
Linking to non available functions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#951]
The Compatibility and Deprecations page of v1.8.0-rc0 mentins that ~`Kernel.ParallelCompiler.files/2`~ `Kernel.ParallelRequire.files/2` is being hard-deprecated, still a link is generated.
the module `Kernel.ParallelCompiler` is marked as `@moduledoc false`,
neither themodule nor the functions are included in the compiled argument that we pass to autolink.
So beats me where this is coming from, posting this before I forget about it.

**Comment by josevalim** [comment]
The parallel compiler does not have `@moduledoc false`.

**Comment by eksperimental** [comment]
Sorry I meant ParallelRequire

**Comment by josevalim** [comment]
Ah, I see. Did we stop linking to functions in other modules are doc false?
I think we only do it for local functions, it is really hard to do
otherwise.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment]
I think I found and fixed the bug. I will polish a bit more the code and upload a PR

**Comment by michallepicki** [comment]
In [Phoenix Guides](https://hexdocs.pm/phoenix/1.4.0/contexts.html#thinking-about-design) I found a broken link to `Logger.Config`, which is marked with `@moduledoc false`. Is this the same bug or should I open a new issue?

**Comment by josevalim** [comment]
Ping @eksperimental :)

**Comment by eksperimental** [comment]
I already have the fix for this. Its kind of a bit of an overhaul, which also brought up other improvements. It will involve some discussion but I'm having some connectivity problems so it will have to wait for a bit

**Comment by eksperimental** [comment]
Here's the WIP commits.
https://github.com/eksperimental/ex_doc/commits/dont_link_to_moduledoc_false
I prefer to upload it so you can have a look and give me your feedback.

The issue here is that we are storing all functions with `@doc` but we are not storing the ones with `@doc false` so ExDoc cannot know whether a function doesn't exist, or it does exist and `@doc` is `false`.

My solution is instead of retuning a map, is to returns a tuple with two maps, but that involves refactoring everything that deals with it.

I was still working on how to deal when linking to erlang modules....

but that's the WIP branch so you can have a look

**Comment by eksperimental** [comment]
> In [Phoenix Guides](https://hexdocs.pm/phoenix/1.4.0/contexts.html#thinking-about-design) I found a broken link to `Logger.Config`, which is marked with `@moduledoc false`. Is this the same bug or should I open a new issue?

@michallepicki it is the same issue

**Comment by josevalim** [comment]
So apparently we already warn for unavailable functions within the same project. We could warn for external functions but that would be too expensive, as it would require us to load bytecode, process it and extract the docs for every external link. So I am thinking the approach we have today is probably the optimal one.

**Comment by eksperimental** [comment]
I think we warn for unavailable functions with known modules (modules that have docs or functions with docs), but not the ones with @moduledoc false

**Comment by eksperimental** [comment]
If we are not to link to external apps, I think it would be ideal at least to take into consideration OTP and Elixir, the question here is that this will change from version to version. So I don't know if there is a right way to do this

**Comment by josevalim** [comment]
We can do it for Elixir, but not for OTP (for now), and it should be fairly stable. We will still have the issue thought it can be very expensive. So I don't know...

**Comment by michallepicki** [comment]
We can try linking to docs for a specific version for dependencies? I don't know if it's a good idea though, it means dependencies need to be fetched to read the version from their mix.exs, guessing 1.3.0 for ~> 1.3 could be wrong

**Comment by eksperimental** [comment]
Michal thats a good idea, it will also help spot mentions to functions that are not supported by.the minum supported version. The question is, if we are compiling the docs with v1.8 and minimum supported version is 1.5, how does ExDoc know what are the available functions for v1.5.
Should we cover 100 of the functions with the @since attribitute? Export a manifest with all publicly available functions and types for every elixir

**Comment by josevalim** [comment]
We always check against the version you are running against so we could use `since`... but it doesn't solve the issue that we will have to load the byte code, parse it, and decode the docs.

**Comment by eksperimental** [comment]
Regardless bytecode loading, are we doing it for Elixir?

**Comment by josevalim** [comment]
Unsure.

**Comment by eksperimental** [comment]
I will submit a PR that only keeps track of the current project. So we van move this forward

**Comment by eksperimental** [comment]
Alternatively we could add and option which will be false by default --deep-scan that will allow the scanning of deps, elixir and otp.
Me, as a developer, I'm more interested in my documentation being correct than in building it fast

**Comment by josevalim** [comment]
An option sounds good, IMO. It is also a good way for us to give the feature a try without  making everything slow  out of the box.

**Comment by wojtekmach** [comment]
This is handled in #1132.
