### ISSUE TITLE
Search results should indicated if a function is deprecated 

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#952]
It should be next to it, in italics and parenthesis IMO

**Comment by josevalim** [comment]
@eksperimental in my opinion it should look exactly like it does here:

![image](https://user-images.githubusercontent.com/9582/50562481-78e08d80-0d14-11e9-8a0f-7f6d7bd31a52.png)

**Comment by josevalim** [comment]
We are getting a whole new search that is full text based. We can revisit this once it is up.
