### ISSUE TITLE
Menu behaviour is inconsistent when opening module with and without content

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#953]
The behaviour of the menu is inconsistent. When a module has no content, it doesnt open the menu and takes your to the page.
This is undesired, as the user has no idea whether this item is empty or not, and may not want to load another page.
It should behave consistently regardless of whether it has content or not.

**Comment by josevalim** [comment]
This is actually a feature: #855

Honestly, I can see an argument for both sides so I don't think we should just revert it because we will have then the opposite issue being opened. It is clear we have a usability issue here, so I believe we should just go ahead and implement #895.

**Comment by josevalim** [comment]
This has been reverted as we now provide a feature similar to the one requested in #895.

**Comment by josevalim** [comment]
Here is a live page http://hexdocs.pm/ex_doc with the latest changes.

**Comment by eksperimental** [comment]
@josevalim I like the feature a lot, but I would like to discuss something about it and I see no PR and no issue, could you please point me where to go to discuss, or create a new issue. Thank you.
