### ISSUE TITLE
Built-int and basic types are not returned in search results

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#954]
Searching for "charlist" doesn't return the built-in charlist/0 type
"charlist/0" doesn't return anything

**Comment by josevalim** [comment]
Yes, all of the built-in types are unfortunately "hidden". There are not listed in any API and we don't have full text search. I don't think it is a bug in ExDoc. We would have to find a way to make this information available in Elixir itself but I don't know how. Somebody would need to write a proposal (or get full text search).

**Comment by wojtekmach** [comment]
This is far from proposal, but I think we can make this work by defining types on the Kernel module.

https://github.com/wojtekmach/elixir/commit/cd235eb6ec2f7ac3cd7219426091ee8568feb1f1

```
iex> t keyword
@type keyword(t) :: [{atom(), t}]

@type keyword() :: [{atom(), any()}]

iex> t atom
@type atom() :: atom()
```

```
iex> t literal
@type literal() :: literal()

    type ::                               ## Atoms
          :atom                           # atoms: :foo, :bar, ...
          | true | false | nil            # special atom literals

                                          ## Bitstrings
          | <<>>                          # empty bitstring
          | <<_::size>>                   # size is 0 or a positive integer
          | <<_::_*unit>>                 # unit is an integer from 1 to 256
          | <<_::size, _::_*unit>>

                                          ## (Anonymous) Functions
          | (-> type)                     # 0-arity, returns type
          | (type1, type2 -> type)        # 2-arity, returns type
          | (... -> type)                 # any arity, returns type

                                          ## Integers
          | 1                             # integer
          | 1..10                         # integer from 1 to 10

                                          ## Lists
          | [type]                        # list with any number of type elements
          | []                            # empty list
          | [...]                         # shorthand for nonempty_list(any())
          | [type, ...]                   # shorthand for nonempty_list(type)
          | [key: value_type]             # keyword list with key :key of value_type

                                                  ## Maps
          | %{}                                   # empty map
          | %{key: value_type}                    # map with required key :key of value_type
          | %{required(key_type) => value_type}   # map with required pairs of key_type and value_type
          | %{optional(key_type) => value_type}   # map with optional pairs of key_type and value_type
          | %SomeStruct{}                         # struct with all fields of any type
          | %SomeStruct{key: value_type}          # struct with required key :key of value_type

                                          ## Tuples
          | {}                            # empty tuple
          | {:ok, type}                   # two-element tuple with an atom and any type
```

![screenshot 2018-12-31 at 16 48 11](https://user-images.githubusercontent.com/76071/50563310-14293100-0d1c-11e9-9579-37d66aaf0de3.png)

![screenshot 2018-12-31 at 16 53 38](https://user-images.githubusercontent.com/76071/50563402-be08bd80-0d1c-11e9-9db5-bb26cfa32211.png)

As you can see, IEx, ExDoc etc work pretty much out of the box. 

Note I defined `@type atom :: atom` is such so it compiles, perhaps it could be special cased in Kernel to allow just `@type atom`. The `literal` type is to allow docs for literals, not sure if there's a nicer way to do that. It would need to be special cased not to export it, but still show up in docs.

In any case, I remember I looked into this stuff this/last year and it keeps bugging me, so I'll work on a proposal next year ;-) Have a good one!

**Comment by josevalim** [comment]
Yeah. The thing though is that defining those types may not be the best
idea because the users are not directly using them. In this sense, defining
them over special forms or a separate module only for documentation
purposes would be better. Unsure.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
Yeah, I was also thinking about putting it on special forms module. Separate module just for docs sounds fine too, we could basically move all content from type specs page there I think.

What we could also do is define just _one_ special type and document basic, built-in, literal, remote etc types there, the type definition content we have on type specs page. This type could be defined on either Kernel, Kernel.SpecialForms, or separate module. Something like:

```elixir
@typedoc """
Lorem ipsum

## Basic types

type ::
      any()                     # the top type, the set of all terms
      | none()                  # the bottom type, contains no terms
      # ...
      | Literals                # Described in section "Literals"
      | Builtin                 # Described in section "Built-in types"
      | Remotes                 # Described in section "Remote types"
      | UserDefined             # Described in section "User-defined types"

## Literals

...

The `__type__` type is not meant to be used, it's just defined for documentation purposes.
"""
@type __type__
```

What's nice about using underscores is it says it's special so folks will hopefully be less likely to use it. Having underscores also puts it as the first type in the list :)

**Comment by eksperimental** [comment]
Thank you @wojtekmach for looking into this.
I think this is an important issue (the lack of being able to link to the basic types) and it should either have an issue open here, or in Elixir core. But having it only in a closed issue won't help, maybe other people have anything to offer.

**Comment by wojtekmach** [comment]
@eksperimental I tend to agree that if the conversation happens in a closed issue it has limited visibility to others. At the same time, given its a multi-faceted topic the proper next step seems to be, as José mentioned, writing a proposal. I dont think it’d be fair of me to open an issue and expect others to do the leg work. (Maybe it wasnt fair to throw half-assed ideas here either!)

As I have been investigating it, a few questions popped up:

is defining a „bare” `@type atom()` the best way to go? If its defined in Kernel, will it mess up with tools like Dialyzer for Kernel function specs? If its defined somewhere else (Kernel.SpecialForms, other dedicated module) will it be sufficently discoverable? Whats the inpact on supporting „bare” types by tools like ExDoc? If we ever make `Code.Typespec.fetch_specs` public, should it be built-in types aware? If so, how should they be represented? As „bare”? As `@type atom :: atom`?

These are just some of the questions that I have encountered that I havent time to try answering yet. I do want to eventually answer them though and do send the proposal. In the meantime, if you’d like to push it forward yourself, by all means. :)
