### ISSUE TITLE
Unify spacing and colors between elixir and other code blocks

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/ex_doc#958]
Elixir code blocks (` ```elixir `) have `.3em .5em !important` padding while javascript, console, html and others have `.5em 1em` padding. I think bigger padding looks better.

Also, I think elixir "black" should be the same as javascript (and others') dark grey.

Example screenshot (elixir on top, javascript on bottom):
![image](https://user-images.githubusercontent.com/4972756/50698556-80ba6d80-1045-11e9-819a-e0a0fcb3716e.png)

**Comment by josevalim** [comment]
Good catch. PR please? :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
