### ISSUE TITLE
Feedback about "Go To" functionality in sidebar

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/ex_doc#968]
This is an issue specially created to receive your feedback about the new Go To functionality in the sidebar.
As we progress, you can comment on the implemented changes.

Related issues:
- https://github.com/elixir-lang/ex_doc/issues/967 **Provide "Search or go to..." functionality**

**Comment by josevalim** [comment]
I have pushed the suggestions above, thanks @eksperimental !

**Comment by eksperimental** [comment]
Sorry @josevalim I wasn't able to contribute to this one. I've been swamped with other non-computing related stuff.
thank you for taking care of it
