### ISSUE TITLE
Missing period at end of Summary entry 

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/ex_doc#975]
It appears that ex_doc grabs the first paragraph from each `@doc` entry to use in the Summary section. This seems reasonable, but it also elides any trailing period, which (IMHO) does not. If I choose to write in complete sentences, with appropriate punctuation, I don't think ex_doc should overrule me.

**Comment by josevalim** [comment]
I think we should just leave the period by default. Otherwise if a summary has multiple sentences, it looks weird to have partial punctuation.

**Comment by eksperimental** [comment]
> I think we should just leave the period by default. Otherwise if a summary has multiple sentences, it looks weird to have partial punctuation.

I agree.

I can submit a fix (IIRC it was me who introduced this feature)

**Comment by whatyouhide** [comment]
@eksperimental you're welcome to send a PR! 💟
