### ISSUE TITLE
JSON formatter

### ISSUE THREAD

**Issue by thure** [elixir-lang/ex_doc#981]
For integrating with a wider site, it'd be very handy to be able to generate a JSON document with a similar semantic structure as the HTML `ex_doc` renders. This could eventually facilitate REST/GraphQL APIs for docs too.

What schema would work best for this?

**Comment by josevalim** [comment]
@thure we don't plan to ship with a JSON formatter out of the box but you can pass your own formatter to achieve this. :+1:
