### ISSUE TITLE
Full Text Search: searching for atoms results in not terminating search

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/ex_doc#983]
Hi, first thanks for full text search! :green_heart: 

I went and tried it out for a couple of things I looked for the other day but stumbled on some bugs, first search for an atom gives me the spinner of not completing:

![image](https://user-images.githubusercontent.com/606517/55000203-4fad6180-4fd2-11e9-8928-1bcea9b3232b.png)

Example: 
https://hexdocs.pm/elixir/master/search.html?q=%3Adahsdhasdhaskda

or what I was actually searching for: `:not_consolidated`: https://hexdocs.pm/elixir/master/search.html?q=%3Anot_consolidated

Tried in both current Firefox and current Chromium.

**Comment by josevalim** [comment]
We will ignore the `:` (it is full text search) but we may have bad syntax in other cases. I have pushed another commit that shows the error alongside small search docs:

![image](https://user-images.githubusercontent.com/9582/55003548-e5e48600-4fd8-11e9-94c5-a78fbb1f0af0.png)
