### ISSUE TITLE
Full Text Search: Match on function names without args (regression)

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/ex_doc#984]
:wave: 

As said before, thanks for full text search etc. :green_heart: 

The new implementation doesn't seem to be able to match on function names without their argument counts/parantheses etc. which I think is a very important property of the search. This seems to be a regression, as it still works on the elixir 1.8.1 docs.

Sample:

1.8 works: https://hexdocs.pm/elixir/search.html?q=assert_protocol%21
master doesn't work: https://hexdocs.pm/elixir/master/search.html?q=assert_protocol%21

Sticking witht he sample, you also used to be able to partially match function names:

1.8: https://hexdocs.pm/elixir/search.html?q=assert_proto
master: https://hexdocs.pm/elixir/master/search.html?q=assert_protoc

I think this is crucial for finding functions.

For reference, what I had hoped to find with the full text search:

https://hexdocs.pm/elixir/master/search.html?q=__protocol__

Works with an appended `/1`:
https://hexdocs.pm/elixir/master/search.html?q=__protocol__%2F1

Thanks :green_heart:

**Comment by josevalim** [comment]
Thanks for the report @PragTob. The functionality you describe will be added back as part of the autocomplete described in #967 and the search will now be exclusive to full text search. :)
