### ISSUE TITLE
Autocomplete improvements

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/ex_doc#987]
Ref: https://github.com/elixir-lang/ex_doc/pull/985#issuecomment-476887884

Some ideas here: http://jeremymikkola.com/posts/2019_03_19_rules_for_autocomplete.html

**Comment by archdragon** [comment]
To keep it simple I would propose:
1. Sorting according to quality where `quality` = `matched chers count`/`total chars count`
2. Prioritising Modules and Functions over Exceptions and Mix Tasks

**Comment by josevalim** [comment]
> Sorting according to quality where quality = matched chers count/total chars count

Agreed.

**Comment by josevalim** [comment]
Apparently this feature was pushed to the branch already! :D
