### ISSUE TITLE
Inconsistent vertical spacing in lists

### ISSUE THREAD

**Issue by ndreynolds** [elixir-lang/ex_doc#989]
I noticed a small styling issue related to how Earmark renders HTML for lists. It wraps list item content with `<p>` tags under certain circumstances, which causes the vertical spacing to be all over the place in nested lists such as a table of contents.

Here's a visual comparison of my Elixir library's README.md as rendered by ExDoc and GitHub:

ExDoc | GitHub
:-------------------------:|:-------------------------:
![ex_doc](https://user-images.githubusercontent.com/670471/55283828-1fdac280-5320-11e9-99bc-4145e1e4f2c2.png) | ![github](https://user-images.githubusercontent.com/670471/55283832-2e28de80-5320-11e9-9142-25ddc3444c1a.png)

You can see there's a `1em` margin applied to the top and bottom of paragraphs on the left.  Only the list items with a nested list have the wrapping `<p>` tag, which explains why some items are very close together while others are far apart.  Most other Markdown implementations don't do this (there are no `<p>` tags on the right).

I created pragdave/earmark#226 and proposed changing the output there, but @RobertDober suggested I open the discussion here first as to whether this can be fixed without breaking backwards compatibility.   

So, would removing these `<p>` wrappers cause any trouble in ExDoc?  I'd love to see it updated so that these lists look as clean in ExDoc as they do on GitHub, and would be willing to do some testing afterwards to check that it doesn't introduce any new styling issues.

**Comment by josevalim** [comment]
Removing the <p> tags sound good to me, especially if it will make the markdown implementations more consistent. :+1:

**Comment by RobertDober** [comment]
I have changed the corresponding Earmark ticket https://github.com/pragdave/earmark/issues/226 to **bug**.
@josevalim you might want to close it here.

**Comment by josevalim** [comment]
Thank you @RobertDober !
