### ISSUE TITLE
Inconvenient shortcut SHIFT + /

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#991]
On german mac keyboards `/` is created by `SHIFT + 7`, so it's not possible to hit `SHIFT + /` at all.

**Comment by josevalim** [comment]
@LostKobrakai does pressing the question mark work for you on GitHub?

I looked into GitHub and they make the shortcut be `?` and not `SHIFT + /`. Is that something we could change @archdragon?

**Comment by josevalim** [comment]
@LostKobrakai actually, let me change the question. Does pressing the question mark `?` work for you on ExDoc? Maybe it all works correctly, we are just showing the wrong information.

**Comment by LostKobrakai** [comment]
Yep. `?` does work.

**Comment by josevalim** [comment]
Ok, so I just need to change the text. Fix coming soon!

Btw, #protip: most websites that support keyboard shortcuts show the help exactly when you press question mark. GitHub, Gmail, etc.

**Comment by josevalim** [comment]
Fixed in 27ad5b60fc127d77eb6152a895236d8c89cae441.
