### ISSUE TITLE
Button to toggle keyboard shortcuts help modal

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/ex_doc#992]
See title. I had to come here to find out what shortcuts ex_doc actually supports after reading of the feature on twitter.

**Comment by josevalim** [comment]
It is on the bottom of the page on purpose. We will give a try on this approach and we will collect feedback as necessary.

**Comment by LostKobrakai** [comment]
Ah there it is. I was really wondering if this could've been missed. I would've expected it at the bottom of the sidebar though.
