### ISSUE TITLE
Full text search fails with error in console

### ISSUE THREAD

**Issue by brainlid** [elixir-lang/ex_doc#993]
Love the update and the features being added.

## Versions

Version: 0.20.1
Elixir version: 1.7.3
OS: Ubuntu Linux 18.04

## Context

Generating the documentation for an Umbrella project. It generates without error.

Using either Chromium or Firefox (checked both), it works until a full text search is attempted. It spins forever. There is an error in the console:

**Chromium:**

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'QlpexUmbrella vdev' exceeded the quota.
```

**Firefox:**

```
QuotaExceededError: The quota has been exceeded.
```

I don't think it's being blocked in any way. I explicitly allow local html files to have access to local storage.

From some searching around, it seems like it might actually be a quota issue where it's possibly trying to store too much data into local storage?

**Comment by josevalim** [comment]
@brainlid thanks for the report. I have pushed a fix to master, can you please give it a try?

**Comment by brainlid** [comment]
@josevalim That fixed it. Thanks! Love the new feature! :+1:
