### ISSUE TITLE
Duplicate headings have the same id

### ISSUE THREAD

**Issue by rinpatch** [elixir-lang/ex_doc#998]
Example:
```
# Changelog
## 1.0
### Changed
- foo
## 0.9
### Changed
- bar
```
In this case both h3s will have `changed` as their id, resulting in inability to link to the second h3.

Git{lab,hub} solves this problem by giving duplicates an id that looks like this `name-<number of name occurences starting from the top>`. So in this case the first h3 wil have `changed` as it's id and the second will have `changed-1`

**Comment by cybrox** [comment]
Looking into this

**Comment by eksperimental** [comment]
Awesome is has been fixed, it has been in my bucket list for ages.
Thank you @cybrox for fixing it and @rinpatch for reporting it
