### ISSUE TITLE
Preserve casing of `codes` in table headers

### ISSUE THREAD

**Issue by Dalgona** [elixir-lang/ex_doc#999]
Currently all words in table headers are uppercased. While this is good for visually separating table headers and bodies, I think it shouldn’t apply to any text in `<code>`, since codes are usually case sensitive.

For example, following is the screenshot taken from the module documentation of `Version` in Elixir 1.8.1.

![IMG_0640](https://user-images.githubusercontent.com/2667858/56086238-3559fb80-5e8d-11e9-9f62-7976715fa1ca.jpeg)

This can be confusing to some readers as `:allow_pre` and `:ALLOW_PRE` are completely different two values.

**Comment by josevalim** [comment]
Yes, good call! A PR is welcome!

**Comment by Dalgona** [comment]
I just opened a pull request #1000. Please review. Thank you!
